### ISSUE TITLE
Kirby Button renders text in UpperCase in android

### ISSUE THREAD

**Issue by gags88** [kirbydesign/designsystem#100]
**Describe the bug**
When we operate DRB project on android device emulator then i can see that text on Kirby button is rendered as UpperCase everywhere in application.

**To Reproduce**
1. Open DRB in android device emulator
2. Locate The `Get Started` Button
3. See error as text will be in uppercase
4. Refer to screens attached with this issue

**Kirby version**
 - 0.0.63

**Expected behavior**
The Button text shall rendered as per the code logic.

**Screenshots**
<img width="338" alt="screenshot 2019-02-11 at 9 43 48 am" src="https://user-images.githubusercontent.com/9352091/52546099-a542fb80-2de2-11e9-971c-b2f2dcf589fb.png">
<img width="423" alt="screenshot 2019-02-11 at 9 44 05 am" src="https://user-images.githubusercontent.com/9352091/52546101-a8d68280-2de2-11e9-805a-8fc7d51f7ec3.png">
<img width="837" alt="screenshot 2019-02-11 at 9 46 56 am" src="https://user-images.githubusercontent.com/9352091/52546102-abd17300-2de2-11e9-992c-274bb3b95ff1.png">
<img width="826" alt="screenshot 2019-02-11 at 9 47 17 am" src="https://user-images.githubusercontent.com/9352091/52546103-af64fa00-2de2-11e9-80dc-6525afe7138f.png">

**Native (please complete the following information):**
 - Device: [Pixel 2 XL API 28]
 - OS: [Android]

**Comment by jonasjensen-brolstark** [comment]
It looks like it is not a bug, but is by design in android.

A possible solution can be found here [https://medium.com/@scottmgerstl/nativescript-android-buttons-all-caps-angular-2-40aff5dbe37b](https://medium.com/@scottmgerstl/nativescript-android-buttons-all-caps-angular-2-40aff5dbe37b).
