### ISSUE TITLE
[BUG] Dropdown med scroll - selecter item ved "drag"

### ISSUE THREAD

**Issue by labanos** [kirbydesign/designsystem#1002]
**Describe the bug**
When opening af dropdown with more items, than are visible it is hard to select the items needing a scroll/drag, as the touched item gets selected before being able to drag.

**To Reproduce**

1. Go to 'investering'
2. Click on 'any security with "chart data"'
3. Try to select 5 years in the dropdown for "periode"

**Kirby version**
- [1.1.6]

**Expected behavior**
It should be possbile to drag down in the dropdown without selecting an item.

**Screenshots**
![File (5)](https://user-images.githubusercontent.com/5631507/80576954-58a70880-8a06-11ea-9b37-32c2547c9f06.jpg)

**Please complete the following information:**
- OS: reproduced on iOS

**Additional context**
Currently the dropdown is feature toggled - so remember to toggle in.

Should be fixed before releasing the current solution - or shortly after.

## Tasks:
- [ ] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [ ] Create Fix Branch
- [ ] Create test reproducing the error
- [ ] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch

**Comment by labanos** [comment]
dropdown does not close on "navigation" - investigate ;)

**Comment by sorenfruergaard** [comment]
This is also an issue in `drb/wealth/pensions/forecast` when selecting pension age.
