### ISSUE TITLE
[BUG] swipe button arrow disapeared

### ISSUE THREAD

**Issue by yucelbas** [kirbydesign/designsystem#1004]
**Describe the bug**

Swipe button has lost the arrow - is is now a white round circle on the green button

**To Reproduce**
Can be reproduced by making a transfer to own account on a mobile device - both android and iOS
1) click "overfør og betal"
2) Input an amount
3) choose an account from the "Egne konti" segment
4) click "Fortsæt"
5) notice the missing arrow on the swipe button. 

**Expected behavior**
It is expected that the swipe button has an arrow in the white circle on it. 
**Screenshots**

<img width="754" alt="Screenshot 2020-04-30 at 10 41 52" src="https://user-images.githubusercontent.com/43955031/80690548-3c22d300-8acf-11ea-9c33-a9ec57366c40.png">

**Please complete the following information:**
Android and iOS devices

## Tasks:
- [ ] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [ ] Create Fix Branch
- [ ] Create test reproducing the error
- [ ] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch

**Comment by bommariusser** [comment]
@jakobe noget vi kan lukke? :)

**Comment by jakobe** [comment]
Fixed by #1014
