### ISSUE TITLE
[BUG] Action sheet - Multiple overlays on top of each other.

### ISSUE THREAD

**Issue by sorenfruergaard** [kirbydesign/designsystem#1007]
**Describe the bug**
After opening action sheet, the focus stays on the button, which makes it possible to open multiple overlays on top of each other if you use the keyboard.

**To Reproduce**

1. Go to https://cookbook.kirby.design/examples/action-sheet
2. Click on 'show action sheet'
3. Press enter multiple times to see multiple overlays on top of each other

**Kirby version**
- 1.2.11

**Expected behavior**
User should not be able to press buttons beneath the overlay -  not by mouse and not by keyboard.

**Screenshots**
![actionsheet-overlay](https://user-images.githubusercontent.com/2383744/80950574-65f13800-8df6-11ea-8bc2-b89cc4fcf421.gif)

**Please complete the following information:**
- OS: MacOS
- Browser Chrome
- Browser version 81.0.4044.129

**Additional context**
Error can be reproduced on Android 10 and Android 9.1.387, when the user is using accessibility tools (voiceover or talkback)

## Tasks:
- [ ] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [ ] Create Fix Branch
- [ ] Create test reproducing the error
- [ ] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch

**Comment by bommariusser** [comment]
Looks like you have som spare time? @sorenfruergaard :DDDDD

There are some more issues concerning the actionsheet if you are up to making some enhancements... ;)

**Comment by jakobe** [comment]
@sorenfruergaard :
The "Show action sheet" button is not part of the Kirby Action Sheet - it's up to the target project to disable the button if you wish to... (or whatever other element/service you use to open the action sheet)
