### ISSUE TITLE
[Enhancement] Close on backdrop

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#1008]
**Is your enhancement request related to a problem? Please describe.**
We would like the actionsheet to drop (✋🏻 🎤 )  when pressing the backdrop (and not only the Cancel button)
**Please note** This is especially important when looking at the desktop version where you dont have a backdrop :D

**Comment by jakobe** [comment]
**Tech refinement:**
Flip the `backdropDismiss: false` flag to `true` on `ActionSheetHelper.showActionSheet()` in `action-sheet.helper.ts`
