### ISSUE TITLE
[Enhancement] Swipe to navigate on page (Not just on the edge)

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#1015]
**Is your enhancement request related to a problem? Please describe.**
Right now it's actually quite hard to swipe back to navigate. You have to be on the very edge of the page to do that.

**Describe the solution you'd like**
We would like it to feel more "fluid" and also allow swiping back from anywhere on the page, not just the very edge.

This doesnt mean that we want to enable swiping back when you are on another component! It's only intended when you do it on the very page background.

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
