### ISSUE TITLE
[Enhancement] Item with an inputfield

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#1023]
**Is your enhancement request related to a problem? Please describe.**
We would like to combine an item with an input-field, so that the input-field can be placed inside an item without any input-border or label. 

In the use-case we have right now this is only relevant for the end-slot in an item. See also:
![Skærmbillede 2020-05-12 kl  11 44 31](https://user-images.githubusercontent.com/49033002/81669091-f60e2d80-9445-11ea-9426-5db2a2ed160c.png)

**Additional context**

What our use cases need right now:

### Need to have:

- [x] Input format: numerical with comma seperation
- [ ] The maximum number of digits is defined by the project eg. 12
- [x] Default input style: 16px, bold (use `host-context`, see [avatar](libs\designsystem\src\lib\components\avatar\avatar.component.scss) for an example)
- [x] Always 16 px distance between text and input (like it is right now)
- [x] Form field looses its styling when its put into a card/item
- [x] Spec: Form-field set is the one who styles the input field and not the input field (e.g. replace existing `:host` selector with `:host-context(kirby-form-field)`)

### Nice to have:

- [ ] Placeholder text with or without decimal numbers.
- [ ] Dynamic width of text in 'Default' (Default should pr. default truncate)
- [ ] Dynamic sizes on the input field (not only min/max) (in 1. release it might be fixed width if complex to solve)
- [ ] The horizontal touch area of the input field must always be 80 px as a minimum.
- [ ] Restrictive number of decimal numbers. Eg. 2 digits. --- See also https://github.com/kirbydesign/designsystem/issues/1030
- [ ] thousand separator on numerical numbers (this should happen automatically as the user types or after the user copy/pastes a number in) --- See also: https://github.com/kirbydesign/designsystem/issues/1029 
- [ ] Don't allow copy/paste or inputting stuff like (. + -) etc.
- [ ] Possibility to have a custom format string (e.g. `123.45 KR.`) in the input field

![image](https://user-images.githubusercontent.com/49033002/81668776-6e282380-9445-11ea-822a-7f153b007a65.png)

Use cases
'Valuta':https://zpl.io/290A0Ny
'Split': https://zpl.io/VQQjqZn

**Comment by jakobe** [comment]
Closed by #1054
