### ISSUE TITLE
[Enhancement] Decimal Separation (1000's)

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#1029]
[Milestone ](https://github.com/kirbydesign/designsystem/milestone/13)for this issue could be end of 2020.

**Is your enhancement request related to a problem? Please describe.**
Right now our numerical inputs don't have any decimal separation so when you input a high number the number is displayed as it is eg. 10000000000

**Describe the solution you'd like**
We would like decimal seperation while the user is typing or after the user has copy/pasted some numbers into a input field so that a number like 10000000000 is separated into 10.000.000.000

![Skærmbillede 2020-05-14 kl  15 39 03](https://user-images.githubusercontent.com/49033002/81941857-a3757280-95f9-11ea-8281-c8b5b2d4ad17.png)

### Kick Off:

- [x] Ensure the enhancement is `UX refined` and aligned with UX 
_The component and/or enhancement should be published and available in the [Kirby Styleguide on Zeplin](https://zpl.io/258pXGj)_
- [x] Ensure the enhancement has been `Tech refined` with @kirbydesign/kirby-guild and this issue is updated with a clear implementation description  
_This issue should be in the [Ready to do](https://github.com/kirbydesign/designsystem/projects/1#column-4590936) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1) before starting implementation)_
- [x] Assign yourself to this issue and move it to the [In progress](https://github.com/kirbydesign/designsystem/projects/1#column-4590937) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1)

### Code:

- [x] Create Feature Branch from [master branch](https://github.com/kirbydesign/designsystem/tree/master)
- [x] Create a draft implementation and push to Github
- [x] Ask a member of @kirbydesign/kirby-guild for a WIP review by creating a draft Pull Request
- [x] Implement unit tests
- [x] Update Cookbook Examples and Showcase, i.e. see [Radio](https://cookbook.kirby.design/home/showcase/radio)  
_Also remember to add any relevant new API documentation_

### Review:

- UX review:
  - [x] Ensure implementation is correct in relation to the UX design and the [Kirby Styleguide on Zeplin](https://zpl.io/258pXGj)
  - [x] With UX agree on the version of the implementation
- Code review:
  - [x] Open a pull request (or mark the existing draft PR as `Ready for review`) and ask @kirbydesign/kirby-guild for a review  
_Remember to add `closes #issueno` to the description of the PR._
  - [ ] Once approved, merge feature branch/PR to master
- [ ] Ask a member of @kirbydesign/kirby-guild to add a link to component showcase from Kirby Component Status and update the version number

**Comment by MartinSkovsen** [comment]
@labanos As per the issue template instructions can you remove NOT PRIORITIZED label from this issue? It's prioritized [here](https://github.com/kirbydesign/designsystem/milestone/13).

**Comment by karlgodtliebsen** [comment]
@labanos 

https://github.com/kirbydesign/designsystem/issues/1029

[Enhancement] Decimal Separation (1000's)

Precision: The described specification relates to a 1000’s separator aka grouping separator, and not decimal separator

Exploration for this Enhancements shows this possible solution:

Create a Directive that can be attached to HTML input field or ionic input field.
Use Locale information to find the grouping separator (decimal and or grouping separator)

Either use NgControl ChangeValue to add the separator or go with the keydown/keyup (keypress is obsolete) strategy.

If we combine the numeric grouping separator issue with the decimal issue (support for 0..n decimals), and the filter for only allowing digits, and related key chars, and the ability to add separators on the fly, the keydown keyup solutions seems to be the best match for the requirements.


-Handle keydown, combined with the pressed key, selection information, regular expressions, to validate/invalidate the pressed key, thus allowing or preventing it from appearing in the 
-Handle keyup, ensuring automatik addition of grouping separator
-Ensure final pretty formatted output using blur event


By creating different directives, but having a common library, this library can be uses as part of solving several issues:

1029 - 1211 - 1212 - 1213 - 1079 - 1030

**Comment by labanos** [comment]
@karlgodtliebsen sounds like a good candidate for a small meeting - since it sounds like we can set a good direction for all the cases. I will try to find someone and will get back to you asap.
