### ISSUE TITLE
[Enhancement] "Clickable" as a modifier/attribute on cards

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#1032]
**Is your enhancement request related to a problem? Please describe.**
Right now the cards we have, that are "clickable", don't come out of the box with an `<a>` tag or `<button>` tag - thus they are not accessible, because the user doesnt get any help on which cards can be pressed and which cannot.

**Describe the solution you'd like**
We would like to be able to set a card to "clickable/selectable" like our items can be modified. 

Technically the component that changes state should change its fill color by putting a fillcolor on top of the color with a given opacity, fx:

- If a white card changes state it should get a black color (Whites contast color) on top of it so it gets "grey"

**Specs are different from light to dark:**

Hover light component (dark contrast color): 2%
Hover dark component (white contrast color): 8%

Pressed light component (dark contrast color): 6%
Pressed dark component (white contrast color): 24%

This would also imply that the card gets the needed states like press and hover, see also: 

Hover: https://zpl.io/bAxdkEx
Pressed: https://zpl.io/agmDqN1

<img width="357" alt="Skærmbillede 2021-10-26 kl  20 31 40" src="https://user-images.githubusercontent.com/49033002/138939552-a0107d35-1c2a-4011-9817-325d391c337d.png">

**Comment by jakobe** [comment]
**Tech refinement:**
- Option A: Check for `(click)` event handler and change cursor to `pointer`
- Option B: Add @Output property/event `click` to card and change cursor to `pointer`
- Also consider whether elevation should be automatically set if clickable? And/or opt-in/opt-out
- Also ensure a11y (`role="button"` or something...)

**Comment by RasmusKjeldgaard** [comment]
**Tech refinement:**
If we add an output decorator (which will have to define a custom event), the solution will by nature be opt-in, and thus existing cards that have a click event handler will have to be updated to implement this new functionality.

So instead, @jakobe figured out that we can use a directive to set an input property on all cards that implement a click event handler `(click)="something()" `, like this:

```
@Directive({
  selector: 'kirby-card[click]'
})
export class KirbyCardClickDirective implements OnInit {
  constructor(private card: CardComponent) {}

  ngOnInit(): void {
    this.card.isButton = true;
  }
}

``` 

Then the card itself can handle elevation, `role="button"`, and hover + active states.

**Comment by bommariusser** [comment]
Cards with elevation z0 should get a z2 as default

**Comment by RasmusKjeldgaard** [comment]
> Cards with elevation z0 should get a z2 as default

See bottom of [card cookbook page](https://cookbook.kirby.design/home/showcase/card) for related elevation modes on card.

**Comment by bommariusser** [comment]
@RasmusKjeldgaard i've refined a bit more in regards to how the specs should be. maybe you can give it a look? <3

**Comment by RasmusKjeldgaard** [comment]
Cool - could we consider to use the same approach that is used for button now (.8 opacity on hover), and add the card to the list of components for this issue? https://github.com/kirbydesign/designsystem/issues/549 

Otherwise we will get two different behaviors.
