### ISSUE TITLE
[BUG] modal/drawer swipe down to close scrolls down (iOS 12)

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#1036]
**Is your enhancement request related to a problem? Please describe.**
When you swipe a drawer down on an iOS 12 device you scroll on the view below as well 

**Describe the solution you'd like**
Swiping a "modal" down should not affect the view below itself.

**Comment by jakobe** [comment]
Needs verification

**Comment by RasmusKjeldgaard** [comment]
This is no longer reproducible, please open a new issue if the problem persists
