### ISSUE TITLE
[Enhancement] Prevent modal from closing while global loading overlay displays

### ISSUE THREAD

**Issue by mvindahl** [kirbydesign/designsystem#1062]
**Is your enhancement request related to a problem? Please describe.**
We would like a way to temporarily prevent a modal from closing. We would typically combine this with a global loading overlay while awaiting the server response for a request that cannot be meaningfully cancelled. Arguably it should be a feature of the global loading overlay.

The current behaviour for the global loading overlay is to prevent any mouse/touch interaction with the underlying UI, but the modal will still be dismissed when pressing Esc on the keyboard or when pressing the Android back button (inferred from code; I haven't verified this). 

**Describe the solution you'd like**
While the global loading overlay is displayed, it is not possible to dismiss the underlying modal.

**Describe alternatives you've considered**
Our main modal contains a flow which should be cancellable at almost any point but there are certain points, specifically when performing a request to the backend to actually transfer money, when we want to force the user to await the response.

The obvious alternative would be to allow dismissing at *any* point and to let the user live with never seeing any receipt or error message. However we fear that users might mistakenly regard the Esc button as a way to cancel the transfer.

**Additional context**
Ionic seems to offer four ways to dismiss a modal:
1) Programmatically, from the UI embedded into the modal, e.g. the top right "X"
2) By clicking the area around the modal (medium and large viewport sizes)
3) By pressing the escape key (web only)
4) By pressing the back button on the Phone (Android only)

Methods 1) and 2) are preventable by calling LoadingOverlayService.showLoadingOverlay(). Methods 3) and 4) require further configuration of ionic.

Ionic offers a backdropDismiss property when opening a modal; setting this as false would prevent methods 2), 3), and 4) from above. I'm sure how to apply it dynamically. Worst case we could apply it statically and copy pasta the logic.

Ref: https://github.com/ionic-team/ionic/blob/9d0dcbbd31fc34ad8952eacb9864ad1b31636113/core/src/utils/overlays.ts#L75

**Comment by jakobe** [comment]
**Input to tech refinement:**
Consider adding a `preventClose` option to the modal configuration + a `allowClose` method to the `Modal` interface that handles this built-in. OR built this into the showLoader/hideLoader option in #1108

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
