### ISSUE TITLE
[Enhancement] Small dropdown button

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#1068]
**Is your enhancement request related to a problem? Please describe.**
We would like a dropdown button that is smaller in size (32px height) but still uses the same dropdown-popover.

**Comment by MortenGregersen** [comment]
I Zeplin the small dropdown is 32px in height. The medium is 40px in height. Shouldn't the small be 32px?

**Comment by bommariusser** [comment]
yes it should @MortenGregersen it should follow the same structure as the button
