### ISSUE TITLE
[Enhancement] Android performance (Samsung)

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#1070]
**Is your enhancement request related to a problem? Please describe.**
Performance on some Android devices, especially samsung, is questionable. Questionable is vague but performance Android vs iOS should be the same, as much as possible.

This goes especially for all our transitions. In regards to Kirby components, this is in our **modals** (also **alerts**) and navigational transitions which probably is on **page**

**Comment by jakobe** [comment]
This is a bit too general, we need more specific performance issues...
