### ISSUE TITLE
[Enhancement] Forward/Backward navigation in Modal footer

### ISSUE THREAD

**Issue by LVinther** [kirbydesign/designsystem#1072]
**Describe the solution you'd like**
We want to be able to use the modal for longer flows, where you can navigate back and forth and see the progress you've made in the modal through some buttons in the footer. We need to support:

- The footer needs to be able to have some configuration that support this kind of button placement. In our library we do this through a buttongroup with 2 buttons which are aligned left/right. Buttongroups are documented in this task: https://github.com/kirbydesign/designsystem/issues/1144

![Skærmbillede 2020-10-28 kl  09 56 42](https://user-images.githubusercontent.com/49033002/97414106-e30fec80-1903-11eb-80d8-c18c7bc07e58.png)

**Describe alternatives you've considered**
It doesn't need to be icon button but could be any kind of buttons. They should be Medium size in this case though.

**Additional context**
Add any other context or screenshots about the feature request here, e.g. a link to the corresponding component from [Ionic](https://ionicframework.com/docs/components/)

### Kick Off:

- [ ] Accept Feature incl. name of component (DSL)
- [ ] Update Kirby Component Status and publish to [Kirby Cookbook](https://cookbook.kirby.design)

### Code:

- [ ] Create Feature Branch
- [ ] Implement Skeleton Component
- Ask UX for review:
  - [ ] Ensure implementation is correct in relation to UX design
  - [ ] Define the version of the implementation + steps needed to reach version 1.0 (create [enhancement requests](https://github.com/kirbydesign/designsystem/issues/new?assignees=&labels=enhancement&template=enhancement-request.md&title=%5BEnhancement%5D))
- [ ] [Implement Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Add link to showcase on Kirby Component Status (`component-status-items.ts => code.cookbookUrl`)
- [ ] Also remove `githubIssueNo` and set `status` to `ItemCodeStatus.ready`
- [ ] Push commits to GitHub

### Review:

- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- Merge to master and delete branch

**Comment by MartinSkovsen** [comment]
Currently, team 9 solves this by changing --kirby-modal-footer-justify-content to space-between. 
Should we make the footer content justification optional with a component property?

**Comment by labanos** [comment]
@MartinSkovsen did you look at https://github.com/kirbydesign/designsystem/issues/1144 as suggested on the issue? I think this sounds light the "right" way - and one that adds value to solve other cases. That is add a button group feature - and use the button group to solve this issue. If that makes sense?

**Comment by labanos** [comment]
@MartinSkovsen forget about #1144 for now. It sounds right - but we dont use ion-button ATM - so maybe it does not make much sense now. In regards to optional - sound ok - always think that your enhancement should not have any effect on already running code using the component. So you dont introduce change by default - unless it is really important or a bug fix ;)

**Comment by MartinSkovsen** [comment]
Check 👍 I realize just implementing component properties ad hoc usually isn't in line with general best practices when developing component libraries, however I don't see any other way to support this enhancement in the footer. We can choose to accept that consumers of kirby-modal-footer per their need change the --kirby-modal-footer-justify-content variable ad hoc. Could be nice with some feedback from an experienced kirby developer.

**Comment by MartinSkovsen** [comment]
Alright, so after discussing this briefly with @jakobe, team 9 can achieve their goal with current behaviour by using --kirby-modal-footer-justify-content. I'll remove the team 9 label and remove myself as asignee. Perhaps I can take this issue later on :)

**Comment by bommariusser** [comment]
Can we close this task or is this related to also making a "seperate" component-configuration to get this kind of behavior? :) @MartinSkovsen @jakobe

**Comment by MartinSkovsen** [comment]
During our previously referred conversation @jakobe mentioned that we keep this issue open. @jakobe can provide the context if necessary

**Comment by RasmusKjeldgaard** [comment]
**Refinement:**
The focus/scope of this issue is a UI component for the modal.

**Comment by bommariusser** [comment]
@RasmusKjeldgaard should we consider a good name for that one? Footer Navigation or something :D

**Comment by RasmusKjeldgaard** [comment]
I think for solving this specific issue, we don't need a new name, as it should be configurable directly on the footer. 
But down the line, I think using a generic Button Group, or whatever we decide on calling it, will be the way to go.
