### ISSUE TITLE
[COMPONENT] Graph to show risk/return scenario

### ISSUE THREAD

**Issue by LVinther** [kirbydesign/designsystem#1073]
**Describe the solution you'd like**
We would like a graph where the user can simulate risk/return scenario. The content in the graph should be adjusted based on selection on the range.

Example of context
![Investeringsprofiler Copy 4](https://user-images.githubusercontent.com/53176253/84800805-9be12900-affe-11ea-8df1-81e98cc1ed56.png)

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here, e.g. a link to the corresponding component from [Ionic](https://ionicframework.com/docs/components/)

### Kick Off:

- [ ] Accept Feature incl. name of component (DSL)
- [ ] Update Kirby Component Status and publish to [Kirby Cookbook](https://cookbook.kirby.design)

### Code:

- [ ] Create Feature Branch
- [ ] Implement Skeleton Component
- Ask UX for review:
  - [ ] Ensure implementation is correct in relation to UX design
  - [ ] Define the version of the implementation + steps needed to reach version 1.0 (create [enhancement requests](https://github.com/kirbydesign/designsystem/issues/new?assignees=&labels=enhancement&template=enhancement-request.md&title=%5BEnhancement%5D))
- [ ] [Implement Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Add link to showcase on Kirby Component Status (`component-status-items.ts => code.cookbookUrl`)
- [ ] Also remove `githubIssueNo` and set `status` to `ItemCodeStatus.ready`
- [ ] Push commits to GitHub

### Review:

- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- Merge to master and delete branch

**Comment by alxzak** [comment]
Fixed by chart.js
And also this issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
