### ISSUE TITLE
Swipe på kontobevægelser giver firkantede hjørner [BUG]

### ISSUE THREAD

**Issue by MikaelKristoffersenBankdata** [kirbydesign/designsystem#1077]
**Describe the bug**
Se vedhæftede film.

**To Reproduce**

1. Gå til 'kontobevægelser'
2. Swipe på en postering
3. Se at der er firkantede hjørner på øverste celle

Notes:
Det ser ud til kun at være et problem på nummer to postering...
Det er ikke et problem på Android

[](url)
**Kirby version**
1.2.42

**Expected behavior**
Der skal være buede hjørner

**Screenshots**
Se vedhæftede film - oh no Github supporterer ikke videofiler... Har sendt filen til Jakob.

**Please complete the following information:**
- OS: iOS

**Additional context**

## Tasks:
- [ ] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [ ] Create Fix Branch
- [ ] Create test reproducing the error
- [ ] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch

![Skærmbillede 2020-06-17 kl  14 50 55](https://user-images.githubusercontent.com/55275492/84900292-2b8fe180-b0aa-11ea-8af7-d2547b5e3e0c.png)

**Comment by bommariusser** [comment]
@MikaelKristoffersenBankdata kan du tilføje et screenshot? :)

**Comment by bommariusser** [comment]
I can also recreate it on drb as you said on the 2nd item in the list.

I can not recreate on cookbook though (on iOS)

**Comment by jakobe** [comment]
Fixed by #1102
