### ISSUE TITLE
[Enhancement] Input field with currency formatting and more

### ISSUE THREAD

**Issue by RasmusTraeholt** [kirbydesign/designsystem#1079]
**Is your enhancement request related to a problem? Please describe.**
We would like to expand the current input field's capabilities to meet new requirements as listen below. This enhancement builds upon previous issue: https://github.com/kirbydesign/designsystem/issues/1023

![Skærmbillede 2020-05-12 kl  11 44 31](https://user-images.githubusercontent.com/49033002/81669091-f60e2d80-9445-11ea-9426-5db2a2ed160c.png)

**Additional context**

What our use cases need right now:

- [ ] Placeholder text with or without decimal numbers.
- [ ] Dynamic width of text in 'Default' (Default should pr. default truncate)
- [ ] Dynamic sizes on the input field (not only min/max) (in 1. release it might be fixed width if complex to solve)
- [ ] The horizontal touch area of the input field must always be 80 px as a minimum.
- [ ] Restrictive number of decimal numbers. Eg. 2 digits. --- See also https://github.com/kirbydesign/designsystem/issues/1030
- [ ] thousand separator on numerical numbers (this should happen automatically as the user types or after the user copy/pastes a number in) --- See also: https://github.com/kirbydesign/designsystem/issues/1029 
- [ ] Don't allow copy/paste or inputting stuff like (. + -) etc.
- [ ] Possibility to have a custom format string (e.g. `123.45 KR.`) in the input field

![image](https://user-images.githubusercontent.com/49033002/81668776-6e282380-9445-11ea-822a-7f153b007a65.png)

Use cases
'Valuta':https://zpl.io/290A0Ny
'Split': https://zpl.io/VQQjqZn

**Comment by jakobe** [comment]
@RasmusTraeholt Is this still relevant or covered by separate issues? Maybe change this to a [TRACKING] issue and link to the relevant subtasks 🙏🏻

**Comment by RasmusTraeholt** [comment]
I don't think this is relevant anymore. Most of the desired enhancements here are already implemented, covered by other issues or things we can live without :)
