### ISSUE TITLE
[BUG] - Kirby list not visible

### ISSUE THREAD

**Issue by SilverGull** [kirbydesign/designsystem#1080]
**Describe the bug**
In rare cases we see that a Kirby list is invisible. The dom node itself has visibility set to visible but its `ion-list` child node has visibility set to hidden. All of the child nodes - items and such - looks perfectly fine containing the correct data, they are just hidden (because of its hidden parent `ion-list`).

**To Reproduce**
We have only seen it in DRB and we have no certain way of reproducing it. We hope that someone might have an idea as to what is happening and maybe what we can do.

1. Open DRB with a user that has "Power of Attorney" custody accounts or pool accounts (ask for cpr :-) )
2. Go to Investment Overview
3. Click on the cog for settings
4. Click on "Power of Attorney"
5. In some cases the lists are invisible. Only headers and empty space below is shown.

**Kirby version**
- 1.2.43

**Expected behavior**
Visible lists

**Screenshots**
![Screenshot 2020-06-25 at 08 59 13](https://user-images.githubusercontent.com/43959200/85676729-28f34480-b6c7-11ea-8b21-3b96080ded08.png)
![Screenshot 2020-06-25 at 08 59 37](https://user-images.githubusercontent.com/43959200/85676741-2c86cb80-b6c7-11ea-8dc7-9ce3ff1512d6.png)

**Please complete the following information:**
- OS: MacOS and Android
- Browser: Chrome on MacOS and Android
- Browser version: 83

**Additional context**

## Tasks:
- [ ] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [ ] Create Fix Branch
- [ ] Create test reproducing the error
- [ ] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch

**Comment by jakobe** [comment]
@SilverGull Is this still relevant or did you fix it? Sounds very specific to your use case, so wondering if this is a Kirby bug at all? 🤔

**Comment by SilverGull** [comment]
@askarby we saw this problem last year. Can you (or someone else from Team 3) look into whether or not it is still relevant and answer @jakobe ?

**Comment by RasmusKjeldgaard** [comment]
Talked with @askarby about this and it seems like this has not been an issue for quite a long time. Closing it for now.
