### ISSUE TITLE
[Enhancement] Remove danger (red) state of toast

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#1085]
**Is your enhancement request related to a problem? Please describe.**
We've decided to clean up our toast definition and flavors: Toasts are in their nature never "critical" and should thus not be red - Red should be used sparingly, only for destructive actions, and thus only in **Alerts** because they are by their nature more "critical"

**Additional context**
All red toasts should be yellow instead and green should stay green

**Comment by MortenGregersen** [comment]
What color should the toast be then? Shall it only be possible to specify `success` and `warning`?

**Comment by bommariusser** [comment]
yes @MortenGregersen

**Comment by jakobe** [comment]
**Tech refinement** Keep 'danger' as valid input and:*
- "translate"  to warning
- console.warn about danger is deprecated as valid color/state
