### ISSUE TITLE
[Enhancement] Backdrop of FAB Sheet should be covering the whole viewport

### ISSUE THREAD

**Issue by hafstad** [kirbydesign/designsystem#1094]
Team 6 will solve this themselves
This enhancement has been requested by @tja1607 

**Is your enhancement request related to a problem? Please describe.**
ATM the backdrop of the FAB Sheet is not covering the whole viewport even though it has been styled with "position:fixed" (note this can only be replicated if it's inside page, or tabs-component). This is because Ionic is using the css property "contain" on many of the components because of performance improvements which changes the relative for the fixed positioned element instead of using the viewport as normal. In this case .tabs-inner, ion-router-outlet and .ion-page 

**Describe the solution you'd like**
Adding the backdrop of the FAB Sheet dynamically to the root of the DOM so we ensure it's not inside of a container which uses the "contain" property

**Describe alternatives you've considered**
Setting "contain: none" of .tabs-inner, ion-router-outlet and .ion-page when .backdrop-no-scroll is active (and ofc. only when the backdrop is shown, NOT on desktop). However if there's other parent components of the FAB Sheet which are using contain later on, the problem will NOT be resolved. Also it's possible that this could have bad impact of the overall performance.

**Comment by MortenGregersen** [comment]
Is this different from #756?
