### ISSUE TITLE
[BUG] Title in page not fitting on one line when actions are present

### ISSUE THREAD

**Issue by MortenGregersen** [kirbydesign/designsystem#1095]
**Describe the bug**
When a non-breakable title is used in a page with `titleMaxLines` set to 1 and actions present, the title isn't fitting/scaled down on small screen sizes like the iPhone 5s/SE (5-inch).

In "Investment" in DRB we have a long non-breakable title and a wide button as action, so it isn't looking great on the small screens.

**To Reproduce**

Create a page like the following. The easiest is to use the `PageFitHeadingExampleComponent` in the Cookbook and change the title and add the actions.

```html
<kirby-page title="Loremipsumbum" titleMaxLines="1">
  <kirby-page-actions *kirbyPageActions="{ sticky: false }">
    <button kirby-button>Get bacon</button>
  </kirby-page-actions>
  <kirby-page-content>
    <div>Some content</div>
  </kirby-page-content>
</kirby-page>
```

**Kirby version**
- 1.2.53

**Expected behavior**
I would expect the title to scale down

**Screenshots**
![Screenshot 2020-07-28 at 11 12 52](https://user-images.githubusercontent.com/759680/88644482-4ef37680-d0c3-11ea-98de-ba087d98c57e.png)

**Please complete the following information:**
- OS: Doesn't matter
- Browser: Doesn't matter
- Browser version: Doesn't matter

## Tasks:
- [ ] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [ ] Create Fix Branch
- [ ] Create test reproducing the error
- [ ] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch

**Comment by bommariusser** [comment]
is this also happening when u have a button with only an icon @MortenGregersen ? :)

**Comment by MortenGregersen** [comment]
> is this also happening when u have a button with only an icon @MortenGregersen ? :)

Yes

![Screenshot 2020-07-31 at 12 45 17](https://user-images.githubusercontent.com/759680/89027965-bf9ccc00-d32b-11ea-8bba-c5238528e6a5.png)

**Comment by bommariusser** [comment]
Jeah i see that. Long words and the page-title don't go along very well... :(

**Comment by jkaltoft** [comment]
# Suggestion for solution

A solution must take into consideration what should happen when things do *not* fit. Expect the worst: Longer words, larger font sizes (which are controlled by the end-user), small device/viewport sizes etc.

**Suggestion**

- Always display actions button
- Manage text overflow within remaining space
  - See https://github.com/kirbydesign/designsystem/issues/967#issuecomment-902556772

**Comment by RasmusKjeldgaard** [comment]
Consider migrating to new header where this is fixed: https://cookbook.kirby.design/#/home/showcase/header
<img width="429" alt="image" src="https://github.com/kirbydesign/designsystem/assets/42470636/b84daf47-b887-48eb-938d-6beeb7e5a6e9">
