### ISSUE TITLE
[Enhancement] FAB positioning like a FABSheet

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#1105]
**Is your enhancement request related to a problem? Please describe.**
If you have a FAB without a sheet you have to manually set its position in the view. 

**Describe the solution you'd like**
Right now our FAB's don't come with any positioning, like our FABSheet does - The FABSheet doesn't work without the sheet, even though it might just be a variable for it so you can decide if you want to use the sheet or not.

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
