### ISSUE TITLE
[FORM FIELD]  Should retain it's height even if a message is added

### ISSUE THREAD

**Issue by ckibsen** [kirbydesign/designsystem#1107]
**Is your enhancement request related to a problem? Please describe.**
We are facing an issue with the behaviour of the form field, when eg. we have a layout where a checkbox is rendered below the form field. Say the form field is focused, and the user tries to click the checkbox. And say this results in a validation being made to the form field, and the message "Must contain a value" being shown below the form field. In effect this will cause an increase in height of the form field, and the checkbox being rendered further down the page, which is why the click in the checkbox misses, as the checkbox is now sitting in another location. 

**Describe the solution you'd like**
If a Kirby Component (in this case form field including message) always takes up the same amount of space regardless of it's state, this will give a more "steady" UI experience, and in the case described the user won't miss the checkbox when trying to hit it. This expected behaviour of Kirby elements generally having a fixed height has been discussed with @mvindahl !

The additional height that should be added to the form field probably should take into consideration the font size of the message field (in order to address future requirements of eg. accessibility scaling of fonts).

**Describe alternatives you've considered**
Wrapping the form field in a div with a fixed height, in order to create a more steady UI, without the risc of elements changing locations due to size changes. 

**Additional context**
n/a

**Comment by bommariusser** [comment]
@ckibsen this goes for the input, or? like the input pushes the rest of the content down because there comes another line of "validation error" under the input field, or?

**Comment by ckibsen** [comment]
@bommariusser yes, in this case a validation text appearing below the input field pushes the rest of the content. After further consideration, It's probably a bit hard to figure out what a proper fixed height would be, as the validation can be so long that it wraps over two or maybe even more lines. 

In that case, it probably doesn't make much sense to try to set af fixed height! So, perhaps this shouldn't be the responsibility of Kirby Form Field after all, but instead we might need to wrap our Form Fields in another tag where we can specify a minimum or fixed height!

**Comment by bommariusser** [comment]
@ckibsen true :) it can happen that validation can fill more then one line, although it's not best practice. Thanks for your answer :)

**Comment by jakobe** [comment]
**Tech refinement** This should be based on whether the slotted input/textarea/radio etc is required or not (automatically reserve space for validation errors if required)

**Comment by bommariusser** [comment]
maybe we even should showcase that better in the cookbook? that is: how to make required or not required input fields? and how we want people to "make" a optional input field? @RasmusKjeldgaard @jakobe visually and technically ;)

![Skærmbillede 2021-04-14 kl  07 37 03](https://user-images.githubusercontent.com/49033002/114659574-2a443b00-9cf4-11eb-805c-f94d2acda2e6.png)

**Comment by RasmusKjeldgaard** [comment]
Yes, it should be doable to show how to wire it up a form field in a Reactive and Template-driven Angular form. 

Then it would showcase more like the [https://cookbook.kirby.design/home/showcase/radio](radio) **ngForms** example.

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
