### ISSUE TITLE
[BUG] Transitions are slower on iOS 14

### ISSUE THREAD

**Issue by Lars-Bruun** [kirbydesign/designsystem#1114]
**Describe the bug**
Transitions are running too slow with iOS 14 Beta.

- List drill-down (right to left slide)
- Modals (full screen AND alerts) (bottom to middle slide)
- Drawers

**To Reproduce**

List drill down
1. Go to 'Faste betalinger'
2. Click on 'BS-aftale'

Modal alert
1. Go to 'Faste betalinger'
2. Click on 'Loan' (bottom of list)

Modal full screen
1. Go to 'Til dig'
2. Click on 'Overfør og betal'

Drawer
1. Go to 'Til dig'
2. Click on 'Overfør og betal'
3. Click on 'Vælg modtager'

**Kirby version**
- [e.g. 1.2.63]

**Expected behavior**
Transitionerne kører hurtigere med iOS 13

**Screenshots**
Video clips are not supported in Github.

**Please complete the following information:**
- OS: iOS 14.0
- Channel: DRBMock
- Build: #38667

**Additional context**
Compare with iOS 13 app, to see transitions difference

## Tasks:
- [ ] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [ ] Create Fix Branch
- [ ] Create test reproducing the error
- [ ] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch

**Comment by bommariusser** [comment]
@Lars-Bruun https://forum.ionicframework.com/t/animation-speeds-on-ios-14/191777/6 they are looking into it as far as i can understand :)

**Comment by bommariusser** [comment]
Det kan også godt være at ios selv fikser det når de releaser. svært at sige 👍

**Comment by jakobe** [comment]
@Lars-Bruun Is this issue still relevant after iOS14 was released? I see Ionic has closed their issue...

**Comment by Lars-Bruun** [comment]
Just retested. Fixed with current releases of iOS 14

**Comment by Lars-Bruun** [comment]
@jakobe Har lukket issue :)
