### ISSUE TITLE
[Enhancement] Toolbar subtitle

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#1127]
**Is your enhancement request related to a problem? Please describe.**
We would like to be able to insert a subtitle below the page-title in the toolbar
![Skærmbillede 2020-09-01 kl  08 03 28](https://user-images.githubusercontent.com/49033002/91800638-a4bebf80-ec29-11ea-84a6-f44531f834cc.png)

Subtitle should be sized in XS (12 px, regular center)

See also: https://zpl.io/anDWO4x

ATTENTION: Remember that the kirby-page both has a title and toolbarTitle, and a *kirbyPageTitle directive

**Comment by hafstad** [comment]
@bommariusser Should the subtitle be visible on canvas? IE when page isn't scrolled yet

**Comment by bommariusser** [comment]
@hafstad i think it should be variable like the toolbar title. The only usecase we have for this right now is on "kontoliste" where you scroll both page-title and "page-subtitle" out of the view and get a sticky title+subtitle 

![Skærmbillede 2021-02-16 kl  15 14 25](https://user-images.githubusercontent.com/49033002/108074645-be35b580-7069-11eb-957d-5d8e3561b95f.png)

but there are probably other usecases where you start with both toolbartitle and toolbarsubtitle and have no sticky title.

Tbh i think https://github.com/kirbydesign/designsystem/issues/1171 is more important in regards to subtitle at this point. In this usecase its always visible

**Comment by alxzak** [comment]
Toolbar has been moved to https://cookbook.kirby.design/home/showcase/page and issue is not relevant.
