### ISSUE TITLE
[BUG] Attention level three button loses border on focus

### ISSUE THREAD

**Issue by SilverGull** [kirbydesign/designsystem#1130]
**Describe the bug**
In native app or browser in mobile device mode, the kirby button at attention level 3 loses its border when pressed (focused). It does not disappear on web.

**To Reproduce**

1. Go to https://cookbook.kirby.design/home/showcase/button
2. Set the browser in mobile device mode
3. Click on attention level 3 button
4. See that the border disappears
5. Click somewhere else on the page
6. See that the border reappears

**Kirby version**
- 1.2.68

**Expected behavior**
I expect the border not to disappear (like web)

**Screenshots**
![Screenshot 2020-09-07 at 08 51 14](https://user-images.githubusercontent.com/43959200/92356993-5d33aa00-f0e7-11ea-8a18-43a8d3cf3ac3.png)

**Please complete the following information:**
- OS: MacOS, Android native
- Browser Chrome in mobile mode
- Browser version 85

**Additional context**

## Tasks:
- [ ] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [ ] Create Fix Branch
- [ ] Create test reproducing the error
- [ ] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch

**Comment by bommariusser** [comment]
the screenshot is taken from the cookbook? @SilverGull Can you also make a screenshot on how it looks on a background that is not white? :) Thanks!
