### ISSUE TITLE
[BUG] (iPhone) unnecessary tactile feedback end of reorder list

### ISSUE THREAD

**Issue by MGKBankdata** [kirbydesign/designsystem#1131]
**Describe the bug**
Addtional and unnecessary tactile feedback at end of list.
Marvin confirms the bug.

**To Reproduce**
1. Go to "Menu" -> "Investering" -> "Indstillinger" (3 small dots) -> "Sortering"
2. Click and hold on the list icon infront of either "Depoter" or "Værdipapirer"
3. Drag the element to the bottom of the screen
4. Notice 1 tactile feedback at the end of the list and 1 tactile feedback when leaving the list. Neither should be there.

**Kirby version**
1.2.68

**Expected behavior**
Tactile feedback should only be triggered when elements swap places.

**Screenshots**
N/A

**Please complete the following information:**
iPhone XS Max
iOS 13.7

**Additional context**
N/A

## Tasks:
- [ ] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [ ] Create Fix Branch
- [ ] Create test reproducing the error
- [ ] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch

**Comment by jakobe** [comment]
@bommariusser Can you verify this?

**Comment by jakobe** [comment]
@MGKBankdata Could you please add a screenshot? 🙏🏻

**Comment by bommariusser** [comment]
@jakobe yes i can. just verified ;)

**Comment by Fuzzy3** [comment]
This works by design
