### ISSUE TITLE
[Enhancement] Option to use dark color scheme for Kirby page toolbar

### ISSUE THREAD

**Issue by mvindahl** [kirbydesign/designsystem#1132]
**Is your enhancement request related to a problem? Please describe.**

We'd like to be able to optionally use a dark color scheme for the toolbar of a Kirby page to clearly distinguish the header from the contents.

**Describe the solution you'd like**

We suggest an optional attribute `headerColorScheme` on the `<kirby-page>`. Legal values are `light` and `dark`, defaulting til `light` if not specified.

When set to dark, we suggest that the background color uses the tertiary color from the color scheme, and the text color changes to a light gray.

**Describe alternatives you've considered**

**Additional context**
The header and the toolbar color should follow along in its color.

**Comment by bommariusser** [comment]
@mvindahl jeg har samlet alle opgaver omkring header og toolbar i denne opgave https://github.com/kirbydesign/designsystem/issues/1155 og ændret lidt i beskrivelsen af denne opgave: "The header and the toolbar color should follow along in its color." hvad tænker du?

**Comment by jakobe** [comment]
@bommariusser Can you align this with #1155 (optionally include it in that [TRACKING] issue)? 🙏🏻

**Comment by jakobe** [comment]
@mvindahl Could you plz include a screenshot? 🙏🏻

**Comment by flemcito** [comment]
Closing this as it is covered by #1155
