### ISSUE TITLE
[Enhancement] Optional top section of Kirby page contents, visually blending with toolbar

### ISSUE THREAD

**Issue by mvindahl** [kirbydesign/designsystem#1133]
**Is your enhancement request related to a problem? Please describe.**
We'd like a way to render the top of the Kirby page contents so that it visually blends with the toolbar. This includes color scheme (see #1132) as well as removing the 16px left and right margins that are applied to the rest of the contents. It is to be used for rendering the visual representation of a card.

**Describe the solution you'd like**
I think we'd need a new `<kirby-page-top-content>` tag to accomplish this. It would be the (optional) first child of the `<kirby-page>`, and it would render its contents within the `<ion-content>` to make it scroll with the rest of the regular contents. 

If the toolbar is in dark mode (see #1132) then the top content would render using the same background and text colors.

**Describe alternatives you've considered**
In some ways this is similar to a custom page title but the custom page title play together with the toolbar title in a way that this is not intended to. Still, I'm a bit undecided as to whether we need a new tag or a way to customize custom page titles.

**Additional context**
As mentioned, this is designed to work with the enhancement suggested in #1136.

It should be carefully considered how the UI should work if there is *both* a page title and a page top content, or if we should mark this as an error. In the same vein, we should consider if the proposed top content is conceptually overlapping with the concept of a page title or if it's a conceptually different beast.

Special cases which we don't restrict but which we may want to flag as errors:
- <kirby-page-top-content> not being the first child; this would render to top content anywhere but the top.
- multiple <kirby-page-top-content> tags: this would render multiple sectipns

Lars Bruun has wireframes which suggest that the new section may in the future adjust dynamically to scrolling, maybe decreasing its height, then becoming sticky. This is not in scope for now.

**Comment by bommariusser** [comment]
@mvindahl maybe we can make a task that sums the "header" task up - eg. the reason we need these tasks you made? :) or is this it?

**Comment by bommariusser** [comment]
@mvindahl Jeg tænker at det er Headeren der bestemmer toolbar farve, hvad tænker du?

**Comment by bommariusser** [comment]
@mvindahl men rent lavpraktisk så skal vi afkoble headeren fra page sådan at det bliver nemmere at skifte fra den ene header til den anden eller hvad tænker du? Jeg tænker i hver fald den del er en anden opgave, men er ikke sikker @mvindahl

**Comment by jakobe** [comment]
@mvindahl Could you plz add a screenshot? 🙏🏻

**Comment by flemcito** [comment]
Closing this as it is covered by #1155
