### ISSUE TITLE
[Enhancement] Access to runtime-evaluated brand colors

### ISSUE THREAD

**Issue by askarby** [kirbydesign/designsystem#1134]
**Is your enhancement request related to a problem? Please describe.**
To support multiple banks in DRB, we need access to various brand colors, that are runtime evaluated. That is, we would like to get the branded `primary`, `secondary`, `tertiary`... colors, if we acquire them based on SCSS variables, we get the "stock" kirby colors.

This is a problem for Team 3 and Team 5, as we need programmatic access to colors, to style charts (in Highcharts / Charjs)

**Describe the solution you'd like**
A class / (set of) functions that acquires the runtime evaluated values (computed values) of the CSS variables, eg.:

```
KirbyColors.get('primary')
```

**Describe alternatives you've considered**
1. Acquiring the values in DRB (from the CSS variables there (but decided not to, since it putting "styling" into kirby (hence you'd have an expectation, albeit a wrong one, that you can "get it back")
2. Push our chartjs based graph support into kirby (but we don't have the resources to do so, at this moment in time)

**Additional context**
N/A?

**Comment by jakobe** [comment]
@askarby We need more input on this? Guessing you need the hex code? Why can't you evaluate the css vars and get the computed color from there?

**Comment by askarby** [comment]
Since charts are being moved from DRB into Kirby, I think this can be closed.
