### ISSUE TITLE
[Enhancement] Section sort order

### ISSUE THREAD

**Issue by jonasjensen-brolstark** [kirbydesign/designsystem#114]
**Is your enhancement request related to a problem? Please describe.**
When using sections on the kirby list, the sections are sorted alphabetical natively and not in the order sections are created.

**Describe the solution you'd like**
I would like to be able to control the order of the sections, both natively and on web.

**Describe alternatives you've considered**
The `getSectionName` callback could return either a string (to be backwards compatible) or a object like:

```javascript
{
  order: 1;
  name: 'name of section';
} 
``` 

**Work around**
For now a workaround could be:

The `getSectionName` callback should look like:

```typescript
getSectionName(item: any): string {
  return `${item.magicSortKey}@${item.section}`
}
```

```typescript
cleanSectionHeader(section: string): string {
  if (section) {
    return section.split('@')[1];
  }
  return '';
  }
```

the views should then be:

```html
<kirby-list [items]="transactions" [getSectionName]="getSectionName">
  <div *kirbyListSectionHeader="let section" class="section-header">
    {{ cleanSectionHeader(section) }}
  </div>
</kirby-list>
```
```html
<kirby-list [items]="transactions" [getSectionName]="getSectionNameCallback">
  <FlexboxLayout *kirbyListSectionHeader="let section" class="section-header">
    <Label text="{{ cleanSectionHeader(section) }}"></Label>
  </FlexboxLayout>
</kirby-list>
```

**Comment by labanos** [comment]
@jonasjensen-brolstark is this still a relevant issue or has it been fixed in a different way?

**Comment by jonasjensen-brolstark** [comment]
Use the workaround if sorting is needed.
