### ISSUE TITLE
[Enhancement] Alerts should be notification color, not primary (No branding)

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#1142]
**Is your enhancement request related to a problem? Please describe.**
Right now our alerts have branding inside them and they use a primary color on buttons. This hasn't be a problem in the Jyske Bank context, because they are so alike (branding & success). In another context like sydbank, almbrand and so on this isn't what we expected.

**Describe the solution you'd like**
Alerts can by definition be either warning or destructive. The buttons inside them can either be destructive (for destructive actions) or success (for warning alerts that are always built upon at least one success button.

<img width="1216" alt="Skærmbillede 2020-09-17 kl  08 37 49" src="https://user-images.githubusercontent.com/49033002/93429255-26b51680-f8c1-11ea-8670-1a6637573a30.png">

**Describe alternatives you've considered**
The primary color on our alerts should be replaced with a success color.

This will have an effect like this on a bank like Sydbank:

<img width="1026" alt="Skærmbillede 2020-09-17 kl  08 40 44" src="https://user-images.githubusercontent.com/49033002/93429447-78f63780-f8c1-11ea-8bc9-23a19ae4184f.png">

**Additional context**
We can't do this until we allow buttons to be notification color - RIght now they only can take danger when looking at our notification color.

**Comment by jakobe** [comment]
**Tech refinement**
It should still not be possible to set the color of the button to success through the API.
Instead we should style the button through it's host-context of an alert.
