### ISSUE TITLE
[Enhancement] Buttons should be able to take all notification colors

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#1143]
**Is your enhancement request related to a problem? Please describe.**
We have different tasks that are reliant on that buttons can take notification colors success & warning.

Success on Alerts: https://github.com/kirbydesign/designsystem/issues/1142
Toggle buttons: https://github.com/kirbydesign/designsystem/issues/626

**Describe the solution you'd like**
Buttons should be able to take all notification colors...

**Comment by lydemann** [comment]
After conversation with @jakobe  we agreed to do as in FlagComponent.
