### ISSUE TITLE
[Enhancement] Horizontal Button groups

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#1144]
**Is your enhancement request related to a problem? Please describe.**
Right now we need to manually place buttons side by side to create a button-group like functionality.

Those buttons also always have the size of the original button; the size of the amount of the text inside the button, which ends up in something like this:

![Skærmbillede 2020-09-17 kl  10 57 13](https://user-images.githubusercontent.com/49033002/93449033-8a950a80-f8d4-11ea-9514-c8f034bd3fde.png)

**Describe the solution you'd like**
We want some button groups that have the same functionality like 50/50, which can be placed either inline or in a footer. 

![Skærmbillede 2020-09-17 kl  10 54 48](https://user-images.githubusercontent.com/49033002/93449269-d5af1d80-f8d4-11ea-8fe3-a383bd61da18.png)

**Additional context**
See also: https://zpl.io/25W9NLo for reference.

**Comment by MadsBuchmann** [comment]
@bommariusser: As part of estimating tasks on our radar @jkaltoft and I have been discussing this for a bit. We got a couple of questions 😄

We're doubting whether it is really necessary to introduce a whole new layouting component to the designsystem to place buttons next to each other with the same width. Is it not something that is better handled by consumers of Kirby? Or are there rules that would potentially be 'encoded' into the component, such as which button can have which attention levels etc.

Also can it handle more than two buttons? How would it behave in the instance of 3, 4, 10 buttons?
