### ISSUE TITLE
[Enhancement] Add color to Flag

### ISSUE THREAD

**Issue by sorenfruergaard** [kirbydesign/designsystem#1146]
**Is your enhancement request related to a problem? Please describe.**
No, but we would like to use color "medium" on kirby-flag

**Describe the solution you'd like**
Add color "medium" to flag themeColors

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

![Screenshot 2020-09-18 at 10 09 42](https://user-images.githubusercontent.com/2383744/93573260-3010b280-f997-11ea-8b09-86169cb5c84f.png)

**Comment by bommariusser** [comment]
hey @sorenfruergaard - det er noget gammelt screenshot du kigger på :) For et halvt år siden har vi 'minimeret' antal af grå farver, for at gøre valget nemmere. Har du et screeen? :)

**Comment by sorenfruergaard** [comment]
@bommariusser Screenshot er lavet ved at selv at tilføje farven i gennem koden.
Men issuet kan bare lukkes. Vi går bare med "semi-light" som findes allerede.
