### ISSUE TITLE
[Enhancement] Add custom kirby icons using an icon registry service

### ISSUE THREAD

**Issue by lydemann** [kirbydesign/designsystem#1148]
**Is your enhancement request related to a problem? Please describe.**
The enhancement request is related to the problem of custom icons being overridden if it is imported in different places because it is using Angular DI.

**Describe the solution you'd like**
I want to be able to merge icons imported from different places using a KirbyIconRegistry which is a service containing a map of icons.
To begin with, I think we should still support the DI way of adding custom icons but combining the icons with the icons from the icon registry service in the icon component.

**Describe alternatives you've considered**

**Additional context**
The solution with the icon registry service is inspired from Angular Material:
https://material.angular.io/components/icon/api

**Comment by MadsBuchmann** [comment]
closed by #1157
