### ISSUE TITLE
[Enhancement] Header Item(s)

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#1152]
**Is your enhancement request related to a problem? Please describe.**
Right now we only have 1 Header which is put into a Page, so when making something else we have to customize quite a lot to make that work. See also: https://cookbook.kirby.design/home/showcase/page

See also this task which is very related (the background for the header item) https://github.com/kirbydesign/designsystem/issues/1133

**Describe the solution you'd like**
In 

V1. 
- PageTitle (should move to toolbar like it does now)
- (optional) Display
- (optional) Description
- Right side Primary Action
 or Avatar (Should change placement on big screens)

V2.
- Ability to changes size of components, dependant on the screensize (Avatar & Buttons in the Buttongroup)

V3.
- Buttongroups as a part of the header which switch placement and function dependant on size and amount. 

Buttongroups are here as a task https://github.com/kirbydesign/designsystem/issues/1144

**Additional context**

With avatar on right Side:
![Skærmbillede 2020-09-25 kl  10 16 18](https://user-images.githubusercontent.com/49033002/94247913-0e2aa900-ff1e-11ea-955c-7d68c1610c8a.png)
![Skærmbillede 2020-09-25 kl  10 16 02](https://user-images.githubusercontent.com/49033002/94247925-0ff46c80-ff1e-11ea-8476-c5dcd8d4021e.png)

With primary action on right side:
<img width="1101" alt="Skærmbillede 2020-09-28 kl  21 17 16" src="https://user-images.githubusercontent.com/49033002/94475911-0f82fc80-01d0-11eb-80d4-81b670e5969f.png">

And there are more examples...

**Comment by jakobe** [comment]
@bommariusser I think this needs to split up into several subtasks and make this issue a [TRACKING] issue (see other [TRACKING] issues for an example). Also needs to be linked with #1155

**Comment by flemcito** [comment]
Closing this, as it is covered by #1155
