### ISSUE TITLE
[BUG] Flagged item example relies upon privately defined CSS

### ISSUE THREAD

**Issue by mvindahl** [kirbydesign/designsystem#1161]
**Describe the bug**
The flagged item example at https://cookbook.kirby.design/home/showcase/item shows how to flag an item by rendering a dot at the leftmost edge of an item. However, this HTML in this example will not work in DRB unless the example specific CSS is also copied from Kirby.

E.g., see https://github.com/kirbydesign/designsystem/blob/master/apps/cookbook/src/app/examples/item-example/examples/flagged.ts#L18

Identical CSS is "inlined" into several other example files; search for ".flag.success" acress the files. 

**To Reproduce**

Make a verbatim copy of the HTML from the flagged example and dump it into DRB. Observe that no colored dot is visible in the item.

**Kirby version**
- 1.2.83

**Expected behavior**
I'd expect the example to be "batteries included", i.e. I would expect the required styles to be delivered as part of the Kirby stylesheets, ensuring consistency in rendering

_or_

I would like the Kirby cookbook to clearly document the current limitations

**Screenshots**

**Please complete the following information:**
- OS: [e.g. Windows, MacOS, iOS]
- Browser [e.g. Chrome, Safari]
- Browser version [e.g. 22]

**Additional context**
A very obvious workaround is to just copy the relevant CSS to my local stylesheet in DRB. This works like a charm, of course.

## Tasks:
- [ ] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [ ] Create Fix Branch
- [ ] Create test reproducing the error
- [ ] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch

**Comment by jakobe** [comment]
Will be fixed by #498
