### ISSUE TITLE
[BUG] Focus on segmented control removes borders (background?) on Chrome and Android

### ISSUE THREAD

**Issue by lydemann** [kirbydesign/designsystem#1169]
**Describe the bug**
Focus on segmented control removed borders on Chrome and Android

**To Reproduce**

Button hover:
1. Click on segmented control with chrome or Android device
2. See borders are gone

**Kirby version**
- [e.g. 1.1.10]

**Expected behavior**

**Please complete the following information:**
- Samsung Galaxy S8-S10,

**Additional context**

## Tasks:
- [ ] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [ ] Create Fix Branch
- [ ] Create test reproducing the error
- [ ] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch

**Comment by bommariusser** [comment]
@lydemann har du screens?

**Comment by MikaelKristoffersenBankdata** [comment]
![IMG_3363](https://user-images.githubusercontent.com/55275492/99807694-298deb00-2b40-11eb-8959-dc134068ed3a.jpg)

Here you go @bommariusser

**Comment by RasmusKjeldgaard** [comment]
Cannot reproduce anymore
