### ISSUE TITLE
[BUG] Keyboard offset makes the modal bigger on input focus

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#1170]
**Describe the bug**

**To Reproduce**

1. Go to a modal like "overfør & betal" or "rediger email"
2. Click on a input/form

**Expected behavior**
The modal should keep its size. The offset might have been made to make the view scroll up

**Screenshots**
<img width="995" alt="Skærmbillede 2020-10-09 kl  18 16 28" src="https://user-images.githubusercontent.com/49033002/95607393-f85bce80-0a5b-11eb-9a66-cd008c24c842.png">
<img width="967" alt="Skærmbillede 2020-10-09 kl  18 16 23" src="https://user-images.githubusercontent.com/49033002/95607402-fb56bf00-0a5b-11eb-8f63-e00244a3a02d.png">

**Please complete the following information:**
- OS: [e.g. Windows, MacOS, iOS]
- Browser [e.g. Chrome, Safari]
- Browser version [e.g. 22]

**Additional context**

## Tasks:
- [ ] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [ ] Create Fix Branch
- [ ] Create test reproducing the error
- [ ] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch

**Comment by labanos** [comment]
closed by #1196
