### ISSUE TITLE
[Enhancement] Subtitle in Modal header

### ISSUE THREAD

**Issue by henrikvoetmand** [kirbydesign/designsystem#1171]
**Is your enhancement request related to a problem? Please describe.**
Modals can be used in many situations and we need a header that can contain more information.

**Describe the solution you'd like**
The ability to have a subtitle below the title in a Modal header.
E.g A step process is displayed in a modal, the Title is describing the process and the Subtitle is describing each step.

1. The title should be p bold (16pt) 
2. The subtitle should be xs (12pt) and both the title and subtitle should be aligned center with the close button.

**Additional context**
See also zeplin: https://zpl.io/V1PXWv4

and this screenshot
![02 Experimental:Modal:01 Mobile:01 Modal:02 + Subtitle](https://user-images.githubusercontent.com/49033002/99671599-89b65b80-2a72-11eb-9aa5-8c0ac8e4903b.png)

**Comment by bommariusser** [comment]
@henrikvoetmand kan du evt. prøve at sætte nogen labels på hvilket komponent det er, samt at beskrive udfordringen? Altså at modaler til tider godt kan trænge til lidt mere forklaring  osv. ? :)

**Comment by henrikvoetmand** [comment]
@bommariusser - hvad siger du til beskrivelsen nu? skal der mere til?

**Comment by bommariusser** [comment]
kan du flytte den beskrivelse i toppen under "related issue" ? :D @henrikvoetmand

**Comment by henrikvoetmand** [comment]
?? :-)
