### ISSUE TITLE
[Enhancement] Page progress in modal header

### ISSUE THREAD

**Issue by henrikvoetmand** [kirbydesign/designsystem#1174]
**Is your enhancement request related to a problem? Please describe.**
Modals can be used in many situations and we need a header that can contain more information. 

**Describe the solution you'd like**
The ability to have the progress circle in a Modal header. The progress circle is of size Small and Should only support text since an icon isn't really relevant in this context.

A step process is displayed in a modal. To visually indicate the process and the progress, we aim to use the Progress Circle in the Modal header. The Progress Cricle will be placed to the left of the Title/Subtitle area in the header and is center aligned with both the header (&Subtitle) and the close button.

specs: 
- The title should be sized to a p bold (16pt) instead of the h2, as soon as a progresscircle is combined with the modal.

**Additional context**
zeplin:
- With subtitle: https://zpl.io/bPZe5LL
- With title only: https://zpl.io/2GrL6z3 

Right now there is no need for support in the drawer. If you have to use it you should use a modal. 

![02 Experimental:Modal:01 Mobile:01 Modal:03 ProgressCircle](https://user-images.githubusercontent.com/49033002/99671910-021d1c80-2a73-11eb-8fc8-df01ef5f318b.png)

![Skærmbillede 2020-12-04 kl  13 04 02](https://user-images.githubusercontent.com/49033002/101161548-4262ca00-3631-11eb-870a-77d81138016e.png)

### Kick Off:

- [x] Ensure the enhancement is `UX refined` and aligned with UX 
_The component and/or enhancement should be published and available in the [Kirby Styleguide on Zeplin](https://zpl.io/258pXGj)_
- [x] Ensure the enhancement has been `Tech refined` with @kirbydesign/kirby-guild and this issue is updated with a clear implementation description  
_This issue should be in the [Ready to do](https://github.com/kirbydesign/designsystem/projects/1#column-4590936) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1) before starting implementation)_
- [x] Assign yourself to this issue and move it to the [In progress](https://github.com/kirbydesign/designsystem/projects/1#column-4590937) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1)

### Code:

- [x] Create Feature Branch from [master branch](https://github.com/kirbydesign/designsystem/tree/master)
- [x] Create a draft implementation and push to Github
- [x] Ask a member of @kirbydesign/kirby-guild for a WIP review by creating a draft Pull Request
- [x] Implement unit tests
- [x] Update Cookbook Examples and Showcase, i.e. see [Radio](https://cookbook.kirby.design/home/showcase/radio)  
_Also remember to add any relevant new API documentation_

### Review:

- UX review:
  - [x] Ensure implementation is correct in relation to the UX design and the [Kirby Styleguide on Zeplin](https://zpl.io/258pXGj)
  - [x] With UX agree on the version of the implementation
- Code review:
  - [x] Open a pull request (or mark the existing draft PR as `Ready for review`) and ask @kirbydesign/kirby-guild for a review  
_Remember to add `closes #issueno` to the description of the PR._
  - [ ] Once approved, merge feature branch/PR to master
- [ ] Ask a member of @kirbydesign/kirby-guild to add a link to component showcase from Kirby Component Status and update the version number

:tada: Celebrate

**Comment by MartinSkovsen** [comment]
What would the best approach be to achieve this? AFAIK there aren't any straight forward way to solve this with current components. I could think of adding some container-like CSS to kirby-page-title, but that wouldn't be coherent. Not to mention that it's preferable to center the title.

**Comment by labanos** [comment]
@MartinSkovsen long term - we might want to align the modal header more with how page works - but for now it would be ok to extend so that the modal header can optinally add a progress circle. That is extend the current and do some styling.

**Comment by MartinSkovsen** [comment]
As per a brief discussion with @jakobe, adding CSS properties for display, content justification and item alignment to kirby-page-title seems like the right solution regardless of the particular content injected via ng-content. I'll explore, and probably  create a draft pull request, once I've found a good solution for managing content (briefly explained: center aligning text, left aligning content, etc.) in kirby-page-title.

**Comment by labanos** [comment]
I'll move it to in progress =)

**Comment by MartinSkovsen** [comment]
After having @bommariusser and @henrikvoetmand review the current PR on this, we've decided that custom content should be enabled for modal header start slot instead. After having discussed a technical solution with @jakobe I can now start working on the new solution where we move embedded content based on an attribute slot=start to parent, which in this case is ion toolbar.
