### ISSUE TITLE
[Enhancement] Safe-area on Modal should be the same as on Page/Tabbar

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#1176]
**Is your enhancement request related to a problem? Please describe.**
Safe-area on modal is different then on page, which makes our content in the modal come pretty close to the edge and make it hard to read and interact. 

It is right now something around:
- Page: 22px
- Modal: 16px

The safe-area is something we get from Ionic and @hafstad mentioned that this is something we don't change. 

![Skærmbillede 2020-10-27 kl  11 53 30](https://user-images.githubusercontent.com/49033002/97292053-075bc280-184b-11eb-9105-859024193556.png)

**Describe the solution you'd like**
We would like it to be the same and in this case the 22px

**Comment by jakobe** [comment]
This might already be fixed? Need to verify...

**Comment by alxzak** [comment]
@bommariusser is this stille relevant?
