### ISSUE TITLE
[BUG] List swipe is performing poorly on IPad

### ISSUE THREAD

**Issue by lydemann** [kirbydesign/designsystem#1177]
**Describe the bug**
List swipe is performing poorly on IPad (transaction list and saved recipients in Relationsbank).
It is lagging on IPad, especially with large lists.
There is a small delay when initially starting the scroll for big lists with Ipad (IOS14)

**To Reproduce**

**Swipe**
1) Go to transaction list
2) Swipe right on item
3) See it is "laggy"

**Slow initial scroll**
1) Go to transaction list
2) Do fast scroll down
3) See there is a delay

**Kirby version**
- 1.2.90

**Expected behavior**
List swipe and initial scroll should be smooth

**Screenshots**

**Please complete the following information:**
- Ipad with IOS 14

**Additional context**

## Tasks:
- [ ] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [ ] Create Fix Branch
- [ ] Create test reproducing the error
- [ ] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch

**Comment by Kristian2332** [comment]
Nedenstående film viser hvor 'delay på scroll' og 'Delay/laggy swipe' ser ud i praksis. - Skriv gerne hvis I har brug for mere info derom. - Optagelserne er lavet på en iPad 2017 (iOS14). 

[IMG_1530.MOV.zip](https://github.com/kirbydesign/designsystem/files/5465927/IMG_1530.MOV.zip)
[IMG_1529.MOV.zip](https://github.com/kirbydesign/designsystem/files/5465928/IMG_1529.MOV.zip)

**Comment by labanos** [comment]
Closing - as this issues has been mitigated by other efforts.
