### ISSUE TITLE
[COMPONENT] Accordion

### ISSUE THREAD

**Issue by henrikvoetmand** [kirbydesign/designsystem#1179]
**Describe the solution you'd like**
The accordion component delivers large amounts of content in a small space through sections that can be expanded and collapsed. The title give the user a high level overview of the content allowing the user to decide which sections to read.
**States**
The accordion component has two main states: collapsed and expanded. The chevron icon at the end of the accordion indicates which state the accordion is in. The chevron points down to indicate collapsed and up to indicate expanded. To further indicate the states, the title text will be regular when collapsed and bold when expanded.

Accordions begin by default in the collapsed state with all content panels closed. Starting in a collapsed state gives the user a high level overview of the available information.

A user can then independently expand each section of the accordion allowing for multiple sections to be open at once.
**Interaction**
Users can trigger a state change by clicking on the chevron or clicking anywhere in the title area.
**Styling**
Title text should support text in 2 lines.

**Describe alternatives you've considered**
An alternative solution could be to just have a long scrollable text page with no expandable sections.
Other solution could be sections as seperate "pages" with navigation.

**Additional context**
Zeplin link:
https://app.zeplin.io/styleguide/5e734ec04ee3d6bac20654e2/components?cseid=5fa2b58acbcb0e8512f515ee

![Accordion - collapsed - 1 2 lines](https://user-images.githubusercontent.com/71710012/98557802-f0828a80-22a4-11eb-8215-076a49d6a954.png)
![Accordion - expand](https://user-images.githubusercontent.com/71710012/98558001-38091680-22a5-11eb-8925-c53038e05791.png)

Furthermore. You should be able to place the accordion inside a card, so the background gets white with rounded corners like this screenshot, but without the subtitle:
![Screenshot 2020-11-18 at 14 15 45](https://user-images.githubusercontent.com/1279879/99535006-98d0d700-29a8-11eb-85af-aec3eb462422.png)

Add any other context or screenshots about the feature request here, e.g. a link to the corresponding component from [Ionic](https://ionicframework.com/docs/components/)

**Tech refinement**
The accordion can be made with one "Expandable" component. The Expandable can be used alone or with several Expandables to form a list of expandables. When using the Expandable it can have 2 types of ui. The gray look or the  inside a card. 

The Expandable itself handles the different looks, according to what context it is used in. 
It should not have start-top and end-bottom border if it is used inside a card, but it should if it is used without a card wrapping it.

The component has a boolean that can be used to toggle if the content is shown

### Kick Off:

- [x] Accept Feature incl. name of component (DSL)
- [x] Update Kirby Component Status and publish to [Kirby Cookbook](https://cookbook.kirby.design)

### Code:

- [x] Create Feature Branch
- [x] Implement Skeleton Component
- Ask UX for review:
  - [ ] Ensure implementation is correct in relation to UX design
  - [ ] Define the version of the implementation + steps needed to reach version 1.0 (create [enhancement requests](https://github.com/kirbydesign/designsystem/issues/new?assignees=&labels=enhancement&template=enhancement-request.md&title=%5BEnhancement%5D))
- [x] [Implement Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Add link to showcase on Kirby Component Status (`component-status-items.ts => code.cookbookUrl`)
- [ ] Also remove `githubIssueNo` and set `status` to `ItemCodeStatus.ready`
- [x] Push commits to GitHub

### Review:

- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- Merge to master and delete branch

**Comment by HStokbro** [comment]
We need the accordion component to display big chunks of info in a simple way.
Besides the title per expandable item. We also need a sub-title. Like so:
![Screenshot 2020-11-06 at 13 45 22](https://user-images.githubusercontent.com/1279879/98367683-5b7a5a00-2036-11eb-8c56-7a131f694684.png)
