### ISSUE TITLE
[Enhancement] Calendar year navigator

### ISSUE THREAD

**Issue by karlgodtliebsen** [kirbydesign/designsystem#1185]
**Is your enhancement request related to a problem? Please describe.**
When using the Calendar Component in Applications requiring the ability to select Years directly from a larger range, it is not feasible for the user to navigate/select at year in the distant future, using the current Month based navigation

**Describe the solution you'd like**
To be able to select a year from a specified range.
The requirement calls for an easy scrollable list of years to be shown on demand, and it must be easy to scroll and select one year (within the specified range). 
The first item in the selectable list is set to the current year. When you select a year (eg. 2035) and reopens the list, the new selected year will be the first item.

**Describe alternatives you've considered**
Ionic Date Picker/Calendar and others Date pickers does not seem to fit the purpose, and as it could be just a small extension to the existing Kirby Calendar, retaining backwards compatibility, this seems to be the correct path to take.

**Additional context**
The proposed solutions has been UX refined, and based on the input a functional complete solution has been made

Default backwards compatibility mode is as shown in the cookbook:
(Is not present as long as the source is not merged into master)
https://cookbook.kirby.design/home/showcase/calendar

Proposed design when the "Selectable Year" extension functionality is enabled:
**Mobile**
![image (1)](https://user-images.githubusercontent.com/326808/98295828-5b387b00-1fb2-11eb-8ab0-3c44cde43a2f.png)

![Vælg dato - dropdown](https://user-images.githubusercontent.com/71710012/100078708-15016980-2e44-11eb-8b5d-1db79019280b.png)

**Tablet**

![Tablet-YearSelect](https://user-images.githubusercontent.com/71710012/100101184-34a78a80-2e62-11eb-9263-a218293bfc32.png)

![Tablet-YearSelectDropdown](https://user-images.githubusercontent.com/71710012/100101196-38d3a800-2e62-11eb-86d1-6245f037b8df.png)

The implementation ensures that the component keeps it look and feel when no "Selectable Year" extension functionality is enabled

**See also zeplin:**

_mobile_: https://zpl.io/VQZNQqk and https://zpl.io/aRZ4Gqp
_tablet_: https://zpl.io/2Gr5xDr and https://zpl.io/b6qw8nm

**Comment by MartinSkovsen** [comment]
@labanos As per the issue template instructions can you remove NOT PRIORITIZED label from this issue? It's prioritized [here](https://github.com/kirbydesign/designsystem/milestone/13).

**Comment by MartinSkovsen** [comment]
@henrikvoetmand Hvad mangler vi for at fjerne NOT UX REFINED label fra den her?

**Comment by henrikvoetmand** [comment]
@MartinSkovsen Vi skal lige have tablet versionen ind i zeplin - det satser vi på at nå i morgen :-)

**Comment by bommariusser** [comment]
done @MartinSkovsen @henrikvoetmand og ændret i kommentaren

**Comment by karlgodtliebsen** [comment]
been solved by 
https://github.com/kirbydesign/designsystem/pull/1228
