### ISSUE TITLE
[Enhancement] Checkbox - Add error state

### ISSUE THREAD

**Issue by HStokbro** [kirbydesign/designsystem#1186]
Checkboxes should have a hasError: boolean state just like the input component.
When a checkbox has error. It should get a border colored red (error color)

Also it would be nice with examples in the cookbook for checkbox states:
- Not checked
- Checked
- Disabled
- Error

Team 3 needs this for a multiple choice quiz in "online trading access"
The usecase is validation, when the user forgets to fill out anything:
https://zpl.io/awv1QOd

See also: https://zpl.io/VY3vmrk

![Screenshot 2020-11-10 at 13 55 48](https://user-images.githubusercontent.com/1279879/98676882-7dd4e600-235c-11eb-8eaf-a4dcec2d2af0.png)

**Comment by bommariusser** [comment]
So the usecase is validation, right? When you press on "next" and have not selected a checkbox? :) @HStokbro

**Comment by HStokbro** [comment]
@bommariusser yes

**Comment by bommariusser** [comment]
super @HStokbro :) we have added it in our library so it is UX refined and i'll remove the label UX
