### ISSUE TITLE
[Enhancement] endless scroll

### ISSUE THREAD

**Issue by jonasjensen-brolstark** [kirbydesign/designsystem#119]
**Describe the solution you'd like**
The Kirby list should notify the user of it, that the end of the list has been reached. That way the user should have the option to load more data into the items array given to the Kirby list. 

**Describe alternatives you've considered**
As we on native uses the RadListView, we can make use of its load more callback.  
On web i suggest we create a directive to observe on the scroll height of the list element of make a callback if it is inside a treshold.

**Comment by byNikx** [comment]
Suggestion: Most UI components (including List) should be what we call 'Dumb Components', so these components should be used only for presentation and any logic related to lazy loading or virtual scrolling should be placed inside the component where it is used.

**Comment by jonasjensen-brolstark** [comment]
> Suggestion: Most UI components (including List) should be what we call 'Dumb Components', so these components should be used only for presentation and any logic related to lazy loading or virtual scrolling should be placed inside the component where it is used.

Valid point, but is this doable in nativescript? As i see it we will need to give the Kirby list a callback that will be called when the internal used RadListView has scrolled to the end of the list.
