### ISSUE TITLE
[BUG] Android back navigation closes modal and navigate to front page (Til dig siden)

### ISSUE THREAD

**Issue by jsn-jyskebank-dk** [kirbydesign/designsystem#1191]
**Describe the bug**
Android back navigation closes modal and navigate to front page (Til dig siden)

**To Reproduce**

1. Go to 'Konto / Kort / Bestil kort'
2. Click on 'Visa Credit' - card and Order Visa Credit card flow is started in a modal view
3. Navigate forward in modal view - f.x. Chose credit max 
4. Use back-button on Android device
5. See that the modal has been closed and navigate to front page (Til dig)

**Kirby version**
- 1.2.91

**Expected behavior**
Android back navigation should navigate only one step back in history in modal

**Please complete the following information:**
- OS: Android

**Additional context**

## Tasks:
- [ ] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [ ] Create Fix Branch
- [ ] Create test reproducing the error
- [ ] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch

**Comment by bommariusser** [comment]
@Jarmila51 i talked with @neigaard yesterday and told him that a workaround could be to set focus on the modal or the "first focusable element" after opening it. I'm pretty sure that the focus is still on the "component" that opens the modal. When you have an input field in the modal and focus that component, the behavior doesn't occur i guess or @Jarmila51 ? can you try opening "overfør and betal" and go back? 

So this behavior could maybe come out of the box for all modals - as inspiration for that enhancement we could look into how carbon has solved this:

See also: https://www.carbondesignsystem.com/components/modal/accessibility

_"After the modal opens, initial focus should be set on the first focusable element in the modal. See WAI-ARIA Authoring Practices Modal Dialog Example, Accessibility Features section for best practices on setting focus."_

Although im not sure if this is a best practice.. It sounds like something you might have a hard time making "out of the box"

**Comment by bommariusser** [comment]
although i can see that you also write "Navigate forward in modal view - f.x. Chose credit max" so it sounds like that you have had focus inside the modal :)

**Comment by RasmusKjeldgaard** [comment]
Cant reproduce this anymore, please reopen issue if you still experience this
