### ISSUE TITLE
[BUG] History back navigation in modal removes modal footer

### ISSUE THREAD

**Issue by neigaard** [kirbydesign/designsystem#1192]
**Describe the bug**
In modal view on a mobile device the modal footer is removed from the DOM when using history back navigation to a previous view in the modal when using modal navigation.

**To Reproduce**
We have made workarounds to this and are not using history back navigation, so there are no active code demonstrating this. It can be reproduced by using history back navigation from a component that are using modal navigation, e.g. card-account-list.component.ts, by using location.back().

**Kirby version**
- 1.2.91]

**Expected behavior**
History navigate back must navigate back to the previous component and if that is in a modal view it must show the modal footer if such footer is used.

**Please complete the following information:**
- OS: Android, iOS

## Tasks:
- [ ] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [ ] Create Fix Branch
- [ ] Create test reproducing the error
- [ ] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch

**Comment by bommariusser** [comment]
@neigaard når du siger history back er det så browser back? man kan vel ikke lave history back på en iOS, medmindre man bruger swipe? :) @Jarmila51 referer også til noget android back i #1191 - Hvis man:
1. åbner https://cookbook.kirby.design/examples/modal 
2. åbner modal outlet
3. går til side 2 og navigerer tilbage med browser back så 
4. kommer man tilbage til side 1 og så lukker man modalen.

men det kan jo godt være at android back og browser back håndteres forskelligt. android back og history back burde vel være det samme, men i beskriver to forskellige use-cases eller hvordan? :D

Men jeg forstår godt at der er en udfordring med back i en modal og footer, måske i kunne samle det i en samlet story eller synes i det er forskellige ting? Den gemmer en tilbagenavigation også i routen selvom den burde fjerne den fra routen?

**Comment by neigaard** [comment]
Det er ikke relateret til #1191, det er hvis man fra koden bruger location.back() (som ja, er det der burde ske ved Android back navigation, men denne fejl sker ligemeget om man kan det eller navigere back i history via kode). Back navigation virker hvis man kalder det fra kode, men modal footer fjernes fra DOM på mobile enheder. @hafstad kender til probemet og kan måske uddybe.

**Comment by bommariusser** [comment]
Du må lige demo det @neigaard fordi jeg kan ikke genskabe det :p

**Comment by neigaard** [comment]
Vi har ingen steder dette kan demoes, kun ved at "hacke" noget kode og kører det på en device.

E.g. Hack approve.component.ts og inject Location ('@angular/common') og erstat indholdet af back metoden med:
`back() {
    this.location.back();
  }`
og naviger helt til approve og naviger back med footer back knappen.

**Comment by RasmusKjeldgaard** [comment]
Can no longer reproduce, most likely solved by https://github.com/kirbydesign/designsystem/pull/2238
