### ISSUE TITLE
[BUG] Weird animation between two kirby pages

### ISSUE THREAD

**Issue by ckibsen** [kirbydesign/designsystem#1203]
**Describe the bug**
When navigating from on Kirby Page to another by pressing an item in a list, the new Page is rendered and animation starts, but a "column" with content from the previous page is shown along with the animation. 

**To Reproduce**

See https://jira.bdpnet.dk/browse/RM-3226 for video of the error, as well as customerId used

1. Go to DRB staging, customer Julie
2. Click on 'Faste betalinger'
3. Press the first item under 'Faste overførsler'
4. See the weird animation behaviour

**Kirby version**
- [e.g. 1.2.91]

**Expected behavior**
A nice, smooth animation

**Screenshots**
See see https://jira.bdpnet.dk/browse/RM-3226 for video

**Please complete the following information:**
- OS: [e.g. Windows, MacOS, iOS] iPad OS 13.7

## Tasks:
- [ ] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [ ] Create Fix Branch
- [ ] Create test reproducing the error
- [ ] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch

**Comment by jakobe** [comment]
@ckibsen Could you please provide the video showing the bug directly on this issue in Github? 🙏🏻

**Comment by alxzak** [comment]
@developer who crabs this issue. Please contact me for the video, we can't attach video here due to GDPR.

**Comment by RasmusKjeldgaard** [comment]
This is no longer reproducible.
