### ISSUE TITLE
[Enhancement] Form field with icon/button

### ISSUE THREAD

**Issue by henrikvoetmand** [kirbydesign/designsystem#1205]
**Is your enhancement request related to a problem? Please describe.**
We would like to have the possibility to add an action to the right of the input field, to give the user - Right now our usecase is "opening a calendar" but it could be anything really, from "deleting the input" or "showing the password"

**Describe the solution you'd like**
The option to add an icon/button to a form field. The icon/button should be placed inside the field and aligned to the right.
The icon/button should be clickable and start an action.
MD Button with icon only attention level 4 (no border and no background)
Should also support disabled state (disabled button)

With a md button its 8pt padding and with an icon its 16pt padding. See also zeplin

**Describe alternatives you've considered**
Add a icon or a medium icon button to the right side of the input field. 

**Additional context**
![vælg dato](https://user-images.githubusercontent.com/71710012/99775959-71951980-2b10-11eb-83ca-6fc570ebad7c.png)

Zeplin: https://zpl.io/Vqp3LO4

**Comment by bommariusser** [comment]
Det nederste input felt findes ikke officielt endnu, så måske kan du fjerne det @henrikvoetmand for ikke at skabe forvirring :) 

Tilføjer du også lige hvilken størrelse knap det er? og hvor mange pixel afstand der er til højre? :) Burde man ikke bare fjerne knappen når funktionaliteten er disabled? Lidt ligesom at "slet" først kommer når man har indtastet noget - At der så kan være tidspunkter hvor man ikke ved det på forhånd kan måske være rigtig :) 

vi har også en "search" i experimental og har også skrevet en kommentar til dig :)

**Comment by henrikvoetmand** [comment]
Yes, det "lille" input er fjernet :-)

I forhold til disabled - er det ikke meget godt at vise at muligheden for at klikke på et ikon er der - den er bare greyet ud?

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
