### ISSUE TITLE
[BUG] Including kirby-modal-footer inside kirby-loading-overlay gives faulty layout

### ISSUE THREAD

**Issue by neigaard** [kirbydesign/designsystem#1210]
**Describe the bug**
kirby-loading-overlay should take up the space of the whole page, but if we wrap kirby-modal-footer inside a  kirby-loading-overlay the kirby-modal-footer is displayed wrong.

A side effect of this means we have to disable any buttons on the footer when the kirby-loading-overlay is visible.

As another side effect the kirby-loading-overlay seem to not center and overlay correctly if the kirby-loading-overlay is not the top most tag, thus causing additional layout problems.

**To Reproduce**

E.g. hack approve.component.html so that the kirby-modal-footer is moved inside the kirby-loading-overlay and see that the footer now has added margin.

**Kirby version**
- 1.3.7

**Expected behavior**
kirby-modal-footer should be able to be wrapped inside a kirby-loading-overlay without having its layout changed.

**Screenshots**
![Expected, Laptop](https://user-images.githubusercontent.com/51361340/99944886-f03dc100-2d73-11eb-94a7-06e701479b95.png)
![Actual, Laptop](https://user-images.githubusercontent.com/51361340/99944933-03e92780-2d74-11eb-95da-579c2a870a84.png)
![Expected, iPhone](https://user-images.githubusercontent.com/51361340/99944973-13687080-2d74-11eb-88f6-87e1275cb0d1.png)
![Actual, iPhone](https://user-images.githubusercontent.com/51361340/99945012-254a1380-2d74-11eb-9daa-2d797e095476.png)

**Please complete the following information:**
- OS: MacOS, iOS
- Browser Chrome, Firefox

## Tasks:
- [ ] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [ ] Create Fix Branch
- [ ] Create test reproducing the error
- [ ] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch

**Comment by bommariusser** [comment]
@neigaard tilføjer du lige en screen hvor loaderen er vist? Det er ret svært at se her :)

**Comment by neigaard** [comment]
Nej en footer i en loading overlay, ikke omvendt :) Det er for at loading overlay dækker footeren også, det skal den, der er også typisk knapper i footer som ikke må aktiveres ved loading.

**Comment by jakobe** [comment]
@neigaard Workaround possible: If you don't need the footer to be visible until the loading has ended, you can place it outside the loading overlay and hide it with the same condition you use for `isLoading`.

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
