### ISSUE TITLE
[Enhancement] Input field masking - date

### ISSUE THREAD

**Issue by MartinSkovsen** [kirbydesign/designsystem#1211]
This issue is a granular option of #937.

[Milestone ](https://github.com/kirbydesign/designsystem/milestone/13)for this issue could be end of 2020.

**Is your enhancement request related to a problem? Please describe.**
No. However, it's related to a specific unresolved UX related need.

**Describe the solution you'd like**
In certain situations we need to restrict/mask the input field. When a date is required we want to mask the input field such that only valid dates are allowed. The user should only be able to enter valid dates, and should not be able to enter letters and other non-date characters. The solution should meet the required date mask `dd.mm.yyyy`.

![image (4)](https://user-images.githubusercontent.com/30232520/100215198-02089b00-2f11-11eb-8a0e-8f719eb8aac6.png)

![dato input felt ux](https://user-images.githubusercontent.com/30232520/100206108-362a8e80-2f06-11eb-8952-f867462994d5.png)

As per @JoanJensenBD's [requirement list](https://github.com/kirbydesign/designsystem/issues/937#issuecomment-720494458_) in #937:
- The placeholder text is 'dd.mm.åååå'
- The user can only enter numbers
-  '.' is automatically entered/skipped
- On mobile phones numeric keyboard is displayed.
- User cannot enter more than 31 for day and 12 for month
- Validation / reformatting happens on blur if necessary

**Describe alternatives you've considered**
Since this is an enhancement on input field and not similar to anything (as per my relatively limited knowledge) in the component library, no alternatives exists. A solution could be a restyle of default date type input field. However that's not a 100% solution, which is why, a directive has been considered.
We did take a look at [this trick](https://css-tricks.com/input-masking/.) for inspiration.

**Additional context**
Zeplin:
- https://zpl.io/V0KveDl
- https://zpl.io/29LWGZe
- https://zpl.io/2ZeQn5G
- https://zpl.io/agj0PDN
### Kick Off:

- [x] Ensure the enhancement is `UX refined` and aligned with UX 
_The component and/or enhancement should be published and available in the [Kirby Styleguide on Zeplin](https://zpl.io/258pXGj)_
- [x] Ensure the enhancement has been `Tech refined` with @kirbydesign/kirby-guild and this issue is updated with a clear implementation description  
_This issue should be in the [Ready to do](https://github.com/kirbydesign/designsystem/projects/1#column-4590936) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1) before starting implementation)_
- [x] Assign yourself to this issue and move it to the [In progress](https://github.com/kirbydesign/designsystem/projects/1#column-4590937) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1)

### Code:

- [x] Create Feature Branch from [master branch](https://github.com/kirbydesign/designsystem/tree/master)
- [x] Create a draft implementation and push to Github
- [x] Ask a member of @kirbydesign/kirby-guild for a WIP review by creating a draft Pull Request
- [x] Implement unit tests
- [x] Update Cookbook Examples and Showcase, i.e. see [Radio](https://cookbook.kirby.design/home/showcase/radio)  
_Also remember to add any relevant new API documentation_

### Review:

- UX review:
  - [ ] Ensure implementation is correct in relation to the UX design and the [Kirby Styleguide on Zeplin](https://zpl.io/258pXGj)
  - [ ] With UX agree on the version of the implementation
- Code review:
  - [ ] Open a pull request (or mark the existing draft PR as `Ready for review`) and ask @kirbydesign/kirby-guild for a review  
_Remember to add `closes #issueno` to the description of the PR._
  - [ ] Once approved, merge feature branch/PR to master
- [ ] Ask a member of @kirbydesign/kirby-guild to add a link to component showcase from Kirby Component Status and update the version number

**Comment by MartinSkovsen** [comment]
Refer to [this comment](https://github.com/kirbydesign/designsystem/issues/937#issuecomment-720494458) for more details.

**Comment by MartinSkovsen** [comment]
@bommariusser or @henrikvoetmand could you help me with any UX and graphically related content as well as UX refinement status?

**Comment by bommariusser** [comment]
sure @MartinSkovsen :) So this is some Visual representation of the masking, where you use a "." in between numbers, but there are probably alot of other UX related questions that @JoanJensenBD could help on.

<img width="572" alt="Skærmbillede 2020-11-23 kl  19 55 36" src="https://user-images.githubusercontent.com/49033002/100003075-cf05c080-2dc5-11eb-9f5f-d51281d2fd25.png">

Like how to validate the field. I guess the validation first comes after you input the number, and i guess the first 2 numbers cant go above 31 and then 12 and so on. So in our other date example, our calendar handles this validation (like the earliest date can be today) so you can't pick a date before today.

**Comment by MartinSkovsen** [comment]
That's exactly what we intend to do. I just want to make sure that we can remove the NOT UX REFINED label, before we deep dive into the technical aspect of the issue.

**Comment by MartinSkovsen** [comment]
@labanos As per the issue template instructions can you remove NOT PRIORITIZED label from this issue? It's prioritized [here](https://github.com/kirbydesign/designsystem/milestone/13).

**Comment by bommariusser** [comment]
but you have a tech refinement tag for the technical aspect or? :D @MartinSkovsen

**Comment by MartinSkovsen** [comment]
I do! And actually @karlgodtliebsen has [this comment](https://github.com/kirbydesign/designsystem/issues/1029#issuecomment-732986703_) regarding the technical aspect :)

**Comment by bommariusser** [comment]
great stuff! @MartinSkovsen @karlgodtliebsen - feel free to tag us for further information! :)

**Comment by MartinSkovsen** [comment]
I completely forgot to link to [this comment](https://github.com/kirbydesign/designsystem/issues/937#issuecomment-720494458_), where Joan has previously provided UX content:
![dato input felt ux](https://user-images.githubusercontent.com/30232520/100206108-362a8e80-2f06-11eb-8952-f867462994d5.png)

As well as this UX checklist:
- [ ] The placeholder text is 'dd.mm.åååå'
- [ ] The user can only enter numbers
- [ ]  '.' is automatically entered/skipped
- [ ] On mobile phones numeric keyboard is displayed.

I've added it to the issue description 👍

**Comment by MartinSkovsen** [comment]
To keep the issue description readable I'll share some screenshots here:

![dato ux indhold 2](https://user-images.githubusercontent.com/30232520/100207440-dfbe4f80-2f07-11eb-82e8-098c70757c8e.png)
![dato ux indhold 3](https://user-images.githubusercontent.com/30232520/100207444-e056e600-2f07-11eb-8151-554f24e46ad0.png)
![dato ux indhold](https://user-images.githubusercontent.com/30232520/100207445-e056e600-2f07-11eb-95d1-0ce7f0cf6913.png)

**Comment by MartinSkovsen** [comment]
@bommariusser I feel like we have the needed UX content for tech refining (and developing) this issue now. It turned out i already had all the content but had forgotten to describe it here in this issue.
