### ISSUE TITLE
[Enhancement] Input field masking - phone number

### ISSUE THREAD

**Issue by MartinSkovsen** [kirbydesign/designsystem#1212]
This issue is a granular option of #937.

**Is your enhancement request related to a problem? Please describe.**
No. However, it's related to a specific unresolved UX related need.

**Describe the solution you'd like**
In certain situations we need to restrict/mask the input field. When a phone number is required we want to mask the input field such that only valid phone numbers are allowed based on country specific (or perhaps locale specific) specifications. The user should only be able to enter valid phone numbers, and should not be able to enter letters and other non-numerical characters. The solution should meet required country specific masks.

**Describe alternatives you've considered**
Since this is an enhancement on input field and not similar to anything (as per my relatively limited knowledge) in the component library, no alternatives exists. A directive has been considered for achieving the desired mask.

**Additional context**
Zeplin: Missing

**Comment by bommariusser** [comment]
@MartinSkovsen har i en usecase hvor i skal maske "+45" ? Det eneste vi har lige pt er 8 tal som fx. "88 88 88 88"

**Comment by MartinSkovsen** [comment]
Det har vi Ikke umiddelbart. Kommentaren kommer udelukkende ud fra en betragtning om, at et frit tilgængeligt komponent bibliotek skal kunne rumme flere forskellige formater. Vi kan sagtens starte med at supporte 8 tal a la `88 88 88 88`

**Comment by bommariusser** [comment]
Så fint :) @MartinSkovsen altså det her 
![Skærmbillede 2020-11-23 kl  11 45 55](https://user-images.githubusercontent.com/49033002/99953375-76143900-2d81-11eb-84f5-5ea60187c942.png)

Hvor man masker med et space imellem tallene og begrænser antallet af tal på 8. noget der mangler? :)

**Comment by bommariusser** [comment]
ja jeg kan godt se at jeg skrev meget af det du også skrev ;) @MartinSkovsen

**Comment by bommariusser** [comment]
Er det behov for mere ux refinement @MartinSkovsen ?

**Comment by MartinSkovsen** [comment]
Ikke for min skyld 👍

**Comment by MartinSkovsen** [comment]
Regarding tech refinement of this issue i'd like to refer to [this comment](https://github.com/kirbydesign/designsystem/issues/1029#issuecomment-732986703) on #1029. For now we don't actually have a mask for phone number specifically, but we do have a suggestion for numerical input, which a potential phone number directive would draw logic from.

**Comment by jkaltoft** [comment]
@MartinSkovsen For semantic and accessibility reasons, wouldn't it make sense to build this on top of a standard HTML input type="tel"?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/tel

https://html.spec.whatwg.org/multipage/input.html#telephone-state-(type%3Dtel)

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
