### ISSUE TITLE
[Enhancement] Input field masking - numerical and decimal

### ISSUE THREAD

**Issue by MartinSkovsen** [kirbydesign/designsystem#1213]
This issue is a granular option of #937.

[Milestone ](https://github.com/kirbydesign/designsystem/milestone/13)for this issue could be end of 2020. 

**Is your enhancement request related to a problem? Please describe.**
No. However, it's related to specific unresolved UX related need.

**Describe the solution you'd like**
In certain situations we need to restrict/mask the input field. When a number with or without decimal is required we want to mask the input field such that only valid numbers are allowed. The user should only be able to enter valid numerical values, and should not be able to enter letters and other non-numerical characters.

![image (5)](https://user-images.githubusercontent.com/30232520/100215639-86f3b480-2f11-11eb-9a77-569ae5903495.png)

- Only allow numerical input
- Allow the user to select desired amount of decimals. 0 should possible as well as indefinite amount of decimals
- Allow the user to write ,99 and automatically insert 0

**Describe alternatives you've considered**
Since this is an enhancement on input field and not similar to anything (as per my relatively limited knowledge) in the component library, no alternatives exists there. A directive has been considered for achieving the desired mask.

**Additional context**
Related issue with contextual information: #1029, #1030 as well as  #1079 and its associated [PR](#1081)
Zeplin: https://zpl.io/a3L5jGN

### Kick Off:

- [x] Ensure the enhancement is `UX refined` and aligned with UX 
_The component and/or enhancement should be published and available in the [Kirby Styleguide on Zeplin](https://zpl.io/258pXGj)_
- [x] Ensure the enhancement has been `Tech refined` with @kirbydesign/kirby-guild and this issue is updated with a clear implementation description  
_This issue should be in the [Ready to do](https://github.com/kirbydesign/designsystem/projects/1#column-4590936) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1) before starting implementation)_
- [x] Assign yourself to this issue and move it to the [In progress](https://github.com/kirbydesign/designsystem/projects/1#column-4590937) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1)

### Code:

- [x] Create Feature Branch from [master branch](https://github.com/kirbydesign/designsystem/tree/master)
- [x] Create a draft implementation and push to Github
- [x] Ask a member of @kirbydesign/kirby-guild for a WIP review by creating a draft Pull Request
- [x] Implement unit tests
- [x] Update Cookbook Examples and Showcase, i.e. see [Radio](https://cookbook.kirby.design/home/showcase/radio)  
_Also remember to add any relevant new API documentation_

### Review:

- UX review:
  - [x] Ensure implementation is correct in relation to the UX design and the [Kirby Styleguide on Zeplin](https://zpl.io/258pXGj)
  - [x] With UX agree on the version of the implementation
- Code review:
  - [x] Open a pull request (or mark the existing draft PR as `Ready for review`) and ask @kirbydesign/kirby-guild for a review  
_Remember to add `closes #issueno` to the description of the PR._
  - [ ] Once approved, merge feature branch/PR to master
- [ ] Ask a member of @kirbydesign/kirby-guild to add a link to component showcase from Kirby Component Status and update the version number

**Comment by MartinSkovsen** [comment]
@bommariusser or @henrikvoetmand could you help me with any UX and graphically related content as well as UX refinement status?

**Comment by bommariusser** [comment]
yes @MartinSkovsen 👍

**Comment by bommariusser** [comment]
So a specific usecase where we already use such a masking is "overfør og betal" where mask the input in a certain way so it cant go over 2 decimals and a number between ,00 and ,99. Anything else? :) 

Do you have a screen with your usecase @MartinSkovsen ?

**Comment by MartinSkovsen** [comment]
Nothing else needed 👍  Check [this](https://zpl.io/a3L5jGN) out from zeplin. Screenshot here:
<img width="380" alt="Screenshot 2020-11-24 at 13 17 36" src="https://user-images.githubusercontent.com/30232520/100093161-6d8e3200-2e57-11eb-97b0-3185d4a44345.png">

**Comment by MartinSkovsen** [comment]
I just noticed the screenshot does not have an example with decimals but the intention is to support decimal limitation. The idea is that the component consumer can choose the amount of allowed decimals.

**Comment by MartinSkovsen** [comment]
@labanos As per the issue template instructions can you remove NOT PRIORITIZED label from this issue? It's prioritized [here](https://github.com/kirbydesign/designsystem/milestone/13).

**Comment by bommariusser** [comment]
hehe ok @MartinSkovsen do you need any other UX info on this? maybe you can find the right screenshot :D

**Comment by MartinSkovsen** [comment]
Finally, I found the right screenshot. It has been added to the issue description. So we should be good to go. I don't need anything else. I've added a checklist to the issue as well as per conversation with Joan
