### ISSUE TITLE
[BUG] Footer should reposition on Keyboard layout change

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#1219]
**Is your enhancement request related to a problem? Please describe.**
When you change the Android Keyboard Layout, the footer will not be right above the keyboard anymore.

![Skærmbillede 2020-12-02 kl  08 38 48](https://user-images.githubusercontent.com/49033002/100845587-c2483300-347d-11eb-8c7a-d80aaaa6ec34.png)

**Describe the solution you'd like**
The footer should always be above the keyboard.

**Additional information**
Happens on all device. It happens because the keyboard height is dependant on the layout.

**Comment by RasmusKjeldgaard** [comment]
I can no longer reproduce this with the new modal design where the whole modal is pushed upwards by the keyboard:
![image](https://github.com/kirbydesign/designsystem/assets/42470636/634bb46b-5fe0-42a7-aeac-0d5f3dd5e057)

**Comment by RasmusKjeldgaard** [comment]
I can no longer reproduce this with the new modal design where the whole modal is pushed upwards by the keyboard:
![image](https://github.com/kirbydesign/designsystem/assets/42470636/634bb46b-5fe0-42a7-aeac-0d5f3dd5e057)
