### ISSUE TITLE
[BUG] Kirby fixed-footer should stick to keyboard on rotation

### ISSUE THREAD

**Issue by yucelbas** [kirbydesign/designsystem#1220]
**Is your enhancement request related to a problem? Please describe.**
The issue is seen on android Huawei tablet. When rotating the device while focus in a field and a keyboard is displayed the kirby sticky footer moves up/moves position away from keyboard. This behaviour is tested when a numeric keyboard used.  For more details see images attached. 

**Describe the solution you'd like**
The kirby-sticky footer should always stick to the keyboard and not move place.

![Screenshot_20201130-093441](https://user-images.githubusercontent.com/43955031/100855437-7780e800-348a-11eb-82a0-364bdd02fa32.jpg)
![Screenshot_20201130-092704](https://user-images.githubusercontent.com/43955031/100855451-79e34200-348a-11eb-85d5-5a2cd27ff925.jpg)

**Comment by alxzak** [comment]
@bommariusser : Is this issue still relevant? And does it only occur on huawei tablets?

**Comment by bommariusser** [comment]
@alxzak i guess so :) i bet @jakobe can verify that. I dont have a android device at home, but i bet it is :)

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
