### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by KemalPajevic** [kirbydesign/designsystem#1221]
**Describe the bug**
Opening a page in a modal by calling the function `navigateToModal` does not work if the component being opened is in a different module.

**To Reproduce**

1. Checkout the branch `origin/feature/T122-162/credit-permission`
2. Go to 'Konto / Kort / Bestil kort'
3. Click on a card product to order, for instance 'Visa Credit'
4. The main window navigates to the settings page (`/drb/settings`)

**Kirby version**
- 1.3.12

**Expected behavior**
A modal is opened containing the Credit permission page (`/drb/settings/credit`)

**Screenshots**

**Please complete the following information:**
- OS: MacOS
- Browser: Chrome
- Browser version: 87.0.4280.67

**Additional context**

## Tasks:
- [ ] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [ ] Create Fix Branch
- [ ] Create test reproducing the error
- [ ] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch

**Comment by bommariusser** [comment]
@KemalPajevic namer du lige din issue? ;)

**Comment by bommariusser** [comment]
@KemalPajevic ??

**Comment by labanos** [comment]
timed out
