### ISSUE TITLE
[Component] Checkbox Group

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#1234]
**Is your enhancement request related to a problem? Please describe.**
Implementing a view with checkboxes/radiobuttons should be easier because they always in its definition come in a group.

**Describe the solution you'd like**
We would like to have grouping of the same components which also can have a label to describe the group and some text below the group for more information or an error text.

![Skærmbillede 2020-12-18 kl  10 25 44](https://user-images.githubusercontent.com/49033002/102597712-502d4a80-411b-11eb-8995-7e7bd2eaefe5.png)

**Describe alternatives you've considered**
nothing

**Additional context**
nothing

**Comment by jakobe** [comment]
**Tech refinement:**
Create a new `kirby-checkbox-group` with similar behavior as `kirby-radio-group` (`items`input property and auto-rendering of each checkbox)

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
