### ISSUE TITLE
[Enhancement] 16 px space between sections when no list section header

### ISSUE THREAD

**Issue by lydemann** [kirbydesign/designsystem#1236]
16 px space between sections when no list section header (instead of 32 px now)
![image](https://user-images.githubusercontent.com/9210691/103647089-01751280-4f5b-11eb-8567-808b7e5eb1eb.png)

**Is your enhancement request related to a problem? Please describe.**
At the moment the spacing seem to big then no list section header. 16 px would be more optimal.

**Describe the solution you'd like**
16 px space between sections when no list section header (instead of 32 px now)

**Describe alternatives you've considered**
Change the spacing to 16 px when no list section header.

**Additional context**

**Comment by bommariusser** [comment]
jeg tror vi skal lige have nogle flere informationer her @lydemann ;)

**Comment by lydemann** [comment]
Parkerer den lige den her og hører med Marcus.
