### ISSUE TITLE
[BUG] Radio button styling on iOS 13.3 and below

### ISSUE THREAD

**Issue by jakobe** [kirbydesign/designsystem#1244]
**Describe the bug**
On iOS version <=13.3 the radio button icon isn't styled correctly regarding
- background color (default, pressed and disabled states),
- elevation (checked state)
- size of check mark
- focus ring (but we don't apply the focus ring on touch devices anyway)

**To Reproduce**
1. Go to https://cookbook.kirby.design/examples/radio on iOS version 13.3 or less
2. See missing styles (as mentioned above)

**Kirby version**
- vNext (when initial Radio PR #1232 has been merged and published, probably 1.4.0)

**Expected behavior**
Should have same styling as when seen in desktop Chrome or iOS Safari >=13.4
The specs can be found here: https://zpl.io/VxEMDJk

**Screenshots**
***❌  Wrong:***
![image](https://user-images.githubusercontent.com/9556693/104723269-4c4b1300-572f-11eb-99c0-cebe6ef08f26.png)

***✅   Expected:***
![image](https://user-images.githubusercontent.com/9556693/104723721-f75bcc80-572f-11eb-84ce-c450b6dd669c.png)

**Please complete the following information:**
- OS: iOS 13.3
- Browser: Chrome+Safari
- Browser 13.3

**Additional context**
iOS <=13.3 doesn't support [CSS Shadow Parts](https://developer.mozilla.org/en-US/docs/Web/CSS/::part) which is used to style the ion-radio.
This can be "polyfilled" by checking for CSS Shadow Parts support (`'part' in HTMLElement.prototype`) and applying the missing styles by extracting selectors with `::part` and applying the styled properties through the shadow dom of the `ion-radio` component:
```ts
function polyfillCssShadowParts() {
  const supportsCssShadowParts = 'part' in HTMLElement.prototype;
  if (supportsCssShadowParts) return;
  /* Todo: extract relevant css into shadowPartsCss.. */
  const ionRadio = this.ionRadioElement.nativeElement;
  const componentOnReady = (ionRadio as any).componentOnReady as () => Promise<void>;
  if (typeof componentOnReady === 'function') {
    await componentOnReady.bind(ionRadio)();
  }
  const styleElement = ionRadio.shadowRoot.querySelector<HTMLStyleElement>('style');
  this.renderer.appendChild(styleElement, this.renderer.createText(shadowPartsCss));
}
```
See: https://github.com/PolymerLabs/part-theme/blob/master/lib/part-theme.js#L94 for a regex example. 

## Tasks:
- [ ] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [ ] Create Fix Branch
- [ ] Create test reproducing the error
- [ ] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch
⁒

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
