### ISSUE TITLE
[Clarification] How to handle licences for peer dependencies (if not MIT)?

### ISSUE THREAD

**Issue by jakobe** [kirbydesign/designsystem#125]

**Comment by askarby** [comment]
It seems like our assumption of using a peer dependency, does indeed pass the responsibility of getting a valid license onto the using library.

We do however need to get an open source license for the cookbook, unless we already have one. Have a look at this page:

https://shop.highsoft.com/noncomform

**Comment by labanos** [comment]
@askarby this is in the "done" column of the board - but not closed? Who is going to get a license?
