### ISSUE TITLE
[Enhancement] Improve Typography showcase

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#1250]
**Is your enhancement request related to a problem? Please describe.**
We need to showcase our font sizes and weights more clearly, because it is quite confusing :) So some visuals like carbon does it would be of benefi, see also https://www.carbondesignsystem.com/guidelines/typography/overview for inspiration.

**Describe the solution you'd like**
Insert a/some visuals that describe it more clearly.

**Describe alternatives you've considered**
nothing more 

**Additional context**
like this:

![Skærmbillede 2021-01-21 kl  11 43 56](https://user-images.githubusercontent.com/49033002/105340294-fa4a3780-5bdd-11eb-9a38-7792c46a822f.png)

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
