### ISSUE TITLE
[Enhancement] Document items css-vars

### ISSUE THREAD

**Issue by hafstad** [kirbydesign/designsystem#1252]
**Is your enhancement request related to a problem? Please describe.**
Atm. you have to inspect an item to locate what you're able to configure ex. backgorund-color
search for `--kirby-*` css-vars for the item component and add it to the showcase.

**Describe the solution you'd like**
Document these cases in the cookbook so they are easy to find
Get inspired here: https://ionicframework.com/docs/api/action-sheet#css-custom-properties

**Comment by jkaltoft** [comment]
Is this intended for the [Item component](https://cookbook.kirby.design/home/showcase/item) only or are we aiming for a solution that can be used for all components in general?

**Comment by hafstad** [comment]
@jakobe and I discussed it, and because that we are considering auto-generated tooling like storybook in the near future we decided to keep it to items for now.
