### ISSUE TITLE
[Enhancement] dateSelect event to calendar

### ISSUE THREAD

**Issue by lydemann** [kirbydesign/designsystem#1256]
**Is your enhancement request related to a problem? Please describe.**
Currently it's not possible to respond to/handle the user clicking on the already selected date, i.e. the user confirming an already selected date.

**Describe the solution you'd like**
Trigger a `dateSelect` event when clicking a selectable date in the calendar as well as showing a `cursor: pointer` on hover for the already selected date.
The `dateChange` event should still only be triggered on an actual date change.

**Additional context**
This is enabling a modal to be closed when clicking on the selected date.

**Comment by MadsBuchmann** [comment]
Should dateSelect include the clicked date like the dateChange event?
