### ISSUE TITLE
[Enhancement] Split badge examples

### ISSUE THREAD

**Issue by MadsBuchmann** [kirbydesign/designsystem#1266]
**Is your enhancement request related to a problem? Please describe.**
It could be easier to see which code snippet relates to which example on the cookbook page for the badge component (https://cookbook.kirby.design/home/showcase/badge).

**Describe the solution you'd like**
Beneath each example a "view code"-button should be inserted which when clicked exposes the code for that example, as is done on the radio page (https://cookbook.kirby.design/home/showcase/radio).

**Comment by RasmusKjeldgaard** [comment]
Fixed when we move badge to storybook (#1595)
