### ISSUE TITLE
[Enhancement] Include font-faces

### ISSUE THREAD

**Issue by hafstad** [kirbydesign/designsystem#1273]
**Is your enhancement request related to a problem? Please describe.**
Right now the consumer applications of Kirby needs to manually add the font-faces for roboto, and therefore need to be synched manually
ex. see cookbook - styles.scss

**Describe the solution you'd like**
It would be nice that Kirby provided these as part of the package just like the rest of the typography styling, so it's easier to consume, and no need for manual synch

**Comment by MadsBuchmann** [comment]
Closed by #1157

**Comment by MadsBuchmann** [comment]
Sorry! - i accidentally closed the wrong issue yesterday.
