### ISSUE TITLE
[Enhancement] Drawer for feature-hint

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#1283]
**Is your enhancement request related to a problem? Please describe.**
Some features are kind of hidden in the UI, e.g. cell swipe actions, features in the overflow menu or triggered after rotation of the device.
User are not always aware of the ‘hidden’ features and needs onboarding to them i context.

**Describe the solution you'd like**
Show a feature onboarding hint (drawer) when relevant and in context.
The timing is essential and would be triggered by different rules in context.
Only one feature onboarding hint can be triggered at a time.
The feature onboarding hint present the feature and how to use/activate it, e.g. a specific gestures.

When triggered, the onboarding hint shows:

1. drawer moves in from the bottom of the page
2. the drawer ist fixed to the bottom
3. the content of the drawer defines it’s height (probably the same min-height as the drawer)
4. the drawer width is 100% of the device screen, but max. 428px on bigger screens (tablet/web)
5. the drawer contains af title, a close button, an optional svg-image/svg-animation and a text area
6. the drawer background is grey-6 (dark)
7. no backdrop behind the drawer

Normally a drawer is modal with backdrop. But in this circumstance the drawer is without blocking backdrop, so it still is possible to interact with the UI in the background, e.g. scrolling the page.
The feature onboarding drawer closes

1. manually when pressing the close button in the drawer
2. automatically when navigating away from the page
3. automatically when doing af gestures, e.g. swipe, longpress etc. (but not scroll!)
4. automatically when rotating the device 

**Describe alternatives you've considered**
We have thought about prioritising the requirements but it was quite hard since its not estimated. Drawer width might be something that can be a "nice to have" the same goes for the close button, dependant how hard it is to change it.

**Additional context**

https://zpl.io/bopXE3M
<img width="948" alt="Onboarding_drawer_examples pmg" src="https://user-images.githubusercontent.com/49033002/107491262-33494c80-6b8b-11eb-86d0-d618b188796e.png">

<img width="1692" alt="Onboarding_drawer" src="https://user-images.githubusercontent.com/49033002/107491276-36dcd380-6b8b-11eb-8042-e1c1251e4332.png">

**Comment by lydemann** [comment]
From tech refinement:

**Version 1.0:**

The initial solution is to add "**interactWithBackground**" input to ModalController for being able to interact with the background when the drawer is open + hide the backdrop. Input only has an effect for type: drawer.

**Scope:**

1. Base solution on drawer
2. Add interactWithBackground for making background interactable and hiding backdrop
3. Use existing arrow down close icon
4. Use existing 720 max width
5. Invert colors: Ensure the appropriate CSS custom properties are exposed to be able to restyle the colors of the drawer (background, text, close icon).

**potential upgrades later:**

1. Later it might be a separate modal flavor.
2. Change close icon
3. Change max-width
