### ISSUE TITLE
[BLOCKED][Enhancement] New Ressources/Core page route

### ISSUE THREAD

**Issue by flemcito** [kirbydesign/designsystem#1293]
This enhancement is part of a larger design overhaul of the Cookbook

**Describe the solution you'd like**
A separate page/route that basically works exactly like Components. So this heavily depends on the component enhancements.
https://github.com/kirbydesign/designsystem/issues/1292
https://github.com/kirbydesign/designsystem/issues/1291

Has initially two entries in the list that should be moved from components:
* Colors
* Typography 

**Additional context**
We could later expand this section with additional content/design principles like, ie. spacing, elevations, and icons.

**Comment by RasmusKjeldgaard** [comment]
Should be solved with storybook - if we choose to go with storybook as per #1316

**Comment by RasmusKjeldgaard** [comment]
Solved by #1316 once implemented.
