### ISSUE TITLE
[Enhancement] Button min-width

### ISSUE THREAD

**Issue by henrikvoetmand** [kirbydesign/designsystem#1305]
**Is your enhancement request related to a problem? Please describe.**
Not all Button sizes have a min-width. As a result we have to narrow buttons in the interface.

**Describe the solution you'd like**
Set a min-width on button size "Medium" and "Small" (se below image for spec.)
Text and icons in buttons should be center aligned.
![Button-spec-min-width](https://user-images.githubusercontent.com/71710012/107680443-28cba780-6c9e-11eb-8b8e-da898e94ea6a.png)

**Describe alternatives you've considered**
There are really no alternatives.

**Additional context**

**Comment by hafstad** [comment]
add css min-width for medium & small buttons
