### ISSUE TITLE
[Cookbook] Improve how "example on github"-links are generated. 

### ISSUE THREAD

**Issue by MadsBuchmann** [kirbydesign/designsystem#1307]
**Is your enhancement request related to a problem? Please describe.**
To fix dead links for the "example on github"-button (related issue: #1282 ), i had to make sure all list examples originally located in a shared `list` folder were directly in the `example` folder, in order for the links to work. This resulted in several example folders named as: `list-*-example`, where i personally think it would be better organized to have them all stored in a `list` folder as it was originally done. I would like for the  generation of the "example on github"-link to be enhanced, to allow for nesting of examples in folders as was done with list examples.   

**Describe the solution you'd like**
Don't have a complete solution - but i would like the "example on github"-link to point to the actual example file. The path found when requiring `exampleHTML` could perhaps be used? (see for example the file: `list-swipe-showcase.component.ts` - line 10). 
![Screenshot 2021-02-12 at 13 00 36](https://user-images.githubusercontent.com/17269698/107765526-4e09f580-6d32-11eb-8e23-7214735e4c47.png)

**Comment by alxzak** [comment]
https://app.zenhub.com/workspaces/zenhub-602b70d809e4aa00141a1a93/board?labels=priority%202&repos=147814567
