### ISSUE TITLE
[BUG] Investigate why clean-up in modal doesn't work as expected (outlet & portal)

### ISSUE THREAD

**Issue by hafstad** [kirbydesign/designsystem#1312]
**Describe the bug**
Our clean-up doesn't work as expected for outlet modals combined with portals. We have done a "quick fix", but needs to investigate why the issue happens. 

By some reason the clean-up function after second navigation (used from a portal) gets a reference to the embedded footer inside the component which is about to be activated and not the "old" footer which should be removed. 

**To Reproduce**
1. Go to http://localhost:4200/drb/micro/cards (make sure you have kirby v. 1.4.5 which doesn't include quickfix) 
2. Click on 'bestil kort'
3. Choose a card, which opens a modal with an outlet
4. Click 'forsæt' in modal footer
5. Choose an account and click 'forsæt'
4. See error (you will see two footers, the footer on top is the footer from the page before which should have been removed)

**Kirby version**
- 1.4.5

## Tasks:
- [ ] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [ ] Create Fix Branch
- [ ] Create test reproducing the error
- [ ] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch

**Comment by RasmusKjeldgaard** [comment]
@hafstad Do we have a link/description of the quickfix? 
Can you look at this sometime soon?

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
