### ISSUE TITLE
[Enhancement] Split button examples

### ISSUE THREAD

**Issue by MadsBuchmann** [kirbydesign/designsystem#1313]
**Is your enhancement request related to a problem? Please describe.**
It can be hard to figure out which part of the example code corresponds to which button in the [button-showcase](https://cookbook.kirby.design/home/showcase/button). 

**Describe the solution you'd like**
I would like for the examples to be split into several separate code snippets as can be seen on the [radio-showcase](https://cookbook.kirby.design/home/showcase/radio).

**Comment by RasmusKjeldgaard** [comment]
Solved by movin button to storybook (#1593)
