### ISSUE TITLE
[Enhancement] Migrate component status from firebase to storyblok

### ISSUE THREAD

**Issue by hafstad** [kirbydesign/designsystem#1319]
**Is your enhancement request related to a problem? Please describe.**
Make it easier to maintain our component status (ux versions, links to zeplin etc.)

**Describe the solution you'd like**
Migrate our current solution at firebase to storyblok or other headless cms which is easy to edit

**Additional context**
https://www.storyblok.com/

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
