### ISSUE TITLE
[Enhancement] Paging of github issues in component status

### ISSUE THREAD

**Issue by hafstad** [kirbydesign/designsystem#1320]
**Is your enhancement request related to a problem? Please describe.**
Not all issues are shown due to pagination of the github api

**Describe the solution you'd like**
Make sure to loop through the pages from the issues api

**Additional context**
https://docs.github.com/en/rest/reference/issues#list-repository-issues
https://docs.github.com/en/rest/guides/traversing-with-pagination

**Comment by flemcito** [comment]
Tech refinement: This should be fairly straight forward. `getGithubComponentIssues()` and `getGithubEnhancementIssues()` in /designsystem/apps/cookbook/src/app/component-status/component-status.component.ts need to be updated to retrieve all the paged issues. The provided links provide the necessary info
