### ISSUE TITLE
[Housekeeping] Remove console errors in unit tests

### ISSUE THREAD

**Issue by hafstad** [kirbydesign/designsystem#1321]
**Is your enhancement request related to a problem? Please describe.**
Errors in console while running our specs

**Describe the solution you'd like**
Fix the issues which are causing the error logs by replacing all imports of IonicModule with `TestHelper.ionicModuleForTest`

**Additional context**
see example: https://github.com/kirbydesign/designsystem/blob/master/libs/designsystem/src/lib/components/radio/radio-group/radio-group.component.spec.ts#L15

https://github.com/kirbydesign/designsystem/blob/master/libs/designsystem/src/lib/testing/test-helper.ts

**Comment by MadsBuchmann** [comment]
**Tech Refinement )** 
1. Use branch `enhancement/remove-unit-test-errors` or delete the branch and create a new one. 
2. Locate tests that are throwing errors and warnings.
3. Import `TestHelper.ionicModuleForTest` for these tests. 

For example of tests that has been fixed see: c9207f33da91c37e1a7ae1a87b3149db7be17433

**Comment by RasmusKjeldgaard** [comment]
It looks like @MadsBuchmann solved the errors in his fix during the tech refinement, so I'll focus on the warnings about missing components.
