### ISSUE TITLE
[Enhancement] Section Headings in Reorder List

### ISSUE THREAD

**Issue by askarby** [kirbydesign/designsystem#1333]
**Describe the solution you'd like**
We'd like a means of re-ordering between lists (effectively that would be drag'n'drop). This is to indicate special meaning of certain items (displaying top 4 favorite securities in our case)

**Describe alternatives you've considered**
Another alternative would be to have one "large list", indicating (in text) that the top X items are assigned "special behavior".

**Additional context**
![image](https://user-images.githubusercontent.com/44014/108213258-1b476f00-712f-11eb-8e7b-f92438ae79a9.png)

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
