### ISSUE TITLE
Not possible to add toggle button to page actions

### ISSUE THREAD

**Issue by LVinther** [kirbydesign/designsystem#1339]
**Is your enhancement request related to a problem? Please describe.**
Right now we are not able to add a ToggleButton to page actions.

**Describe the solution you'd like**
- We would like to add a toggle button to the list of `kirby-page-actions`, eg.:
```
<kirby-page-actions *kirbyPageActions="{ fixed: true }">
    <kirby-toggle-button
            [checked]="true"
            (checkChanged)="toggleFavorite()"
    >
        <button kirby-button unchecked attentionLevel="4">
            <kirby-icon customName="star-empty"></kirby-icon>
        </button>
        <button kirby-button checked attentionLevel="4">
            <kirby-icon customName="star-filled"></kirby-icon>
        </button>
    </kirby-toggle-button>
    
    <!-- Additional buttons / toggle buttons can go here... -->
</kirby-page-actions>

```

**Describe alternatives you've considered**
- Right now we're  applying the `*kirbyPageActions`-directive directly to the `kirby-toggle-button`, eg.:
```
<kirby-toggle-button
        *kirbyPageActions="{ fixed: true }"
        [checked]="true"
        (checkChanged)="toggleFavorite()"
>
    <button kirby-button unchecked attentionLevel="4">
        <kirby-icon customName="star-empty"></kirby-icon>
    </button>
    <button kirby-button checked attentionLevel="4">
        <kirby-icon customName="star-filled"></kirby-icon>
    </button>
</kirby-toggle-button>
```
(this will of course "not work", if we deside to have additional fixed / sticky buttons / toggle buttons)

**Additional context**
![Skærmbillede 2021-02-19 kl  09 48 36](https://user-images.githubusercontent.com/53176253/108480789-ac395a00-7297-11eb-9403-e88568048e31.png)
![Skærmbillede 2021-02-19 kl  09 48 42](https://user-images.githubusercontent.com/53176253/108480791-ad6a8700-7297-11eb-8b15-1dfe2370da44.png)

https://zpl.io/2Gr4rzJ 
https://zpl.io/VO6P9vQ

**Comment by LVinther** [comment]
@henrikvoetmand så har jeg fået lavet issuet :) Er der noget der mangler?

**Comment by bommariusser** [comment]
@LVinther ændrer du ikke dine titler til det det omhandler? fx. her noget ala 'toggle button can't stay the same attentionlvl' eller sådan? :D

**Comment by jakobe** [comment]
@LVinther This already possible as each button in a toggle button is a regular Kirby button and can be styled in [all the ways a Kirby button can be styled in itself](https://cookbook.kirby.design/home/showcase/button)
E.g.:
```
<kirby-toggle-button [checked]="true" (checkedChange)="onCheckedChange($event)">
  <button kirby-button unchecked attentionLevel="4">
    <kirby-icon name="star-outline"></kirby-icon>
  </button>
  <button kirby-button checked attentionLevel="4">
    <kirby-icon name="star-filled"></kirby-icon>
  </button>
</kirby-toggle-button>
```

**Comment by LVinther** [comment]
@askarby see the above comment from Jakob 😄

**Comment by askarby** [comment]
So, we left out the detail that the `kirby-toggle-button` should be placed within the `kirby-page-actions`-directive.

@jakobe  assisted me with a workaround, and told me to update the title / description of this enhancement request to reflect the actual issue.

I've additionally updated the applied labels (hope I didn't mess anything up 🤞)

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
