### ISSUE TITLE
[Inquiry] Size on drawer

### ISSUE THREAD

**Issue by alxzak** [kirbydesign/designsystem#1342]
**Please complete the following information:**

I team 3 har vi et behov for at sætte størrelsen på en drawer (bl.a. søgning på værdipapirer), og dertil har kirbys modal og drawer en property (Size) som kan sættes. Problemet er bare at den ”ikke fungerer” (i hvert fald ikke som jeg, vores UX’er Lotte og Marvin (fra JB) forventer).

Størrelsen har kun en begrænsende indflydelse på den initielle højde af modalen / draweren, så hvis der er mere indhold end der kan vises i den, begrænses højden til  hvad der er angivet.

I vores tilfælde (værdipapir-søgeren) har vi et lille indhold (et søgefelt) når der så indtastet en søgning vil en list vises, som resulterer i at højden på draweren ”hopper” (vores UX’ers ord).

Jeg er bare usikker på om det er den tiltænkte opførsel på ”size”-propertien, eller om det er en desideret bug?

PS: Har vi ikke en kirby-slack-kanal, hvor vi kan stille sådan spørgsmål?

**Additional context**
- Browser [e.g. Chrome, Safari]

## Subject area:
- [x] Kirby UX
- [x] Kirby development
- [ ] Prioritysation status (Product owner)
- [ ] Other

**Comment by bommariusser** [comment]
nu er jeg tagget i den? men hvad forventer vi? @alxzak er den ikke "fullsize"? :D

**Comment by askarby** [comment]
@bommariusser vi har pt. valgt at lave den "full-size", men den "skubber" **ikke** indholdet op, så det er ikke altid en holdbar løsning, såfremt det er en større form (eller en lille smartphone).

Der er ingen forskel på på størrelserne `small`, `medium` og `large` hvis indholdet ændrer størrelse (se vores eksempel med papir-søgeren).

**Comment by bommariusser** [comment]
nååå @askarby :) tjek!

**Comment by bommariusser** [comment]
tilføjer i lige skærme fra jeres usecase? @askarby @alxzak og hvad den gør i jeres case?

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
