### ISSUE TITLE
Get Highcharts license for Kirby Cookbook

### ISSUE THREAD

**Issue by jakobe** [kirbydesign/designsystem#135]

**Comment by labanos** [comment]
Fra	Emne	Modtaget	Størrelse	Kategorier	
Highsoft	Your Highcharts Non-Commercial License Agreement	11:07	52 KB

**Comment by labanos** [comment]
[Your Highcharts Non-Commercial License Agreement.zip](https://github.com/kirbydesign/designsystem/files/3385800/Your.Highcharts.Non-Commercial.License.Agreement.zip)
