### ISSUE TITLE
[Enhancement] Radio-icon & Checkbox-icon alignment

### ISSUE THREAD

**Issue by henrikvoetmand** [kirbydesign/designsystem#1359]
**Please add a short description of your enhancement request**
When a Kirby-radio label spans over more than one line - the radio-icon should be top aligned.

**Describe the solution you'd like**
Align the radio-icon with the first line of the label.

**Describe alternatives you've considered**
Let the radio-icon be center aligned AS-IS - but this results in layout that does not match the designed layout.

**Additional context**

![Radio-Issue](https://user-images.githubusercontent.com/71710012/109046484-15283400-76d5-11eb-9b87-48e88b9d003c.png)

### Kick Off:

- [X] Ensure the enhancement is `UX refined` and aligned with UX 
_The component and/or enhancement should be published and available in the [Kirby Styleguide on Zeplin](https://zpl.io/258pXGj)_
- [X] Ensure the enhancement has been `Tech refined` with @kirbydesign/kirby-guild and this issue is updated with a clear implementation description  
_This issue should be in the [Ready to do](https://github.com/kirbydesign/designsystem/projects/1#column-4590936) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1) before starting implementation)_
- [X] Assign yourself to this issue and move it to the [In progress](https://github.com/kirbydesign/designsystem/projects/1#column-4590937) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1)

### Code:

- [X] Create Feature Branch from [master branch](https://github.com/kirbydesign/designsystem/tree/master)
- [X] Create a draft implementation and push to Github
- [X] Ask a member of @kirbydesign/kirby-guild for a WIP review by creating a draft Pull Request
- [X] Implement unit tests
- [X] Update Cookbook Examples and Showcase, i.e. see [Radio](https://cookbook.kirby.design/home/showcase/radio)  
_Also remember to add any relevant new API documentation_

### Review:

- UX review:
  - [X] Ensure implementation is correct in relation to the UX design and the [Kirby Styleguide on Zeplin](https://zpl.io/258pXGj)
  - [X] With UX agree on the version of the implementation
- Code review:
  - [X] Open a pull request (or mark the existing draft PR as `Ready for review`) and ask @kirbydesign/kirby-guild for a review  
_Remember to add `closes #issueno` to the description of the PR._
  - [ ] Once approved, merge feature branch/PR to master
- [ ] Ask a member of @kirbydesign/kirby-guild to add a link to component showcase from Kirby Component Status and update the version number

:tada: Celebrate

**Comment by MadsBuchmann** [comment]
I've added checkbox-icon to the label after talking with Henrik, as this is also the case for checkbox icons.

**Comment by MadsBuchmann** [comment]
Blocked: https://github.com/kirbydesign/designsystem/pull/1374#issuecomment-790513346
