### ISSUE TITLE
[Housekeeping] Cache `node_modules` in GitHub Actions to speed up builds

### ISSUE THREAD

**Issue by jakobe** [kirbydesign/designsystem#1360]
**Short description of housekeeping request**
We would like to cache `node_modules` in our GitHub Actions to speed up the `rpm install` step.

**Alternatives**
Waiting and drinking ☕ 

**Additional context**
See: https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows

### Kick Off

* [X] Ensure this issue has been `Tech refined` with @kirbydesign/kirby-guild and is updated with a clear implementation description
  _This issue should be in the [Ready to do](https://github.com/kirbydesign/designsystem/projects/1#column-4590936) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1) before starting implementation_
* [X] Assign yourself to this issue and move it to the [In progress](https://github.com/kirbydesign/designsystem/projects/1#column-4590937) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1)

### Code

* [X] Create Feature Branch from [master branch](https://github.com/kirbydesign/designsystem/tree/master)
*  ~~Implement/update unit tests~~
*  ~~Create a draft implementation and push to Github~~
* ~~Ask a member of @kirbydesign/kirby-guild for a WIP review by creating a draft Pull Request~~

### Code Review

* [X] Open a pull request (or mark the existing draft PR as `Ready for review`) and ask @kirbydesign/kirby-guild for a review
  _Remember to add `closes #issueno` to the description of the PR._
* [ ] Once approved, merge feature branch/PR to master

:tada: Celebrate

**Comment by MadsBuchmann** [comment]
Unassigned myself as a blocked issue I was working on was just unblocked.
