### ISSUE TITLE
[BUG] Unable to nest contents of kirby-page-actions in ng-container

### ISSUE THREAD

**Issue by askarby** [kirbydesign/designsystem#1361]
**Describe the bug**
It's not possible to render a (kirby-)`button` inside of the `kirby-page-actions` when said button is wrapped within a `ng-container`-element.

If you're wondering why that's a need (requirement?), sometimes you want to apply multiple (structural) directives to said button, and that's not possible - hence wrapping in `ng-container` is required.

As a workaround, I've combined `Observable`s in the implementing code, but it's clunky since we have declarative constructs in place to accommodate the desired functionality.

**To Reproduce**

Create a component that utilizes the kirby-page, kirby-page-actions and nests a button in a ng-container, eg.:
```html
<kirby-page>
   <kirby-page-actions *kirbyPageActions="{ fixed: true }">
      <ng-container *featureToggleDirective="launchAwesomeFeature">
         <button kirby-button(click)="toggle()" *ngIf="dataHasLoaded">
            <kirby-icon name="cog"></kirby-icon>
         </button>
      </ng-container>
   </kirby-page-actions>
</kirby-page>
```

**Kirby version**
- 1.4.7

**Expected behavior**
To render content of `ng-container` in `kirby-page-actions`.

**Screenshots**
n/a (provided unit test)

**Please complete the following information:**
- OS: all
- Browser all
- Browser version current

**Additional context**
I've created a branch with a failing unit test to illustrate this issue:
https://github.com/kirbydesign/designsystem/tree/ng-container-issue

## Tasks:
- [ ] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [ ] Create Fix Branch
- [ ] Create test reproducing the error
- [ ] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch

**Comment by RasmusKjeldgaard** [comment]
Made obsolete by #2930
