### ISSUE TITLE
[Enhancement]Link from cookbook component pages to component guidelines in Zeplin.

### ISSUE THREAD

**Issue by henrikvoetmand** [kirbydesign/designsystem#1364]
**Please add a short description of your enhancement request**
Link between cookbook components and Zeplin component guidelines.

**Describe the solution you'd like**
Add a link from each component page on cookbook to the corresponding component guideline in Zeplin.
Maybe as a part of the CTA section on the component page?

**Available guidelines in Zeplin:**

- Alert (https://zpl.io/bAN3JQo)
- Avatar (https://zpl.io/bJMzven)
- Badge (https://zpl.io/VDP6nXw)
- Button (https://zpl.io/blGyPO0)
- Card (https://zpl.io/bP65myp)
- Checkbox (https://zpl.io/br9gEKO)
- Footer (https://zpl.io/aX6E4DP)
- MessagingStates (https://zpl.io/V1R6lWB)
- Radio (https://zpl.io/ad6LzPe)
- Spinner (https://zpl.io/aB46RBq)
- Tabbar (https://zpl.io/aN6GmPd)
- Toast (https://zpl.io/2G86GGY)
- Toggle (https://zpl.io/VDP6AWl)

**Describe alternatives you've considered**
No guideline help...

**Additional context**

### Kick Off:

- [ ] Ensure the enhancement is `UX refined` and aligned with UX 
_The component and/or enhancement should be published and available in the [Kirby Styleguide on Zeplin](https://zpl.io/258pXGj)_
- [ ] Ensure the enhancement has been `Tech refined` with @kirbydesign/kirby-guild and this issue is updated with a clear implementation description  
_This issue should be in the [Ready to do](https://github.com/kirbydesign/designsystem/projects/1#column-4590936) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1) before starting implementation)_
- [ ] Assign yourself to this issue and move it to the [In progress](https://github.com/kirbydesign/designsystem/projects/1#column-4590937) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1)

### Code:

- [ ] Create Feature Branch from [master branch](https://github.com/kirbydesign/designsystem/tree/master)
- [ ] Create a draft implementation and push to Github
- [ ] Ask a member of @kirbydesign/kirby-guild for a WIP review by creating a draft Pull Request
- [ ] Implement unit tests
- [ ] Update Cookbook Examples and Showcase, i.e. see [Radio](https://cookbook.kirby.design/home/showcase/radio)  
_Also remember to add any relevant new API documentation_

### Review:

- UX review:
  - [ ] Ensure implementation is correct in relation to the UX design and the [Kirby Styleguide on Zeplin](https://zpl.io/258pXGj)
  - [ ] With UX agree on the version of the implementation
- Code review:
  - [ ] Open a pull request (or mark the existing draft PR as `Ready for review`) and ask @kirbydesign/kirby-guild for a review  
_Remember to add `closes #issueno` to the description of the PR._
  - [ ] Once approved, merge feature branch/PR to master
- [ ] Ask a member of @kirbydesign/kirby-guild to add a link to component showcase from Kirby Component Status and update the version number

:tada: Celebrate

**Comment by RasmusKjeldgaard** [comment]
Consider [zeplin for storybook](https://storybook.js.org/addons/storybook-zeplin/) community addon. 
But be aware of security issue with publicly exposed zeplin token. Might not be an issue if zeplin is already public in itself, but needs further investigation.

**Comment by alxzak** [comment]
We will lookk into this, when we migrate to storybook and make use of the addon described above. 

This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
