### ISSUE TITLE
[Housekeeping] Enforce uniform line endings

### ISSUE THREAD

**Issue by jkaltoft** [kirbydesign/designsystem#1365]
**Short description of housekeeping request**

Add `"endOfLine": "lf"` to `.prettierrc.json` to enforce Line Feed only line endings.

By enforcing a specific value for line endings we can avoid unwanted (potentially large) diffs and remove "noise" once and for all.

`lf` is the default value in Prettier since v2.0.0 and the most common inside git repos.

The Prettier docs mention that Windows users may need to re-clone the repo. Devs working on Kirby on Windows computers should be informed and advised to re-clone the repo.

**Alternatives**

`"endOfLine": "auto"` but may still cause unwanted diffs (at least until all files are normalised).

From Prettier docs:

> `"auto"`: Maintain existing line endings (mixed values within one file are normalised by looking at what’s used after the first line)

`auto` has the advantage that Windows devs don't need to re-clone the repo. However, every dev on the Kirby core team uses MacOS which suggests that we choose the `lf` option.

**Additional context**

https://prettier.io/docs/en/options.html#end-of-line has a step by step description for making sure the entire git repository only contains Linux-style line endings.

http://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#Formatting-and-Whitespace

### Kick Off

* [ ] Ensure this issue has been `Tech refined` with @kirbydesign/kirby-guild and is updated with a clear implementation description
  _This issue should be in the [Ready to do](https://github.com/kirbydesign/designsystem/projects/1#column-4590936) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1) before starting implementation_
* [ ] Assign yourself to this issue and move it to the [In progress](https://github.com/kirbydesign/designsystem/projects/1#column-4590937) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1)

### Code

* [ ] Create Feature Branch from [master branch](https://github.com/kirbydesign/designsystem/tree/master)
* [ ] Implement/update unit tests
* [ ] Create a draft implementation and push to Github
* [ ] Ask a member of @kirbydesign/kirby-guild for a WIP review by creating a draft Pull Request

### Code Review

* [ ] Open a pull request (or mark the existing draft PR as `Ready for review`) and ask @kirbydesign/kirby-guild for a review
  _Remember to add `closes #issueno` to the description of the PR._
* [ ] Once approved, merge feature branch/PR to master

:tada: Celebrate

**Comment by jkaltoft** [comment]
### Tech refinement

* Add "endOfLine": "lf" to .prettierrc.json to enforce Line Feed only line endings.
* Commit auto-generated mock-files (calendar, maybe other)
* Ask a developer using Windows to check if this change introduces problems on Windows machines (before merge to master)
  + If it introduces problems on Windows we should look into solutions mentioned in _Additional context_

**Comment by RasmusKjeldgaard** [comment]
**Note:** If `lf` line endings are enforced, then we will probably need to change newline in [generate-mocks.ts](https://github.com/kirbydesign/designsystem/blob/59c4196a8abb6a75b3f860295862bbe5c84f37d1/tools/generate-mocks/generate-mocks.ts#L7) to `\n` so the generated mocks conform to this.

**Comment by MadsBuchmann** [comment]
@alxzak I would still like this to be looked into as it can be a pain in the 🍑

**Comment by MadsBuchmann** [comment]
Still relevant imo. Go away bot.

**Comment by RasmusKjeldgaard** [comment]
I think we should do this in the Angular 12 upgrade (#1931), as the prettier version is updated there.
