### ISSUE TITLE
[Enhancement] Improve Kirby-list documentation

### ISSUE THREAD

**Issue by MadsBuchmann** [kirbydesign/designsystem#1367]
**Please add a short description of your enhancement request**
I would like for the documentation of the `kirby-list` component to be improved. 

**Describe the solution you'd like**
I would like for the list page (https://cookbook.kirby.design/home/showcase/list) to be improved with: 
- an exhaustive properties table 
- an exhaustive events table
- an exhaustive methods table
- a short user-friendly description of each example on the page 

For examples on how tables should be made see: https://cookbook.kirby.design/home/showcase/reorder-list

Furthermore I would like for the following pages to be merged with the 'list'-page: 
- The 'list - swipe'-page (https://cookbook.kirby.design/home/showcase/list-swipe)
- The 'list - load on demand'-page (https://cookbook.kirby.design/home/showcase/list-load-on-demand)
- The 'list - no styling'-page (https://cookbook.kirby.design/home/showcase/list-no-shape)

I do not think that the 'list - reorder' page should be merged as `kirby-reorder-list` is a separate component. However I think that it could be considered if the menupoint should be renamed to: 'Reorder List' or something similar. 

Make sure that all relevant examples can be found when using the 'examples on GitHub' button. 

**Describe alternatives you've considered**
Instead of merging pages, implement the following menu structure: 
- List 
   - Default 
   - Load on Demand 
   - No styling
   - ... and so on 

### Kick Off:

- [ ] Ensure the enhancement is `UX refined` and aligned with UX 
_The component and/or enhancement should be published and available in the [Kirby Styleguide on Zeplin](https://zpl.io/258pXGj)_
- [ ] Ensure the enhancement has been `Tech refined` with @kirbydesign/kirby-guild and this issue is updated with a clear implementation description  
_This issue should be in the [Ready to do](https://github.com/kirbydesign/designsystem/projects/1#column-4590936) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1) before starting implementation)_
- [ ] Assign yourself to this issue and move it to the [In progress](https://github.com/kirbydesign/designsystem/projects/1#column-4590937) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1)

### Code:

- [ ] Create Feature Branch from [master branch](https://github.com/kirbydesign/designsystem/tree/master)
- [ ] Create a draft implementation and push to Github
- [ ] Ask a member of @kirbydesign/kirby-guild for a WIP review by creating a draft Pull Request
- [ ] Implement unit tests
- [ ] Update Cookbook Examples and Showcase, i.e. see [Radio](https://cookbook.kirby.design/home/showcase/radio)  
_Also remember to add any relevant new API documentation_

### Review:

- UX review:
  - [ ] Ensure implementation is correct in relation to the UX design and the [Kirby Styleguide on Zeplin](https://zpl.io/258pXGj)
  - [ ] With UX agree on the version of the implementation
- Code review:
  - [ ] Open a pull request (or mark the existing draft PR as `Ready for review`) and ask @kirbydesign/kirby-guild for a review  
_Remember to add `closes #issueno` to the description of the PR._
  - [ ] Once approved, merge feature branch/PR to master
- [ ] Ask a member of @kirbydesign/kirby-guild to add a link to component showcase from Kirby Component Status and update the version number

:tada: Celebrate

**Comment by RasmusKjeldgaard** [comment]
Adding this to the Storybook epic, as we can save some time when we move the docs to mdx files.

**Comment by RasmusKjeldgaard** [comment]
Closing this issue - we will address this the next time a list-issue bubbles up, similar to #3637, #3690
