### ISSUE TITLE
[Enhancement] Lazy load cookbook-iphone 

### ISSUE THREAD

**Issue by MadsBuchmann** [kirbydesign/designsystem#1368]
**Please add a short description of your enhancement request**
As there are many examples on the list page, the loading of the iPhone frames on the list page (https://cookbook.kirby.design/home/showcase/list) are getting heavy. Lazy loading could be used to solve this.

**Describe the solution you'd like**
Lazy loading should be implemented for the `cookbook-iphone` such that it is only rendered when it is visible. I am unsure of the "Angular way" to lazy load components - but the following article might be able to help: https://medium.com/angular-in-depth/improve-performance-with-lazy-components-f3c5ff4597d2

### Kick Off:

- [ ] Ensure the enhancement is `UX refined` and aligned with UX 
_The component and/or enhancement should be published and available in the [Kirby Styleguide on Zeplin](https://zpl.io/258pXGj)_
- [ ] Ensure the enhancement has been `Tech refined` with @kirbydesign/kirby-guild and this issue is updated with a clear implementation description  
_This issue should be in the [Ready to do](https://github.com/kirbydesign/designsystem/projects/1#column-4590936) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1) before starting implementation)_
- [ ] Assign yourself to this issue and move it to the [In progress](https://github.com/kirbydesign/designsystem/projects/1#column-4590937) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1)

### Code:

- [ ] Create Feature Branch from [master branch](https://github.com/kirbydesign/designsystem/tree/master)
- [ ] Create a draft implementation and push to Github
- [ ] Ask a member of @kirbydesign/kirby-guild for a WIP review by creating a draft Pull Request
- [ ] Implement unit tests
- [ ] Update Cookbook Examples and Showcase, i.e. see [Radio](https://cookbook.kirby.design/home/showcase/radio)  
_Also remember to add any relevant new API documentation_

### Review:

- UX review:
  - [ ] Ensure implementation is correct in relation to the UX design and the [Kirby Styleguide on Zeplin](https://zpl.io/258pXGj)
  - [ ] With UX agree on the version of the implementation
- Code review:
  - [ ] Open a pull request (or mark the existing draft PR as `Ready for review`) and ask @kirbydesign/kirby-guild for a review  
_Remember to add `closes #issueno` to the description of the PR._
  - [ ] Once approved, merge feature branch/PR to master
- [ ] Ask a member of @kirbydesign/kirby-guild to add a link to component showcase from Kirby Component Status and update the version number

:tada: Celebrate

**Comment by alxzak** [comment]
https://app.zenhub.com/workspaces/zenhub-602b70d809e4aa00141a1a93/board?labels=priority%202&repos=147814567
