### ISSUE TITLE
[BUG] It is not possible to use query parameters when linking directly to a modal

### ISSUE THREAD

**Issue by neigaard** [kirbydesign/designsystem#1369]
**Describe the bug**
When linking directly to a modal, if there a re any query parameters in the url, the modal does not open.

**To Reproduce**
1. Open the url: http://localhost:4200/drb/order-card/product-list/(modal:credit-max)
2. See that the modal is working fine (just without any data, but it will open)
3. Open the url: http://localhost:4200/drb/order-card/product-list/(modal:credit-max)?productNumber=42
4. See that the modal does not open and no error is written to the console

**Kirby version**
- 1.4.7

**Expected behavior**
I expect that the modal will open and that inside the loaded component the query parameter is accessible

**Please complete the following information:**
- OS: [MacOS]
- Browser [Firefox]
- Browser version [latest]

We have a deadline for a planned campain and to make that windown we need to get this on master on 11.3.2021

**Comment by hafstad** [comment]
Seems like modalRouteActivated$ never triggers, bug has been verified

**Comment by hafstad** [comment]
Issue is located in `modalRouteActivatedFor` because `navigationEnd.urlAfterRedirects` includes the query params but the routes inside `modalRouteMap` doesn't which results in no matches
