### ISSUE TITLE
[Housekeeping] Keep a CHANGELOG.md

### ISSUE THREAD

**Issue by Sobuno** [kirbydesign/designsystem#1372]
**Short description of housekeeping request**

Maintain a changelog next to the code instead of only in the cookbook site named CHANGELOG.md This is a pretty standard location for changelogs, thus making it easier for people unfamiliar with Kirby Design System to see changes between versions at a glance. The format could be https://keepachangelog.com/en/1.0.0/

**Alternatives**

The changelog is already present in the cookbook site, so a link in the README.md file could also be a solution.

**Additional context**

I am an administrator in a project that uses Kirby Design System. Bumping package versions in our project requires administrator approval, but I am not well-versed enough in Kirby Design System to know what impact a version bump has.

### Kick Off

* [ ] Ensure this issue has been `Tech refined` with @kirbydesign/kirby-guild and is updated with a clear implementation description
  _This issue should be in the [Ready to do](https://github.com/kirbydesign/designsystem/projects/1#column-4590936) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1) before starting implementation_
* [ ] Assign yourself to this issue and move it to the [In progress](https://github.com/kirbydesign/designsystem/projects/1#column-4590937) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1)

### Code

* [ ] Create Feature Branch from [master branch](https://github.com/kirbydesign/designsystem/tree/master)
* [ ] Implement/update unit tests
* [ ] Create a draft implementation and push to Github
* [ ] Ask a member of @kirbydesign/kirby-guild for a WIP review by creating a draft Pull Request

### Code Review

* [ ] Open a pull request (or mark the existing draft PR as `Ready for review`) and ask @kirbydesign/kirby-guild for a review
  _Remember to add `closes #issueno` to the description of the PR._
* [ ] Once approved, merge feature branch/PR to master

:tada: Celebrate

**Comment by alxzak** [comment]
Duplicate: Should be fixed by #1323
