### ISSUE TITLE
[Enhancement] How to Contribute page on cookbook 

### ISSUE THREAD

**Issue by alxzak** [kirbydesign/designsystem#1373]
**Please add a short description of your enhancement request**
I would like information about how to contribute to be accessible from the Kirby cookbook. So that I have the necessary knowledge to contribute to Kirby. 

**Describe the solution you'd like**
Clear information how to start contribute to Kirby, what processes I should hook into, and who to contact, if any.

Use https://www.carbondesignsystem.com/contributing/overview as a clear example of, what we are trying to accomplish and how everyone can add value to your designsystem. 

### Kick Off:

- [ ] Ensure the enhancement is `UX refined` and aligned with UX 
_The component and/or enhancement should be published and available in the [Kirby Styleguide on Zeplin](https://zpl.io/258pXGj)_
- [ ] Ensure the enhancement has been `Tech refined` with @kirbydesign/kirby-guild and this issue is updated with a clear implementation description  
_This issue should be in the [Ready to do](https://github.com/kirbydesign/designsystem/projects/1#column-4590936) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1) before starting implementation)_
- [ ] Assign yourself to this issue and move it to the [In progress](https://github.com/kirbydesign/designsystem/projects/1#column-4590937) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1)

### Code:

- [ ] Create Feature Branch from [master branch](https://github.com/kirbydesign/designsystem/tree/master)
- [ ] Create a draft implementation and push to Github
- [ ] Ask a member of @kirbydesign/kirby-guild for a WIP review by creating a draft Pull Request
- [ ] Implement unit tests
- [ ] Update Cookbook Examples and Showcase, i.e. see [Radio](https://cookbook.kirby.design/home/showcase/radio)  
_Also remember to add any relevant new API documentation_

### Review:

- UX review:
  - [ ] Ensure implementation is correct in relation to the UX design and the [Kirby Styleguide on Zeplin](https://zpl.io/258pXGj)
  - [ ] With UX agree on the version of the implementation
- Code review:
  - [ ] Open a pull request (or mark the existing draft PR as `Ready for review`) and ask @kirbydesign/kirby-guild for a review  
_Remember to add `closes #issueno` to the description of the PR._
  - [ ] Once approved, merge feature branch/PR to master
- [ ] Ask a member of @kirbydesign/kirby-guild to add a link to component showcase from Kirby Component Status and update the version number

:tada: Celebrate

**Comment by MadsBuchmann** [comment]
@alxzak @RasmusKjeldgaard - Is there a reason this is in the _done_ column on Zenhub without it being closed?

**Comment by RasmusKjeldgaard** [comment]
Must have been moved there by mistake, as this is not implemented yet. Moved it back.
