### ISSUE TITLE
[Housekeeping] Add markdown-to-html pipe to cookbook

### ISSUE THREAD

**Issue by jkaltoft** [kirbydesign/designsystem#1379]
**Short description of housekeeping request**

We use Markdown several places in the cookbook. E.g., where we use `<cookbook-showcase-properties>` the text in the description column often contains Markdown.

It would be a nice addition to have a markdown-to-html pipe for converting Markdown to markup 😎

*Example:*

The tables at the bottom of the [Page showcase](https://cookbook.kirby.design/home/showcase/page).

![image](https://user-images.githubusercontent.com/150451/109820403-3d63e580-7c35-11eb-9823-3f904cf8e55f.png)

It would be great if we could do:

```html
<td *ngIf="columns.Description" class="description">{{ prop.description | markdown }}</td>
```

in the [showcase-properties component template](https://github.com/kirbydesign/designsystem/blob/master/apps/cookbook/src/app/shared/showcase-properties/showcase-properties.component.html) - and anywhere else we need it.

**Alternatives**

Leave it as is.

**Additional context**

https://github.com/markedjs/marked

### Kick Off

* [ ] Ensure this issue has been `Tech refined` with @kirbydesign/kirby-guild and is updated with a clear implementation description
  _This issue should be in the [Ready to do](https://github.com/kirbydesign/designsystem/projects/1#column-4590936) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1) before starting implementation_
* [ ] Assign yourself to this issue and move it to the [In progress](https://github.com/kirbydesign/designsystem/projects/1#column-4590937) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1)

### Code

* [ ] Create Feature Branch from [master branch](https://github.com/kirbydesign/designsystem/tree/master)
* [ ] Implement/update unit tests
* [ ] Create a draft implementation and push to Github
* [ ] Ask a member of @kirbydesign/kirby-guild for a WIP review by creating a draft Pull Request

### Code Review

* [ ] Open a pull request (or mark the existing draft PR as `Ready for review`) and ask @kirbydesign/kirby-guild for a review
  _Remember to add `closes #issueno` to the description of the PR._
* [ ] Once approved, merge feature branch/PR to master

:tada: Celebrate

**Comment by MadsBuchmann** [comment]
@jkaltoft If I understand correctly this wouldn't be understand with the move to storybook, right :D?
