### ISSUE TITLE
[COMPONENT] Bulleted Lists

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#1391]
## Describe the issue you are facing
Right now we don't have a consistent way to make bulletlists in Kirby, nor do we have any Guidelines on how to use which and how. 

There are many different implementation in our products and this goes for both UX and DEV.

We need to come to a world where sketch and dev is 1:1 which thats why this task is here :) 

## Describe the solution you'd like
We would like have to have a component that can do it for us a, which also respects the text padding and margins we have on our components.

**_After tech refining this issue_**, we decided on NOT creating a separate component for this, but rather use the builtin `<ul>` and `<ol>` html tags. We see lists as part of the content, not as a separate component as such. This is the same way we use headings (`<h1-6>`) and paragraphs (`<p>`) which are also built into HTML itself.

We will style `<ul>` and `<ol>` by default in [libs/designsystem/src/lib/scss/base/_typography.scss](https://github.com/kirbydesign/designsystem/blob/87c7b52db92266e4a9153b633eca5e21090ce137/libs/designsystem/src/lib/scss/base/_typography.scss#L10) the same way we style headings (`<h1-6>`) and paragraphs (`<p>`).
This means any project using Kirby by default will get styled bulletlists out-of-the-box

We should also create a showcase on how to use bulleted lists with guidelines from UX (even though we don't have a separate component for them).
Maybe as a separate menu/component item or as part of a "Typography" or "Content" section?

Here are some more screenshots of how we want it to be:

**Specs:** 8px left and 8px right of the bullets for both ordered lists and unordered lists.
**_Please note_** The 16px spacing on the left will come from #1352 

<img width="423" alt="Skærmbillede 2021-03-12 kl  14 44 55" src="https://user-images.githubusercontent.com/49033002/110948504-b653f300-8341-11eb-9d04-989dbae075b5.png">
<img width="405" alt="Skærmbillede 2021-03-12 kl  14 44 52" src="https://user-images.githubusercontent.com/49033002/110948509-b6ec8980-8341-11eb-9462-238b33df77bd.png">

## Describe alternatives you've considered
1. Create a separate component =>
_but it's overhead for something already built into the language_
2. Make styled bulleted lists opt-in (e.g. by mandating a `<ul kirby-bulletlist>` attribute added to the list) =>
_but that would't give consistent list styling out-of-the-box for projects using Kirby_
3. A way to opt-out, e.g. by adding a `<ul kirby-unstyled>` attribute to individual lists and/or a `$list-style: false` flag specified where Kirby `global-styles` is imported in target project for opting out altogether
 
_We might do 2+3 as part of this issue or do it later if needed_

## Additional context

To get a understanding of how we work in sketch there is a screenshot below and how it gets implemented. 

<img width="700" alt="Skærmbillede 2021-03-08 kl  09 06 28" src="https://user-images.githubusercontent.com/49033002/110298858-5681e300-7ff5-11eb-9237-8d7b778ee3aa.png">

And here a screenshot of how a component could be built in both dev and sketch:

<img width="737" alt="Skærmbillede 2021-03-07 kl  14 54 16" src="https://user-images.githubusercontent.com/49033002/110300666-6c90a300-7ff7-11eb-87fc-3945d7b40101.png">

I've found these inspirations:
https://design.va.gov/content-style-guide/bulleted-lists
https://www.carbondesignsystem.com/components/list/usage/

### Kick Off:

- [x] Ensure Feature is `UX refined` and aligned with UX incl. name of component (our shared Design System Language).  
_The component should be published and available in the [Kirby Styleguide on Zeplin](https://zpl.io/258pXGj)_
- [x] Ensure Feature has been `Tech refined` with @kirbydesign/kirby-guild and this issue is updated with a clear implementation description  
_This issue should be in the [Ready to do](https://github.com/kirbydesign/designsystem/projects/1#column-4590936) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1) before starting implementation)_
- [ ] Assign yourself to this issue and move it to the [In progress](https://github.com/kirbydesign/designsystem/projects/1#column-4590937) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1)

### Code:

- [ ] Create Feature Branch from [master branch](https://github.com/kirbydesign/designsystem/tree/master)
- [ ] Implement Skeleton Component and push to Github
- [ ] Ask a member of @kirbydesign/kirby-guild for a WIP review by creating a draft Pull Request
- [ ] Implement unit tests
- [ ] Implement Cookbook Examples and Showcase, i.e. see [Radio](https://cookbook.kirby.design/home/showcase/radio)  
_Also remember to add any relevant API documentation_

### Review:

- UX review:
  - [ ] Ensure implementation is correct in relation to the UX design and the [Kirby Styleguide on Zeplin](https://zpl.io/258pXGj)
  - [ ] With UX agree on the version of the implementation + any additional steps needed to reach version 1.0 (create [enhancement requests](https://github.com/kirbydesign/designsystem/issues/new/choose))
- Code review:
  - [ ] Open a pull request (or mark the existing draft PR as `Ready for review`) and ask @kirbydesign/kirby-guild for a review  
_Remember to add `closes #issueno` to the description of the PR._
  - [ ] Once approved, merge feature branch/PR to master
- [ ] Ask a member of @kirbydesign/kirby-guild to add a link to component showcase from Kirby Component Status

:tada: Celebrate

**Comment by jkaltoft** [comment]
Regarding tech refinement:

I may be missing something here, but is there a reason this is not just implemented using standard HTML lists and CSS?

**Comment by bommariusser** [comment]
@jkaltoft we had refinement last week and we ended up with the same conclusion, not having a component. But if you implement a standard html list it will get some kirby styling :) 

@jakobe has written down some tech refinement stuff and will put them down here soon :)

**Comment by jakobe** [comment]
> @jkaltoft we had refinement last week and we ended up with the same conclusion, not having a component. But if you implement a standard html list it will get some kirby styling :)
> 
> @jakobe has written down some tech refinement stuff and will put them down here soon :)

Yep, the description of the issue has been updated after tech refinement (March 18) and the issue is ready and up for grabs 👍🏻

**Comment by MadsBuchmann** [comment]
I had a chat with @bommariusser regarding the temporary solution that has been made to solve this in DRB when [I self-assigned myself](https://github.com/kirbydesign/designsystem/issues/1391#event-4823365029). 

Just for good measure, here's the notes which can be kept in mind, when solving the issue:
* The distance between the bullet and text might vary depending on:
   * whether a un- or ordered list is used.  
   * whether the list is shown on Android or iOS
   * browser
* If a linebreak is inserted in the text for a list item, the text wraps to the next line directly under the bulletpoint without any indentation. 
* They have troubles applying the [typography classes](https://cookbook.kirby.design/home/showcase/fonts) to the list items due to the margin applied to text-tags such as h1, h2, p, etc...

**Comment by jeppevaldemar** [comment]
Bump

**Comment by bommariusser** [comment]
![Guideline](https://user-images.githubusercontent.com/49033002/134144560-cbeda4ec-a37e-4789-887f-7be9aed1653a.png)

See also guidelines here :)

**Comment by jkaltoft** [comment]
@bommariusser I've created some screen captures of how the solution aligns with what is displayed in Zeplin

**Comment by jkaltoft** [comment]
# Unordered list 1

https://user-images.githubusercontent.com/150451/135845256-42a895dd-8ecf-4132-aef7-c3d69071fbc1.mov

**Comment by jkaltoft** [comment]
# Unordered list 2

https://user-images.githubusercontent.com/150451/135845344-2145fae2-78f0-462e-bd9c-c94fc5f3ce06.mov

**Comment by jkaltoft** [comment]
# Ordered list 1

https://user-images.githubusercontent.com/150451/135845413-b19172ea-5082-4e92-b9f7-5b9ea5aa3221.mov

**Comment by jkaltoft** [comment]
# Ordered list 2

https://user-images.githubusercontent.com/150451/135845482-90e82f59-3eee-4d80-9473-25a548a87626.mov
