### ISSUE TITLE
[Enhancement] Calendar selectable dates need even spacing to all sides

### ISSUE THREAD

**Issue by MartinSkovsen** [kirbydesign/designsystem#1396]
**Please add a short description of your enhancement request**
As per the UX requirements the calendar selectable dates should have even spacing to all sides. Currently, it has none.

**Describe the solution you'd like**
[The required spacing](https://zpl.io/VQP8AxA) to all sides for selectable dates in calendar.

**Describe alternatives you've considered**
As this is a UX requirement and not implemented, no alternatives has been considered

**Additional context**
This is how it looks now in the cookbook:
![billede](https://user-images.githubusercontent.com/30232520/111645574-1db9e900-8801-11eb-8b47-cc7129eed7c6.png)

This is how it should look like (from zeplin):
![billede](https://user-images.githubusercontent.com/30232520/111647165-8b1a4980-8802-11eb-93b2-441d165c1403.png)

Cookbook: https://cookbook.kirby.design/home/showcase/calendar
Zeplin: https://zpl.io/bomPRNE

### Kick Off:

- [x] Ensure the enhancement is `UX refined` and aligned with UX 
_The component and/or enhancement should be published and available in the [Kirby Styleguide on Zeplin](https://zpl.io/258pXGj)_
- [x] Ensure the enhancement has been `Tech refined` with @kirbydesign/kirby-guild and this issue is updated with a clear implementation description  
_This issue should be in the [Ready to do](https://github.com/kirbydesign/designsystem/projects/1#column-4590936) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1) before starting implementation)_
- [x] Assign yourself to this issue and move it to the [In progress](https://github.com/kirbydesign/designsystem/projects/1#column-4590937) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1)

### Code:

- [x] Create Feature Branch from [master branch](https://github.com/kirbydesign/designsystem/tree/master)
- [x] Create a draft implementation and push to Github
- [x] Ask a member of @kirbydesign/kirby-guild for a WIP review by creating a draft Pull Request
- [ ] Implement unit tests
- [x] Update Cookbook Examples and Showcase, i.e. see [Radio](https://cookbook.kirby.design/home/showcase/radio)  
_Also remember to add any relevant new API documentation_

### Review:

- UX review:
  - [ ] Ensure implementation is correct in relation to the UX design and the [Kirby Styleguide on Zeplin](https://zpl.io/258pXGj)
  - [ ] With UX agree on the version of the implementation
- Code review:
  - [x] Open a pull request (or mark the existing draft PR as `Ready for review`) and ask @kirbydesign/kirby-guild for a review  
_Remember to add `closes #issueno` to the description of the PR._
  - [ ] Once approved, merge feature branch/PR to master
- [ ] Ask a member of @kirbydesign/kirby-guild to add a link to component showcase from Kirby Component Status and update the version number

:tada: Celebrate

**Comment by MartinSkovsen** [comment]
Tech refinement: Not having looked too much into this, i'd suggest adding the necessary spacing as padding with the correct size (xxxs) on both sides. There is one caveat, which is that the calendar is build in raw html as a table, so it is worth being aware of first and last child.

**Comment by MartinSkovsen** [comment]
@henrikvoetmand Can you confirm that this is not a fat finger related enhancement, but rather a visually pleasing enhancement? This is probably relevant to whether we use a margin or a padding.

**Comment by MartinSkovsen** [comment]
Alternative tech refinement: 4px spacing to all sides of the selectable dates, and then 4px spacing around the whole table.

**Comment by henrikvoetmand** [comment]
@MartinSkovsen Yes I can confirm - it is a visual enhancement.

**Comment by RasmusKjeldgaard** [comment]
@henrikvoetmand Can we accept that on the smallest of devices (iPhone 5/SE), the vertical spacing between dates will be smaller than the 8px defined in zeplin?

**Comment by RasmusKjeldgaard** [comment]
@henrikvoetmand and I agreed on a solution where we apply the specified spacing vertically, but horizontally the spacing will automatically fill out whatever leftover space there might be, based on the width of the calendars container.
