### ISSUE TITLE
[Enhancement] Dropdown should be confined when used in a calendar

### ISSUE THREAD

**Issue by MartinSkovsen** [kirbydesign/designsystem#1399]
**Please add a short description of your enhancement request**
I would like the dropdown to be confined when used in a calendar, so it becomes visually pleasing.

**Describe the solution you'd like**
When the dropdown is used in calendar wrapped in a card, I would like the dropdown to have same horizontal spacing as the padding of the card. When the calendar expands in width on larger screens, the dropdown should have have a max-width [as defined in zeplin](https://zpl.io/bLvEM7Y).

**Describe alternatives you've considered**

**Additional context**
Cookbook: https://cookbook.kirby.design/home/showcase/calendar
Zeplin - mobile: https://zpl.io/2vRk4Ne
Zeplin - desktop: https://zpl.io/bLvEM7Y

### Kick Off:

- [ ] Ensure the enhancement is `UX refined` and aligned with UX 
_The component and/or enhancement should be published and available in the [Kirby Styleguide on Zeplin](https://zpl.io/258pXGj)_
- [ ] Ensure the enhancement has been `Tech refined` with @kirbydesign/kirby-guild and this issue is updated with a clear implementation description  
_This issue should be in the [Ready to do](https://github.com/kirbydesign/designsystem/projects/1#column-4590936) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1) before starting implementation)_
- [ ] Assign yourself to this issue and move it to the [In progress](https://github.com/kirbydesign/designsystem/projects/1#column-4590937) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1)

### Code:

- [ ] Create Feature Branch from [master branch](https://github.com/kirbydesign/designsystem/tree/master)
- [ ] Create a draft implementation and push to Github
- [ ] Ask a member of @kirbydesign/kirby-guild for a WIP review by creating a draft Pull Request
- [ ] Implement unit tests
- [ ] Update Cookbook Examples and Showcase, i.e. see [Radio](https://cookbook.kirby.design/home/showcase/radio)  
_Also remember to add any relevant new API documentation_

### Review:

- UX review:
  - [ ] Ensure implementation is correct in relation to the UX design and the [Kirby Styleguide on Zeplin](https://zpl.io/258pXGj)
  - [ ] With UX agree on the version of the implementation
- Code review:
  - [ ] Open a pull request (or mark the existing draft PR as `Ready for review`) and ask @kirbydesign/kirby-guild for a review  
_Remember to add `closes #issueno` to the description of the PR._
  - [ ] Once approved, merge feature branch/PR to master
- [ ] Ask a member of @kirbydesign/kirby-guild to add a link to component showcase from Kirby Component Status and update the version number

:tada: Celebrate

**Comment by MartinSkovsen** [comment]
@henrikvoetmand Can you correct me if I got anything wrong here? When we get the description right, next step is to tech refine it.

**Comment by MartinSkovsen** [comment]
This needs further UX and tech refinement. See [this comment for context](https://github.com/kirbydesign/designsystem/issues/1398#issuecomment-801769321).

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
