### ISSUE TITLE
[Enhancement] Modal header title alignment

### ISSUE THREAD

**Issue by henrikvoetmand** [kirbydesign/designsystem#1405]
**Please add a short description of your enhancement request**
Align Modal header title text with progress cicle and "Close" icon.

**Describe the solution you'd like**
Align Modal header title text with progress cicle and "Close" icon.

**Describe alternatives you've considered**
Title is misaligned - bad visual experience :-)

**Additional context**
![Modal-Header-Title-Issue](https://user-images.githubusercontent.com/71710012/111149037-a5e38880-858c-11eb-9849-b7c27141924b.png)
![Modal-Header-Title-Issue-Desktop](https://user-images.githubusercontent.com/71710012/111149511-4174f900-858d-11eb-8665-7aab907d14fa.png)

### Kick Off:

- [x] Ensure the enhancement is `UX refined` and aligned with UX 
_The component and/or enhancement should be published and available in the [Kirby Styleguide on Zeplin](https://zpl.io/258pXGj)_
- [x] Ensure the enhancement has been `Tech refined` with @kirbydesign/kirby-guild and this issue is updated with a clear implementation description  
_This issue should be in the [Ready to do](https://github.com/kirbydesign/designsystem/projects/1#column-4590936) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1) before starting implementation)_
- [x] Assign yourself to this issue and move it to the [In progress](https://github.com/kirbydesign/designsystem/projects/1#column-4590937) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1)

### Code:

- [x] Create Feature Branch from [master branch](https://github.com/kirbydesign/designsystem/tree/master)
- [x] Create a draft implementation and push to Github
- [x] Ask a member of @kirbydesign/kirby-guild for a WIP review by creating a draft Pull Request
- [x] Implement unit tests
- [x] Update Cookbook Examples and Showcase, i.e. see [Radio](https://cookbook.kirby.design/home/showcase/radio)  
_Also remember to add any relevant new API documentation_

### Review:

- UX review:
  - [x] Ensure implementation is correct in relation to the UX design and the [Kirby Styleguide on Zeplin](https://zpl.io/258pXGj)
  - [ ] With UX agree on the version of the implementation
- Code review:
  - [ ] Open a pull request (or mark the existing draft PR as `Ready for review`) and ask @kirbydesign/kirby-guild for a review  
_Remember to add `closes #issueno` to the description of the PR._
  - [ ] Once approved, merge feature branch/PR to master
- [ ] Ask a member of @kirbydesign/kirby-guild to add a link to component showcase from Kirby Component Status and update the version number

:tada: Celebrate

**Comment by MartinSkovsen** [comment]
Tech refinement: Unset the height of ion title and set the top padding to be the UX required padding: 30px for desktop and 38px for mobile.

**Comment by bommariusser** [comment]
We just had a talk about the text size @MartinSkovsen and we only want it to be h2 when there is nothing else in the header. So as soon there is a subtitle or a progresscircle it should be P <3

**Comment by MartinSkovsen** [comment]
I unintenionally moved this to done. This should be reverted and placed correcly on our board.

**Comment by MartinSkovsen** [comment]
> We just had a talk about the text size @MartinSkovsen and we only want it to be h2 when there is nothing else in the header. So as soon there is a subtitle or a progresscircle it should be P <3

@bommariusser I'm not sure that has anything to do with alignment. Perhaps we should take a short call about it tomorrow, so I can better understand the requirement? Also a minor correction, we do, as I remember it, enforce the close button in the right corner. But what you mean is that if we either put content in the start slot or have a subtitle the actual title should be a paragraph?
