### ISSUE TITLE
[BUG] Slide button border radius too small

### ISSUE THREAD

**Issue by flemcito** [kirbydesign/designsystem#1412]
**Describe the bug**

The border radius of the outer container is too small, which makes it misaligned with the inner button 
![Screenshot 2021-03-17 at 08 34 06](https://user-images.githubusercontent.com/909794/111431042-90d93780-86fb-11eb-917e-391e0ed9c618.png)
**To Reproduce**

1. Go to https://cookbook.kirby.design/home/showcase/slide-button
2. See error

**Expected behavior**
The edge around the inner button should be even

**Screenshots**

**Please complete the following information:**
- OS: [e.g. Windows, MacOS, iOS]
- Browser [e.g. Chrome, Safari]
- Browser version [e.g. 22]

**Additional context**

## Tasks:
- [ ] Have the bug report verified by contacting a member of @kirbydesign/kirby-guild
- [ ] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [ ] Create Fix Branch
- [ ] Create test reproducing the error
- [ ] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
