### ISSUE TITLE
[COMPONENT] (Vertical) Stepper/Progress

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#1438]
**Describe the solution you'd like**
We would like a (Vertical) Stepper component that can show a users given process.

The component has 3 states:
1. Finished
2. Active
3. Inactive

The text inside the component should be Title + Subtitle. 

Defaults for text should be: 
_Inactive_ -  Title only 
_Finished/Active_  - Title + Subtitle. Dependant on usecase this should be possible to overwrite.

<img width="490" alt="Skærmbillede 2021-03-23 kl  14 11 40" src="https://user-images.githubusercontent.com/49033002/112153502-9e069280-8be3-11eb-841f-421ca2629ed1.png">

**Describe alternatives you've considered**
We have also a (Horizontal) stepper komponent which is called progress in our modal right now. Maybet this should be aligned. or the vertical stepper should be called vertical progress or something...

<img width="517" alt="Skærmbillede 2021-03-23 kl  14 31 38" src="https://user-images.githubusercontent.com/49033002/112154602-b88d3b80-8be4-11eb-87c7-b85b9b4829d8.png">

**Additional context**
See also https://zpl.io/2jN6gKO

The component should also at some time be able to edit the steps like this:

<img width="620" alt="Skærmbillede 2021-03-23 kl  15 21 30" src="https://user-images.githubusercontent.com/49033002/112161908-da3df100-8beb-11eb-928e-daa5a1efaa5a.png">

For inspiration check this out : https://material.io/archive/guidelines/components/steppers.html#

### Kick Off:

- [ ] Ensure Feature is `UX refined` and aligned with UX incl. name of component (our shared Design System Language).  
_The component should be published and available in the [Kirby Styleguide on Zeplin](https://zpl.io/258pXGj)_
- [ ] Ensure Feature has been `Tech refined` with @kirbydesign/kirby-guild and this issue is updated with a clear implementation description  
_This issue should be in the [Ready to do](https://github.com/kirbydesign/designsystem/projects/1#column-4590936) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1) before starting implementation)_
- [ ] Assign yourself to this issue and move it to the [In progress](https://github.com/kirbydesign/designsystem/projects/1#column-4590937) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1)

### Code:

- [ ] Create Feature Branch from [master branch](https://github.com/kirbydesign/designsystem/tree/master)
- [ ] Implement Skeleton Component and push to Github
- [ ] Ask a member of @kirbydesign/kirby-guild for a WIP review by creating a draft Pull Request
- [ ] Implement unit tests
- [ ] Implement Cookbook Examples and Showcase, i.e. see [Radio](https://cookbook.kirby.design/home/showcase/radio)  
_Also remember to add any relevant API documentation_

### Review:

- UX review:
  - [ ] Ensure implementation is correct in relation to the UX design and the [Kirby Styleguide on Zeplin](https://zpl.io/258pXGj)
  - [ ] With UX agree on the version of the implementation + any additional steps needed to reach version 1.0 (create [enhancement requests](https://github.com/kirbydesign/designsystem/issues/new/choose))
- Code review:
  - [ ] Open a pull request (or mark the existing draft PR as `Ready for review`) and ask @kirbydesign/kirby-guild for a review  
_Remember to add `closes #issueno` to the description of the PR._
  - [ ] Once approved, merge feature branch/PR to master
- [ ] Ask a member of @kirbydesign/kirby-guild to add a link to component showcase from Kirby Component Status

:tada: Celebrate

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
