### ISSUE TITLE
[Component] segmented-chip with Horizontal scroll

### ISSUE THREAD

**Issue by azeemchauhan** [kirbydesign/designsystem#144]
- Need to implement **data driven tabs** as per wireframes.
 - Those tabs are **scrollable** **horizontally**.
 - As of now we need **basic** implementation but in future It will be more enhanced as per need. 

<img width="421" alt="Screenshot 2019-03-12 at 2 10 26 PM" src="https://user-images.githubusercontent.com/33758493/54186136-adb94f80-44d0-11e9-9e3f-240746b36927.png">

### Kick Off:
- [x] Accept Feature incl. name of component (DSL)
- [x] Update Kirby Component Status and publish to [Kirby Cookbook](https://cookbook.kirby.design)
### Code:
- [x] Create Feature Branch
- [x] Implement Skeleton Component:
    - [x] Web implementation
    - [x] {N} implementation
- [x] [Implement Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [x] Push commits to GitHub
### Review:
- [x] Open a pull request and ask @kirbydesign/kirby-guild for review
- [ ] Update Kirby Component Status
- [x] Merge to master

**Comment by jakobe** [comment]
Closed by #176

**Comment by jakobe** [comment]
Closed by #176
