### ISSUE TITLE
[Housekeeping] Support for Node LTS (Node 14)

### ISSUE THREAD

**Issue by lydemann** [kirbydesign/designsystem#1443]
**Short description of housekeeping request**

Support for Node LTS (14.16.0 at this moment).

At the moment Node LTS gives this error:
![image](https://user-images.githubusercontent.com/9210691/112950322-70b56980-913a-11eb-89b2-90808fb54d46.png)

### Kick Off

* [ ] Ensure this issue has been `Tech refined` with @kirbydesign/kirby-guild and is updated with a clear implementation description
  _This issue should be in the [Ready to do](https://github.com/kirbydesign/designsystem/projects/1#column-4590936) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1) before starting implementation_
* [ ] Assign yourself to this issue and move it to the [In progress](https://github.com/kirbydesign/designsystem/projects/1#column-4590937) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1)

### Code

* [ ] Create Feature Branch from [master branch](https://github.com/kirbydesign/designsystem/tree/master)
* [ ] Implement/update unit tests
* [ ] Create a draft implementation and push to Github
* [ ] Ask a member of @kirbydesign/kirby-guild for a WIP review by creating a draft Pull Request

### Code Review

* [ ] Open a pull request (or mark the existing draft PR as `Ready for review`) and ask @kirbydesign/kirby-guild for a review
  _Remember to add `closes #issueno` to the description of the PR._
* [ ] Once approved, merge feature branch/PR to master

:tada: Celebrate

**Comment by MadsBuchmann** [comment]
**A note for whoever is assigned to this issue**: The current draft for the contribution guidelines has a "setup environment and tooling for contribution"-section where node v12 is recommended. It should be updated once we support v14 :)

**Comment by flemcito** [comment]
I have included a .tool-versions file to the repo root that determines which version the CI uses (currently 14.16.1).
If you use https://asdf-vm.com/#/ to manage NodeJS installations, the node version will also be set automatically locally
