### ISSUE TITLE
[Enhancement] Change min. width on dropdown button to 68px instead of 88px

### ISSUE THREAD

**Issue by LVinther** [kirbydesign/designsystem#1454]
**Please add a short description of your enhancement request**
We would like the dropdown button to have a min. width of 68 px instead of 88px

**Describe the solution you'd like**
We would like the dropdown button to have a min. width of 68 px instead of 88px. 

**Describe alternatives you've considered**
An alternative solution could be that we always use a long enough text in the dropdown... But the other solution would be preferable :) 

**Additional context**
On our dropdown in the investment frontpage we have a drop down with the text "I år". The empty area in the dropdown button looks funny :) 

![Skærmbillede 2021-04-07 kl  12 23 56](https://user-images.githubusercontent.com/53176253/113852473-e190fd00-979c-11eb-8364-e42b840431ad.png)

### Kick Off:

- [x] Ensure the enhancement is `UX refined` and aligned with UX 
_The component and/or enhancement should be published and available in the [Kirby Styleguide on Zeplin](https://zpl.io/258pXGj)_
- [ ] Ensure the enhancement has been `Tech refined` with @kirbydesign/kirby-guild and this issue is updated with a clear implementation description  
_This issue should be in the [Ready to do](https://github.com/kirbydesign/designsystem/projects/1#column-4590936) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1) before starting implementation)_
- [ ] Assign yourself to this issue and move it to the [In progress](https://github.com/kirbydesign/designsystem/projects/1#column-4590937) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1)

### Code:

- [ ] Create Feature Branch from [master branch](https://github.com/kirbydesign/designsystem/tree/master)
- [ ] Create a draft implementation and push to Github
- [ ] Ask a member of @kirbydesign/kirby-guild for a WIP review by creating a draft Pull Request
- [ ] Implement unit tests
- [ ] Update Cookbook Examples and Showcase, i.e. see [Radio](https://cookbook.kirby.design/home/showcase/radio)  
_Also remember to add any relevant new API documentation_

### Review:

- UX review:
  - [ ] Ensure implementation is correct in relation to the UX design and the [Kirby Styleguide on Zeplin](https://zpl.io/258pXGj)
  - [ ] With UX agree on the version of the implementation
- Code review:
  - [ ] Open a pull request (or mark the existing draft PR as `Ready for review`) and ask @kirbydesign/kirby-guild for a review  
_Remember to add `closes #issueno` to the description of the PR._
  - [ ] Once approved, merge feature branch/PR to master
- [ ] Ask a member of @kirbydesign/kirby-guild to add a link to component showcase from Kirby Component Status and update the version number

:tada: Celebrate

**Comment by RasmusKjeldgaard** [comment]
68px seems like an arbitrary value that just works in this specific case. 

Should we consider to use either fat finger size, or no minimum width for the button in general?

In the end, that is a UX decision.

**Comment by LVinther** [comment]
@henrikvoetmand I will book you for a meeting about this :)

**Comment by LVinther** [comment]
@RasmusKjeldgaard after a talk with @henrikvoetmand we have decided to remove the min. with for the dropdown button :)
