### ISSUE TITLE
[Enhancement] Update styling in Kirby List

### ISSUE THREAD

**Issue by SilverGull** [kirbydesign/designsystem#146]
The design of the Kirby list has been updated. These updates has to be implemented.

- Round corners on the first and last element of the list and list section
- Row dividers optional - needed for Totalkonto
- grey background in header and section header - is already transparent in section header
  - separate issue created for background colour https://github.com/kirbydesign/designsystem/issues/154

All of the content in the picture is in a list. The first part (value and graphs) being the header and then the data divided into sections.
 
<img width="382" alt="Skærmbillede 2019-03-13 kl  14 33 49" src="https://user-images.githubusercontent.com/43959200/54282877-300f4580-459d-11e9-9a94-5a184f8d6b2f.png">

**Comment by labanos** [comment]
Has been overtaken by other issues, as far as i can see - if anything is missing new issues should be created, with more specific enhancements.
