### ISSUE TITLE
[Housekeeping] Create linting rule to avoid referencing barrel files

### ISSUE THREAD

**Issue by flemcito** [kirbydesign/designsystem#1467]
**Short description of housekeeping request**
When referencing a component via a barrel file internally in our lib, we can get some really hard-to-debug errors, ie `ERROR: Cannot read property 'module' of undefined`.

What should be avoided is importing like this: 
`import { ActionSheetComponent } from './components/action-sheet/';`
(where we have a index.ts file in ./components/action-sheet/ exporting the component)

In stead we need to reference the component directly: 
`import { ActionSheetComponent } from './components/action-sheet/action-sheet.component';`

To enforce this, we need to create a linting rule that checks that, ie internal imports (inside our lib) always contain a `.` 

![image](https://user-images.githubusercontent.com/909794/117771241-2eea0980-b236-11eb-992a-594f3567f6aa.png)

### Kick Off

* [ ] Ensure this issue has been `Tech refined` with @kirbydesign/kirby-guild and is updated with a clear implementation description
  _This issue should be in the [Ready to do](https://github.com/kirbydesign/designsystem/projects/1#column-4590936) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1) before starting implementation_
* [ ] Assign yourself to this issue and move it to the [In progress](https://github.com/kirbydesign/designsystem/projects/1#column-4590937) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1)

### Code

* [ ] Create Feature Branch from [master branch](https://github.com/kirbydesign/designsystem/tree/master)
* [ ] Implement/update unit tests
* [ ] Create a draft implementation and push to Github
* [ ] Ask a member of @kirbydesign/kirby-guild for a WIP review by creating a draft Pull Request

### Code Review

* [ ] Open a pull request (or mark the existing draft PR as `Ready for review`) and ask @kirbydesign/kirby-guild for a review
  _Remember to add `closes #issueno` to the description of the PR._
* [ ] Once approved, merge feature branch/PR to master

:tada: Celebrate

**Comment by hafstad** [comment]
@flemcito why is that an issue? :) Whole kirby package is a barrel. Because we dont want the users to have deep refs to our stuff

**Comment by hafstad** [comment]
Nvm I see your reason in the description now, I'm still not sure however it's the way to go
