### ISSUE TITLE
[BUG] Modal (feature hint) missing box-shadow

### ISSUE THREAD

**Issue by flemcito** [kirbydesign/designsystem#1510]
**Describe the bug**
In https://cookbook.kirby.design/home/showcase/modal
When you select "interact with background" and de-selects "Add custom CSS class", the modal is shown without box-shadow/elevation.

**To Reproduce**

1. Go to https://cookbook.kirby.design/home/showcase/modal
2. Select "interact with background"
3. De-selects "Add custom CSS class"
4. Click "Show drawer"
5. See error

**Screenshots**
![Screenshot 2021-04-27 at 14 35 46](https://user-images.githubusercontent.com/909794/116242110-e32f5e80-a765-11eb-9dc7-fe9b897f28ab.png)

**Please complete the following information:**
- OS: [e.g. Windows, MacOS, iOS]
- Browser [e.g. Chrome, Safari]
- Browser version [e.g. 22]

**Additional context**

## Tasks:
- [ ] Have the bug report verified by contacting a member of @kirbydesign/kirby-guild
- [ ] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [ ] Create Fix Branch
- [ ] Create test reproducing the error
- [ ] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch

**Comment by bommariusser** [comment]
true stuff @flemcito :) Although the light feature-hint is non-existing.

**Comment by MadsBuchmann** [comment]
I've tested out the steps and can verify the bug.

**Comment by Fuzzy3** [comment]
Works as intended (When used as feature hints - always black)
