### ISSUE TITLE
[Enhancement] Button attention levels

### ISSUE THREAD

**Issue by henrikvoetmand** [kirbydesign/designsystem#1512]
**Please add a short description of your enhancement request**
We want to simplify the use of button attention levels. 

**Describe the solution you'd like**

- Reduce the amount of attention levels from 4 to 3. 
- Make the levels visual identical for "light" background (on canvas) and "white" background (on card). 
- Simplify the Cookbook-button page (Remove "Destructive button section and Remove "Toggle button section)

**Describe alternatives you've considered**
Leave the attentions levels As-Is - hard to use and understand.

**Additional context**

![Btn-Issue-image](https://user-images.githubusercontent.com/71710012/116246249-18d64680-a76a-11eb-9176-f91750afe731.png)

### Kick Off:

- [x] Ensure the enhancement is `UX refined` and aligned with UX 
_The component and/or enhancement should be published and available in the [Kirby Styleguide on Zeplin](https://zpl.io/258pXGj)_
- [x] Ensure the enhancement has been `Tech refined` with @kirbydesign/kirby-guild and this issue is updated with a clear implementation description  
_This issue should be in the [Ready to do](https://github.com/kirbydesign/designsystem/projects/1#column-4590936) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1) before starting implementation)_
- [x] Assign yourself to this issue and move it to the [In progress](https://github.com/kirbydesign/designsystem/projects/1#column-4590937) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1)

### Code:

- [x] Create Feature Branch from [master branch](https://github.com/kirbydesign/designsystem/tree/master)
- [x] Create a draft implementation and push to Github
- [x] Ask a member of @kirbydesign/kirby-guild for a WIP review by creating a draft Pull Request
- [x] Implement unit tests
- [x] Update Cookbook Examples and Showcase, i.e. see [Radio](https://cookbook.kirby.design/home/showcase/radio)  
_Also remember to add any relevant new API documentation_

### Review:

- UX review:
  - [x] Ensure implementation is correct in relation to the UX design and the [Kirby Styleguide on Zeplin](https://zpl.io/258pXGj)
  - [ ] With UX agree on the version of the implementation
- Code review:
  - [x] Open a pull request (or mark the existing draft PR as `Ready for review`) and ask @kirbydesign/kirby-guild for a review  
_Remember to add `closes #issueno` to the description of the PR._
  - [ ] Once approved, merge feature branch/PR to master
- [ ] Ask a member of @kirbydesign/kirby-guild to add a link to component showcase from Kirby Component Status and update the version number

:tada: Celebrate

**Comment by henrikvoetmand** [comment]
Tech refinement:
 - Search and replace "AttnLvl2" -> "AttnLvl3"
 - Ask UX to define where the black AttnLvl 2 is used by design
 - Consider major version of Kirby - due to visual breaking change
 - Inform UX about the scedule for this enhancement.
 - Consider how to handle AttnLvl4 in other components
 -

**Comment by RasmusKjeldgaard** [comment]
A couple of small additions: 
Ask UX first about the black AttnLvl 2 buttons, then search and replace all other instances than those. They should remain attention level 2. 

W.r.t. the last point about AttnLvl 4: AttnLvl 4 should no longer be part of the external API, so internally we could instead look at the context of the button and style it accordingly.

**Comment by MadsBuchmann** [comment]
@jkaltoft Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Zenhub-602b70d809e4aa00141a1a93/issues/kirbydesign/designsystem/1512?planning-poker)
