### ISSUE TITLE
[Housekeeping] Get rid of momentjs

### ISSUE THREAD

**Issue by hafstad** [kirbydesign/designsystem#1513]
**Short description of housekeeping request**

Momentjs is considered to be legacy, and performance wise doesn't make any sense as it's not tree-shakeable  

**Alternatives**

We should replace momentjs with a better alternative

**Additional context**

https://momentjs.com/docs/#/-project-status/
https://github.com/you-dont-need/You-Dont-Need-Momentjs
https://blog.logrocket.com/4-alternatives-to-moment-js-for-internationalizing-dates/

### Kick Off

* [ ] Ensure this issue has been `Tech refined` with @kirbydesign/kirby-guild and is updated with a clear implementation description
  _This issue should be in the [Ready to do](https://github.com/kirbydesign/designsystem/projects/1#column-4590936) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1) before starting implementation_
* [ ] Assign yourself to this issue and move it to the [In progress](https://github.com/kirbydesign/designsystem/projects/1#column-4590937) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1)

### Code

* [ ] Create Feature Branch from [master branch](https://github.com/kirbydesign/designsystem/tree/master)
* [ ] Implement/update unit tests
* [ ] Create a draft implementation and push to Github
* [ ] Ask a member of @kirbydesign/kirby-guild for a WIP review by creating a draft Pull Request

### Code Review

* [ ] Open a pull request (or mark the existing draft PR as `Ready for review`) and ask @kirbydesign/kirby-guild for a review
  _Remember to add `closes #issueno` to the description of the PR._
* [ ] Once approved, merge feature branch/PR to master

:tada: Celebrate

**Comment by RasmusKjeldgaard** [comment]
**Tech refinement:** Chartjs (replacing our use of highcharts soon) has adapters for [luxon, moment and date-fns](https://www.chartjs.org/docs/latest/axes/cartesian/time.html?h=adapter) in case we ever need to have a time-axis on our graphs. Furthermore, date-fns is [tree-shakeable](https://github.com/you-dont-need/You-Dont-Need-Momentjs), so all in all, **date-fns** seems to be the most feasible solution to research first.
