### ISSUE TITLE
[BUG] Title and footer do not render correctly in modal with outlet in some cases

### ISSUE THREAD

**Issue by kaelra** [kirbydesign/designsystem#1517]
**Describe the bug**
`<kirby-page-title>` and `<kirby-modal-footer>` render incorrectly when these conditions are met:
- used within modal with outlet
- `<kirby-page-title>` and `<kirby-modal-footer>` are wrapped in sub components and conditionally added to the template i.e. using `*ngIf`
- when navigating to the component using `modalController.navigateWithinModal( ... )`.

**To Reproduce**
Access DRB with mock data on branch `T052/modal-title-footer`

If accessing DRB in a web browser:
1. Go directly to `drb/investment/x-investment/onboarding/(modal:select-profile)` in the URL
2. Click 'Vælg' and then '>'
3. See error
4. Refresh the page and see the modal render correctly.
5. Click '<', 'Vælg' and '>'
6. See the error again

In the app
1. Toggle on 'Jyske Investering' and 'Jyske Investering - Onboarding'
2. Go to 'Investering'
3. Click on 'Start onboarding'
4. Click on 'Start nu > '
5. Check 'Jeg accepterer....'
6. Click 'Lav din plan >'
7. Fill in values and click '>' until arriving at the 'Gennemgå din plan' step
8. See error

**Kirby version**
- 1.4.44

**Expected behavior**
![Screenshot 2021-04-28 at 15 08 58](https://user-images.githubusercontent.com/56592130/116409054-c2353f00-a833-11eb-92c0-18d3426505a6.png)

**Screenshots**
![Screenshot 2021-04-28 at 15 06 51](https://user-images.githubusercontent.com/56592130/116408681-65398900-a833-11eb-9171-606f61956d3b.png)

**Please complete the following information:**
- OS: [e.g. Windows, MacOS, iOS]
- Browser [e.g. Chrome, Safari]
- Browser version [e.g. 22]

**Additional context**

## Tasks:
- [ ] Have the bug report verified by contacting a member of @kirbydesign/kirby-guild
- [ ] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [ ] Create Fix Branch
- [ ] Create test reproducing the error
- [ ] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch

**Comment by RasmusKjeldgaard** [comment]
This seems related to https://github.com/kirbydesign/designsystem/issues/1312 which is already on the backlog.

**Comment by RasmusKjeldgaard** [comment]
I can verify this, both in DRB as instructed, and in the cookbook. The following minimum example can be used to replicate in the cookbook: 

Replace the content of [https://github.com/kirbydesign/designsystem/blob/master/apps/cookbook/src/app/examples/modal-example/modal-route-example/modal-route-page1-example.component.ts](modal-route-page1-example.component.ts) with the following code snippet: 

`import { Component } from '@angular/core';
import { ModalController } from '@kirbydesign/designsystem';

@Component({
  selector: 'cookbook-modal-route-page-1-example',
  template: `
    <test-header *ngIf="showTitle"></test-header>

    <p>
      "Lorem ipsum"
    </p>
    <test-footer *ngIf="showFooter"></test-footer>
  `
})
export class ModalRoutePage1ExampleComponent {
  showTitle: boolean = true;
  showFooter: boolean = true;
}

@Component({
  selector: 'test-header',
  template: `
    <kirby-page-title>Modal Page 1/2</kirby-page-title>
    `,
})
export class TestHeader {
}

@Component({
  selector: 'test-footer',
  template: `
    <kirby-modal-footer>
      <button kirby-button class="nav" (click)="navigateToPreviousModal()">
        Next
        <kirby-icon name="arrow-more"></kirby-icon>
      </button>
    </kirby-modal-footer>
    `,
})
export class TestFooter {

  constructor(private modalController: ModalController) {}

  navigateToPreviousModal() {
    this.modalController.navigateWithinModal('../page2');
  }
}
`

**Comment by RasmusKjeldgaard** [comment]
Possible workaround: 

Move ngIf away from kirby-page-title:

```
<kirby-page-title>
  <div *ngIf="title">{{ title }}</div>
</kirby-page-title>
```

And move the `jbi-onboarding-header` and `jbi-onboarding-footer` components out of the ng-container check, so only `<jbi-goal-status>` is wrapped in `<ng-container *ngIf="!(returnProjectionError$ | async); else error">`, and then maybe disable next button in footer if there is an error?
