### ISSUE TITLE
[Enhancement] Backdrop outlet receives Android back navigation instead of drawer

### ISSUE THREAD

**Issue by trtbankdata** [kirbydesign/designsystem#1549]
**Please add a short description of your enhancement request**
When using the physical or, now in most cases, virtual back-button on Android after a drawer is shown. The navigation event is not directed towards the drawer but to the backdrop outlet.
The result in DRB is that the user of whom has chosen home as the start page is logged out after pressing the back button when the transfer drawer is shown.
I'd like the drawer to receive the navigation event instead of the backdrop outlet.

**Describe the solution you'd like**
I'd like the drawer to receive the navigation event instead of the backdrop outlet.

**Describe alternatives you've considered**
If this is possible in the near future steps will have to be take to remove the back-navigation on Android all together.

**Additional context**
![back_button_navigation_issue](https://user-images.githubusercontent.com/43603079/118940933-82a0d500-b951-11eb-8fd6-e25b294ac05b.gif)

### Kick Off:

- [ ] Ensure the enhancement is `UX refined` and aligned with UX 
_The component and/or enhancement should be published and available in the [Kirby Styleguide on Zeplin](https://zpl.io/258pXGj)_
- [ ] Ensure the enhancement has been `Tech refined` with @kirbydesign/kirby-guild and this issue is updated with a clear implementation description  
_This issue should be in the [Ready to do](https://github.com/kirbydesign/designsystem/projects/1#column-4590936) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1) before starting implementation)_
- [ ] Assign yourself to this issue and move it to the [In progress](https://github.com/kirbydesign/designsystem/projects/1#column-4590937) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1)

### Code:

- [ ] Create Feature Branch from [master branch](https://github.com/kirbydesign/designsystem/tree/master)
- [ ] Create a draft implementation and push to Github
- [ ] Ask a member of @kirbydesign/kirby-guild for a WIP review by creating a draft Pull Request
- [ ] Implement unit tests
- [ ] Update Cookbook Examples and Showcase, i.e. see [Radio](https://cookbook.kirby.design/home/showcase/radio)  
_Also remember to add any relevant new API documentation_

### Review:

- UX review:
  - [ ] Ensure implementation is correct in relation to the UX design and the [Kirby Styleguide on Zeplin](https://zpl.io/258pXGj)
  - [ ] With UX agree on the version of the implementation
- Code review:
  - [ ] Open a pull request (or mark the existing draft PR as `Ready for review`) and ask @kirbydesign/kirby-guild for a review  
_Remember to add `closes #issueno` to the description of the PR._
  - [ ] Once approved, merge feature branch/PR to master
- [ ] Ask a member of @kirbydesign/kirby-guild to add a link to component showcase from Kirby Component Status and update the version number

:tada: Celebrate

**Comment by RasmusKjeldgaard** [comment]
**Discussion: **
A possible solution is to close the drawer on back button click. In the end, it is a UX decision if this is acceptable, as users can have filled in information that will be lost if the drawer is closed. 

Expected behavior in this case would be better achieved by using a modal with outlet instead of the current solution with a modal with component.

**Comment by RasmusKjeldgaard** [comment]
As per agreement with @trtbankdata, I'm closing this one as it should be achieved by using a modal with outlet.
