### ISSUE TITLE
[Enhancement] Respect Font Size User Preference on iOS 

### ISSUE THREAD

**Issue by MadsBuchmann** [kirbydesign/designsystem#1563]
**Please add a short description of your enhancement request**
Kirby does not respect the system wide font scaling on iOS; it however works on Android as it comes out-of-the-box. 

I would like for Kirby to respect it to be more accessible on iOS ♿️

**Describe the solution you'd like**
On iOS we need to use Apples custom font style variables.

**Describe alternatives you've considered**
Leaving as is - causing trouble for users which need increased font sizes. 

**Additional context**
This issue stems from #1010 which was created in May 2020; an issue I closed as it introduced breaking changes with Safari, broke a bunch of tests, had no tests and had some old defaults. This is not because the work in the PR is of poor quality, but simply because it has been laying around for so long. 

#1010 can be used as a reference solution - do note however that `@supports (font: -apple-system-headline)` does not only target iOS devices, but also the Safari browser on macOS ([-webkit-touch-callout](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-touch-callout) might be of use here).

Also remember to add tests to [`typography.spec.ts`](https://github.com/kirbydesign/designsystem/blob/master/libs/designsystem/src/lib/scss/base/typography.spec.ts) for the new resizing functionality. 

It might be more appropriate to include this functionality as part of looking into changing to use relative units for fonts (has been discussed by @jkaltoft and I several times).  

### Kick Off:

- [ ] Ensure the enhancement is `UX refined` and aligned with UX 
_The component and/or enhancement should be published and available in the [Kirby Styleguide on Zeplin](https://zpl.io/258pXGj)_
- [ ] Ensure the enhancement has been `Tech refined` with @kirbydesign/kirby-guild and this issue is updated with a clear implementation description  
_This issue should be in the [Ready to do](https://github.com/kirbydesign/designsystem/projects/1#column-4590936) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1) before starting implementation)_
- [ ] Assign yourself to this issue and move it to the [In progress](https://github.com/kirbydesign/designsystem/projects/1#column-4590937) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1)

### Code:

- [ ] Create Feature Branch from [master branch](https://github.com/kirbydesign/designsystem/tree/master)
- [ ] Create a draft implementation and push to Github
- [ ] Ask a member of @kirbydesign/kirby-guild for a WIP review by creating a draft Pull Request
- [ ] Implement unit tests
- [ ] Update Cookbook Examples and Showcase, i.e. see [Radio](https://cookbook.kirby.design/home/showcase/radio)  
_Also remember to add any relevant new API documentation_

### Review:

- UX review:
  - [ ] Ensure implementation is correct in relation to the UX design and the [Kirby Styleguide on Zeplin](https://zpl.io/258pXGj)
  - [ ] With UX agree on the version of the implementation
- Code review:
  - [ ] Open a pull request (or mark the existing draft PR as `Ready for review`) and ask @kirbydesign/kirby-guild for a review  
_Remember to add `closes #issueno` to the description of the PR._
  - [ ] Once approved, merge feature branch/PR to master
- [ ] Ask a member of @kirbydesign/kirby-guild to add a link to component showcase from Kirby Component Status and update the version number

:tada: Celebrate

**Comment by RasmusKjeldgaard** [comment]
This issue is on track to be fixed by the work listed in #3586.
