### ISSUE TITLE
[BUG] Link External Icon not shown on branch build 

### ISSUE THREAD

**Issue by ckibsen** [kirbydesign/designsystem#1565]
**Describe the bug**
When viewing a link / an `<a>-tag` with a class="kirby-external-icon" on an Artifacts Manager branch build, the link.svg icon is not referenced using the correct path, and is therefore not shown. 

When running a localhost build locally, or a master build on Artifacts Manager, the path to the icon is correct, and it is shown as expected.

**To Reproduce**

1. Visit a page on an Artifacts Manager Branch build which uses a `<a href="xxx" class="kirby-external-icon"> `tag!
2. See that link.svg fails to load 

**Kirby version**
- 2.0.1

**Expected behavior**
link.svg loaded and shown no matter how I access my branch build

**Screenshots**
![Screenshot 2021-06-02 at 14 24 34](https://user-images.githubusercontent.com/832287/120480732-a8959300-c3af-11eb-9b56-35886e02f952.png)
![Screenshot 2021-06-02 at 14 26 41](https://user-images.githubusercontent.com/832287/120480785-b3502800-c3af-11eb-9d79-40efbeae0a0d.png)

**Please complete the following information:**
- OS: macOS 11.3
- Browser Chrome
- Browser version 90.0.4430.212

**Additional context**
Screenshots showing that link.svg fails to load on branch build accessed through Artifacts Manager, but working as expected running the same code on localhost.
Additional screenshot showing that link.svg can be loaded, when specifying the full path to the icon.

*NOT Prioritized*
Urgent fix not needed - can be tested on device builds (iOS/Android) or when code is merged to master. However it would be a nice fix, in order not to be reported as errors by our testers, when testing branch builds.

## Tasks:
- [ ] Have the bug report verified by contacting a member of @kirbydesign/kirby-guild
- [ ] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [ ] Create Fix Branch
- [ ] Create test reproducing the error
- [ ] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch

**Comment by Fuzzy3** [comment]
Fixed by #3527
