### ISSUE TITLE
[Clarification] customization vs. forced look and feel :-)

### ISSUE THREAD

**Issue by SilverGull** [kirbydesign/designsystem#157]
When developing for Kirby it is not clear to which degree the Kirby look and feel should be forced upon the developer and to which degree customisation of the look and feel should be implemented.

I ask because the list design has changed from having row dividers to not having row dividers. I am inclined to remove the row dividers from the list for now and when someone needs it at some point, they can add optional row dividers.

**Comment by labanos** [comment]
@SilverGull not sure there is one answer to this question ;) It sounds like something that should be discussed on the Kirby Guild - case by case... ;)
