### ISSUE TITLE
Keyboard ready: Perform accessibility evaluation on all Kirby components

### ISSUE THREAD

**Issue by jkaltoft** [kirbydesign/designsystem#1588]
For each component in Kirby do:

- [ ] Use an automated tool to point you in the right direction. This is only a first step that can help detect a subset of accessibility issues.
    - [WAVE Web Accessibility Evaluation Tool](https://wave.webaim.org/) - it has extensions for most browsers
    - Use the built-in accessibility tools in web browsers
    - Other tools, e.g. Lighthouse and axe (but mind that you can [build a completely inaccessible site and still get a perfect Lighthouse score](https://www.matuzo.at/blog/building-the-most-inaccessible-site-possible-with-a-perfect-lighthouse-score/))
- [ ] Manual user tests
- [ ] Create issues for each identified accessibility issue
    - Add to [Keyboard ready Kirby](1522) epic

**Comment by RasmusKjeldgaard** [comment]
Replaced by overall accessibility initiative across components, including keyboard behavior.
