### ISSUE TITLE
[Enhancement] List sections support for changing the bottom margin

### ISSUE THREAD

**Issue by lydemann** [kirbydesign/designsystem#1599]
**Please add a short description of your enhancement request**
Support for changing the margin of section bottom:

![image](https://user-images.githubusercontent.com/9210691/120789716-42854900-c532-11eb-9055-f23988d797d6.png)

So we can implement this design:

https://zpl.io/2jNjQWq

With 8px margin.

**Describe the solution you'd like**
A css variable the client can set or support for removing margin bottom from sections (using eg. sectionSection input to list) so you can control it yourself.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or enhancement you've considered.

**Additional context**

### Kick Off:

- [ ] Ensure the enhancement is `UX refined` and aligned with UX 
_The component and/or enhancement should be published and available in the [Kirby Styleguide on Zeplin](https://zpl.io/258pXGj)_
- [ ] Ensure the enhancement has been `Tech refined` with @kirbydesign/kirby-guild and this issue is updated with a clear implementation description  
_This issue should be in the [Ready to do](https://github.com/kirbydesign/designsystem/projects/1#column-4590936) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1) before starting implementation)_
- [ ] Assign yourself to this issue and move it to the [In progress](https://github.com/kirbydesign/designsystem/projects/1#column-4590937) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1)

### Code:

- [ ] Create Feature Branch from [master branch](https://github.com/kirbydesign/designsystem/tree/master)
- [ ] Create a draft implementation and push to Github
- [ ] Ask a member of @kirbydesign/kirby-guild for a WIP review by creating a draft Pull Request
- [ ] Implement unit tests
- [ ] Update Cookbook Examples and Showcase, i.e. see [Radio](https://cookbook.kirby.design/home/showcase/radio)  
_Also remember to add any relevant new API documentation_

### Review:

- UX review:
  - [ ] Ensure implementation is correct in relation to the UX design and the [Kirby Styleguide on Zeplin](https://zpl.io/258pXGj)
  - [ ] With UX agree on the version of the implementation
- Code review:
  - [ ] Open a pull request (or mark the existing draft PR as `Ready for review`) and ask @kirbydesign/kirby-guild for a review  
_Remember to add `closes #issueno` to the description of the PR._
  - [ ] Once approved, merge feature branch/PR to master
- [ ] Ask a member of @kirbydesign/kirby-guild to add a link to component showcase from Kirby Component Status and update the version number

:tada: Celebrate

**Comment by jkaltoft** [comment]
If this is solved before #1604 it can be used as part of the solution for that issue.

**Comment by RasmusKjeldgaard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-Owner-Workspace-602b70d809e4aa00141a1a93/issues/kirbydesign/designsystem/1599?planning-poker) with ZenHub @MadsBuchmann @jkaltoft
