### ISSUE TITLE
[Enhancement] Enable styling for rounded corners

### ISSUE THREAD

**Issue by askarby** [kirbydesign/designsystem#160]
**Is your enhancement request related to a problem? Please describe.**
The list is rendered with rounded corners (both for sections, but also non-sectioned lists) in the kirby design system. We need to implement a feature where corners are "per default" rounded, but generic classes are applied, so that individual styling can be applied.

**Describe the solution you'd like**
Apply a class for top-most (either in entire list, or sectioned content) as well as bottom most items.

**Describe alternatives you've considered**
Using pseudo-selectors, but this doesn't work very well with {N}

**Additional context**
N/A

**Comment by jakobe** [comment]
Closed by #162
