### ISSUE TITLE
[BUG] Animation glitchy upon routing with `skipLocationChange`

### ISSUE THREAD

**Issue by askarby** [kirbydesign/designsystem#1623]
**Describe the bug**
We're trying to create a better navigation flow when searching for securities. In the progress of doing so, we'd like to avoid the following flow:

```
Overview page -> search page -> details page -> search page -> details page
```

Since this provides the following UX issues:
-  having to back-navigate 4 times to get to the Overview page
- Not retaining search, nor search results

Instead, we're aiming for the following solution:

```
Overview page -> search page -> details page \
                    \________________________/
```

To accomplish this, we've made the "search button" (on the details page link to the search page, but replace the state on the history stack, eg.:

```
this.router.navigateByUrl(INVESTMENT_PATHS.search, {
  relativeTo: this.route,
  skipLocationChange: true,
});
```

This does actually work (read: we navigate to where we want to go!), but the page-transition animation is somewhat flaky - almost like it doesn't know if if wants to transition from left-to-right, or right-to-left - and then does "a bit of both".

**To Reproduce**

1. Create a page that navigates to another page
2. Make the button navigate using the `Router` passing the option `skipLocationChange: true`
3. See the page animate in an interesting manor

**Kirby version**
- 2.0.7

**Expected behavior**

**Screenshots**

n/a

**Please complete the following information:**
- iOS and Mac (web on Chrome)
- Chrome and safari?
- Latest version

**Additional context**

## Tasks:
- [ ] Have the bug report verified by contacting a member of @kirbydesign/kirby-guild
- [ ] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [ ] Create Fix Branch
- [ ] Create test reproducing the error
- [ ] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch

**Comment by MadsBuchmann** [comment]
I will attempt to verify this bug

**Comment by RasmusKjeldgaard** [comment]
Any way related to this issue? #1203

**Comment by MadsBuchmann** [comment]
@askarby - would it be possible to provide a codesnippet & eventually also a video of what goes wrong?

**Comment by askarby** [comment]
There's already a code-snippet in the description of the issue above, eg.:

```ts
this.router.navigateByUrl(INVESTMENT_PATHS.search, {
  relativeTo: this.route,
  skipLocationChange: true,
});
```

I'll try and see if I can hack together a solution (to provide a video), I abandoned my branch as I filed this bug. I'll get back to you (tomorrow) when I'm able to reproduce it.

**Comment by MadsBuchmann** [comment]
Apologies - I should perhaps have specified it a bit more 😅

I would just like to be able to see the surrounding context. What does `this.route` & `this.router` refer to and is there any other details in the surrounding code that might cause problems.

**Comment by askarby** [comment]
@MadsBuchmann will you try to catch me on Slack, some time after 9... I'm not able to reproduce it any more. Maybe we should have a talk about "what we want to accomplish" (on the investment team) instead of hacking the navigation mechanism?

**Comment by MadsBuchmann** [comment]
@askarby - avoiding hacking stuff together seems like the way to go 😄
I have some stuff I need to get done. So I might not get back to you before Tomorrow or Monday. But I've created a reminder to give you a call!

**Comment by askarby** [comment]
Hi Mads,

I'm having Lotte attach a video of what we're experiencing.

We have discovered that the issue may be solved by us manually specifying the page animation, based on a routing event (not sure if that's an option). Regardless, we'll have an enhancement request following this bug, since we see a need for specifying this behavior. It's all very complicated to describe in text - hopefully, the video will explain it much more cleanly. 

Will you give me a call tomorrow, so we can have a talk about a possible solution?

**Comment by LVinther** [comment]
Hi Mads and Anders,

We would like to be able choose wether we navigate back or forward when the user pushes a button depending on his previous interactions (where he comes from). See videos for examples: 


https://user-images.githubusercontent.com/53176253/133415720-18bbf504-b38d-43e0-a621-94444918b078.mp4


https://user-images.githubusercontent.com/53176253/133415744-b02cd98d-bba9-4b42-87c1-def8af1a87d6.mp4

**Comment by MadsBuchmann** [comment]
For the sake of history I'm going to write a summary of what @askarby and I have talked about. 

To my understanding, it is desired to have a _search button_ on a _details page_ which leads to a _search page_. When the button is clicked one of two things should happen: 
1. If the previous page in the history stack is the _search page_ then navigate to the _search page_ using a backwards animation. 
2. If the previous page in the history stack is NOT the _search page_ then navigate to the _search page_ using a forwards animation. 

Clicking the _search button_ should not just go to the _search page_ by pushing it on top of the history stack. The user will most likely go to a new _details page_ where they might click the _search button_ again; this would result in a huge stack making it hard to navigate backwards. 

The current solution has been to change locations 'in place' by setting 'skipLocationChange' to true. This however means we're neither moving back or forth. We are staying in place. On iOS this triggers both the forward and backwards navigation. 

So to resolve this we can either: 
1. Avoid the use of `skipLocationChange` and use backwards or forwards navigation. Instead check the history stack and see if the previous page was the _search page_; if it is then just go a single step back in the history stack, which will cause the backwards animation to be triggered. If it is not, then go to the search page by pushing it on top of the history stack; this will cause the forwards animation to be triggered. 
2. Keep using `skipLocationChange` but provide a way to tell the kirby-router-outlet which animation should be used, as it is not able to determine this by itself. 

I personally would vouch for solution 1 as I think this is the simplest solution (@askarby will be testing it out). 

In case we go for solution 2 this issue should be closed and a new enhancement request should be created for that new mechanism. 

@askarby - lemme know if I misunderstood anything 😄

**Comment by askarby** [comment]
Closing this issue, in favor of #1760
