### ISSUE TITLE
[Enhancement] Change color for Sparekassen Sjælland-fyn

### ISSUE THREAD

**Issue by alxzak** [kirbydesign/designsystem#1643]
- [ ] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the enhancement
Beskrivelse 
På et tidligere intromøde for hjemmesideredaktører mv. præsenterede Team Kirby deres koncept. Herunder stillede jeg et spørgsmål om vi kan rette lyskurven (rød - gul - grøn) i Mobilbanken og svaret var at det sagtens kan lade sig gøre. Så derfor vil vi gerne have ændret farverne i Mobilbank så de matcher vores farve univers/design manual. Overtræksgul skal fremover være #f7aa4e
Den rød ved bl.a. investering skal fremover være #eb5f60
Den grønne må gerne skifte til vores primære logofarve/CTA #83C6A9 – hvis muligt
 
Meld gerne retur hvis i ser nogle problemer eller andre issues
 
Link til sagen:
Konsulentydelse 1131215 

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](../CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Refinement

- [ ] Request that the issue is [UX refined](../CONTRIBUTING.md/#ux-refinement); do not proceed until this is done.
- [ ] Request that the issue is [tech refined](../CONTRIBUTING.md/#tech-refinement); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](../CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [master branch](https://github.com/kirbydesign/designsystem/tree/master) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Publish a WIP implementation to Github as a draft PR and ask for feedback. 
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Update the [cookbook](https://cookbook.kirby.design) with examples and showcases.

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request. If you created a draft PR during implementation you can just mark that as "ready for review".

**Comment by alxzak** [comment]
Promark number is pending.

**Comment by bommariusser** [comment]
er det notifikation colors @alxzak ?

**Comment by jkaltoft** [comment]
Description in english, please 😊

**Comment by bommariusser** [comment]
@alxzak answer <3

**Comment by alxzak** [comment]
@bommariusser - It is the notification colors! :)

**Comment by jkaltoft** [comment]
**Suggestion for solution/workaround**

Change the `apps/relationsbank/src/scss/bank/spks/theming/_colors.scss` partial to:

```scss
$brand-colors: (
  'primary': #83c6a9,
  'secondary': #328639,
  'tertiary': #00594e,
);

$notification-colors: (
  'success': chartreuse,
  'warning': goldenrod,
  'danger': crimson,
);

$drb-colors: generate-colors(map-merge($brand-colors, $notification-colors));
```

![image](https://user-images.githubusercontent.com/150451/133273869-47da047b-ac57-4a5c-aa1b-dddba462a6b1.png)

⚠️ DISCLAIMER

This suggestion should be taken with a grain of salt. I'm not sure if I think it's the correct way to work around this, but it seems to work technically.
