### ISSUE TITLE
[BUG] Missing (leave)-event, when swiping on iOS device

### ISSUE THREAD

**Issue by askarby** [kirbydesign/designsystem#1644]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
When navigating back, using the "swipe left-to-right" on iOS devices, the `kirby-page`'s `(leave)`-event is not triggered!

## Describe how to reproduce the bug

1. Create an app that has two pages (**A** and **B**)
2. Make **Page A** navigate to **Page B**
3. Setup a callback on the `(leave)`-event on **Page B**, and do something when the hook is invoked (eg. display a `Toast`)
4. Build the app using Capacitor and deploy it to an iOS device
5. Open the app, and navigate from **Page A** to **Page B**
6. Now, navigate back using the back-button (see that the `Toast` is displayed)
7. Navigate back to **Page B**
8. Now, "swipe back" (gesture of swiping left-to-right on screen)
9. See that **no** `Toast` is displayed

## Which Kirby version was used?
2.0.7

## What was the expected behavior?
Back-navigation, regardless of it being:

- Clicking the browser's back-button
- Clicking upon a "in app" back-button
- Using a hardware back-button (Android phones)
- Swiping back (common iOS gesture)

...should **always** trigger the `(leave)`-event on the `kirby-page`-Component.

## Add any screenshots
n/a

## Please complete the following information:
- OS: iOS 14.6
- Browser Capacitor app (Safari / `WKWebview`)
- Browser version: (follows iOS version)

## Are there any additional context?

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](../CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](../SUPPORT.md/#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](../CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [master branch](https://github.com/kirbydesign/designsystem/tree/master) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by MadsBuchmann** [comment]
I will attempt to verify this bug 😄

**Comment by mictro** [comment]
Fixed by #1259
