### ISSUE TITLE
[BUG] Horizontal white line on "list with no background shape" (Android only)

### ISSUE THREAD

**Issue by askarby** [kirbydesign/designsystem#1645]
- [ ] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe how to reproduce the bug
1. Create an capacitor application on Android, having a list with no shape (https://cookbook.kirby.design/home/showcase/list-no-shape)
2. Add a footer to the list
3. See that a white 1px wide horizontal line appears above the footer

## Which Kirby version was used?
2.0.7

## What was the expected behavior?
The footer appears without a 1px wide horizontal line

## Add any screenshots
![image](https://user-images.githubusercontent.com/44014/123653637-9df2e000-d82d-11eb-8028-08525cfe7606.png)

## Please complete the following information:
- OS: Android S (12 and below... )
- Browser Webkit (blink?) in a Capacitor app
- Browser version [e.g. 22]
This was tested on an emulator, but you're able to reproduce this on certain phones as well.

## Are there any additional context?

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](../CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](../SUPPORT.md/#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](../CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [master branch](https://github.com/kirbydesign/designsystem/tree/master) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by RasmusKjeldgaard** [comment]
Solved in #3666
