### ISSUE TITLE
[Enhancement] Calendar year navigation event emitter

### ISSUE THREAD

**Issue by bdytos** [kirbydesign/designsystem#1653]
- [ ] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the enhancement
It would be nice if the calendar triggers an event emitter when the user changes the date from the year navigator. Right now the calendar only triggers an event when the user changes a date.

![image](https://user-images.githubusercontent.com/77673731/124251679-7d28d400-db26-11eb-98a0-f9714ae00eec.png)

## Describe the solution you'd like
When the user changes year, an event should be emitted so the application can get the new selected year.

## Are there any additional context?

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](../CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Refinement

- [ ] Request that the issue is [UX refined](../CONTRIBUTING.md/#ux-refinement); do not proceed until this is done.
- [x] Request that the issue is [tech refined](../CONTRIBUTING.md/#tech-refinement); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [x] Make sure you have read: "[Before you get coding](../CONTRIBUTING.md/#before-you-get-coding)".
- [x] Signal to others you are working on the issue by assigning yourself.
- [x] Create a branch from the [master branch](https://github.com/kirbydesign/designsystem/tree/master) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [x] Publish a WIP implementation to Github as a draft PR and ask for feedback. 
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [x] Update the [cookbook](https://cookbook.kirby.design) with examples and showcases.

### Review
Once the issue has been implemented and is ready for review:

- [x] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request. If you created a draft PR during implementation you can just mark that as "ready for review".

**Comment by RasmusKjeldgaard** [comment]
Tech refinement:
Emit event `yearSelect` when the dropdown value changes (`changeYear()`).
While you are at it, please consider to align name with `_changeMonth()`, e.g. prepend `_` so the method name becomes `_changeYear() `to signal that it is an internal method (that needs to be public so it is available in the template). Please verify first that the method is not in use in DRB.
