### ISSUE TITLE
[Housekeeping] Make Kirby compatible with @use & @forward

### ISSUE THREAD

**Issue by MadsBuchmann** [kirbydesign/designsystem#1670]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the housekeeping request
The use of `@import` in Sass is now [discouraged](https://sass-lang.com/documentation/at-rules/import); it will be deprecated in the future. 

Consumer projects might use the new `@use` & `@forward` rules instead as this is the replacement for `@import`. We should consider our Sass structure to ensure it is compatible for use with these two new rules. 

## Have you considered any alternatives?
Restructuring Kirby to use the `@use` & `@forward` syntax. 

We should consider if this will be a breaking change. Is the use of `@use` & `@forward` also supported in node-sass for example? Also I do not think `@forward` is compatible with `@import`.  

This might be a wholly separate issue. 

## Are there any additional context?
This issue stems from talking with @MortenGregersen which has encountered issues when updating to dart-sass & replacing `@import` with `@use` and `@forward`. He eventually found a work-around - but that is not what is desired.

**Comment by MortenGregersen** [comment]
It should be considered, maybe splitting up the scss files, so consuming projects could @use parts, when overriding properties.

**Comment by MadsBuchmann** [comment]
#1878 might fix this

**Comment by MadsBuchmann** [comment]
@jkaltoft as #1878 has been merged is it safe to close this issue?

**Comment by jkaltoft** [comment]
Solved by #1878
