### ISSUE TITLE
[BUG] Point Annotation Not Rendering (Chart.js)

### ISSUE THREAD

**Issue by MadsBuchmann** [kirbydesign/designsystem#1674]
- [X] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
When inserting a point annotation in a chart provided by the [Chart Component](https://cookbook.kirby.design/home/showcase/chart) the point annotation is not being rendered. 

## Describe how to reproduce the bug
Insert a point annotation on in a chart and see that nothing happens. 

## What was the expected behavior?
The point should be rendered. 

## Please complete the following information:
- OS: MacOS
- Browser: Safari
- Browser version 14.0.3

## Are there any additional context?
I think this might be caused by the 'point' element having a radius of 0. This is meant to not draw the non-annotation points the charts are shipped with by default. But perhaps this also turns off the annotation points? 
If this is the case, we should probably find a way to either overwrite the radius for the annotation points or finding another way to turn them off for charts. 

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](../CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [X] Make sure the `NOT verified` label has been removed by a member of [team Kirby](../SUPPORT.md/#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](../CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [master branch](https://github.com/kirbydesign/designsystem/tree/master) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by Fuzzy3** [comment]
This is actually an enhancement - please reopen if still needed
