### ISSUE TITLE
[BUG] Dropdown with attention level does not show that the field is selected

### ISSUE THREAD

**Issue by AndreasPetersen** [kirbydesign/designsystem#1685]
# Description
The dropdown with attention level does not show any outline or background color when selected. In contract, all other styles of the dropdown display a blue outline when selected. This makes the dropdown difficult and confusing to use on a keyboard when filling out forms.

# How to reproduce
This can easily be reproduced by going to the dropdown showcase 
(https://cookbook.kirby.design/home/showcase/dropdown) and tabbing through all the dropdowns. When you reach the dropdown with attention level, you will notice it's impossible to see that it is selected.

In the following screenshot the "dropdown with event handler" is selected:
![Screenshot 2021-07-27 at 09 42 39](https://user-images.githubusercontent.com/2496648/127115828-885c577b-4a15-40ea-b76b-b4c23575bce9.png)

In the following screenshot the "dropdown with attention level" is selected. Notice the lack of selection around the dropdown.
![Screenshot 2021-07-27 at 09 42 45](https://user-images.githubusercontent.com/2496648/127115837-da213d0d-cc36-4595-b10e-43f1ad1079a2.png)

# Version information
Kirby version is the version displayed on the kirby website, I assume that's the latest: 3.0.2.
Running on Mac OS 11.4 and Chrome Version 92.0.4515.107 (Official Build) (arm64).

**Comment by MadsBuchmann** [comment]
Verifying this is a bug. Also I thinks this might be a candidate for a good first issue. 

So if there's any first time contributors interested, head on over to the contribution guidelines to get started: https://github.com/kirbydesign/designsystem/blob/b15c974bc91358bc21a8447671a7d0b4b54a00dd/.github/CONTRIBUTING.md

**Comment by MadsBuchmann** [comment]
Might be related to #1792

**Comment by RasmusKjeldgaard** [comment]
Fixed in #1863, to be released with Kirby v7 later this summer. 
Can be verified here: https://cookbook.kirby.design/branch/kby-v7-0-0/#/home/showcase/dropdown
