### ISSUE TITLE
[Enhancement] Better Card examples on cookbook with properties

### ISSUE THREAD

**Issue by MonsterGameDev** [kirbydesign/designsystem#1687]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the enhancement
CookBook - Card-example
Not all properties shown in example is present in the property-table below

## Describe the solution you'd like
Add description of:
 [class.bg-color]="hasHeaderFooterBgColor"
 [flagged]="flagged"

## Have you considered any alternatives?
No

<hr />

**Comment by MadsBuchmann** [comment]
@MonsterGameDev please add a proper title for this issue.
