### ISSUE TITLE
[BUG] Kirby-item, when rotating device running Safari items unintentionally gets more padding at the ends 

### ISSUE THREAD

**Issue by FinnCarlsen** [kirbydesign/designsystem#1689]
## Describe the bug
When a handheld device running Safari is rotated from vertical to horizontal items unintentionally gets more padding at the ends 

## Describe how to reproduce the bug
The easiest way to reproduce the bug is by opening the Kirby cookbook.

1. Go to 'https://cookbook.kirby.design/home/showcase/item'
2. Scroll down to where item examples are shown
3. Rotate the device
4. See that padding in horizontal position is far wider than in vertical position (see screen shots below)

## Which Kirby version was used?
The examples below is from the cookbook which uses 3.0.3

## What was the expected behavior?
The items must have the same padding before and after rotating the device.

## Add any screenshots
**Vertical**:
![image](https://user-images.githubusercontent.com/53520395/128187525-668023b7-bac0-49f1-a6b1-4fd64b6ebdb4.png)
**Horizontal**:
![image](https://user-images.githubusercontent.com/53520395/128187755-9e732f26-020c-47a0-9982-929dd99d2cff.png)

## Please complete the following information:
- OS: iOS v. 14.6
- Browser: Safari
- Browser version ?

## Are there any additional context?

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](../CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [x] Make sure the `NOT verified` label has been removed by a member of [team Kirby](../SUPPORT.md/#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](../CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [master branch](https://github.com/kirbydesign/designsystem/tree/master) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by jkaltoft** [comment]
Cannot reproduce bug using iOS 14.7

**Comment by jkaltoft** [comment]
![image](https://user-images.githubusercontent.com/150451/128344147-387441e6-8036-49e5-ac0d-5c132d6a6cc7.png)

**Comment by jkaltoft** [comment]
![image](https://user-images.githubusercontent.com/150451/128344163-19719470-aad2-4f6f-b506-2db69e17e00f.png)

**Comment by FinnCarlsen** [comment]
I have the feeling that the verification wasn't executed in Safari.
We are three colleagues that has experienced the "error" all using different iPhones and Safari.
The error will not show in Chrome.

**Comment by jkaltoft** [comment]
That's odd. The screenshots above were taken using Safari on an iPhone 8 running iOS 14.7.1. 

Can you provide more information on which devices and iOS versions you and your colleagues use? Does it happen both in private and non-private tabs? And does it make any difference deleting cached files from kirby.design in Safari?

**Comment by jkaltoft** [comment]
Btw, thanks for the easy to understand bug description and the "How to reproduce". Unfortunately I'm still not able to experience the error on my device.

**Comment by jkaltoft** [comment]
https://user-images.githubusercontent.com/150451/128360182-f5404e59-f492-4d2c-9ded-312a7ccff216.MOV

**Comment by jkaltoft** [comment]
@FinnCarlsen, are you and/or your colleagues located at Bankdata in Silkeborg? I'd be happy to come by and "see the bug in action". It's rather difficult to do anything about it without being able to reproduce it myself 😊

**Comment by FinnCarlsen** [comment]
Sorry, that I haven't mentioned it earlier, but we are all running iPhone X. The first iPhone with the "notch".
And it might be the handling of the notch that is the problem.
Unfortunately we are all located at Jyske Bank in Lyngby.

**Comment by jkaltoft** [comment]
Ah, ok. Then I probably won't swing by 😁. 

I'll try to get my hands on a newer iPhone than my iPhone 8. Thanks for the info.

**Comment by FinnCarlsen** [comment]
If you have a Mac you can use a simulator to verify the problem.
![image](https://user-images.githubusercontent.com/53520395/128701063-0a4d51f6-4ab1-406e-8a89-ff16c4e64616.png)

**Comment by jkaltoft** [comment]
Verified on iPhone 12, iOS 14.7.1
