### ISSUE TITLE
[BUG] [REOPENED] kirby-list with only one item does not have rounded corners

### ISSUE THREAD

**Issue by sorenfruergaard** [kirbydesign/designsystem#1711]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
Kirby-list with only one item is missing rounded corners

## Describe how to reproduce the bug
Use Kirby-ist with only one item.

1. Limit the array in base-list.components.ts to only have one item.
2. Go to http://localhost:4200/home/showcase/list
3. See that all the examples are missing the rounded corners

## Which Kirby version was used?
3.0.3

## What was the expected behavior?
The one and only kirby-item in the list should have rounded corners in top and bottom.

## Add any screenshots
![image](https://user-images.githubusercontent.com/2383744/130221809-4772f0ac-d1ab-4d3a-9678-7b69cc8d8902.png)

## Please complete the following information:
- OS: All OS
- Browser All browsers

## Are there any additional context?

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](../CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](../SUPPORT.md/#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](../CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [master branch](https://github.com/kirbydesign/designsystem/tree/master) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by MadsBuchmann** [comment]
Verified - the bug has been reproduced.

**Comment by jkaltoft** [comment]
Suggestion: Solve this issue before #1604

**Comment by jkaltoft** [comment]
**Suggestion for solution**

Set `--border-radius` on `<ion-item>` to a proper value when a list consists of just a single item.

**Comment by jkaltoft** [comment]
Needs more fixing. Missing top border-radius.

Reopening issue.

![image (1).png](https://images.zenhubusercontent.com/60b5ee2813189c6118c321c9/2da0726a-0843-41be-b7ec-4ed8378ef95a)
