### ISSUE TITLE
[Housekeeping] Deprecate Grid component

### ISSUE THREAD

**Issue by jkaltoft** [kirbydesign/designsystem#1721]
- [ ] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the housekeeping request

The Grid component should be deprecated and scheduled for being removed completely from the library. Projects using Kirby can get a starting point for implementing the layout from [the Layout section of the cookbook](https://cookbook.kirby.design/home/layout-recipes). Team Kirby could consider providing an example of implementation of the layout.

The Grid component is only being used in a few places (maybe just one), so the inconvenience will limited.

## Have you considered any alternatives?

No.

## Are there any additional context?

No.

**Comment by MadsBuchmann** [comment]
Still relevant.

**Comment by MadsBuchmann** [comment]
@jkaltoft - We could remove the "Grid" from the navigation to avoid new consumers taking this into use for now? 
I've submitted a PR doing just that: #2023

**Comment by RasmusKjeldgaard** [comment]
The grid component has been deprecated and an alternative provided by Kirby: https://cookbook.kirby.design/#/home/showcase/grid
