### ISSUE TITLE
[Enhancement] Add support for labels in chart

### ISSUE THREAD

**Issue by MadsBuchmann** [kirbydesign/designsystem#1729]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the enhancement
It should be possible to apply labels to a chart that is displayed for each datapoint as can be seen on this chart: 
![image](https://user-images.githubusercontent.com/17269698/131503514-3661e348-3f4b-4ed6-a0fa-7c5244d571d5.png)

## Describe the solution you'd like
Needs more refinement, but I think we should look into using [tooltip](https://www.chartjs.org/docs/latest/configuration/tooltip.html) or perhaps the [datalabels](https://github.com/chartjs/chartjs-plugin-datalabels) plugin. 

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](../CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Refinement

- [ ] Request that the issue is [UX refined](../CONTRIBUTING.md/#ux-refinement); do not proceed until this is done.
- [ ] Request that the issue is [tech refined](../CONTRIBUTING.md/#tech-refinement); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](../CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [master branch](https://github.com/kirbydesign/designsystem/tree/master) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Publish a WIP implementation to Github as a draft PR and ask for feedback. 
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Update the [cookbook](https://cookbook.kirby.design) with examples and showcases.

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request. If you created a draft PR during implementation you can just mark that as "ready for review".

**Comment by MadsBuchmann** [comment]
As part of #1882 the input property `dataLabelOptions` has been created to apply labels to data. 

Before #1905 dataLabels referred to the labels along the x-axis. When #1905 is closed, they will just be called labels instead.

**Comment by RasmusKjeldgaard** [comment]
Closing this, as this functionality is available as tooltips on the stock chart. Please reopen if this functionality is still needed on other charts.
