### ISSUE TITLE
[COMPONENT] Chip

### ISSUE THREAD

**Issue by azeemchauhan** [kirbydesign/designsystem#173]
**Describe the solution you'd like**

Chips represent complex entities in small blocks

**Describe alternatives you've considered**
![image](https://user-images.githubusercontent.com/33758493/54992290-f00c8180-4fe4-11e9-9c9a-bb9d711266da.png)

**Additional context**
https://ionicframework.com/docs/api/chip

### Kick Off:
- [x] Accept Feature incl. name of component (DSL)
- [x] Update Kirby Component Status and publish to [Kirby Cookbook](https://cookbook.kirby.design)
### Code:
- [x] Create Feature Branch
- [x] Implement Skeleton Component:
    - [x] Web implementation
    - [x] {N} implementation
- [x] [Implement Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [x] Push commits to GitHub
### Review:
- [x] Open a pull request and ask @kirbydesign/kirby-guild for review
- [x] Update Kirby Component Status
- [x] Merge to master

**Comment by jakobe** [comment]
Closed by #176
