### ISSUE TITLE
[BUG] Modal overlay is activated too late

### ISSUE THREAD

**Issue by mvindahl** [kirbydesign/designsystem#1733]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
When opening a modal using modalController.showModal(), an overlay is rendered to prevent the underlying UI from receiving further mouse clicks. However, in some cases this appears too late. This may, if the user double clicks, lead to more than one click registering, potentially causing multiple dialogs to be opened or other kinds of unexpected behaviour. This has been an issue for a while and in some places the DRB code has implemented its own workarounds, none of which are pretty.

 

## Describe how to reproduce the bug

The behaviour can be reproduced by opening the Kirby cookbook, going to https://cookbook.kirby.design/home/showcase/modal, and double clicking the "Show Modal" button. This will result in two modals being opened on top of each other. It will only work the first time, and it will only work if you click quickly enough.

Note: this *may* not work on faster machines. On my Macbook Pro, there is a ~140 mSec delay during which the button is still active, and if I double click quickly, I can manage to hit the button twice within ~110 mSec.

## Which Kirby version was used?
3.0.8

## What was the expected behavior?
I would expect the modal overlay to appear before I could put in my second click, blocking mouse clicks.

## Please complete the following information:
- OS: MacOS
- Browser: Chrome
- Browser version: 91.0.4472.114 

## Are there any additional context?
I've investigated a bit without yet having fully understood it. At the core of the problem, it seems like the ion-modal needs to have the class `show-modal` in order for the overlay to be active. This is set by Ionic, but while opening the modal for the first time; alas, this happens a bit late.

I've created a branch `show-modal-experiments` with debug logging in Kirby and in Ionic. To see the same logging as in the subsequent examples, check out the branch and:
```
npm run patch-ion-modal-js
npm start
```

The following is the typical output when *initially* opening a modal:
![image](https://user-images.githubusercontent.com/5991804/131895039-a652c8ce-b016-4563-a751-ae0db5c45bea.png)

A couple of observations:
1) the call this.ionicModalController.create does create an ion-modal i DOM, but as it lacks the show-modal class, the overlay is not initially active.
2) After about 140 mSecs, the ionic code attaches this class to the existing element. This is sufficient to put in a second click if you click quickly.

Here is an example where I double click as fast as I can (but I've added a guard so that I log but don't process it):
![image](https://user-images.githubusercontent.com/5991804/131895673-cd17c6c1-332e-4bd7-aa66-8f604d2c7398.png)

This is how it looks if I have opened and closed the modal, and then open it a *second* time:

![image](https://user-images.githubusercontent.com/5991804/131895997-5a03d651-c66a-42d7-a482-89082b7c6d3c.png)

In this case, the logged time intervals are all shorter, and the ion-modal already has the desired class when it's logged the first time. So some kind of reuse is going on. When I open a modal and then open a nested modal, the nested modal also opens pretty quickly.

I've found a fix that prevents the bug on my machine, but TBH it feels more like a workaround and a hack. Anyway, once  this.ionicModalController.create returns, and the ion-modal thus exists in the DOM, I can look it up and manually attach the class. As this happens after about 70 mSecs it's soon enough to prevent at least me from double clicking.

Still, the 70 mSecs will probably vary across machines and browsers so I don't trust the fix to work in the general case.

Next steps in my investigation:
- given that the show-modal class is present on the second run at that seems to do no harm then why doesn't ionic add it initially?
- what is taking the initial call to ionicModalController.create so long? Could we "warm it up" by calling it at an earlier point in time? 

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](../CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](../SUPPORT.md/#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](../CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [master branch](https://github.com/kirbydesign/designsystem/tree/master) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by MadsBuchmann** [comment]
I've been able to reproduce this in the cookbook example once. As mentioned in the issue it is a bit hard to reproduce on fast machines - so it is a bit flaky when it is reproduced. 

I'm Removing the NOT Verified label 🐛

**Comment by MadsBuchmann** [comment]
Also thank you for a well written issue!

**Comment by mvindahl** [comment]
I added even more debugging and I believe that I now understand the cause of the issue. It wasn't the `show-modal` class, it was the `overlay-hidden` class.

When Ionic creates the ion-modal element, it attaches the `overlay-hidden` class ([code link](https://github.com/ionic-team/ionic-framework/blob/7315e0157b917d2e3586c64f8082026827812943/core/src/utils/overlays.ts#L51)). At a later point, when it's ready to animate, it removes the class again ([code link](https://github.com/ionic-team/ionic-framework/blob/7315e0157b917d2e3586c64f8082026827812943/core/src/utils/overlays.ts#L395)).

Initial rendering of the modal:
```
showModal: 10.784912109375 ms 🍋 createOverlay > element.classList.add('overlay-hidden')
...
showModal: 142.305908203125 ms 🍋 > baseEl.classList.remove('overlay-hidden')
```

Subsequent rendering of the modal:
```
showModal: 3.73779296875 ms 🍋 createOverlay > element.classList.add('overlay-hidden')
...
showModal: 63.156005859375 ms 🍋 > baseEl.classList.remove('overlay-hidden')
```

As long as the `overlay-hidden` class is present, neither the `<ion-modal>` nor its embedded `<ion-backdrop>` render. This is controlled by [this CSS rule](https://github.com/ionic-team/ionic-framework/blob/7315e0157b917d2e3586c64f8082026827812943/core/src/components/modal/modal.scss#L53). Once the class is removed, the calculated style changes from `display: none` to `display:flex`.

While initially rendering the "window" of ~130 ms without a backdrop is plenty of time for me to put in a second click on my machine. I cannot click fast enough to beat the ~60 ms "window" during subsequent renderings but on slower machines I might.

I am not sure why Ionic insists upon adding and removing this class. I have not been able to spot any visual difference from *not* doing it, at least not in my setup. I doubt if we could convince the Ionic team to stop doing it even if it seems to solve our problem.

Anyway, even though we cannot modify the Ionic code prevent the class from appearing, we *can* tell our CSS to ignore it. My suggestion for a Kirby-level fix would be to add the following rule to `_global-styles.scss`:

```css
ion-modal {
  display: flex !important;
}
```

We'd obviously need to test this on various devices to make sure that it doesn't break anything.

**Comment by NikolajSkousen** [comment]
> I've been able to reproduce this in the cookbook example once. As mentioned in the issue it is a bit hard to reproduce on fast machines - so it is a bit flaky when it is reproduced.
> 
> I'm Removing the NOT Verified label 🐛

@MadsBuchmann it can be consistently reproduced in drb on modals. Another way to activate the issue is e.g. on the '...' *kirbyPageActions in drb. 

I can reproduce it on the kirby-cookbook website by selecting a button and hitting enter a couple of times. This is both when activating modals and the action sheet.

**Comment by AndreasPetersen** [comment]
Hi, any update on this issue? It is still an issue with the latest version at time of writing, see attached videoes. In addition, it is an issue for drawers and alerts as well.

https://user-images.githubusercontent.com/2496648/192768064-baef0272-963a-4e07-817f-92fadc3b0c24.mp4

https://user-images.githubusercontent.com/2496648/192768094-f54c5113-a4e0-4144-8394-ed03b4f53fc3.mp4

I can also add, that this isn't simply some theoretical issue. We are actually seeing this issue in production with real users in our logs.

**Comment by Joeskov** [comment]
We have had to implement a workaround to prevent users to make a dobbelt trade because of this bug.
The customer journey for at trade:
1. Trade modal open -> 
2. Sign modal open -> 
3. receipt modal open

The receipt modal has a dependency to a backend call which confirm the trade is executed, but when the sign-modal is finish it's closeing and the customer see the trade modal (and will be able to make another trade like the first one).

https://user-images.githubusercontent.com/88030854/192782321-3a0bfc68-bfcf-45b7-8657-5939ac6e77cd.mp4
