### ISSUE TITLE
[Housekeeping] Fix Typescript error regarding inlineSources

### ISSUE THREAD

**Issue by jkaltoft** [kirbydesign/designsystem#1738]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the housekeeping request

There is a TS error in `libs/designsystem/tsconfig.lib.json` (see screenshot below).

1. Research and consider the consequences of adding option `inlineSourceMap` or `sourceMap`
2. Add the preferred of those options to get rid of the error

## Have you considered any alternatives?

Leave it as is. Doesn't seem to prevent build etc.

## Are there any additional context?

- https://www.typescriptlang.org/tsconfig#inlineSources
- https://www.typescriptlang.org/tsconfig#inlineSourceMap
- https://www.typescriptlang.org/tsconfig#sourceMap

![image (1).png](https://images.zenhubusercontent.com/60b5ee2813189c6118c321c9/efc3ade8-35a8-4fac-9dbe-8f3a46d08a62)

**Comment by MadsBuchmann** [comment]
As far as I can see, inlineSourceMap will result in the sourceMap being included as part of the compiled Javascript files - which results in larger javascript files. But can be useful in situations where it is not allowed to serve .map files. 

sourceMap on the other hand generates source maps in separate files. 

I think we should go with the latter to not bloat the compiled JS.

**Comment by MadsBuchmann** [comment]
The error is still there - so stilll relevant. Go away stale bot.
