### ISSUE TITLE
[BUG] Wrong spacing in lists

### ISSUE THREAD

**Issue by lydemann** [kirbydesign/designsystem#1745]
- [ ] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
List has wrong vertical spacing, too much spacing now.

## Describe how to reproduce the bug

A list with has wrong spacing now:

## Which Kirby version was used?
3.0.9

## What was the expected behavior?
List has wrong vertical spacing, too much spacing now. Should be smaller as in the screenshot.

## Add any screenshots
Before (correct spacing):
![Image from iOS (1)](https://user-images.githubusercontent.com/9210691/133041518-6b38a719-c2b5-4cb3-921c-7b5bde82dead.png)

Now:
![Image from iOS](https://user-images.githubusercontent.com/9210691/133041528-85a192a5-5667-4403-b247-866ebe098908.png)

## Please complete the following information:
- OS: [e.g. Windows, MacOS, iOS]
- Browser [e.g. Chrome, Safari]
- Browser version [e.g. 22]

## Are there any additional context?

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](../CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](../SUPPORT.md/#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](../CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [master branch](https://github.com/kirbydesign/designsystem/tree/master) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by jkaltoft** [comment]
@lydemann, please describe how to reproduce it, so we can verify the bug.  "A list with has wrong spacing now:" is not very useful. We cannot address this bug before we have verified it.

**Comment by jkaltoft** [comment]
# Tech refinement

With the introduction of virtual scroll the markup structure for lists have been changed.

With the modified structure `ion-item-sliding` will _always_ be `:last-of-type`; it is _always_ be wrapped in a `kirby-list-item` component.

## Suggestion for solution

- Identify what the selector […]`ion-item-sliding:last-of-type` is intended for.
- Rewrite the selector - make sure it still matches the exisiting purpose as well as fixes the bug
- Avoid writing a selector that is too specific and tied to markup-structure
