### ISSUE TITLE
[BUG] Unable to focus input-field on kirby-page

### ISSUE THREAD

**Issue by askarby** [kirbydesign/designsystem#1748]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
When a `kirby-page` is displayed (pushed onto the navigation stack), it's not consistently possible to focus a text-field and bring up a device's on-screen keyboard.

This is only an issue on iOS / iPadOS devices, and cannot be consistently reproduced (read: it's a periodically reproduceable bug).

## Describe how to reproduce the bug
To reproduce the issue in a "kirby + capacitor app"
1. Create an app with two pages (**Page A**, that has a link to **Page B** - with **Page B** having a text field)
2. When the `ngAfterViewChecked` hook on **Page B** is called, call `focus()` (through `@ViewChild`-injected element)
3. See that when navigation from **Page A** to **Page B**, the field on **Page B** does not get focus (and trigger the keyboard) - consistently!

If you have access to DRB, you can:

1. Go to the investment-area
2. Click on Search-button'
3. See that the input field does not get focus (and trigger the keyboard) - consistently!

## Which Kirby version was used?
2.0.7

## What was the expected behavior?
That the input field is able to consistently (automatically) recieve focus, and display the keyboard!

## Add any screenshots
n/a

## Please complete the following information:
- OS: iOS, iPadOS
- Browser Capacitor App (so, Safari?)
- Browser version iOS 14.x's browser

## Are there any additional context?
We've previously had success with setting focus on a input/text field, when said field was in a `kirby-modal`. 

The only difference I can spot here, is that the interaction with the `ElementRef` was not initiated through the `ngAfterViewChecked` hook, but through the Modal's `didPresent` callback / hook. I suspect that it may have
something to do with the Shadow DOM not being hydrated when the `ngAfterViewChecked` hook has fired (it's pure speculation at this point, though).

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](../CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](../SUPPORT.md/#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](../CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [master branch](https://github.com/kirbydesign/designsystem/tree/master) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by RasmusKjeldgaard** [comment]
Can no longer be reproduced at all, so closing this one. Please reopen if problem reoccurs.
