### ISSUE TITLE
[BUG] Bump chartjs to 3.5.1 (latest)

### ISSUE THREAD

**Issue by lydemann** [kirbydesign/designsystem#1749]
- [ ] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

Bump chartjs to 3.5.1

## Describe the enhancement
Bump chartjs to 3.5.1 to be compatible with chartjs plugins.

## Are there any additional context?

Currently with chartjs 3.5.1 the newest version of annotations fail with:
![image](https://user-images.githubusercontent.com/9210691/133248664-0e64e9d9-4698-41a4-b9c5-2be558b5ac34.png)

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](../CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Refinement

- [ ] Request that the issue is [UX refined](../CONTRIBUTING.md/#ux-refinement); do not proceed until this is done.
- [ ] Request that the issue is [tech refined](../CONTRIBUTING.md/#tech-refinement); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](../CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [master branch](https://github.com/kirbydesign/designsystem/tree/master) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Publish a WIP implementation to Github as a draft PR and ask for feedback. 
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Update the [cookbook](https://cookbook.kirby.design) with examples and showcases.

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request. If you created a draft PR during implementation you can just mark that as "ready for review".

**Comment by RasmusKjeldgaard** [comment]
What is the reason for this bump? Currently, the Kirby chart.js version is 3.3.2, which seems to work fine with the annotation plugin, based on our example in the cookbook. 

It would probably be better to try and match our version, and then figure out how to solve the emerging errors. Then we can bump the version to latest at another time.

**Comment by lydemann** [comment]
We got other problems with a "cannot redefine property: color" if we are not using this chartjs version in drb. Maybe something with the other drb plugins, error is coming from the moment chartjs plugin.

**Comment by RasmusKjeldgaard** [comment]
I think that could sound more like an issue with the order of how the configurations are loaded. 

I think it is something we should work to fix where you use the kirby charts, instead of introducing more uncertainty by upgrading to a newer version. 

I am closing this issue, and will instead support the upgrading teams, and try to fix the issue together with them.
