### ISSUE TITLE
[Enhancement] Add shadow option to Kirby Card

### ISSUE THREAD

**Issue by jb-trm** [kirbydesign/designsystem#175]
The kirby card needs to support an option where you can disable to shadow. Example use: 
https://app.zeplin.io/project/5c99d69a79d02b35ea3b8f41/screen/5c9f7948ff87da691c8ecc1f

**Comment by bommariusser** [comment]
@jb-trm i made this issue https://github.com/kirbydesign/designsystem/issues/182 its kinda the same or? :) Can we merge issues?

**Comment by hafstad** [comment]
This has been fixed by #342, closing this.
To see how elevation works on cards, see https://cookbook.kirby.design/home/showcase/card
