### ISSUE TITLE
[BUG] Kirby tab-menu-layout (Safari iOS 15) is not looking good after Apple switched the URL-navigation from top to bottom on the phone

### ISSUE THREAD

**Issue by BDUJOG** [kirbydesign/designsystem#1755]
## Describe the bug
I have tested the Kirby example template with iOS 15 device on web-page and found som issues regarding the tab-menu in the bottom. Se pictures:

![image](https://user-images.githubusercontent.com/90897094/133748583-3853f431-e39d-4eff-860c-5e187105f7a9.png)
![image](https://user-images.githubusercontent.com/90897094/133748600-a5b1b59d-6bf1-417a-ba7f-7b379140016d.png)

On iOS 15 software, Apple has moved the normal URL-navigation bar from top to bottom and i belive, that this is the problem

## Describe how to reproduce the bug

1. Go to 'https://cookbook.kirby.design/examples/tabs/dashboard'
3. Scroll down to 'bottom of page'
4. See error --> the tab-menu is flouting i mid-air, when the url bar i collapsing 

## Please complete the following information:
- OS: [e.g. Windows, MacOS, iOS]
- Browser [e.g. Chrome, Safari]
- Browser version [e.g. 22]

## Are there any additional context?
Maybe its the enviroment_variable = safe-area-insert-bottom

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](../CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](../SUPPORT.md/#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](../CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [master branch](https://github.com/kirbydesign/designsystem/tree/master) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by RasmusKjeldgaard** [comment]
Thank you for reporting this. Please give the issue a fitting title 🙂 

Is it currently a use case for the DRB-app to be accessed on a URL like this? E.g. can end users access the mobile app in their browser?

Remember that the app for ios and android is wrapped in capacitor, and served as a native app, with no url bar, as I understand it.

**Comment by RasmusKjeldgaard** [comment]
Note: I do realise that it will be a use case at a later point, but I just want to understand the urgency/timing of this 😃

**Comment by BDUJOG** [comment]
Hi Rasmus, the urgency is not that high. We are in the moment on the discussion board of things and the plan for web-rollout are i late Q4 2021 og Q1 2022

**Comment by RasmusKjeldgaard** [comment]
Alright, good to know. 

Please remember to provide a suitable title for this issue, otherwise it will for sure not hit our radar.

**Comment by RasmusKjeldgaard** [comment]
You can see guidelines for issue titles here: https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue 😀

**Comment by RasmusKjeldgaard** [comment]
No longer an issue
