### ISSUE TITLE
[Enhancement] Programmatically navigate back

### ISSUE THREAD

**Issue by askarby** [kirbydesign/designsystem#1760]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the enhancement
We currently have a requirement where we want to navigate "backwards", programmatically. Currently we're using the `Router`'s `skipLocationChange`-extra parameter, eg.:

```ts
this.router.navigateByUrl(INVESTMENT_PATHS.search, {
  skipLocationChange: this.previouslySearch(),
});
```

but this seems to confuse Kirby's animations (at least on a native iOS build, using Capacitor) where it does a bit of a left-to-right transition concurrently with a right-to-left transition (leading to a somewhat jittering, erratic animation).

## Describe the solution you'd like
We want a solution to programmatically navigate back, possible by exposing the `NavController`-class (from Ionic), eg.:

```ts
constructor(private navController: NavController) {}
...
goBack() {
  this.navController.back({
    animated: true,
    animationDirection: 'back',
  });
}
```

## Have you considered any alternatives?
Yes, please see #1623 

## Are there any additional context?
Only (consistently) reproduceable on iOS.

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](../CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Refinement

- [ ] Request that the issue is [UX refined](../CONTRIBUTING.md/#ux-refinement); do not proceed until this is done.
- [ ] Request that the issue is [tech refined](../CONTRIBUTING.md/#tech-refinement); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](../CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [master branch](https://github.com/kirbydesign/designsystem/tree/master) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Publish a WIP implementation to Github as a draft PR and ask for feedback. 
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Update the [cookbook](https://cookbook.kirby.design) with examples and showcases.

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request. If you created a draft PR during implementation you can just mark that as "ready for review".

**Comment by MadsBuchmann** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-Owner-Workspace-602b70d809e4aa00141a1a93/issues/kirbydesign/designsystem/1760?planning-poker) with ZenHub @jkaltoft @RasmusKjeldgaard
