### ISSUE TITLE
[RESEARCH] Web component styling - Architecture and methodologies

### ISSUE THREAD

**Issue by jkaltoft** [kirbydesign/designsystem#1763]

**Comment by RasmusKjeldgaard** [comment]
Timeboxed for 4 days initially, to familiarize ourselves with the concepts, and learn from these initial investigations.

**Comment by MadsBuchmann** [comment]
@jkaltoft & @RasmusKjeldgaard - can you refresh my memory, what is the expected outcome of the research? 
Should we document it on the issue?
