### ISSUE TITLE
[Enhancement] Make modals return data before sliding away

### ISSUE THREAD

**Issue by mvindahl** [kirbydesign/designsystem#1769]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the enhancement

I'd like the modal to return its data sooner.

For context, the standard way to return data from a modal is to call modal.close() with an argument.
```typescript
// in the component within the modal
this.modal.close({ foo: 'bar' });
```

When opening the modal, a handler can be passed to receive and process this return value:
```typescript
// in the invoking code
const modalConf: ModalConfig = { ... }
this.modalController.showModal(modalConf, (returnValue) => {
  console.log(returnValue); // > { foo: 'bar' }
})
```

However, **this callback is not invoked until the modal has fully transitioned away**.

A common use case for modals in our code is to display a sheet of properties (of a money transfer), allowing the user to click each of these to edit its value in a drawer, and finally submitting the change or cancelling by dismissing the modal.

With the current callback behaviour, this results in a "glitchy" experience where the old value is displayed in the properties as the modal slides out, and then abruptly changes.

## Describe the solution you'd like

I believe that the modal should call back with its value at the moment that it starts transitioning away.

This is a change in behaviour but I don't think it would break any client code.

## Have you considered any alternatives?

We currently use the following workaround several places in our code:
```typescript
// in the component within the modal
this.componentProps.onWillClose({ foo: 'bar' })
this.modal.close();
```

```typescript
// in the invoking code
const modalConf: ModalConfig = {
  ...
  onWillClose: (returnValue) => {
    console.log(returnValue); // > { foo: 'bar' } -- but sooner
  }
}
this.modalController.showModal(modalConf)
```
It does feel like this should be supported at framework level though.

## Are there any additional context?

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](../CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Refinement

- [ ] Request that the issue is [UX refined](../CONTRIBUTING.md/#ux-refinement); do not proceed until this is done.
- [ ] Request that the issue is [tech refined](../CONTRIBUTING.md/#tech-refinement); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](../CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [master branch](https://github.com/kirbydesign/designsystem/tree/master) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Publish a WIP implementation to Github as a draft PR and ask for feedback. 
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Update the [cookbook](https://cookbook.kirby.design) with examples and showcases.

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request. If you created a draft PR during implementation you can just mark that as "ready for review".

**Comment by MadsBuchmann** [comment]
Took a short look at this and I personally think it is a good suggestion for which I can see the use case. 

I believe that the `OnClose` callback should actually be called something along the lines of `OnDidDismiss`/`OnDidClose` as this is actually the method used by Kirby to call the `OnClose` callback. 

From `libs/designsystem/src/lib/components/modal/services/modal.controller.ts` around line 123 to 143.
```typescript
    ...
    const overlay: Overlay = await showOverlay();  
    ...
    overlay.onDidDismiss.then((event) => {
      this.overlays.pop();
      if (typeof onCloseOverlay === 'function') {
        onCloseOverlay(event.data);
      }
    });
```

Renaming it would be a breaking change however - but one I guess that should be easy to fix by consumers of Kirby and will make it more clear what is actually going on. 

We could then create an additional callback `OnWillDismiss`/`OnWillClose` which will be called right before the overlay begins to transition away. If I understand your issue correctly this new callback would solve your problem, right?

Please note that this is just my suggestion and it has not been discussed in the team yet 😄

Also thank you for writing a _good_ issue!

**Comment by mvindahl** [comment]
Hi, thanks for taking the time to consider this.

One minor point though; when passing the callback to modalController.showModal, it is not passed by name, it is simply passed as the (optional) second argument. Thus, renaming it would not cause any existing code to break. Changing its behaviour to return the data sooner would, of course, cause existing code to work slightly differently, but that would be the point. I'd be surprised if it breaks anything.

I we instead want a solution that is 100% backwards compatible, we should probably introduce more than one "life cycle hook" and be explicit about naming.

Current method signature
```typescript
  public async showModal(config: ModalConfig, onClose?: (data?: any) => void): Promise<void> {
```

Suggested signature:
```typescript
  public async showModal(
    config: ModalConfig,
    callbacks?: 
      (data?: any) => void | // deprecated shorthand for { onDidClose: .. }, for backward compatibilty
      {
        onWillClose?: (data?: any) => void;
        onDidClose?: (data?: any) => void
      }
  ): Promise<void> {
```
The somwhat fugly signature ensures that existing code can still just pass a function to get the existing "onDidClose" style callback, although this behaviour should be deprecated. It also points towards the future of passing named callbacks for the modal (I'm listing two but the list could be extended).

**Comment by MadsBuchmann** [comment]
@mvindahl Good point with the callback not being passed by name - changing the name shouldn't break anything. 
I really like your proposed method signature and I simply think we should go with that. 

I will ping @alxzak and let him know it is ready to be put in the backlog. 

Alternatively if you need it ASAP, you're also welcome to submit a PR. Just remember to follow the [contribution guidelines](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md) and if necessary we can setup a kick-off meeting.

**Comment by mvindahl** [comment]
It's not ASAP, we've lived with since forever and we have workarounds 🙂
