### ISSUE TITLE
[Enhancement] Add Component Overview to Cookbook

### ISSUE THREAD

**Issue by jakobe** [kirbydesign/designsystem#178]
**Describe the solution you'd like**
Would be nice to have an overview page where all the Kirby Components are listed as cards with an icon/avatar and a short description.

**Additional context**
See https://ionicframework.com/docs/components/ for a nice example.

### UX:
- [ ] Create Icons for each component (see #179)
- [ ] Make short descriptions for each component (with Dev)
### Code:
- [x] Create `components-overview` component + `components` route
- [x] Make a data-driven list of components rendered as Kirby Cards
  - [x] Make short descriptions for each component (with UX)
  - [ ] Implement Icons
- [ ] Reuse Icons for nav menu

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
