### ISSUE TITLE
[BUG] kirby router outlet fills entire page

### ISSUE THREAD

**Issue by KemalPajevic** [kirbydesign/designsystem#1786]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
Normally, in an Angular app, if I want to add a header and a footer I would place them in the app component template like this:
```
<app-header></app-header>
<router-outlet></router-outlet>
<app-footer></app-footer>
```
But it does not work in a Kirby-based app where the app component template contains:
```
<kirby-app>
  <kirby-router-outlet></kirby-router-outlet>
</kirby-app>
```
This is due the fact that `kirby-router-outlet` has `position: absolute` med `top`, `right`, `bottom` and `left` sat to `0px`.

I am currently using a workaround for the issue where I set up my app component template like this:
```
<kirby-app>
  <app-header></app-header>
  <div class="container">
    <kirby-router-outlet></kirby-router-outlet>
  </div>
  <app-footer></app-footer>
</kirby-app>
```
```
container {
  position: relative;
  display: flex;
  flex-grow: 1;
}
```

## Describe how to reproduce the bug
1. Create a new Kirby-based project
2. Add a header/footer in the app component template
3. See that the header/footer is hidden behind the `kirby-router-outlet` element

## Which Kirby version was used?
3.0.10

## What was the expected behavior?
The content in the `kirby-router-outlet` is wrapped between the header and footer.

## Please complete the following information:
- OS: MacOS
- Browser: Chrome
- Browser version: 94.0.4606.61

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/master/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [master branch](https://github.com/kirbydesign/designsystem/tree/master) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by MadsBuchmann** [comment]
I can verify the behaviour - but It seems to be intentional. We should look into if we should support @KemalPajevic's use case and why it is build like it is now.

**Comment by RasmusKjeldgaard** [comment]
Intentional behavior, and the workaround is to wrap the outlet in a parent that is relatively positioned, as per the original post.
