### ISSUE TITLE
[Enhancement] Slim desktop modal 

### ISSUE THREAD

**Issue by RikkeHolmJessen** [kirbydesign/designsystem#1787]
Our UX specialist has requested that we use a slim version of the desktop modal. Therefore, we need a new version of the existing desktop modal. 
It should have a width of 375px, mand a padding-left and padding-right of 16 px. 
![image](https://user-images.githubusercontent.com/88831871/135604410-c1097996-614a-425d-b0e6-fac98b6af22f.png)

**Comment by bommariusser** [comment]
@RikkeHolmJessen who is the UX specialst? :)

**Comment by bommariusser** [comment]
thanks @RikkeHolmJessen :) it does a lot!

**Comment by RikkeHolmJessen** [comment]
We still want to do this task, and we are planning to begin as soon as possible :)
