### ISSUE TITLE
[Enhancement] Create Component Icons for Cookbook

### ISSUE THREAD

**Issue by jakobe** [kirbydesign/designsystem#179]
**Describe the solution you'd like**
Would be nice to have icons for components which can be used on an overview page as well as in the side menu on the Cookbook.

**Additional context**
See https://ionicframework.com/docs/components/ for a nice example.

Related to #178 

### Icons:
- [ ] Avatar
- [X] Badge
- [x] Button
- [ ] Calendar
- [X] Card
- [ ] Chart
- [ ] Checkbox
- [ ] Chip
- [X] Floating Action Button
- [ ] Icons
- [ ] Grid
- [ ] Input
- [X] List
- [ ] Modal
- [ ] Loading Indicators
- [ ] Radiobutton
- [x] Segment
- [ ] Select
- [ ] Switch

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
