### ISSUE TITLE
[BUG] Two chips marked as selected (at the same time) in Segmented Control

### ISSUE THREAD

**Issue by hawkish** [kirbydesign/designsystem#1791]
- [ ] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
A user has been able to select two segmented chip controls at the same time. 

## Describe how to reproduce the bug

1. Go to cookbook.kirby.design
2. Click on Segmented Control
3. Select Chip in Configuration
4. Select the first chip
5. Let you finger rest more than 1 second on a random chip number two
6. See that the two chips are shown as selected - but only the first chip has caused an event

## Which Kirby version was used?
3.0.15

## What was the expected behavior?
That chip number two is selected, causing an event and the first chip is shown as being deselected

## Add any screenshots
![Screenshot_20211006-074853_Chrome](https://user-images.githubusercontent.com/6479516/136164272-b3993c13-6cf3-4d9d-b80d-45dd6978b99f.jpg)

## Please complete the following information:
- OS: Android 11, Samsung Galaxy S10+ 
- Browser Chrome

## Are there any additional context?
Please note: I've tested on iPhone 12, iOS 14.7.1 without being able to replicate the bug. 
Also the bug only appears to be consistent on Samsung phones: The bug cannot be replicated on Google Pixel 4A. 

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/master/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [master branch](https://github.com/kirbydesign/designsystem/tree/master) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by RasmusKjeldgaard** [comment]
Solved by #2417
