### ISSUE TITLE
[BUG] Dropdown with popover has flashing blue outline

### ISSUE THREAD

**Issue by MadsBuchmann** [kirbydesign/designsystem#1792]
- [X] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
Whenever the dropdown is used with `popover=true` the button quickly flashes blue when clicked. This does not happen when popover is false.

It is easier to describe with videos, so here's two: 

When `popover` is disabled: 

https://user-images.githubusercontent.com/17269698/135060350-5acb024a-0bcc-49b1-8e21-0c6040182079.mov

When `popover` is enabled:

https://user-images.githubusercontent.com/17269698/135059817-abeebca6-3929-4c07-a139-3eed96871b70.mov

## Describe how to reproduce the bug

1. Set `usePopover` to `true` for any dropdown in the cookbook. 
2. Click the dropdown and see the error happen. 

## What was the expected behavior?
Either the blue outline should never appear or it should stay. 

## Please complete the following information:
- OS: MacOS
- Browser: Chrome, Safari, Firefox

## Are there any additional context?
This was discovered when working on #1671. It has not yet been merged; this issue is created to be able to finish off the PR and break it down into smaller issues. 

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [X] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/master/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [master branch](https://github.com/kirbydesign/designsystem/tree/master) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by RasmusKjeldgaard** [comment]
No longer an issue 🎉
