### ISSUE TITLE
[Enhancement] Find a better way to lock scroll for Popover

### ISSUE THREAD

**Issue by MadsBuchmann** [kirbydesign/designsystem#1793]
- [X] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the enhancement
When a dropdown is opened in the following context: 
- `usePopover` is set to `true` 
- The page it is used on has an always on scrollbar 

The scrollbar dissapears causing all of the content to shift. 

This happens because the `Popover` component locks the scroll by disabling overflow. Much as is done with the modal; also causing the content to shift. 

A better solution should be found for locking scroll in cases where the scrollbar is always on (e.g. when using Firefox on a Mac with a mouse connected) that does not cause the content to shift.. 

https://user-images.githubusercontent.com/17269698/135633780-23073069-5d8f-425e-8769-0392d2161693.mov

## Describe the solution you'd like
I have no ideas currently. We should probably research what is possible. 

## Are there any additional context?
This issues stems from working on #1671 which is currently unmarked. This issue has been created to split the PR up into smaller manageable issues; such that the functionality in the PR can be merged and marked as experimental.

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Refinement

- [ ] Request that the issue is [UX refined](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#ux-refinement); do not proceed until this is done.
- [ ] Request that the issue is [tech refined](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#tech-refinement); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [master branch](https://github.com/kirbydesign/designsystem/tree/master) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Publish a WIP implementation to Github as a draft PR and ask for feedback. 
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Update the [cookbook](https://cookbook.kirby.design) with examples and showcases.

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request. If you created a draft PR during implementation you can just mark that as "ready for review".

**Comment by MadsBuchmann** [comment]
We should look into using `ion-popover`: https://ionicframework.com/docs/api/popover

**Comment by RasmusKjeldgaard** [comment]
This is no longer an issue 🎉
