### ISSUE TITLE
[BUG] Fix style issues caused by introduction of default HTML list styling

### ISSUE THREAD

**Issue by jkaltoft** [kirbydesign/designsystem#1802]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug

When a list item contains other HTML elements, e.g., a link, the layout strategy using CSS Grid Layout fails. 

In general, the default list styling can not handle more than 1 direct descendant element of list items.

**Workaround**

A possible workaround is to wrap all content inside each `<li>`, e.g. in a `<div>`, but it is not ideal. It won't solve every case. Vertical alignment will probably also be off.

## Describe how to reproduce the bug

1. Go to e.g. [https://cookbook.kirby.design/#/home/showcase/page](https://cookbook.kirby.design/#/home/showcase/page) or [https://cookbook.kirby.design/#/home/changelog](https://cookbook.kirby.design/#/home/changelog)
1. See error

## Which Kirby version was used?

v4.0.1

## What was the expected behavior?

Proper list styling

## Add any screenshots

![image.png](https://images.zenhubusercontent.com/60b5ee2813189c6118c321c9/eaea0b58-a6e8-4b79-aed6-f02b1b88d174)

![image.png](https://images.zenhubusercontent.com/60b5ee2813189c6118c321c9/7c9eff36-6461-45e3-9761-f7214c1f7bf9)

## Please complete the following information:
- OS: [e.g. Windows, MacOS, iOS]
- Browser [e.g. Chrome, Safari]
- Browser version [e.g. 22]

## Are there any additional context?

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/master/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [master branch](https://github.com/kirbydesign/designsystem/tree/master) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by jkaltoft** [comment]
# After

![image](https://user-images.githubusercontent.com/150451/139815900-c1fce30b-39f6-4857-a9b7-f1345554dd57.png)

![image](https://user-images.githubusercontent.com/150451/139815970-28ab2fe5-5957-412b-abaf-45b042bfb0ff.png)

**Comment by MadsBuchmann** [comment]
We should create a v5 branch and merge it there 😄
