### ISSUE TITLE
[Enhancement] Card & button shadow/elevation

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#182]
**Is your enhancement request related to a problem? Please describe.**
Right now the shadow on the cards/buttons are not perfect. 

A card/button can either have a shadow or have no shadow. Shadows are also pretty damn ugly right now on nativescript.

**Describe the solution you'd like**
 We want the card / button to be able to have different elevation from: z0, z2, z4 or z8. Also the shadow should drop its own color and not just black. 

Our general rules for shadow are like this:
"Når en knap (også segment) ligger på canvas så har den ikke skygge, men derimod har cards når du kan trykke på dem skygger (z2 på standard ting og z4 på ting der skal fremhæves)

Når knapper er floating så får de skygger (z8)"

**Additional context**
The way we handle it in sketch is that elevations are components that you put on your atoms (buttons & cards). So if you have a button it can toggle between different elevations dependent on the situation.

**Comment by jonasjensen-brolstark** [comment]
Should it be possible to have a `z0` elevation also? Basically disabling the shadow?

**Comment by bommariusser** [comment]
of course @jonasjensen-brolstark ! Ændrer det lige, da det måske er for implicit det jeg mente med det her :)

Vi har nogen principper til hvornår vi bruger skygger:

"Når en knap (også segment) ligger på canvas så har den ikke skygge, men derimod har cards når du kan trykke på dem skygger (z2 på standard ting og z4 på ting der skal fremhæves)

Når knapper er floating så får de skygger (z8)"

**Comment by jakobe** [comment]
Will be fixed by #342
