### ISSUE TITLE
[Enhancement] Floating action button "evolution" dependent on amount of content

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#183]
**Is your enhancement request related to a problem? Please describe.**
On screens where we have a floating action button the user can end up in situations where the content and the button are separated too much (Especially on desktop)

Eg. the user has only one message in his inbox. (see also attached screenshot 1.png)

**Describe the solution you'd like**
We would like a behavior where the button takes care of the content and follows the content.

See evolution of the button here: https://sketch.cloud/s/D0E2e/zxnx1Ky/play

A more simple solution would also just be that the fab isnt sticky to the bottom but follows the content dependent on the amount of content.

![1](https://user-images.githubusercontent.com/49033002/55168289-ddc04e00-5172-11e9-9980-baaab636dcfd.png)

**Comment by jakobe** [comment]
@bommariusser This can already be done, because the target feature decides where the FAB should be placed.
