### ISSUE TITLE
[Housekeeping] Harden flakey test

### ISSUE THREAD

**Issue by RasmusKjeldgaard** [kirbydesign/designsystem#1836]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 
## Describe the housekeeping request
We should consider if we can refactor either the dropdown component or the component test related to the isOpen functionality of the dropdown, as I am seeing sporadic test failures when running the test suite. The TestHelper.whenTrue function returns its Timeout Error for [this test.](https://github.com/kirbydesign/designsystem/blob/master/libs/designsystem/src/lib/components/dropdown/dropdown-popover.component.spec.ts#L311)

## Have you considered any alternatives?
Could we either avoid using actual time (some fakeAsync magic or similar?) or otherwise consider to add more milliseconds to the timeout in [dropdown.popover.component.spec.ts](https://github.com/kirbydesign/designsystem/blob/master/libs/designsystem/src/lib/components/dropdown/dropdown-popover.component.spec.ts#L311 )

## Are there any additional context?
![image](https://user-images.githubusercontent.com/42470636/139015773-81359142-5f7d-4255-9179-d0bddf1eff72.png)

**Comment by MadsBuchmann** [comment]
I have taken the liberty of changing the title of this issue in order to make it a general issue for documenting flakey tests. I think they should all be fixed in one go. 

I know @troelslenda and @mictro has had trouble with the one below from `libs/designsystem/src/lib/components/modal/services/action-sheet.helper.spec.ts`: 
```typescript
it('backdrop click should dismiss action-sheet', async () => {
      let modalDidDismiss = false;
      ionModal.onDidDismiss().then((_) => (modalDidDismiss = true));
      backdrop.dispatchEvent(new MouseEvent('click'));
      await new Promise<void>((resolve) => setTimeout(resolve, 15));
      expect(modalDidDismiss).toBeTrue();
});
```   

I haven't been able to recreate either of those on my own. It might be related to M1 Macs.

**Comment by RasmusKjeldgaard** [comment]
Just adding [this workflow run](https://github.com/kirbydesign/designsystem/runs/4354448350?check_suite_focus=true#step:8:3288) to the pile of possible flakey tests. First time seeing this on the CI, for me at least, so we should investigate if something changed around this time.

**Comment by RasmusKjeldgaard** [comment]
[This test](https://github.com/kirbydesign/designsystem/blob/master/libs/designsystem/src/lib/components/modal/services/action-sheet.helper.spec.ts#L66) which seems very similar to the above, started failing during the Angular upgrade. For now solved by slightly bumping the timeout from 15 to 20, but of course not ideal. Another testament to how flaky this way of doing it is, if small performance differences from version to version of Angular can affect this.

**Comment by MadsBuchmann** [comment]
[Another dropdown test that keeps failing](https://github.com/kirbydesign/designsystem/runs/5813726617) and [has been excluded for now](https://github.com/kirbydesign/designsystem/pull/2099/files#diff-5d4fe7219f5b19f4191b138beb1c5ebdee77907799067a917f3f9c3f92a1d550).
