### ISSUE TITLE
[COMPONENT] Dropdown

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#184]
**Describe the solution you'd like**
Dropdowns are toggleable, contextual overlays for changing its state. Its a way to "filter/toggle" different states. 

https://ionicframework.com/docs/api/picker 
https://ionicframework.com/docs/api/select 
https://fezvrasta.github.io/bootstrap-material-design/docs/4.0/bootstrap-components/dropdowns/

**Describe alternatives you've considered**
Picker, Popover, **Select** etc.

**Additional context**
Medium buttons that are either:

Closed (Attention 3 + no elevation): https://zpl.io/blLzdxz
Open (Attention 2 + z8 elevation): https://zpl.io/bJ1p973

a simple model would be something like this (walking skeleton):

In sketch we've build this like this:
- The button is an medium button with an icon (arrow down or arrow up)
- The overlay is a card with a z8 shadow.
- The buttons are described above.

### Kick Off:
- [x] Accept Feature incl. name of component (DSL)
- [x] Update Kirby Component Status and publish to [Kirby Cookbook](https://cookbook.kirby.design)
### Code:
- [x] Create Feature Branch
- [x] Implement Skeleton Component:
    - [x] Web implementation
- [x] [Implement Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [x] Add link to showcase on Kirby Component Status (`component-status-items.ts => code.cookbookUrl`)
- [x] Push commits to GitHub
### Review:
- [x] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- Merge to master and delete branch

**Comment by jakobe** [comment]
Closed by #899
