### ISSUE TITLE
[Enhancement] Long text inside a kirby-label gets truncated instead of breaking

### ISSUE THREAD

**Issue by ahmadakhmiev** [kirbydesign/designsystem#1857]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the enhacement
A long text inside a kirby-label gets truncated instead of breaking.

## Describe the solution you would like

1. Insert following code snippet where you can test it
```
<p>Jyske Banks automater</p>
<kirby-divider></kirby-divider>
<kirby-item>
  <kirby-label>
    <h3>Weekender/helligdage og bankdage kl. 18-9</h3>
    <p detail>Heraf brugt</p>
  </kirby-label>
  <kirby-label slot="end">
    <data>5000,00</data>
    <data detail>0,00</data>
  </kirby-label>
</kirby-item>
```
2. Open web inspect and toggle device toolbar
3. Choose e.g. iPhone X
4. Text should not truncate

## Which Kirby version was used?
4.0.8

## What was the expected behavior?
I would expect the text to break into two lines.

## Add any screenshots
![Screenshot 2021-10-29 at 10 28 13](https://user-images.githubusercontent.com/3372121/139858780-1154fe66-528b-4eb1-ad9b-009ce1b4a808.png)

## Please complete the following information:
- OS: iOS, Android, Web (Device toolbar)
- Browser Chrome
- Browser version Version 95.0.4638.54 (Official Build) (x86_64)

## Are there any additional context?

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Refinement

- [ ] Request that the issue is [UX refined](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#ux-refinement); do not proceed until this is done.
- [ ] Request that the issue is [tech refined](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#tech-refinement); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [master branch](https://github.com/kirbydesign/designsystem/tree/master) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Publish a WIP implementation to Github as a draft PR and ask for feedback. 
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Update the [cookbook](https://cookbook.kirby.design) with examples and showcases.

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request. If you created a draft PR during implementation you can just mark that as "ready for review".

**Comment by askarby** [comment]
Just noticed this issue, can we make it so that it's configurable (to have it truncate or not) - eg. not break backwards compatability?

**Comment by jeppevaldemar** [comment]
> Just noticed this issue, can we make it so that it's configurable (to have it truncate or not) - eg. not break backwards compatability?

Could it be a default truncating text, with an opt-in property of line break? E.g. how we do it with elevation on Cards, or did you imagine something else.

**Comment by askarby** [comment]
I think that would be a sound solution @jeppevaldemar. Perhaps with similar configuration abilities as the `*kirbyFitHeading`-directive (that is, the ability to provide the number of maximum lines, unless beginning to add ellipsis)

**Comment by RasmusKjeldgaard** [comment]
I'm converting this issue to an enhancement, to indicate that current functionality it is _not_ a bug. The solution should not break backwards compatibility as described above, and should most likely be opt-in.

**Comment by alxzak** [comment]
It is unfortunately outside future Kirby epics, and I can't see Team Kirby develop this issue. Instead of burying it, waould it be possible for You guys @Nohcho or @askarby to develop it, and contribute to Kirby?

**Comment by Nohcho** [comment]
Hi @alxzak. I'd like to give it a try, just don't know when it will happen.

**Comment by bommariusser** [comment]
@alxzak we can maybe support developing this. We just need help to refine it. The task is probably not only about truncating the text but also alignement of the different slots. Who is the best person to help us refine this issue? https://github.com/kirbydesign/designsystem/issues/1996 this issue is about the same :)

**Comment by RasmusKjeldgaard** [comment]
This is now possible with the `kirby-item-wrap` css class, see more on the item docs: 
https://cookbook.kirby.design/#/home/showcase/item
