### ISSUE TITLE
[Enhancement] Input validation

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#186]
**Is your enhancement request related to a problem? Please describe.**
Its not really related to a problem but related to the input kirby component..

**Describe the solution you'd like**
When the user either:
- inputs something "wrong" or
- inputs nothing in the required field

We want to show some kind of validation in the ui. in some case it'll be related to the component input but it can also be related to the button to go to the next screen when the user hasnt done it right ;)

Zeplin: https://zpl.io/aMWA0Om

![Bitmap2](https://user-images.githubusercontent.com/49033002/57353821-08d29000-716a-11e9-9bce-395c2906285d.png)

**Comment by jonasjensen-brolstark** [comment]
Closed by #628
