### ISSUE TITLE
[Enhancement] Desktop ready general solution for focus with keyboard

### ISSUE THREAD

**Issue by RasmusKjeldgaard** [kirbydesign/designsystem#1863]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the enhancement
For components that can be focussed (button, card, dropdown) we need to align the focus functionality.

#### Design
- [x] The focus ring should have a 2px spacing to the element, and have a stroke width of 2px. 

#### Implementation
- [x] Make sure focus does not occur when clicking with mouse or touch
- [x] When using keyboard, we should get a focus outline
- [x] How  do we ensure that the space between the ring and the element is the correct color?
  - For now it is just set to the background color of the application. It seems to be good enough in 99% of the cases and once we can move from box-shadow to outline when more major browser versions support it this should be mitigated.
- [x] What is the color of the ring?

## Are there any additional context?
Look at [focus-visible](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible). Is not supported for safari, so we need to see if we can live with it, or do something else or similar.

**Comment by jkaltoft** [comment]
`:focus-visible` will soon be enabled by default in Safari 🎉
