### ISSUE TITLE
[Housekeeping] Add release manangement workflow to CI

### ISSUE THREAD

**Issue by RasmusKjeldgaard** [kirbydesign/designsystem#1871]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the housekeeping request
Instead of only having patch releases for bugfixes and features, and bumping the version on all breaking changes, we should embrace [SemVer](http://semver.org) more thoroughly.

This means releasing bugs as patch versions, backwards compatible features as minor version, and breaking changes as major releases.

In addition to this, it would be awesome to be able to bundle multiple breaking changes in to each major release, so the releases where projects need to migrate can be spaced a bit more out. 

There are several tools that might get this job done in an automated fashion, and create a nice changelog simultaneously. One tool that seems widely used is [Semantic Release](https://github.com/semantic-release/semantic-release), or a less automated alternative [Conventional changelog](https://github.com/conventional-changelog/conventional-changelog)

## Have you considered any alternatives?
Other alternatives to Semantic Release include:
[Auto](https://github.com/intuit/auto)
[Release-it](https://github.com/release-it/release-it)
... and other similar tools that I have not stumbled upon.

## Are there any additional context?
We could consider forcing commit-conventions
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
https://github.com/ionic-team/ionic-framework/blob/master/.github/CONTRIBUTING.md#commit-message-guidelines
https://github.com/commitizen/cz-cli

**Comment by RasmusKjeldgaard** [comment]
This replaces #1323

**Comment by MadsBuchmann** [comment]
still relevant. Go away stale bot.

**Comment by RasmusKjeldgaard** [comment]
Closed by #2577
