### ISSUE TITLE
[RESEARCH] Angular 13 Upgrade 

### ISSUE THREAD

**Issue by alxzak** [kirbydesign/designsystem#1877]
## Describe the solution you'd like
We would like to upgrade from angular 12 til 13. 

## Are there any additional context?
https://angular.io/guide/update-to-latest-version

## Checklist:
- [ ] Speak to Team 0 about their progress
- [ ] Investigate if there should be any difficulty regarding upgrade

**Comment by RasmusKjeldgaard** [comment]
Looks like Ionic expects Angular 12, and I don't think we need 13 for anything in particular:
https://ionicframework.com/docs/next/intro/upgrading-to-ionic-6. 

I have made an issue for upgrading to 12: #1931

**Comment by RasmusKjeldgaard** [comment]
@alxzak closing this for now as it is very unlikely to happen before Ionic supports Angular 13.
