### ISSUE TITLE
[EPIC]  Declarative list enabling virtual scroll

### ISSUE THREAD

**Issue by MadsBuchmann** [kirbydesign/designsystem#1883]
## A bit of history
We would like to enable the use of virtual scroll with the `kirby-list` component. As a result of #1794 it was decided that Kirby should _not_ provide any utilities for virtual scrolling.  

Instead the list should be restructured to allow for consumers to bring their own virtual scroll library. 

This has the benefits: 
- Consumers can bring their preferred virtual scroll solution.
- Consumers have more possibilities to tweak the virtual scrolling in their specific context, as it can be very sensitive. 
- We do not need to provide and maintain a virtual scroll solution for each framework, as the components are moved to web-components and used in React, Vue, Svelte, etc. 

## What should be done?
To enable this we should make it possible to use the list declaratively. The current implementation is too "closed" to enable consumers to bring their own virtual scrolling solution. 

The specific details are still being decided on. But an example of a list with virtual scroll enabled using the [`@angular/cdk`](https://v7.material.angular.io/cdk/scrolling/overview) library could be: 
```html
<kirby-list> 
   <cdk-virtual-scroll-viewport itemSize="72"> 
      <kirby-item *cdkVirtualFor="let item of items">
         {{item}}
      </kirby-item>
   </cdk-virtuall-scroll-viewport>
</kirby-list>
```

## Phases 
In this epic we've attempted to collect all of the issues related to making the list declarative to enable virtual scroll. An attempt has been made to split them into sensible phases, that allows us to easily get out and test the new list: 

### 1. Structure 

- [x] #1813
- [x] #1887
- [x] #1816 
- [x] #1910
- [x] #1885 

### 2. Styling 
- [x] #1814 
- [x] #1817 
- [x] #1909

### 3. Advanced behaviour 
- [x] #1819  
- Have load on demand work with declarative list 
-  [x] Have no shape work with declarative list/create equivalent functionality 

### 4. Documentation
- [x] #1820 

### 5. Cleanup & Housekeeping 
- [ ] #1923 
- [x] #1934

**Comment by MadsBuchmann** [comment]
# Alternative approach: 
## 0. Prep 
- #1887 

## 1. Get kirby-item to work 
- #1813 
- #1814 
- #1815 

## 2. Get sections/groups/divider to work: 
- #1816
- #1817 
- #1818

## 3. Advanced features 
- #1885 
- #1819 
- Have load on demand work with declarative list
- Have no shape work with declarative list/create equivalent functionality

## 4. Documentation 
- #1820

**Comment by RasmusKjeldgaard** [comment]
Just adding this here, so we remember it: This solution in general might be out answer for solving https://github.com/kirbydesign/designsystem/issues/1604.

**Comment by MadsBuchmann** [comment]
@RasmusKjeldgaard should we add a final "5. Cleanup" phase to the epic? Because i just spawned #1923 which never will get done if we don't bundle it in with these tasks 😛

**Comment by RasmusKjeldgaard** [comment]
Most definitely! Makes a lot of sense to also take care of the deprecation plan in a phase "5. cleanup" 👍

**Comment by MadsBuchmann** [comment]
@RasmusKjeldgaard If you create an issue for deprecation feel free to just plop it into the last phase :)

**Comment by RasmusKjeldgaard** [comment]
I have just added a check-mark to the no-shape functionality in the original issue, as it is solved with our approach for styling the list described in https://github.com/kirbydesign/designsystem/issues/1814#issuecomment-1016487522
