### ISSUE TITLE
[BUG] Modal closes with fading overlay, if a nested drawer has been opened in the modal

### ISSUE THREAD

**Issue by BDUCLM** [kirbydesign/designsystem#1894]
- [ ] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
Modal closes with fading overlay, if a nested drawer has been opened in the modal

## Describe how to reproduce the bug
E.g. budget plan and manual edit

See video attached.

1) Open a budget plan (modal)

2) Close it again and see that there is no fading

3) Open the budget plan again

4) Change to manual and open a month

5) Close edit mode drawer

6) Close the budget plan

7) Observe that fading is visible, which it should not be

The error can be reproduced in other modules with the nested drawer, e.g. transfer and search for postings/transactions.

## Which Kirby version was used?
3.0.15

## What was the expected behavior?
No fading.

## Add any screenshots
https://user-images.githubusercontent.com/94539419/142206537-3182886a-7c5c-4706-a554-b66c7876caaa.MP4

## Please complete the following information:
- OS: iOS

## Are there any additional context?

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/master/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [master branch](https://github.com/kirbydesign/designsystem/tree/master) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by mictro** [comment]
Cannot be reproduced on kirby version 8.3.1 - closed
