### ISSUE TITLE
[Enhancement] Deprecate Icon Component ‘customName’ input property

### ISSUE THREAD

**Issue by RasmusKjeldgaard** [kirbydesign/designsystem#1897]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the enhancement
Currently, an icon can either be added as a default icon in [kirby-icon-settings.ts](https://github.com/kirbydesign/designsystem/blob/master/libs/designsystem/src/lib/components/icon/kirby-icon-settings.ts#L65), or registered as a custom icon via the `icon-registry.service.ts`. 
Unfortunately, these two types of icons have to be specified on the icon component via two different input properties. This is confusing, and makes for extra checks and complexity in for example our [SegmentedControl](https://github.com/kirbydesign/designsystem/blob/master/libs/designsystem/src/lib/components/segmented-control/segmented-control.component.html#L16-L22), when we want to be able to use both custom icons and normal icons programatically.

## Describe the solution you'd like
I would expect the `name` input on an icon to work for any icon, default or registered in Kirby via the service. 
If this is possible, we should deprecate [customName]. Currently, I guess it is possible to have a custom icon and a default icon with the same name, without any clashes. We would need to account for this in the implementation, or declare this a breaking change. 

This should be possible by extending the iconRegistryService to also handle the default icons, instead of having them defined in a separate map.  

## Are there any additional context?

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Refinement

- [ ] ~~Request that the issue is [UX refined](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#ux-refinement); do not proceed until this is done.~~
- [ ] Request that the issue is [tech refined](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#tech-refinement); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [master branch](https://github.com/kirbydesign/designsystem/tree/master) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Publish a WIP implementation to Github as a draft PR and ask for feedback. 
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Update the [cookbook](https://cookbook.kirby.design) with examples and showcases.

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request. If you created a draft PR during implementation you can just mark that as "ready for review".

**Comment by MadsBuchmann** [comment]
> We would need to account for this in the implementation, or declare this a breaking change. 

I think we should deprecate the `customName` field and mark it as such in the documentation. It should then be removed in the future. 

If there's a name clash between an icon defined in Kirby i think we should either: 
- Throw an error informing the consumer that they can't name their icon that. 
- Overwrite icon in kirby with the custom one. 

I'm personally more for the first option as i think it is more predictable - if a user working in a codebase is not aware that e.g. `trash` has been overwritten and then discovers  that it differs from the one in the cookbook, they might get confused. 

I also think we should encourage prefixing custom icons names with something like `custom-` or perhaps `drb-` to prevent name clashes.
 
We could also enforce the `custom-` naming convention when registering the icons to make sure name clashes does not happen between the icons in Kirby and custom ones.

Such that if i register "cool-icon" as a custom icon i will have to use it as "custom-cool-icon".

**Comment by MadsBuchmann** [comment]
Solving this issue would most likely also solve: https://github.com/kirbydesign/designsystem/issues/1922
