### ISSUE TITLE
[Enhancement] Enlarge 'pull down range' of refresher on page

### ISSUE THREAD

**Issue by LVinther** [kirbydesign/designsystem#1903]
- [ ] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the enhancement

As a user I want the content to follow my gesture until I lift my finger. Right now the content follows my finger to a fixed distance from the top, which doesn't give a natural experience (see attachment). 

## Describe the solution you'd like

In the Refresher component it is possible to adjust MaxPull and MinPull - maybe we need to adjust these to achieve the desired behavior. https://ionicframework.com/docs/api/refresher
https://user-images.githubusercontent.com/53176253/143008265-fa3c22a0-162c-4c6d-8fe6-bd97d199af58.mov
 
## Are there any additional context?

Pinterest has the desired behavior (see attachment)
https://user-images.githubusercontent.com/53176253/143008387-67bd6508-bd04-4e52-8d81-ba5926ddc2f9.mov
<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Refinement

- [x] Request that the issue is [UX refined](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#ux-refinement); do not proceed until this is done.
- [x] Request that the issue is [tech refined](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#tech-refinement); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [master branch](https://github.com/kirbydesign/designsystem/tree/master) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Publish a WIP implementation to Github as a draft PR and ask for feedback. 
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Update the [cookbook](https://cookbook.kirby.design) with examples and showcases.

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request. If you created a draft PR during implementation you can just mark that as "ready for review".

**Comment by LVinther** [comment]
@RasmusKjeldgaard @alxzak we will try to find time in team 3 to solve this issue :)

**Comment by RasmusKjeldgaard** [comment]
Closing this as the requesting team has not found the time. Please reopen if this is still needed, and consider contributing the fix ❤️
