### ISSUE TITLE
[BUG] Blue arrows in calendar on iOS

### ISSUE THREAD

**Issue by bduvsi** [kirbydesign/designsystem#1914]
- [ ] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
When opening the calendar vi see the color of the right and left arrow turns into Blue color . 

## Which Kirby version was used?
4.0.10

## What was the expected behavior?
The color of the arrows in calendar drawer(modal) should be same color(gray color) as other arrows and should not turn in Blue color 

## Add any screenshots
![Image from iOS (1)](https://user-images.githubusercontent.com/83588631/144035964-927d1bb7-837d-45f5-938e-94fa4b40e7fd.jpg)

## Please complete the following information:
- OS: Iphone 12 

## Are there any additional context?
Similarly on hover in Web button border also turns into Blue color , but sure if this is relevant with arrows color. 

![image (4)](https://user-images.githubusercontent.com/83588631/144036197-85a16e3d-d0d1-4728-872e-c8eb9910c194.png)

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/master/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [master branch](https://github.com/kirbydesign/designsystem/tree/master) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by RasmusKjeldgaard** [comment]
@bduvsi does this only happen when the calendar is in a drawer?

**Comment by RasmusKjeldgaard** [comment]
This can be verified by going to https://cookbook.kirby.design/#/home/showcase/calendar on an iPhone with iOS 15.

**Comment by MadsBuchmann** [comment]
We've had a similar issue before: https://github.com/kirbydesign/designsystem/issues/1628#issuecomment-880675493

**Comment by bduvsi** [comment]
Thasts true. It happens also in safari browser.
![IMG_1365](https://user-images.githubusercontent.com/83588631/144043340-8e8d3650-33f3-4b3c-8684-1219a894fcd3.jpg)
 .
