### ISSUE TITLE
[Enhancement] Card stack

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#193]
**Is your enhancement request related to a problem? Please describe.**
The enhancement is related to the card component. 

**Describe the solution you'd like**
We want cards to be stackable, so that a series of cards can be bundled and unbundled dependent on the context.

Bundle: https://sketch.cloud/s/D0E2e/jgdJKda & https://zpl.io/agzDzB9
Unbundle: https://sketch.cloud/s/D0E2e/zxo2roa & https://zpl.io/2GyNywm

**Additional context**
The stack should remember its state, so that when a user unstacks a bundle it shouldnt stack again until the user does it.

**Comment by jakobe** [comment]
@bommariusser Still relevant? 🤔
