### ISSUE TITLE
[Housekeeping] Upgrade to Angular 12

### ISSUE THREAD

**Issue by RasmusKjeldgaard** [kirbydesign/designsystem#1931]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the housekeeping request
We need to upgrade to Angular 12, to support the new Ionic 6 version.
See more here: https://ionicframework.com/docs/next/intro/upgrading-to-ionic-6

## Have you considered any alternatives?
No, we should definitely do this! 😄

**Comment by MadsBuchmann** [comment]
I've moved this to our impeeded column as it is blocked by #1984
