### ISSUE TITLE
[Housekeeping] Upgrade to Ionic 6

### ISSUE THREAD

**Issue by RasmusKjeldgaard** [kirbydesign/designsystem#1932]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the housekeeping request
Ionic v6 is out, and we should upgrade ASAP, before we introduce our own enhancements (to for example accessibility) on top of the newest improvements. 

https://ionicframework.com/docs/next/intro/upgrading-to-ionic-6.

## Have you considered any alternatives?
No! 😄

**Comment by MadsBuchmann** [comment]
Ionic 6 introduces a popover component! 
We might be able to replace our own experimental popover functionality which was introduced in https://github.com/kirbydesign/designsystem/pull/1671 with it. This could perhaps aid us in solving the following issues: 
- https://github.com/kirbydesign/designsystem/issues/404
- #1411

Having played a bit around with [their example for `ion-popover`](https://ionicframework.com/docs/demos/api/popover/index.html?ionic:mode=ios) i think they've stumbled upon the same issue as us with the flickering scrollbar when locking scroll: #1793

**Comment by RasmusKjeldgaard** [comment]
Waiting for #1931

**Comment by RasmusKjeldgaard** [comment]
Upgrading to Ionic 6 should allow us to remove the skipLibCheck flag introduced in the Angular 13 upgrade as discussed here: https://github.com/kirbydesign/designsystem/pull/2284#discussion_r879493687
