### ISSUE TITLE
[Housekeeping] Changelog management

### ISSUE THREAD

**Issue by RasmusKjeldgaard** [kirbydesign/designsystem#1933]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the housekeeping request
We should https://keepachangelog.com/ to more easily and consistently communicate the new changes in Kirby.
The current changelog reflects our current release flow, where we communicate major, minor and patch-versions all in the same manner. 

If we are more consistent in describing each change, we can automatically bundle and release our changelog as a more meaningful set of changes, when new features or major versions arrive. This can, combined with our research for branching patterns (#1926) 

It would be beneficial to store this as a CHANGELOG.md file here in github, as it will be readily available to developers. At the same time, we can easily reuse that file in our documentation tools, instead of fetching information about releases from github into the cookbook. 

There are some nice tools for the job:
- [Conventional changelog ](https://github.com/conventional-changelog/conventional-changelog) - more specifically the [CLI](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-cli) for generating the changelog based on commits. 
- [Semantic Pull Requests](https://github.com/apps/semantic-pull-requests) for ensuring the format of the pr title, OR [Commitizen](https://github.com/commitizen/cz-cli) to control it for each commit (probably overkill for our use-case. 
- There is also a more automated approach with [semantic release](https://github.com/semantic-release/semantic-release), that utilizes conventional changelog under the hood, but I think we can have a cleaner setup with a bit more control by combining Github Actions and conventional changelog.

**Comment by jkaltoft** [comment]
We should have a look at these files when we address this issue. It seems like a bad idea to store tokens and API keys in a public code repository 😊

https://github.com/kirbydesign/designsystem/blob/2588e0ce28121a2c649e5cf952981bdfbdc8e12b/apps/cookbook/src/environments/environment.prod.ts

https://github.com/kirbydesign/designsystem/blob/2588e0ce28121a2c649e5cf952981bdfbdc8e12b/apps/cookbook/src/environments/environment.ts

**Comment by RasmusKjeldgaard** [comment]
The plan for now is to remove the component status page of the cookbook, so hopefully this firebase integration should be entirely unnecessary!

**Comment by RasmusKjeldgaard** [comment]
Closing this as it will be solved by #2466 and #2464 in combination with squashing our PR's to create changelog friendly commits on the develop branch.
