### ISSUE TITLE
[BUG] ChartJS - this.chart is undefined

### ISSUE THREAD

**Issue by bdytos** [kirbydesign/designsystem#1942]
- [ ] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
The `<kirby-chart>` is throwing an error with `TypeError: this.chart is undefined` (See fig 1 in the screenshot section).
If the code inside the `ngAfterViewInit()` in `libs/designsystem/src/lib/components/chart/chart.component.ts` is removed and only uses `this.renderChart()` it works without errors. (see fig 2 in the screenshot section)

## Which Kirby version was used?
v4.0.25

## What was the expected behavior?
The chart should not throw an error.

## Add any screenshots
fig 1
<img width="919" alt="image" src="https://user-images.githubusercontent.com/77673731/146508608-48433f65-da51-42dc-bf6f-d683258ecc22.png">

fig 2
<img width="631" alt="image" src="https://user-images.githubusercontent.com/77673731/146508946-53ccab91-4651-49fc-bb2a-baae315a82f9.png">

## Please complete the following information:
- OS: MacOS v.12.0.1
- Browser Firefox
- Browser version v95.0

## Are there any additional context?
<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/master/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [master branch](https://github.com/kirbydesign/designsystem/tree/master) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by MadsBuchmann** [comment]
**Tech Refinement )** 

- For the `ChartComponent` class content of the `ngOnChanges` function should not be executed unless the `renderChart` method has been ran once. 
- A test should be written testing the above behaviour 
- @bdytos should test it in the DRB app to ensure it fixes his issue.

**Comment by MadsBuchmann** [comment]
A solution has been released in v5.1 https://github.com/kirbydesign/designsystem/pull/2048
