### ISSUE TITLE
[Enhancement] Adjust the Danger color on flags

### ISSUE THREAD

**Issue by LVinther** [kirbydesign/designsystem#1956]
- [ ] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the enhancement

We get a lot of feedback from investment customers that they are not able to read the black text in our 'danger' colored flags (return). We would like to change the color of red flag so that it is more readable.

## Describe the solution you'd like

Jonathan and Henrik have been working on a lighter 'danger' color for our flags.

## Are there any additional context?

![Forside, Igangværende handler](https://user-images.githubusercontent.com/53176253/146819922-93aee941-fdc9-4997-8f47-7c4924e2e741.png)

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Refinement

- [ ] Request that the issue is [UX refined](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#ux-refinement); do not proceed until this is done.
- [ ] Request that the issue is [tech refined](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#tech-refinement); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [master branch](https://github.com/kirbydesign/designsystem/tree/master) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Publish a WIP implementation to Github as a draft PR and ask for feedback. 
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Update the [cookbook](https://cookbook.kirby.design) with examples and showcases.

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request. If you created a draft PR during implementation you can just mark that as "ready for review".

**Comment by LVinther** [comment]
@henrikvoetmand will you tage a look at this and maybe elaborate on the solution you are working on? :)

**Comment by MadsBuchmann** [comment]
@henrikvoetmand - the stalebot has closed the issue but i suppose it was actually solved by #2041, right?
