### ISSUE TITLE
[Housekeeping] Store core distribution bundle with designsystem

### ISSUE THREAD

**Issue by MadsBuchmann** [kirbydesign/designsystem#1973]
- [X] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the housekeeping request

Distribution bundles for "core" and "designsystem" libs when running `npm run build` are outputted to respectively: 
- `designsystem/libs/core/dist` 
- `designsystem/dist/libs/designsystem` 

To keep it consistent and seperate source code from distribution bundles i would like for the core distribution bundle to be outputted to `designsystem/dist/libs/core` instead. 

`scripts/forward-scss-files` will probably have to be updated as part of this.

**Comment by mictro** [comment]
This issues is handled by issue #1974
Closed
