### ISSUE TITLE
[Housekeeping] Copy SCSS files from core on publish instead of dev time

### ISSUE THREAD

**Issue by MadsBuchmann** [kirbydesign/designsystem#1974]
- [X] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the housekeeping request
Currently the gitignored folder `libs/core/scss` which contains the distributed sass files for core is generated whenever stencil builds. This includes when running the development server. 

This is unnecessary as the files are never accessed during development and should be used for distribution only. Honestly it is also annoying as it is easy to mistake `libs/core/scss` for `libs/core/src/scss` when developing causing confusion. 

The code responsible for copying out the sass files can be found in `libs/core/stencil.config.ts`: 
```
    {
      type: 'dist',
      esmLoaderPath: '../loader',
      copy: [{ src: 'scss', dest: '../../scss', warn: true }],
    },
```

The copy key should be removed and it should be done as part of `scripts/publish.js` instead. 

## Are there any additional context?

The location of `libs/core/scss` might have changed with #1973

**Comment by mictro** [comment]
This issue depends on #1975

**Comment by mictro** [comment]
This issue also solves #1973 and #1975
