### ISSUE TITLE
[Housekeeping] Move build and publish of core to publish.js script

### ISSUE THREAD

**Issue by MadsBuchmann** [kirbydesign/designsystem#1975]
- [X] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the housekeeping request
Right now the designsystem package is built and published in the `scripts/publish.js` script which is ran when calling `npm run publish`. 

Core on the other hand is built and published in `.github/workflows/publish.yml` when github actions run.  

To be consistent in how we handle publishing, i think we should remove the step `Publish core package to npm` from `publish.yml` and instead have equivalent functionality in `publish.js`.

**Comment by mictro** [comment]
This issues is handled by issue https://github.com/kirbydesign/designsystem/issues/1974
Closed
