### ISSUE TITLE
Animation of btn's and titles on scroll

### ISSUE THREAD

**Issue by MadsBuchmann** [kirbydesign/designsystem#1981]
This is a placeholder for now :)

**Comment by henrikvoetmand** [comment]
https://user-images.githubusercontent.com/71710012/153842950-1be1a649-cc16-4df8-9bac-296837537a1d.mp4

**Comment by MadsBuchmann** [comment]
@henrik - the buttons, do they retain their size and is it just the distance between the elements that are decreased? 
Which properties are we changing exactly when animating?

**Comment by henrik** [comment]
![](https://media3.giphy.com/media/zEXWm8ymudM8W91j5I/giphy.gif?cid=ecf05e470ngk2jpu2brwns8cc4rgplarmokcpbfl3zxvy89s&rid=giphy.gif&ct=g)

Wrong Henrik!

**Comment by MadsBuchmann** [comment]
Hah sorry @henrik! Paging @henrikvoetmand!

![](https://media1.tenor.com/images/135c8a1606c6fb9e522d56403d24acb7/tenor.gif)
