### ISSUE TITLE
[Enhancement] Refactor Kirby-Slide (Desktop Ready?)

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#1986]
## Describe the enhancement and the 
Since the Ionic slide is deprecating we should consider changing our kirby slide implementation to the one Ionic is pointing towards to: https://swiperjs.com/

Also.. The implemented slide in kirby is very specific bound upon the one usecase which it is used in, but it should be more generic useable for everyone.

See also https://www.jyskebank.dk/bolig/regn-paa-bolig/beregn-laan-i-frivaerdi

Also. The slide implementation above could be more "desktop ready" with adding both button and pagination, which could be part of this issue.

Slide in general has a wide variety of usecases, see also the screenshots below.. 

<img width="423" alt="Skærmbillede 2022-01-07 kl  12 53 09" src="https://user-images.githubusercontent.com/49033002/148540492-56ade0a6-207b-4f96-bb88-8cc901d475b5.png">

![Skærmbillede 2022-01-07 kl  12 54 02](https://user-images.githubusercontent.com/49033002/148540524-afbe9c60-d75b-463a-b645-14a06c8dca22.png)

![Skærmbillede 2022-01-07 kl  12 53 52](https://user-images.githubusercontent.com/49033002/148540531-47dfd20c-cfbf-4743-84f0-d3cdeb514a50.png)

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Refinement

- [ ] Request that the issue is [UX refined](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#ux-refinement); do not proceed until this is done.
- [ ] Request that the issue is [tech refined](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#tech-refinement); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [master branch](https://github.com/kirbydesign/designsystem/tree/master) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Publish a WIP implementation to Github as a draft PR and ask for feedback. 
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Update the [cookbook](https://cookbook.kirby.design) with examples and showcases.

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request. If you created a draft PR during implementation you can just mark that as "ready for review".

**Comment by MadsBuchmann** [comment]
Swiperjs looks good! But it has a ton of functionality some of which might be superflous. 

Therefore i think it is worth considering what our exact requirements for a slider is and then discuss if it is worth dragging in another dependency to fulfill those. If the requirements are simple enough, perhaps we would be better served by building the functionality ourselves to have full control? 

I've never tried building a slider from scratch so i do not know if it is a PITA, but i think it is worth discussing before jumping to the conclusion that we must use swiperjs.

**Comment by jkaltoft** [comment]
Suggestion: Do some research before "throwing in another JS library"

[Swiper](https://swiperjs.com/) may or may not be overkill. Can [CSS Scroll Snap](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scroll_Snap) cover the use cases?

**Comment by mark-drastrup** [comment]
I have done some research as suggested above to see if we can implement our own slider from scratch. It hard to tell whether we can do it ourselves or not, before the slider is UX refined. If it's a simple use case like our current slider, but with pagination and buttons, then is should be feasible for us to do by ourselves. Then we could take inspiration from and expand upon a simple codepen like this: https://codepen.io/bushblade/pen/ZEpvzbK?editors=0010, which supports both desktop and mobile.
But if the expected use cases for the slider is complex, then I believe it would be easier for us to migrate our slider to use Swiper.js

Once this issue has been UX refined, then we are in a better position to decide which direction we want to go.
