### ISSUE TITLE
[BUG] Kirby Dropdown submits the form

### ISSUE THREAD

**Issue by KemalPajevic** [kirbydesign/designsystem#1987]
- [X] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
When a `kirby-dropdown` is placed within a submittable form, clicking on the dropdown submits the form.
This is probably due to the fact that the `kirby-button` in the dropbox component doesn't have a specified type so it defaults to "submit".

## Describe how to reproduce the bug

1. Create a template with a `form`
2. Add the `(ngSubmit)="onSubmit()"` event to the form
3. Add a `kirby-dropdown` to the form
4. Click on the dropdown
5. See that the form is submitted

## Which Kirby version was used?
4.0.24

## What was the expected behavior?
The dropdown is opened

## Please complete the following information:
- OS: MacOS
- Browser Chrome
- Browser version 96.0.4664.110

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [x] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/master/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [master branch](https://github.com/kirbydesign/designsystem/tree/master) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by jkaltoft** [comment]
This bug has been verified.

## Suggestion for solution

Add `type="button"` to the `<button>` in `<kirby-dropdown>`

## Explanation

See https://html.spec.whatwg.org/multipage/form-elements.html#attr-button-type:

> The missing value default and invalid value default are the Submit Button state.
