### ISSUE TITLE
[BUG] Ionic wrapped components doesn't show outline when focused.

### ISSUE THREAD

**Issue by ghost** [kirbydesign/designsystem#199]
**Describe the bug**
When tabbing through kirby elements the ones that uses Ionic components doesn't show the browser outline.

**To Reproduce**
1. Go to '[FAB example](https://cookbook.kirby.design/home/showcase/floating-action-button)'
2. Tab through until the FAB buttons get focus - they don't show any signs of focus 

**Kirby version**
 - All

**Expected behavior**
Focused elements should show the default browser outline like all other default elements.

**Desktop (please complete the following information):**
 - OS: Windows/Mac/Linux
 - Browser Chrome, Safari, Edge, Firefox

**Additional context**
Ionic sets outline to none, so its a matter of disabling that.

**Comment by jakobe** [comment]
Fixed
