### ISSUE TITLE
[Enhancement] Items that supports linebreaking (multiline)

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#1996]
## Describe the enhancement
All items truncate right now as default and this is the only option for a item. Also: the end slot is always center-aligned which can be a issue when the default slot goes into more then 1 line.

## Describe the solution you'd like
We would like to have the opportunity to have items that can support to show more then 1 line. 

A possibility for this could be something like "line clamping" support.

## Have you considered any alternatives?
A alternative could be that it should be a different component for this kind of behavior. All the examples i have right now, there is no avatar, which already could be a sign of "this is not a item" but this can be discussed :)

## Are there any additional context?

![Skærmbillede 2022-01-17 kl  13 08 16](https://user-images.githubusercontent.com/49033002/149769131-7a9e2883-c7cb-4471-8919-1bb8dc5563ab.png)
![Skærmbillede 2022-01-17 kl  13 05 38](https://user-images.githubusercontent.com/49033002/149769135-6e66f2e4-1abb-4c5f-b1f8-ae9f3c6d1474.png)
![Skærmbillede 2022-01-17 kl  13 05 30](https://user-images.githubusercontent.com/49033002/149769136-c12e40f1-dcee-4b41-868d-625383400845.png)

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Refinement

- [ ] Request that the issue is [UX refined](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#ux-refinement); do not proceed until this is done.
- [ ] Request that the issue is [tech refined](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#tech-refinement); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [master branch](https://github.com/kirbydesign/designsystem/tree/master) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Publish a WIP implementation to Github as a draft PR and ask for feedback. 
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Update the [cookbook](https://cookbook.kirby.design) with examples and showcases.

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request. If you created a draft PR during implementation you can just mark that as "ready for review".

**Comment by bommariusser** [comment]
Workaround is something like this: 

![Skærmbillede 2022-01-18 kl  13 21 07](https://user-images.githubusercontent.com/49033002/150121656-719dfd01-185e-4f4e-8c61-bf9eeff80c7a.png)



With this the end slot doesn't align top though...

**Comment by bommariusser** [comment]
We have actually found usecases where linebreak should/could be on both default and end see also...

<img width="573" alt="truncate" src="https://user-images.githubusercontent.com/49033002/154454483-3c20c0c7-17b0-433d-b503-0de79e91412c.png">
 
 Is there any chance that we can make the change ourselves for Kirby (aka solve this issue on our own with kirby help)? what do you think @MadsBuchmann @RasmusKjeldgaard ? We really do not want to make some custom drb stuff for that.. :/

**Comment by RasmusKjeldgaard** [comment]
This is now possible with the `kirby-item-wrap` css class, see more on the item docs: 
https://cookbook.kirby.design/#/home/showcase/item
