### ISSUE TITLE
[Enhancement] Card Outline

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#1998]
## Describe the enhancement
Right now cards only support fill-colors but we would like to have support for outline cards too.

## Describe the solution you'd like
Add Outline as a 3th. visual variant for the existing Card component. (Default, Flat, **Outline**)
Outline should be similar to the existing "Flat" variant in regards to guidelines (not used for clickable cards)
The outline is available in our sketch library but just not available for our cards right now.
The relevant color right now is "grey"/"medium" (#D1D1D1) 

**SPEC:**
Outline stroke 1px - "grey"/"medium" (#D1D1D1)
Background: none

## Have you considered any alternatives?
No

## Are there any additional context?
Here is just one example

![Skærmbillede 2022-01-18 kl  09 06 32](https://user-images.githubusercontent.com/49033002/149896213-7c97cab7-822e-48c3-8f69-19ebebe2cca7.png)

**Link to Zeplin:**
https://zpl.io/8Ejm3Ww

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Refinement

- [ ] Request that the issue is [UX refined](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#ux-refinement); do not proceed until this is done.
- [ ] Request that the issue is [tech refined](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#tech-refinement); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [master branch](https://github.com/kirbydesign/designsystem/tree/master) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Publish a WIP implementation to Github as a draft PR and ask for feedback. 
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Update the [cookbook](https://cookbook.kirby.design) with examples and showcases.

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request. If you created a draft PR during implementation you can just mark that as "ready for review".

**Comment by mark-drastrup** [comment]
I just discussed this enhancement with @henrikvoetmand and we agreed i needs UX refinement before development can begin.

**Comment by RasmusKjeldgaard** [comment]
Tech refinement with @Fuzzy3:
This could be an input property 'outline' similar to 'flat' where we use a host-binding to set some class that we can base our styling on:

```
&.outline {
    background-color: transparent;
    outline: 1px solid utils.get-color('medium') //OR var(--kirby-card-main-background-color);
  }
```
