### ISSUE TITLE
Create hover solution for non-solid backgrounds in card (pseudo element and opacity)

### ISSUE THREAD

**Issue by jkaltoft** [kirbydesign/designsystem#2006]
With interaction state (#1935) we've tried to avoid creating an additional element in the DOM to alter the background on elements when hovering. 

Some places we have multi-colored backgrounds such as a card with an image background - this requires an additional element in the DOM, as we can't just alter the background color as is done in #1935. 

Instead we should put an additional layer on top to alter the background-color; inspired by material design interaction layers. 

A general solution for doing this should be created. 

### Questions: 
- [x] Should #2022 be carried out? If not, just close this issue.    
- [x] How do we toggle whether we use solution from #1935 or the new one where we introduce a new element to color the elements. There might not exist a pretty solution :-) 
   - Should we use an input property to toggle, css custom property?

### Requirements: 
- If it is interactive (i.e. click event is given) & it has an image background image: use new solution with additional element in DOM. 
- If it is interactive & it has a solid background: use solution from #1935 

### Blocked by: 
- [x] #2022

**Comment by MadsBuchmann** [comment]
@jkaltoft - i suppose this is somewhat in progress with the current state layer solution 🤔 ?

**Comment by jkaltoft** [comment]
> @jkaltoft - i suppose this is somewhat in progress with the current state layer solution 🤔 ?

@MadsBuchmann, yes it is. This issue may be solved by #2008

**Comment by MadsBuchmann** [comment]
@jkaltoft - it will perhaps result in some wild git gymnastics; you might be able to cherry-pick https://github.com/kirbydesign/designsystem/commit/321de10c11ac016da5eb6ef546e9d30c67fc4dc4 to your branch. 

That is where the changes are present at least :-)
