### ISSUE TITLE
Verify hover in components that use `<button>`

### ISSUE THREAD

**Issue by jkaltoft** [kirbydesign/designsystem#2007]
Make sure that every component that has a `kirby-button` is checked and updated as needed.

A quick search suggests that we check out the following:

- [x] Create solution for buttons with transparent background (mostly attention level 3 and undecorated buttons)
- [x] Adjust loudness - dark backgrounds must be louder, light backgrounds must be quieter (e.g. attention level 2)
  - Verify/modify buttons in `.kirby-color-brightness-dark` context
- Calendar
  - [x] Buttons in month navigator should be `undecorated` `kirby-button`s
- Alert
  - [x] Use `apply-hover()` with notification colors (success etc.)
- [x] Modal wrapper
  - Will be solved by solution for transparent background (undecorated)
- Action Sheet
  - [x] Styles for options should not override hover styles
  - [x] Awaiting UX decision (related to hover on list items)
- [x] Dropdown
  - Awaiting UX decision
- Are buttons used elsewhere?
  - [x] Toggle button

**Comment by MadsBuchmann** [comment]
Should be released as part of theme: release/theme/0000-button-attention-levels-and-hover
