### ISSUE TITLE
[BUG] absolute asset paths in Kirby prevent use of base href

### ISSUE THREAD

**Issue by KemalPajevic** [kirbydesign/designsystem#2009]
- [X] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
If you deploy a project using base href, it is only applied by the browser on relative asset paths. Since Kirby is setting absolute paths for the assets, it is preventing the application of the base href.

## Describe how to reproduce the bug

1. Create a new project that uses Kirby.
2. Make a component with a link `<a href="#" class="kirby-external-icon">Test</a>`.
2. Build the project using `ng build --base-href /mypath/`.
3. See that the link icon is not shown.
4. Edit the page code so that the `background-image` of the `a` points to `assets/kirby/icons/svg/link.svg` in stead of `/assets/kirby/icons/svg/link.svg`.
5. See that the link icon is shown.

## Which Kirby version was used?
5.0.18

## Please complete the following information:
- OS: MacOS
- Browser: Chrome
- Browser version: 97.0.4692.71

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/master/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [master branch](https://github.com/kirbydesign/designsystem/tree/master) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by alxzak** [comment]
Should also fix #1565 & #1735

**Comment by mark-drastrup** [comment]
Hi @KemalPajevic! :)

I have been trying to reproduce the bug, but without any luck. Do you still experience it? :)
