### ISSUE TITLE
[BUG] Tooltip not shown on bar chart after introduction of stock chart in 5.0.5

### ISSUE THREAD

**Issue by SilverGull** [kirbydesign/designsystem#2046]
- [x ] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
When going from Kirby 5.0.4 to 5.0.5 tooltips on our bar chart is no longer showed. I currently have standalone example but it can be seen in the mock version of "Relationsbanken" under menu => pension => "Forventede udbetalinger" and it is the component https://github.com/Bankdata/relationsbank/tree/master/libs/portals/jyskebank/jb-wealth/domain/src/lib/pension-forecast/components/pension-forecast-chart. If need be I will see if I can make a standalone example.

## Describe how to reproduce the bug

1. Open "Relationsbanken"
2. Click on menu => pension => "Forventede udbetalinger"
3. See that there is no tooltip on the selected bar displaying the value
4. Click on another bar to see that it is also missing the tooltip

## Which Kirby version was used?
5.0.5 to 5.0.15.
5.0.4 is working

## What was the expected behavior?
A tooltip with a value should be shown on the selected bar

## Please complete the following information:
- OS: Windows, Android, iOS
- Browser: Chrome
- Browser version: all

## Are there any additional context?

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/master/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [master branch](https://github.com/kirbydesign/designsystem/tree/master) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by MadsBuchmann** [comment]
@SilverGull - would you mind sharing the necessary code changes? It would be much appreciated 😄

**Comment by MadsBuchmann** [comment]
@SilverGull - was a bit curious why it caused you problems; i've discovered why it broke!

In 218a462 the following default for all chart types is set: 
```typescript 
...
  tooltip: {
      enabled: false,
    },
...
```

Which means all tooltips are disabled by default - unless it is enabled either in the individual chart type configs (which can not be customized by consumers of Kirby) or via `customOptions` as you're doing.
