### ISSUE TITLE
[Enhancement] Card background color

### ISSUE THREAD

**Issue by jonasjensen-brolstark** [kirbydesign/designsystem#205]
**Is your enhancement request related to a problem? Please describe.**
I can on web style the background color of the card. But this is not possible on native.

**Describe the solution you'd like**
I want to be able to set the background color of a card so i can make it look like: 

![image](https://user-images.githubusercontent.com/46445487/55622860-a7ea1d80-57a1-11e9-96e9-d469601c8246.png)

**Describe alternatives you've considered**

One way it could be done, is like it is done on `kirby-icon`.
A card would then have a `colorType` attribute like:

```html
<kirby-card ... colorType="NAME_OF_COLOR">
...
</kirby-card>
```

```typescript
export class CardComponent {
...
  @Input() colortype: 'primary' | 'secondary' | 'tertiary' | 'alert' | 'success' | 'danger';
...
}
```

**Comment by bommariusser** [comment]
@jonasjensen-brolstark i like!
