### ISSUE TITLE
👣  [Tracking] Removal of older deprecations in Kirby v6

### ISSUE THREAD

**Issue by RasmusKjeldgaard** [kirbydesign/designsystem#2061]
We have a lot of older deprecations (more than a year and several major versions old) that could be removed to clean up the code base before the next major release, Kirby v.6.

- [x] #2062
- [x] #2063
- [x] #2060 
- [x] #2064
- [x] #2065
- [ ] #1578 
- [x] #2066
- [x] #2068 

Up for consideration:
- [ ] https://github.com/kirbydesign/designsystem/issues/1979 (only 10 months old, but released in v. 1.5.7)

**Comment by MadsBuchmann** [comment]
I've added #2068 to the list. Also i think we should update the deprecation warnings in the next minor version to tell people that the features referred to in the list will be deprecated in v6 specifically.
