### ISSUE TITLE
[Housekeeping] General solution for testing interaction states

### ISSUE THREAD

**Issue by RasmusKjeldgaard** [kirbydesign/designsystem#2072]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the housekeeping request
The [hover](https://github.com/kirbydesign/designsystem/issues/2008) and [focus](https://github.com/kirbydesign/designsystem/issues/1863) interaction states should be covered by tests.

A general solution for testing both of these (and the upcoming active state) would be awesome, as it would be much easier to maintain a single solution for all the interaction states. 

The solution could possibly be a custom matcher, that makes it easy to expect a certain state/set of styles for a component. 
This could then be used across all relevant components.

## Have you considered any alternatives?
We could consider to test the mixins themselves instead of test the correctly applied style on each component.

**Comment by MadsBuchmann** [comment]
I've created an issue for the visual testing part of this: https://github.com/kirbydesign/designsystem/issues/2168

**Comment by MadsBuchmann** [comment]
Please refer to #2168 instead.
