### ISSUE TITLE
Introduce `danger-background` design token

### ISSUE THREAD

**Issue by MadsBuchmann** [kirbydesign/designsystem#2079]
## Context
With #2041 we begin experimenting with introducing design tokens following a naming convention (see [the write up on the issue](https://github.com/kirbydesign/designsystem/issues/2041#issuecomment-1055502831) for more info).

## Task
#2041 will introduce the new design token `danger-background-weak` which uses the color `red-30` and apply it to the flag component. 

The current danger color (`red-50`) stored in the `notification-colors` map (file: `.../themes/_colors.scss`) should be replaced with a `danger-background` token and that token should be used in place of the current `notification-colors.danger` token. 

The structure should be something along the lines of: 

```scss
$red-50: #ff595e;
$danger-background: $red-50; 
```

Note that the `$red-50` variable does not exist yet and also has to be introduced. 

How we arrange this in regards to file structure etc. is still up in the air. I think #2041 should lay the ground work for that tho. 

## Next steps 
After having solved this issue and #2041 i think we should arrange a new meeting - using what we've learned to discuss how we could potentially tackle a full revamp of our design tokens.

**Comment by RasmusKjeldgaard** [comment]
Just dropping this article here if we at some point want some inspiration for our naming strategy for design tokens: https://bradfrost.com/blog/link/the-practical-guide-to-naming-design-tokens-ux-collective/

Disclaimer, I have not read it. So I do not know how it compares to our naming convention.

**Comment by MadsBuchmann** [comment]
@RasmusKjeldgaard - i've also gathered some resources on the tracking issue: https://github.com/kirbydesign/designsystem/issues/2106

**Comment by jkaltoft** [comment]
# Notes from estimation

Needs shaping.

We should talk about structure and next steps. Introducing danger-background doesn't add value in itself.

**Comment by MadsBuchmann** [comment]
@jkaltoft didn't we agree on the approach outlined in the issue description? Also a list of general unknowns has been outlined in the tracking issue here:https://github.com/kirbydesign/designsystem/issues/2106
