### ISSUE TITLE
[Documentation] Styleguide / best practices 

### ISSUE THREAD

**Issue by hafstad** [kirbydesign/designsystem#211]
**Is your enhancement request related to a problem? Please describe.**
We need a place to have an overview of our best practices, styles guide, gotchas and examples doing a shared code project (web/native).

**Describe the solution you'd like**
Add a section called "styleguide" in the cookbook which documents, and share our knowledge.

**Describe alternatives you've considered**
A separate repo under the kirby org.

**Comment by hafstad** [comment]
- [ ] reference.ts (turn off indexing)
- [ ] Inheritance or delegation – when to use can find the cause contra if(ios)… ?
- [ ] Specific iOS or Android - tns.android.ts / tns.ios.ts
- [ ] Using native modules/plugins
- [ ] Generic NativeScript encapsulation good practice
- [ ] NativeScript pure vs. Angular
- [ ] Angular vs. NativeScript Angular
- [ ] No error schema - what and why?
- [ ] NativeScript plugins
- [ ] Pure wrapped by to angular
- [ ] 70% code sharing, process
- [ ] TNS only component
- [ ] Debugging tips / tricks

**Comment by jakobe** [comment]
Will be fixed by #1393

**Comment by MadsBuchmann** [comment]
@jakobe: I'm not sure I agree. The points being requested by @hafstad is not part of the current outline for the contribution guidelines. The contribution guidelines in their current form mainly focus on how to contribute properly. 

But does not specify how to write actual code and technical preferences. 

If we want what @hafstad requests to be incorporated in Kirby - we could do it either as: 
- part of the contribution guidlines 
- a separate and more technical styleguide

**Comment by MadsBuchmann** [comment]
Reopening issue. 
Reason: https://github.com/kirbydesign/designsystem/issues/211#issuecomment-823218223

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
