### ISSUE TITLE
[BUG] Calendar goes back 1 day when selecting a date in the last week of the month after daylight saving time if "USE UTC instead of local time is checked.

### ISSUE THREAD

**Issue by KristianAM** [kirbydesign/designsystem#2114]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
When selecting a date in the kirby calendar after daylight saving time - the chosen date is pushed back 1 day.  
It only happens if the chosen date is in the same month as the shift to daylight saving time.

## Describe how to reproduce the bug

1. Go to https://cookbook.kirby.design/#/home/showcase/calendar 
2. Click on "Use UTC instead of local time"
3. Click on 2022-03-30
4. See error -->below the calendar, the text: "Selected Date: Mar 29, 2022 GMT+0" is displayed

## Which Kirby version was used?
Whatever version the cookbook is using

## What was the expected behavior?
I expect the date selected to be the same as the one I pressed :)

## Add any screenshots
![image](https://user-images.githubusercontent.com/14964549/158808829-ae7e13cf-f5df-47b5-b687-18969e6997f2.png)

## Please complete the following information:
- OS: [e.g. Windows, MacOS, iOS] Windows
- Browser [e.g. Chrome, Safari] Chrome 
- Browser version [e.g. 22] Version 98.0.4758.102 (Officiel version) (64-bit)

## Are there any additional context?

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/stable/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/stable/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/stable/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [stable branch](https://github.com/kirbydesign/designsystem/tree/stable) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by KristianAM** [comment]
The cause of the issue seem to be the time of day that the calendar sets.  
When picking 2022-03-25 the selected timestamp is 2022-03-25:00:00:00   
But for some reason, after daylight saving time the selected timestamp is 1 hour earlier:  
2022-03-30 picked on the calendar turns into:  
2022-03-29:23:00:00

**Comment by KristianAM** [comment]
Hey,  
Thank you for your reply!  
The issue seems to only be present when the option:  
 [timezone]="'UTC'"  
 is set.  
 
 The issue is in production right now - we use it in our component for account transfers:  
 https://github.com/Bankdata/relationsbank/blob/master/libs/micro/payment/feature/src/lib/transfer-and-pay-bill/transfer/components/select-date/select-date.component.html

**Comment by RasmusKjeldgaard** [comment]
I still think this could maybe be a problem with how the selected date is processed on your end afterwards.
For example, if I display the selected day in the cookbook using format from `date-fns-tz` like [here](https://github.com/kirbydesign/designsystem/pull/2115/files#diff-77f93fdcddccaaddca8fac01ead976681f5ea61648e91f516e98a4b9c9d2cd91R56-R58), I see the correct date selected. 
I made a quick deploy for you to see here: 
https://cookbook.kirby.design/branch/kby-2114-calendar-utc-time-offset/#/home/showcase/calendar

**Comment by jkaltoft** [comment]
I'm not completely sure, but the function `subtractTimezoneOffset()` 

https://github.com/kirbydesign/designsystem/blob/37e94b06b213e2b6c2d8d3585574fe0344f324fb/libs/designsystem/src/lib/components/calendar/calendar.component.ts#L496-L499

could be a problem. Why do we subtract a timezone offset? Shouldn't the date library handle such things?

If we replace this line:

https://github.com/kirbydesign/designsystem/blob/37e94b06b213e2b6c2d8d3585574fe0344f324fb/libs/designsystem/src/lib/components/calendar/calendar.component.ts#L411

with

```
newDate = zonedTimeToUtc(newDate, this.timeZoneName);
```

the problem appears to be fixed.

Disclaimer: I'm not sure why, and I'm not completely sure that it _does_ fix the bug 😎

**Comment by jkaltoft** [comment]
I suggest we create one or more unit tests for Daylight Saving Time stuff. If we had had such tests maybe we could've caught this bug when we switched from Moment.js to date-fns last year.

**Comment by jkaltoft** [comment]
> I suggest we create one or more unit tests for Daylight Saving Time stuff. If we had had such tests maybe we could've caught this bug when we switched from Moment.js to date-fns last year.

I've created a housekeeping issue for adding unit tests: #2120
