### ISSUE TITLE
[BUG] Kirby list items gets extensive padding in webkit

### ISSUE THREAD

**Issue by troelslenda** [kirbydesign/designsystem#2117]
- [ ] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
When using kirby-items within modals they get extensive padding in webkit and IOS.

## Describe how to reproduce the bug

1. Install 5.1.1 or higher of designsystem.
2. Navigate to a security-details page
3. kirby-item that resides within a modal/is not part of a kirby-page (not entirely sure what's the cause)
4. Compare the page in Chrome and safari

## Which Kirby version was used?
5.1.1 and higher

## What was the expected behavior?

That the kirby-item renders alike across platforms.

## Add any screenshots

<img width="1334" alt="Screenshot 2022-03-18 at 11 25 07" src="https://user-images.githubusercontent.com/263060/158986538-af8c9ed6-05bd-4e53-a2a8-b7f2bf7b17b3.png">
<img width="1392" alt="Screenshot 2022-03-18 at 11 25 55" src="https://user-images.githubusercontent.com/263060/158986542-461a927a-a690-47de-80f1-93177cde880c.png">

## Please complete the following information:
- OS: MacOS and iOS
- Browser: Safari
- Browser version: Version 15.1 (17612.2.9.1.20)

## Are there any additional context?

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/stable/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/stable/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/stable/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [stable branch](https://github.com/kirbydesign/designsystem/tree/stable) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by RasmusKjeldgaard** [comment]
Can confirm this bug is introduced in 5.1.1, [right here.](https://github.com/kirbydesign/designsystem/pull/2029/files#diff-47a4f9a6346abfbf0d4e08bccd42083ab3cf87d2871dc195a50fcd143ecf2c0bR10-R11)

I think it is because Safari handles these differently from other browsers, when `--item-padding-top/bottom` is not set. 
This might be fixed by providing a default value here, like `--padding-top: var(--item-padding-top, 8px);`

**Comment by troelslenda** [comment]
🔥
