### ISSUE TITLE
[Enhancement] Add "backButtonClick" event to page

### ISSUE THREAD

**Issue by MadsBuchmann** [kirbydesign/designsystem#2119]
- [X] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the enhancement
In some cases we want to be able to override the behaviour of the back button in the `kirby-page` element. 

For example when using a micro frontend (MF). A MF is composed of several frontend applications each having their own local router. Here the back button needs to navigate to a page outside of the router using functions exposed by some MF framework. 

Our current `kirby-page` can not facilitate this at the moment. The closest we come is the `defaultBackHref` input property. But this only allows for routes within the local router. 

## Describe the solution you'd like
@NikolajSkousen and i had a meeting the 18th of March 2022 where we came up with the following solution: 
 
- A `backButtonClick` event should be added to the `kirby-page` element
- When a value is set for `backButtonClick` the default back behaviour of the back button should be disabled
    - This should be done by overwriting the `onClick` event of the `ion-back-button`. This is marked as internal by the ionic type declarations. But `onClick` is a standard html attribute and therefore we can assume it will not be removed. It is merely the attribute used by ionic to handle clicks and provide default behaviour; allowing us to overwrite it to disable that behaviour.  

### Other implementation notes
Providing a value for `backButtonClick` should not alter the default display logic. If one wish to override the default the `hideBackButton` input property should be used instead.

**Comment by NikolajSkousen** [comment]
👍
