### ISSUE TITLE
[Research] Visual testing for interaction states & possible general testing

### ISSUE THREAD

**Issue by MadsBuchmann** [kirbydesign/designsystem#2168]
- [X] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the housekeeping request
In order to test the styles made as part of the [interaction states milestone](https://github.com/kirbydesign/designsystem/milestone/29) we're going to need visual testing. 

This was decided when discussing #2072 as we want to test the outcome of applying the styles. Not the implementation details - which would be testing the mixins we're using. Testing the outcome of styles is currently done by using the matcher `expect(something).toHaveComputedStyle(styleDict)` - but this relies on the assumption: 
> If the subset of styles in `styleDict` is correct it looks as expected 

But there might be other styles not represented in `styleDict` that affects the visual outcome when rendering the component. This we will be able to catch with visual testing. 

A couple of things to consider: 
- Should we use chromatic with storybook? (see: #1829)
- Should we use jest snapshot testing? 
- Could cypress also be a possibility? 
- Which one has best support for testing interaction states i.e: how do we force the interaction states for each of the tools?

**Comment by RasmusKjeldgaard** [comment]
Research done ✅ We now have visual testing, and should implement the interaction state tests there.
