### ISSUE TITLE
[BUG] Kirby-icon in kirby-badge is misaligned when added to a kirby-button with text 

### ISSUE THREAD

**Issue by TheOlinone** [kirbydesign/designsystem#2172]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
When nesting a `kirby-badge` with a `kirby-icon` inside of a `kirby-button` the icon is misaligned when the button also has text.

## Describe how to reproduce the bug
Add a `kirby-badge` with a `kirby-icon` to a `kirby-button`

```
<kirby-page title="Simple page">
  <kirby-page-content>

    <!--Works as intended-->
    <kirby-badge><kirby-icon name="attach"></kirby-icon></kirby-badge>

    <!--Works as intended-->
    <button kirby-button>
      <kirby-badge><kirby-icon name="attach"></kirby-icon></kirby-badge>
    </button>

    <!--Icon is misaligned-->
    <button kirby-button>
      Button text <kirby-badge><kirby-icon name="attach"></kirby-icon></kirby-badge>
    </button>

  </kirby-page-content>
</kirby-page>
```

## Which Kirby version was used?
5.0.18

## What was the expected behavior?
The expected behavior is that the `kirby-icon` remains aligned inside the `kirby-badge` when used in a `kirby-button`.

## Add any screenshots
![Screenshot 2022-04-20 at 11 58 13](https://user-images.githubusercontent.com/83649639/164203642-a7232082-057b-426b-8673-8b5ccf8e9dde.png)

## Please complete the following information:
- OS: Windows, Mac, Android
- Browser Chrome
- Browser version 99

## Are there any additional context?
As shown in the screenshot above, the `kirby-icon` is only misaligned when added to a `kirby-button` which also contains text. When the `kirby-button` only contains the `kirby-badge` the icon is aligned correctly.

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/stable/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/stable/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/stable/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [stable branch](https://github.com/kirbydesign/designsystem/tree/stable) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by MadsBuchmann** [comment]
I can verify this bug! Thank you for a well written issue and an easy to replicate snippet @TheOlinone!

**Comment by henrikvoetmand** [comment]
Hi @TheOlinone If I understand the issue, you are trying to put a badge with icon inside a button. This is not the right way to use badges. Can you show or describe the UX scenario?

**Comment by TheOlinone** [comment]
@henrikvoetmand That is exactly what I am doing :) 
We are using badges inside buttons to show the status of the view that the button represents.
![image](https://user-images.githubusercontent.com/83649639/164612904-ca00172a-0020-4011-bd30-89292410f56b.png)

I can also provide a link to the specific zeplin resource if that is more helpful?

**Comment by henrikvoetmand** [comment]
@TheOlinone Yes a Zeplin resource would be great :-)
Who is your UX'er on this?

**Comment by TheOlinone** [comment]
@henrikvoetmand 
Our UX'er is Ulrik Boisen (UBO)
Zeplin: https://app.zeplin.io/project/607447fb8e59c63b234e6f85/screen/625fbc7ff00dbe1789aa7033

**Comment by henrikvoetmand** [comment]
@TheOlinone

I have talked with Ulrik and he agree - this is not the way to use badges.

We will close this bug issue.
