### ISSUE TITLE
[COMPONENT] Local navigation bar

### ISSUE THREAD

**Issue by henrikvoetmand** [kirbydesign/designsystem#2186]
- [ ] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the solution you'd like
This issue is for Pre tech-refinement of a new component that we should evaluate.

I will call in for a short presentation...

## Are there any additional context?
<img width="375" alt="Skærmbillede 2022-04-26 kl  14 36 19" src="https://user-images.githubusercontent.com/71710012/165301957-7e707b7c-e55e-4bc5-8c33-974a3588bb46.png">
<img width="375" alt="Skærmbillede 2022-04-26 kl  14 37 07" src="https://user-images.githubusercontent.com/71710012/165302008-baabb2b0-6816-4030-9e82-45900b625c8d.png">
<img width="1440" alt="Skærmbillede 2022-04-26 kl  14 39 02" src="https://user-images.githubusercontent.com/71710012/165302031-39db5411-2f54-40aa-8851-965211be5d10.png">
<img width="1440" alt="Skærmbillede 2022-04-26 kl  14 39 24" src="https://user-images.githubusercontent.com/71710012/165302050-4b6532e4-eb73-426d-8f3a-d2adc9f368b1.png">

https://material.io/components/tabs#usage

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/stable/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Refinement

- [ ] Request that the issue is [UX refined](https://github.com/kirbydesign/designsystem/blob/stable/.github/CONTRIBUTING.md/#ux-refinement); do not proceed until this is done.
- [ ] Request that the issue is [tech refined](https://github.com/kirbydesign/designsystem/blob/stable/.github/CONTRIBUTING.md/#tech-refinement); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/stable/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [stable branch](https://github.com/kirbydesign/designsystem/tree/stable) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Publish a WIP implementation to Github as a draft PR and ask for feedback. 
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Update the [cookbook](https://cookbook.kirby.design) with examples and showcases.

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request. If you created a draft PR during implementation you can just mark that as "ready for review".

**Comment by alxzak** [comment]
This issue should be prioritized for development during sprint 10.

**Comment by RasmusKjeldgaard** [comment]
# Early Tech Refinement
This components functionality seems similar to the existing [kirby-tab-bar](https://cookbook.kirby.design/#/home/showcase/tabs) component, but the styling differs quite a lot. Based on this, one of the major tasks of our initial research is to determine if local navigation should: 
1. be its own component
2. be baked into the Tabs component somehow
3. utilise shared functionality and/or sub-components between tabs and local navigation components where possible.

## Identified Requirements
1. Consumers should be able to create a local navigation bar (tab bar?) with a set of buttons, ideally declaratively like so: 
```
<kirby-local-navigation>
    <kirby-local-navigation-button>
        Home
    </kirby-local-navigation-button>
    <kirby-local-navigation-button>
        Inbox
    </kirby-local-navigation-button>
    <kirby-local-navigation-button>
        Messages
    </kirby-local-navigation-button>
</kirby-local-navigation>
```
2. Consumers should have a way to register a component or route to be shown when a local navigation button is pressed. 
3. Visually, the local navigation should fill out the whole width of its container, and become scrollable when more buttons are present outside the view. The actual scroll behavior should be determined - see question below.

## Further Questions
- [ ] Is local navigation the correct name for this component?
- [ ] Understand the current functionality of tab bar. Why is it implemented with a router outlet inside the component? Is it possible to hand over control to consumer apps, that could themselves put a router outlet in the template?
- [ ] How should the scrolling work? We talked about the tab bar scrolling itself along on click on the rightmost buttons - but should it also be scrollable itself? 
- [ ] How to handle routing - ideally this should not be baked into the component in a similar way as the Tabs component. Can we instead make it possible for consumers to register 

# Initial solution sketching
One approach we discussed is to separate the existing tabs components into more distinct sub-components with a better defined responsibility, with a DOM-structure like this:
```
<kirby-tabs>
    <kirby-tab-bar>
        <kirby-tab-button>
            Home
        </kirby-tab-button>
    </kirby-tab-bar>
</kirby-tabs>
```
This way, the `<kirby-tabs>` component could support the current behavior of wrapping a router outlet and showing different routes inside the component itself, while the tab-bar becomes its own component only concerned with layout and grouping of the nested buttons.

**Comment by RasmusKjeldgaard** [comment]
https://carbondesignsystem.com/components/tabs/usage/
https://material.io/components/tabs

Two good examples of what we want.
