### ISSUE TITLE
[BUG] Modal tab issues

### ISSUE THREAD

**Issue by jb-trm** [kirbydesign/designsystem#221]
**Describe the bug**
1. The modal should take focus when its opened - in the cookbook the button that opens the modal keeps the focus and you can then scroll in the background.
2. Should be able to tab to the close button (X) - currently it only tabs through the two buttons.
3. When first tabbing it scrolls the background to the bottom (Might be related with no. 1)

**To Reproduce**
1. Go to https://cookbook.kirby.design/home/showcase/modal
2. Click open modal
3. Scroll with mouse - it scrolls in the background
4. Press tab and it scrolls the background to the bottom

**Kirby version**
 - v0.0.120

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version Newest

**Comment by mmmtrifork** [comment]
In addition to your discoveries, I found out that the link to the modal-showcase readme is not working in the cookbook. It should be changed to: https://github.com/kirbydesign/designsystem/tree/master/src/app/showcase/modal-showcase

**Comment by mmmtrifork** [comment]
I think it might be a good idea to move the title and the close button to the embedded component, allowing users to decide whether they want to have a title and a close button at all. I will discuss this with Jakob
