### ISSUE TITLE
[Enhancement] Change background color on focus inside accordion, list, action sheet and dropdown

### ISSUE THREAD

**Issue by RasmusKjeldgaard** [kirbydesign/designsystem#2236]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the enhancement
The current solution for focus with a blue outline around elements is not suitable for some of our elements:
- List items 
- Accordion items
- Buttons in action sheet 
- Buttons inside an opened dropdown

Instead we want to change the background of these to be similar to active state for the time being.

A small refactor of dropdown is possibly needed here as the current focus-behavior is not exactly as we want it. Right now, when using the arrow keys the elements are selected. They should instead have focus state when browsed with arrow keys, and only be selected (bold text and checkmark) when enter or space is pressed. 

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/stable/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Refinement

- [ ] Request that the issue is [UX refined](https://github.com/kirbydesign/designsystem/blob/stable/.github/CONTRIBUTING.md/#ux-refinement); do not proceed until this is done.
- [ ] Request that the issue is [tech refined](https://github.com/kirbydesign/designsystem/blob/stable/.github/CONTRIBUTING.md/#tech-refinement); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/stable/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [stable branch](https://github.com/kirbydesign/designsystem/tree/stable) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Publish a WIP implementation to Github as a draft PR and ask for feedback. 
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Update the [cookbook](https://cookbook.kirby.design) with examples and showcases.

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request. If you created a draft PR during implementation you can just mark that as "ready for review".

**Comment by jkaltoft** [comment]
I think the background change should to be similar to _hover_ state instead of _active_ state. Active state background color change should be applied when "activating" or "submitting" with `ENTER` and/or `SPACE` key.

**Comment by jkaltoft** [comment]
If possible we should include focus on tabs in "desktop view", see https://github.com/kirbydesign/designsystem/issues/2244#issuecomment-1140858450

**Comment by jkaltoft** [comment]
The Dropdown parts should be solved by https://github.com/kirbydesign/designsystem/issues/2342. Skipping those in this issue.
