### ISSUE TITLE
[Placeholder] Fix interaction state issues discovered during UX review

### ISSUE THREAD

**Issue by jkaltoft** [kirbydesign/designsystem#2256]
## Must solve

- [x] #2083 
- [x] #2243 
- [ ] #2241
- [x] #2242

## Should solve

- [ ] #2248 
- [ ] #2257
- [ ] #2258
- [ ] #2260
- [ ] #2265
- [ ] #2261
- [ ] #2246
- [ ] #2247
- [ ] #2266
- [x] ~~#2251~~

## Needs UX first

We should also consider if these issues should be addressed in the first place.

- [ ] #2244
- [x] ~~#2259~~
- [x] ~~#2262~~

**Comment by RasmusKjeldgaard** [comment]
Closing this as we have prioritised the issues and they are added to a milestone.
