### ISSUE TITLE
[BUG] Segmented Control is missing transition

### ISSUE THREAD

**Issue by jkaltoft** [kirbydesign/designsystem#2260]
...when navigating/selecting with keyboard (`SPACE`, `ENTER`) - press when control has focus.

Transition should be identical to when using mouse click.

## Screen recordings

First navigate using keyboard, then select using mouse:

https://user-images.githubusercontent.com/150451/168806280-b4de8044-3d69-491e-85ba-c0463c70041e.mov

https://user-images.githubusercontent.com/150451/168807262-c0214c1c-b464-4531-9a27-e5de8fea667a.mov

**Comment by jkaltoft** [comment]
## Pre-tech refinement

https://forum.ionicframework.com/t/how-to-manually-trigger-ion-segment-animation/220089 states mentions a similar request and it doesn't seem to be possible. 

It may be worth a shot to try to trigger a click event manually from the keydown event handler. It probably won't be pretty...

**Comment by RasmusKjeldgaard** [comment]
This will be fixed by moving to Ionic 6, including nice keyboard interactions! 
A small preview here: 
https://user-images.githubusercontent.com/42470636/170267154-c990971b-7ba1-442b-8b5c-b857d9f3d08a.mov
