### ISSUE TITLE
[Enhancement] Micro frontend with title, footer and progress within Kirby Modal

### ISSUE THREAD

**Issue by roa-jyskebank-dk** [kirbydesign/designsystem#2267]
## Describe the enhancement
I would like for a micro frontend (custom element) to be displayed as a full-page modal element with title, footer and progress. 

## Describe the solution you'd like
Either by 1) The title, footer and progress elements being recognized inside the custom element DOM and placed correctly in the modal, or by a "shell" flavor of the modal, allowing us to control all the space within the modal frame, i.e. "stretching" the custom element.

## Are there any additional context?
<img width="443" alt="Screenshot 2022-05-11 at 12 50 30" src="https://user-images.githubusercontent.com/53940402/168082011-f292a4ca-6956-4dd6-992e-c92055299d44.png">
<img width="763" alt="Screenshot 2022-05-11 at 12 48 17" src="https://user-images.githubusercontent.com/53940402/168082018-d637f472-4e01-4361-b8ec-9081b6ba4dc0.png">

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/stable/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Refinement

- [ ] Request that the issue is [UX refined](https://github.com/kirbydesign/designsystem/blob/stable/.github/CONTRIBUTING.md/#ux-refinement); do not proceed until this is done.
- [ ] Request that the issue is [tech refined](https://github.com/kirbydesign/designsystem/blob/stable/.github/CONTRIBUTING.md/#tech-refinement); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/stable/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [stable branch](https://github.com/kirbydesign/designsystem/tree/stable) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Publish a WIP implementation to Github as a draft PR and ask for feedback. 
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Update the [cookbook](https://cookbook.kirby.design) with examples and showcases.

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request. If you created a draft PR during implementation you can just mark that as "ready for review".

**Comment by andershessellund** [comment]
Vi åbner re1-mf-purpose-and-extent micro frontenden i en modal: https://github.com/Bankdata/re1-mf-purpose-and-extent . Vi åbner modal'en ved at kalde et API som micro frontenden udstiller. 

Der er nogle bugs i kirby der forhindrer at header og footer placeres korrekt i DOM'en i visse tilfælde. Hvis du løber ind i dem kan du se workarounds til denne problematik her:

https://github.com/Bankdata/relationsbank-sdk/blob/master/libs/dynamic-form/src/lib/page-elements/modal-heading/modal-heading.component.ts

https://github.com/Bankdata/relationsbank-sdk/blob/master/libs/dynamic-form/src/lib/page-elements/wizard-footer/wizard-footer.component.ts

**Comment by MadsBuchmann** [comment]
Just an addition to what @andershessellund is writing - we're currently working on a fix for the modal DOM problems: 
https://github.com/kirbydesign/designsystem/pull/2238 

We're however being quite careful and moving a slowly as the modal is a complex and widely used component. 

This fix might however not work if the modal wrapper is part of the host application and the MF is opened as a component in the modal - the solution is dependent on the DI hierachy which i do not believe are shared between the host and embedded application.

**Comment by RasmusKjeldgaard** [comment]
With #2238 the known workarounds mentioned by @andershessellund could be removed, so I am closing this one. 
@roa-jyskebank-dk if the problem persists, please let us know.
