### ISSUE TITLE
[Enhancement] List - Item background color

### ISSUE THREAD

**Issue by jonasjensen-brolstark** [kirbydesign/designsystem#227]
**Describe the solution you'd like**

I would like to be able to determine the background color of single items in the list.

![image](https://user-images.githubusercontent.com/46445487/56948789-7b6fba00-6b31-11e9-8c5a-1698f157e435.png)

Right now, both the `KirbyListCell` and `KirbyListItem` elements are wrapped in an element that contains the background. So i am not able as user of the Kirby list to controll the background color of my items.

**Describe alternatives you've considered**
##### Option 1

One way of doing this would be to have a callback to return the wanted color for a single item:

```typescript
export class ListComponent implements OnInit {
...
@Input() getItemColor?: (item: any) => 'primary' | 'secondary' | 'tertiary' | 'warning' | 'success' | 'danger';
...
}
```

But I think this option is only a quick fix and will start to clutter up the lists interface.

##### Option 2

An other way is to use the already existing `KirbyListItem` construct and then do like on `KirbyIcon` and `KirbyBadge`:

```html
<kirby-list-item 
    *kirbyListItem="let item" 
    [colortype]="item.isInTheDangeZone ? 'success' : 'danger'" >
...
</kirby-list-item>
```

The same could be done for `KirbyListCell``

```html
<kirby-list-cell 
    *kirbyListCcell="let item" 
    [colortype]="item.isInTheDangeZone ? 'success' : 'danger'" >
...
</kirby-list-cell>
```

**Comment by SilverGull** [comment]
We have similar problem for the entire list as well: https://github.com/kirbydesign/designsystem/issues/154. The solution for these issues should properly be alike.
