### ISSUE TITLE
[Enhancement] List - List Item on selection

### ISSUE THREAD

**Issue by azeemchauhan** [kirbydesign/designsystem#228]
**Is your enhancement request related to a problem? Please describe.**
 This enhancement related to list, when I **tap** on list item there is not gesture/interaction with list item
open kirby list in iOS & Android and **tap** of any list item
 https://cookbook.kirby.design/home/showcase/list

**Describe the solution you'd like**
When I click on **list item** there should be some tappable action on tapped list item or some visual effect or something else that indicate that list item has been pressed.

**Additional context**
<img width="238" alt="Screenshot 2019-04-30 at 3 13 06 PM" src="https://user-images.githubusercontent.com/33758493/56953749-df5aa880-6b5a-11e9-8673-8211d5aaf64e.png">

**Comment by jonasjensen-brolstark** [comment]
@azeemchauhan Firstly you my have to add a headline to this issue, just so it is easier to spot in the issue list 😄 

Secondly what do you mean with 

> When I click on list item there should be some gesture/interaction on tapped element/item.

Do you think that there should be some visual feedback, like and animation, color change and so on?

**Comment by azeemchauhan** [comment]
> @azeemchauhan Firstly you my have to add a headline to this issue, just so it is easier to spot in the issue list 😄
> 
> Secondly what do you mean with
> 
> > When I click on list item there should be some gesture/interaction on tapped element/item.
> 
> Do you think that there should be some visual feedback, like an animation, color change and so on?

**Comment by azeemchauhan** [comment]
> > @azeemchauhan Firstly you my have to add a headline to this issue, just so it is easier to spot in the issue list 😄
> > Secondly what do you mean with
> > > When I click on list item there should be some gesture/interaction on tapped element/item.
> > 
> > 
> > Do you think that there should be some visual feedback, like an animation, color change and so on?
>> @jonasjensen-brolstark - Ohh I missed headline 😄😄

**Comment by jonasjensen-brolstark** [comment]
> > > @azeemchauhan Firstly you my have to add a headline to this issue, just so it is easier to spot in the issue list 😄
> > > Secondly what do you mean with
> > > > When I click on list item there should be some gesture/interaction on tapped element/item.
> > > 
> > > 
> > > Do you think that there should be some visual feedback, like an animation, color change and so on?
> > > @jonasjensen-brolstark - Ohh I missed headline 😄😄
> > > I have updated the description of issue, i think it is more clear now

Cool, i think we will have to have UX into the disquisition if it is only visual feedback.

**Comment by labanos** [comment]
Duplicated by #549
