### ISSUE TITLE
[BUG] Modal rendered to large on Android

### ISSUE THREAD

**Issue by ckibsen** [kirbydesign/designsystem#231]
**Describe the bug**

On Android, modal dialog stretches all the way to the status bar at the top, and below the "button bar" at the bottom (see attached comparison with iOS).

![ModalLayoutErr](https://user-images.githubusercontent.com/832287/57008852-4f1c7200-6bf3-11e9-852f-0e59d8130acb.png)

**To Reproduce**
Open a modal with layout as shown in attached screenshot.

**Kirby version**
 - [e.g. 0.0.122]

**Expected behavior**
Content should be rendered within visible boundaries, and leave room for spacing above modal dialog.

**Screenshots**
Attached.

**Desktop (please complete the following information):**
 - OS: Android (sample provided is Pixel_XL_API_28)

**Native (please complete the following information):**
 - Device: Pixel_XL_API_28
 - OS: Android 9

**Comment by jakobe** [comment]
Fixed by #323
