### ISSUE TITLE
[BUG] UsePopover iOS

### ISSUE THREAD

**Issue by RasmusTraeholt** [kirbydesign/designsystem#2317]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
UsePopover is not working correctly on iOS. 
When selecting an element in a dropdown (with usePopover="true") on iOS, the dropdown just closes without selecting or emitting the selected element.

It works fine when used on a calendar component though

## Which Kirby version was used?
5.4.1

## Please complete the following information:
- OS: [iOS]

## Are there any additional context?

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/main/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by RasmusTraeholt** [comment]
It could be related. It does not explain why it only breaks on iOS devices though.

**Comment by RasmusKjeldgaard** [comment]
> It could be related. It does not explain why it only breaks on iOS devices though.

You are right, we are still trying to figure out what is going on with that. One thing @mictro figured out is that it is happening in Safari as a whole, so not only iOS.
