### ISSUE TITLE
[Enhancement] Responsive toolbar / header 

### ISSUE THREAD

**Issue by alxzak** [kirbydesign/designsystem#2325]
Som bruger af netbank (privat/erhverv)
Ønsker jeg, at action-knapper i toolbar er tilgængeligt tæt på indholdet på siden
Så jeg nemt får overblik over de handlinger jeg kan tage i relation til det indhold jeg får vist.

![Image](https://user-images.githubusercontent.com/78357155/173295125-a362d170-ad56-4bcc-a00e-0d63f8b918e0.png)

**Comment by RasmusKjeldgaard** [comment]
# General Thoughts
A big part of this is to research if we ca pick the toolbar apart and remove some of the logic that has been baked into the component. Hopefully we should just provide the building blocks, and the responsivity and rearrangement functionality should come from the specific project. 

#To Do

**Comment by henrikvoetmand** [comment]
### Notes from design / tech pre refinement meeting (02.11.22)

Split this up in separate issues:

**Responsive button group**
Build a responsive button group with a number of buttons and a "more" button.
The user (code) defines a list of prioritized "actions" (labels and icons) used to populate the button group.
Depending on the available space - the button group component expands / collapses (displaying action buttons or list the remaining actions in a "more" menu. 

**Toolbar buttons**
Toolbar buttons can be either:

- Toolbar button group:
Display max. one action button and a "more" menu button (icon only) (from the list of prioritized actions) in the toolbar area.

- Custom buttons:
Open slot (one button with label and icon or one or two icon buttons.)  

For both cases:
On Mobile breakpoint: 

- Option to display allways or display on scroll. 

On tablet/desktop breakpoints:

- Display action buttons to the right of the title area and on scroll in the toolbar.

**Header content**
To be continued....

![Guidelines Copy](https://user-images.githubusercontent.com/71710012/199504970-656bbc51-10c9-42d7-95bf-bd34f20af54a.png)
