### ISSUE TITLE
[BUG] Scrolling/swiping in dropdown on native devices with pull to refresh

### ISSUE THREAD

**Issue by RasmusTraeholt** [kirbydesign/designsystem#2335]
- [ ] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
On native devices if a page has pull to refresh, sometimes pull to refresh is activated when swiping down in a dropdown popout list. Which can make it impossible to scroll/swipe down the list.

## Add any screenshots

https://user-images.githubusercontent.com/23026215/173568598-e29a73e6-303e-4e7b-a097-f20a53f1a432.mov

## Please complete the following information:
- OS: [iOS, Android]
- 
## Are there any additional context?

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [x] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/main/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by MadsBuchmann** [comment]
Is this with or without `usePopover` enabled?

**Comment by RasmusTraeholt** [comment]
Without. I was told the other issue #2317 would not be prioritized since it was an experimental feature. So i made this issue instead
