### ISSUE TITLE
NPM: Require two-factor authentication or automation tokens

### ISSUE THREAD

**Issue by jkaltoft** [kirbydesign/designsystem#2338]
We should require additional authentication to provide the proper level of security for our packages.

To allow publishing access we should select the option **Require two-factor authentication or automation tokens** in Settings for our packages ([Designsystem](https://www.npmjs.com/package/@kirbydesign/designsystem/access) and [Core](https://www.npmjs.com/package/@kirbydesign/core/access)).

We need to provide an automation token for our CI publish workflow. See https://docs.npmjs.com/creating-and-viewing-access-tokens 

More info here:

- https://docs.npmjs.com/configuring-two-factor-authentication
- https://docs.npmjs.com/integrations/integrating-npm-with-external-services

## Before

![Image](https://user-images.githubusercontent.com/150451/173783915-c586b601-b6ec-446c-89fe-25306a1a4b84.png)

## After

![Image](https://user-images.githubusercontent.com/150451/173783947-5770d0be-826b-4ac5-ba8d-091a51e601d9.png)

**Comment by mictro** [comment]
This issue is no longer relevant since CI automated publishing has been replaced by manual publishing.
Closed
