### ISSUE TITLE
Dropdown keyboard navigation selects an option

### ISSUE THREAD

**Issue by RasmusKjeldgaard** [kirbydesign/designsystem#2342]
It should just hover it and space/enter should select it.

**Comment by jkaltoft** [comment]
After implementing a working solution, the following issues have to be solved

- [x] Fix bug: Don't select previously focused (non-selected) Item when opening again
    - Open Dropdown using ENTER/SPACE
    - Select an item e.g. Item 1
    - Move focus using arrow keys, e.g. to Item 4
    - Close Dropdown using ESCAPE
    - Open Dropdown again using ENTER/SPACE
    - Item 4 is selected - That's a bug! It should still be latest selected Item, i.e. Item 1
- [x] When opening, move focus to selected index (if any)
- [ ] Fix failing tests
- [ ] Fix focus styles on mobile
- [ ] Fix Right Aligned eksample
- [ ] Fix using Home and End keys (they still select when they shouldn't)
- [ ] Inspect the *Event handler*-example (select on arrow up/down)
- [ ] CSS: How can Ionics custom properties best be utilized?
- [ ] Fix Pre-selected example (doesn't work properly) - could be an old defekt
- [ ] Consolidate solution

**Comment by jkaltoft** [comment]
I suggest we postpone this feature until `v7.1.0`. There seems to be a lot of things that sort of breaks and need fixing when rewriting the Dropdown component. Even though it is very related to `v7.0.0` interaction state features we should take the time to improve the Dropdown properly - without postponing the release of `v7.0.0`.
