### ISSUE TITLE
Adjust loudness scale for the selected segment item

### ISSUE THREAD

**Issue by RasmusKjeldgaard** [kirbydesign/designsystem#2345]

**Comment by jkaltoft** [comment]
I assume this issue is referring to this

**Before**

https://user-images.githubusercontent.com/150451/175008762-56ba3b38-fdbc-46cb-8029-4c0712a0e79a.mov

**After**

https://user-images.githubusercontent.com/150451/175008963-a3cc34c3-6bea-45b8-b909-3b2839188340.mov
