### ISSUE TITLE
Segmented control - Align keyboard interactions between the different modes

### ISSUE THREAD

**Issue by RasmusKjeldgaard** [kirbydesign/designsystem#2347]
The arrow key functionality for the default Segmented Control has been introduced by the Ionic 6 upgrade. Chip mode should use the same method as default mode (arrow keys once it has received focus).

**Comment by jkaltoft** [comment]
There seems to quite a lot more work in this than I first expected. I'm putting it on hold for the summer until we can collaborate on a solution.
