### ISSUE TITLE
[BUG] Badge on Segmented Control removes selected state

### ISSUE THREAD

**Issue by dennispedersen-bd** [kirbydesign/designsystem#2388]
- [ ] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
If there is a Badge on a segmented control it acts as some kind of extra segment that can be toggled when the user presses the badge. Tha badge itself should not be clickable.

## Describe how to reproduce the bug
When the user tabs og clicks the badge on the segmented control the selected state disapears.

1. Go to 'Inbox'
2. Click on 'Red badge'
3. See the selected stat on the segmented control dissapear.

## What was the expected behavior?
Nothing. The badge should not be clickable

## Add any screenshots

<img width="279" alt="Skærmbillede 2022-07-04 kl  09 41 24" src="https://user-images.githubusercontent.com/70525609/177106137-4747e2e2-9720-4275-8b8a-86e09bf74c62.png">

## Please complete the following information:
Both Web and mobile

## Are there any additional context?

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/main/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by RasmusKjeldgaard** [comment]
@dennispedersen-bd I have created a fix and deployed it to this test environment: https://cookbook.kirby.design/branch/kby-2388-badge-click-removes-focus/#/home/showcase/segmented-control

Could you please verify that it seems to solve your issue?

**Comment by dennispedersen-bd** [comment]
The branch is deleted so I cannot verify.



Fra: RasmusKjeldgaard ***@***.***>
Dato: torsdag, 4. august 2022 kl. 13.46
Til: kirbydesign/designsystem ***@***.***>
Cc: Dennis Pedersen ***@***.***>, Mention ***@***.***>
Emne: [EXTERNAL]: Re: [kirbydesign/designsystem] [BUG] Badge on Segmented Control removes selected state (Issue #2388)
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


Closed #2388<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkirbydesign%2Fdesignsystem%2Fissues%2F2388&data=05%7C01%7Cdpe%40bankdata.dk%7C1ab6893621af4e93b8bc08da760f021f%7C1177168698fc4f1b8e0076c52159e8a6%7C0%7C0%7C637952104087463277%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ZyGOMxa3FnfGTqmx5evxVYHbphKNMPl4yKWxXRHi3eY%3D&reserved=0> as completed via #2400<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkirbydesign%2Fdesignsystem%2Fpull%2F2400&data=05%7C01%7Cdpe%40bankdata.dk%7C1ab6893621af4e93b8bc08da760f021f%7C1177168698fc4f1b8e0076c52159e8a6%7C0%7C0%7C637952104087463277%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=l4rAskg5w3aDHQ9JUAnczpBq9ufsq%2FgMzGhakBap0kk%3D&reserved=0>.

**Comment by RasmusKjeldgaard** [comment]
> The branch is deleted so I cannot verify.

Sorry about that, should be testable here: https://cookbook.kirby.design/branch/kby-v7-0-0/#/home/showcase/segmented-control

**Comment by dennispedersen-bd** [comment]
Testet OK on iPhone (Safari) and Mac (Edge and Safari).

Fra: RasmusKjeldgaard ***@***.***>
Dato: mandag, 8. august 2022 kl. 12.48
Til: kirbydesign/designsystem ***@***.***>
Cc: Dennis Pedersen ***@***.***>, Mention ***@***.***>
Emne: [EXTERNAL]: Re: [kirbydesign/designsystem] [BUG] Badge on Segmented Control removes selected state (Issue #2388)
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


The branch is deleted so I cannot verify.

Sorry about that, should be testable here: https://cookbook.kirby.design/branch/kby-v7-0-0/#/home/showcase/segmented-control<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcookbook.kirby.design%2Fbranch%2Fkby-v7-0-0%2F%23%2Fhome%2Fshowcase%2Fsegmented-control&data=05%7C01%7Cdpe%40bankdata.dk%7C32cd2af689764bf63bcd08da792b74e3%7C1177168698fc4f1b8e0076c52159e8a6%7C0%7C0%7C637955524804101798%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=G4OihtLjerk4geRUY2ZJFxsJ8v4MtY32dojieMS2KRo%3D&reserved=0>
