### ISSUE TITLE
[Enhancement] Menu icons in Kirby

### ISSUE THREAD

**Issue by henrikvoetmand** [kirbydesign/designsystem#2395]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the enhancement
Some icons for the new left menu is not in Kirby icons - they should be added.

## Describe the solution you'd like
Add the attached svg icons to Kirby icons

## Have you considered any alternatives?
No

## Are there any additional context?
car
![car](https://user-images.githubusercontent.com/71710012/178687651-f199960a-d02c-43fa-81be-95b8b0511227.svg)
coinstack
![coinstack](https://user-images.githubusercontent.com/71710012/178687653-1d0d7053-daca-4016-b166-1cb6a3047efb.svg)
contact
![contact](https://user-images.githubusercontent.com/71710012/178687656-00db4ef5-aef3-431b-9509-0be406fe6bef.svg)
recurring
![recurring](https://user-images.githubusercontent.com/71710012/178940216-aae5b3a8-837d-46d8-951b-93d3b7b1edc1.svg)
salery
![salary](https://user-images.githubusercontent.com/71710012/178687663-779989ac-8049-429e-8729-dd6222160c86.svg)

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Refinement

- [ ] Request that the issue is [UX refined](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#ux-refinement); do not proceed until this is done.
- [ ] Request that the issue is [tech refined](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#tech-refinement); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Publish a WIP implementation to Github as a draft PR and ask for feedback. 
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Update the [cookbook](https://cookbook.kirby.design) with examples and showcases.

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request. If you created a draft PR during implementation you can just mark that as "ready for review".

**Comment by jkaltoft** [comment]
@henrikvoetmand Do you know the names of the icons? If so, could you add them to the description?

**Comment by jkaltoft** [comment]
@henrikvoetmand Shouldn't it say `recurring` instead of `reaccurring`?
