### ISSUE TITLE
[Enhancement] Button with icon

### ISSUE THREAD

**Issue by jonasjensen-brolstark** [kirbydesign/designsystem#241]
**Is your enhancement request related to a problem? Please describe.**
I want to be able to have a `kirby-button` that contains an icon, like:

![image](https://user-images.githubusercontent.com/46445487/57351914-e473b500-7163-11e9-866b-7e236e78989d.png)

Currently this is doable on web, but as a {N} `Button` doesn't support any other child elements than a 'FormattedString` this will have to be done as an input parameter. 

**Describe the solution you'd like**
I would like to be able to define an icon name (or a custom icon name) and the position of the icon. Either left or right of the text.

To use a built-in kirby icon you would make a button like:
```html
<Button  text="Icon button" iconName="search" iconPosition="left"></Button>
```
Here the attribute `iconName` will have the same type as the `name` attribute on `kirby-icon`.
The attribute `iconPosition` will have the type `'left' | 'right'`.

If you wanted to use a custom icon there needs to be a third attribute `customIconName`:

```html
<Button  text="Icon button" customIconName="unicorn" iconPosition="right"></Button>
```
Here the functionality will be the same as in the `CustomIconNameDirective`, searching the `CustomIconSettings` for the used name.

**Describe alternatives you've considered**
The `kirby-button` could also be made from a directive to a component, where we natively builds or own button. But i think this will hit the accessibility on native. 

https://zpl.io/bJG9Qd3

**Comment by jonasjensen-brolstark** [comment]
When #242 is merged a workaround is possible. You can get an icon button natively by doing:

```html
  <Button kirby-button class="icon-button">
    <FormattedString>
      <Span text="Icon button &#xf2f6;" class="my-icon"></Span>
    </FormattedString>
  </Button>
```

```scss
.my-icon {
  font-family: 'Ionicons', 'ionicons';
}
```

**Comment by mmmtrifork** [comment]
There are certain {N} limitations that still prevent this from being implemented. There is an open issue on GitHub, which needs to be fixed before we can continue: https://github.com/NativeScript/NativeScript/issues/4795
