### ISSUE TITLE
[BUG] Right button in modal footer is too far to the right

### ISSUE THREAD

**Issue by LVinther** [kirbydesign/designsystem#2425]
- [ ] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
The right button in the modal footer is too far to the right, when the modal is opened from a MEP context (as opposed to DRB), where the MEP app is then the host for the microfrontend.

The microfrontend looks like it should when running inside DRB - e.g. when the rest of the UI for DRB is loaded. 

## Describe how to reproduce the bug
Ask Rasmus Træholt Pedersen (Team 3) how to reproduce in MEP

## Which Kirby version was used?
v6.1.1 in both microfrontend and host. 

## Add any screenshots
![modal-footer (1)](https://user-images.githubusercontent.com/53176253/185071498-72f80c2d-e3ff-4d9b-a90e-1a8b53d158cc.JPG)

## Please complete the following information:
- OS: [e.g. Windows, MacOS, iOS]
- Browser [e.g. Chrome, Safari]
- Browser version [e.g. 22]

## Are there any additional context?

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/main/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by RasmusKjeldgaard** [comment]
Took the liberty to add some information after a quick talk with @RasmusTraeholt

**Comment by david-carlos-zachariae-jyskebank-dk** [comment]
Oplever samme problem med at `ion-footer` bliver bredere end modalen.

Kirby version: 9.3.2
Angular version: 17.2.2

![image](https://github.com/kirbydesign/designsystem/assets/159132916/64cc4596-40ce-421b-ae34-96807f9bc6e6)

Workaround er at overskrive width for ion-footer med "inherit"

**Comment by jakobe** [comment]
Additional info:
`kirby-modal-footer` has `box-sizing` set to `content-box` but `ion-footer` doesn't. As a result it defaults to `border-box` and the padding is added to the width of the footer as seen in the screenshots above.

The reason why it works in DRB and the cookbook is because of a global style that sets `box-sizing` on all elements to `inherit` which in turn makes `ion-footer` inherit the `content-box` value from `kirby-modal-footer`:
```css
*,
*::before,
*::after {
  box-sizing: inherit;
}
```

How to fix: explicitly set `box-sizing` to `inherit` on `ion-footer` in the styles for `kirby-modal-footer`.
