### ISSUE TITLE
Interaction State findings

### ISSUE THREAD

**Issue by jkaltoft** [kirbydesign/designsystem#2431]
- [ ] #2443
- [x] #2446 
- [x] Contact relevant teams about missing `selectable` on `kirby-item`?
    - **Investering** - List, Missing `selectable` on `kirby-item`? - No interactivity indicators (hover effect) but has click action 
    - **Posteringsliste** Kommende betalinger (opened) - List, Missing `selectable` on `kirby-item`?  - No interactivity indicators (hover effect) but has click action 

## Card

![Image](https://user-images.githubusercontent.com/150451/185948554-ddd0e653-8e34-46f3-92b5-a832e79a9d5b.png)

## Investering - box shadow top missing

![Image](https://user-images.githubusercontent.com/150451/185948943-b5102dd4-052f-4b4a-b7bb-d09efd34a719.png)

### Investering

![Image](https://user-images.githubusercontent.com/150451/185949357-dcd48969-c31c-4a78-b8a8-d86fc6e125b2.png)

### Kommende betalinger

![Image](https://user-images.githubusercontent.com/150451/185948365-e5f57bc4-f0b3-442e-94b6-340475c46584.png)

**Comment by RasmusKjeldgaard** [comment]
Closing this as I have contacted the relevant teams, and the other issues have been created and are being worked on 👍
