### ISSUE TITLE
[Enhancement] Tabbar with medium text badge

### ISSUE THREAD

**Issue by henrikvoetmand** [kirbydesign/designsystem#2432]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the enhancement
DRB is working to enhance the tabbar to make is possible to see the number of unread messages. A medium badge with text is used to show this info. The placement and alignment of the badge with text is not correct.

## Describe the solution you'd like
Adjust the position and the alignment (left-align) of the badge.

## Have you considered any alternatives?
No

## Are there any additional context?

![Text-badge-layout-issue](https://user-images.githubusercontent.com/71710012/185953829-a0a3e9c1-449c-431e-b796-9a99778071d2.png)

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Refinement

- [x] Request that the issue is [UX refined](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#ux-refinement); do not proceed until this is done.
- [x] Request that the issue is [tech refined](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#tech-refinement); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Publish a WIP implementation to Github as a draft PR and ask for feedback. 
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Update the [cookbook](https://cookbook.kirby.design) with examples and showcases.

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request. If you created a draft PR during implementation you can just mark that as "ready for review".

**Comment by RasmusKjeldgaard** [comment]
I have linked a draft that illustrates how this should look for for mobile view.

**Comment by henrikvoetmand** [comment]
UPDATE!
The requirements for the tablet and the desktop version has changed. The mobile implementation/design is NOT changed.
On tablet and desktop we want to place the badge to the right of menu point label. See below:

![Text-badge-layout-issue-desktop](https://user-images.githubusercontent.com/71710012/187411355-603fbe86-3d43-44da-b2a8-139addb31cd2.png)
