### ISSUE TITLE
[Enhancement] Disable padding on modal content drawer

### ISSUE THREAD

**Issue by bdytos** [kirbydesign/designsystem#2434]
- [ ] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the enhancement
We need an option to disable ion content padding inside a drawer to get our slides to work.

## Describe the solution you'd like
To get an option in the `ModalConfig` interface that allows us to disable the content padding .

## Are there any additional context?

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Refinement

- [ ] Request that the issue is [UX refined](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#ux-refinement); do not proceed until this is done.
- [ ] Request that the issue is [tech refined](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#tech-refinement); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Publish a WIP implementation to Github as a draft PR and ask for feedback. 
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Update the [cookbook](https://cookbook.kirby.design) with examples and showcases.

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request. If you created a draft PR during implementation you can just mark that as "ready for review".

**Comment by RasmusKjeldgaard** [comment]
@bdytos could you by any chance have a zeplin/sketch-drawing of what you need?

**Comment by mlrh-JB** [comment]
@RasmusKjeldgaard @bdytos - We need a caroussel like this one: https://app.zeplin.io/project/621f29e794f260a96ae2330a/screen/6228c6567b85ce04099a0d96

**Comment by RasmusKjeldgaard** [comment]
@mlrh-JB Could you provide a screenshot instead of a zeplin link? I do not have access.

**Comment by mlrh-JB** [comment]
![Carousel](https://user-images.githubusercontent.com/112431777/187362566-c7fc441c-73d2-483b-b4b2-fd647967b3ea.png)
@RasmusKjeldgaard - here you go

**Comment by RasmusKjeldgaard** [comment]
**Tech refinement:**
We suggest to define a new custom property `--kirby-modal-padding-inline-start`, `--kirby-modal-padding-inline-end`, that if set applies the given padding instead of the current default padding. 

This way, the `cssClass` property of the `ModalConfig` can be used to apply a class in the project that sets these Custom CSS Props on the modal via the global styles of the project.

**Comment by RasmusKjeldgaard** [comment]
This issue is solved by the new slides design implemented in #2949:

<img width="452" alt="image" src="https://github.com/kirbydesign/designsystem/assets/42470636/723ba2de-7c1d-4565-ad42-7e4dc80f5ed4">
