### ISSUE TITLE
[BUG] Topbaren forsvinder i modaler på Iphone 13 Pro

### ISSUE THREAD

**Issue by antbankdata** [kirbydesign/designsystem#2456]
## Describe the bug
Hej

Vi har observeret, at topbaren forsvinder, når vi åbner et modal på en Iphone 13 Pro. Problemet fremkommer ikke på en alm. Iphone 13. Jeg har vedhæftet et billede af problemet. Det lader til, at teksten er hvid, som den ikke er på en alm. Iphone 13
![image](https://user-images.githubusercontent.com/99955097/188397508-f905239d-39a7-4a97-86d3-d01f6a496e10.png)

## Describe how to reproduce the bug
Find og brug en Iphone 13 Pro
Gå til 'Pension'
Gå til 'Sygdom og død'
Gennemgå Wizard hvis nødvendigt
Klik på indstillinger ikonet
Observér at topbaren forsvinder.

## Which Kirby version was used?
6.3.1

## What was the expected behavior?
At man tydeligt kan se topbaren.

## Please complete the following information:
- OS: iOS
- Browser: Sydbank appen
- Browser version: Ved ikke hvad for en browser sydbank appen bruger.

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/main/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by Joeskov** [comment]
The issue also appears on kirby version 6.4.1 after upgrade to iOS 16.0 (iPhone 13)
Can be reproduced in mock.

Steps to reproduce;
Start Relationsbanken in Mock
Open any modal (e.g. 'Overfør og betal' in for-you)

![image](https://user-images.githubusercontent.com/88030854/191448136-88816d2e-8a2f-48aa-82e9-8f17a4f0be49.png)
