### ISSUE TITLE
[BUG] Modal: Close icon does not show on web

### ISSUE THREAD

**Issue by unnamjolner** [kirbydesign/designsystem#246]
**Describe the bug**
When opening a modal on web, the close icon seems to be hidden above the modal. The outline of the green button can vaguely be seen at the top of the modal.

The behavior seems to be correct in the Kirby Cookbook.

**To Reproduce**
1. Open a modal in DRB
2. The modal does not have a close button

**Kirby version**
 - 0.0.131

**Expected behavior**
A close button

**Screenshots**
Attached

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
![Screenshot 2019-05-08 at 13 00 02](https://user-images.githubusercontent.com/43847833/57370780-3979f000-7191-11e9-84ac-1f6da74aa126.png)

**Comment by mmmtrifork** [comment]
External issue.
