### ISSUE TITLE
[Enhancement] New icons in Kirby

### ISSUE THREAD

**Issue by henrikvoetmand** [kirbydesign/designsystem#2476]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the enhancement
We are working towards that all icons should be located in Kirby...

## Describe the solution you'd like
Upload attached icons to Kirby and add the icons to Cookbook icon page.

## Have you considered any alternatives?
No

## Are there any additional context?
![help-decoration](https://user-images.githubusercontent.com/71710012/189370684-415770ec-2801-4126-95b9-1b3fea0df036.svg)
![information-decoration](https://user-images.githubusercontent.com/71710012/189370687-7c268045-9964-4a01-a8f1-5b2450e55f0d.svg)
![notification](https://user-images.githubusercontent.com/71710012/189370690-10de8333-e836-46f7-b2f5-91ddfd04d901.svg)
![transfer-ownership](https://user-images.githubusercontent.com/71710012/189370691-872c6aa5-6a06-42ac-8ba2-c8c6951e1118.svg)

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Refinement

- [ ] Request that the issue is [UX refined](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#ux-refinement); do not proceed until this is done.
- [ ] Request that the issue is [tech refined](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#tech-refinement); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Publish a WIP implementation to Github as a draft PR and ask for feedback. 
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Update the [cookbook](https://cookbook.kirby.design) with examples and showcases.

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request. If you created a draft PR during implementation you can just mark that as "ready for review".

**Comment by jkaltoft** [comment]
@henrikvoetmand can you provide names for the icons?

**Comment by henrikvoetmand** [comment]
help-decoration
information-decoration
notification
transfer-ownership
