### ISSUE TITLE
[BUG] Dropdown focus state

### ISSUE THREAD

**Issue by henrikvoetmand** [kirbydesign/designsystem#2477]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the enhancement
In both chrome and safari, the focus state is shown on a dropdown (on mouse click) If you click on eg. a button on the same page, the focus state is not shown. If you the reload the page the state is shown again?!?

(See screen recording)

Chrome (Version 105.0.5195.102 (Officiel version) (x86_64))

Safari (Version 15.6.1 (17613.3.9.1.16))

## Describe the solution you'd like
No focus state on mouse click

## Are there any additional context?

https://user-images.githubusercontent.com/71710012/189891488-147f542b-816e-439a-99f0-dbef4332f5a9.mov

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Refinement

- [ ] Request that the issue is [UX refined](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#ux-refinement); do not proceed until this is done.
- [ ] Request that the issue is [tech refined](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#tech-refinement); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Publish a WIP implementation to Github as a draft PR and ask for feedback. 
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Update the [cookbook](https://cookbook.kirby.design) with examples and showcases.

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request. If you created a draft PR during implementation you can just mark that as "ready for review".

**Comment by jkaltoft** [comment]
Known remaining tasks to finish PR #2486:

- [ ] Check that `disabled` Dropdown works as intended – fix if broken
- [ ] Check that Dropdown _with pop-over_ works – fix if broken
- [ ] Check that Dropdown still works when in a form – fix if broken
- [ ] Reenable tests and make sure they pass
- [ ] _Dropdown with attention level_ is missing focus ring when given focus with keyboard
