### ISSUE TITLE
[BUG] Modal forces view to scroll down on web

### ISSUE THREAD

**Issue by unnamjolner** [kirbydesign/designsystem#248]
**Describe the bug**
When opening a Modal in Relationsbanken on web, the view is scrolled to the bottom of the page and one can see content below the dimmed layer. See attached escreenshot.

**To Reproduce**
1. Open Menu
2. Click on Mikro Økonomi
3. Scroll down to bottom of page
4. Click "Overfør penge"
5. The page is scrolled to the bottom and looks strange. It is also possible to scroll up and down.

**Kirby version**
 - 0.0.131

**Expected behavior**
It should not scroll down and it should not be possible to scroll away from the modal layer.

**Screenshots**
![web - scrolls down](https://user-images.githubusercontent.com/43847833/57371518-3ed83a00-7193-11e9-863e-5b3f01921318.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Comment by mmmtrifork** [comment]
External issue.
