### ISSUE TITLE
[BUG] Cannot find name 'OffscreenCanvas' in new project

### ISSUE THREAD

**Issue by lcersly** [kirbydesign/designsystem#2485]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
Installing Kirby design breaks angular build.

## Describe how to reproduce the bug

1. npx @angular/cli@13 new kirby-project
2. cd kirby-project
3. npm i @kirbydesign/designsystem
4. Import KirbyModule under imports in app.module.ts
5. ng serve

## Which Kirby version was used?
7.0.1

## What was the expected behavior?
Build succeeded

## Add any screenshots
![image](https://user-images.githubusercontent.com/6221577/191022178-37fb9538-0bde-43fa-95e3-f12bb8994b14.png)

## Please complete the following information:
- OS: Windows

## Are there any additional context?

It seems to be caused by an old version of chart.js

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/main/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by RasmusKjeldgaard** [comment]
Just adding to this: As already mentioned in the original issue, this should be fixed by updating Chart.js. More specifically to [version 3.6 or later](https://github.com/chartjs/Chart.js/pull/9617)

**Comment by RasmusKjeldgaard** [comment]
When bumping chart.js, remember to remove the `"skipLibCheck": true` flag from our tsconfigs so this does not happen again.
