### ISSUE TITLE
[BUG] Modal does not have rounded corners on web

### ISSUE THREAD

**Issue by unnamjolner** [kirbydesign/designsystem#249]
**Describe the bug**
When opening a modal on web, the modal only has very small rounding on their corners, different from the expected design.

**To Reproduce**

1. Open Menu
2. Click on Mikro Økonomi
3. Scroll down to bottom of page
4. Click "Overfør penge"
5. The modal has almost no rounding on corners

**Kirby version**
 - 0.0.131

**Expected behavior**
Rounded corners :)

**Screenshots**
Actual
![Screenshot 2019-05-08 at 13 00 02](https://user-images.githubusercontent.com/43847833/57371767-f2412e80-7193-11e9-873c-af781d01bf21.png)

Expected
![774b12c4-a23a-4bd6-a1cf-cd69da94ad72](https://user-images.githubusercontent.com/43847833/57371773-f66d4c00-7193-11e9-9dd2-f30199e7545a.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Comment by mmmtrifork** [comment]
External issue.
