### ISSUE TITLE
[Enhancement] Modal: should have a background color

### ISSUE THREAD

**Issue by unnamjolner** [kirbydesign/designsystem#250]
**Is your enhancement request related to a problem? Please describe.**
We have several items in our Transfer modal that has a white background. According to the designs we have received, the modal should have a light shade of grey in order to allow the white elements (see screenshot).

**Describe the solution you'd like**
Either a change of the background color to the desired grey or the ability to set the background color as part of the modal configuration.

Desired design:
![7fb6d692-10fe-4054-a07c-be873581c006](https://user-images.githubusercontent.com/43847833/57371976-988d3400-7194-11e9-8fc6-a3da4cb107e7.png)

**Comment by unnamjolner** [comment]
As I have been informed, it should always have the same background-color for Relationsbanken project. So if it could just be grey by default, it would be fine with us. :)

**Comment by jakobe** [comment]
Fixed by #259
