### ISSUE TITLE
[BUG] Contributing link gives 404

### ISSUE THREAD

**Issue by AndreasPetersen** [kirbydesign/designsystem#2509]
- [ ] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
The contributing link in the README links to a page that gives 404.

## Describe how to reproduce the bug
Press the contributing link in the README.

## Which Kirby version was used?
Latest at the time of writing

## What was the expected behavior?
A page that does not give 404

## Add any screenshots
![brave_jTeEHwie5O](https://user-images.githubusercontent.com/2496648/192757554-b80a8034-6380-40cd-8c22-101aad5d1031.png)
![brave_gr2iR10J9O](https://user-images.githubusercontent.com/2496648/192757585-04cba5be-8bb9-4f8b-827d-6aadd40db61c.png)

## Please complete the following information:
- OS: Windows 10 Enterprise 21H2, 19044.2006
- Browser: Brave, version 1.43.93, Chromium: 105.0.5195.127 (Official Build) (64-bit)

## Are there any additional context?
No

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/main/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by RasmusKjeldgaard** [comment]
I know that this is not strictly related, but now that we are at it, we should remove the highcharts notice. As of Kirby v7 we no longer ship any highcharts-based charts.
