### ISSUE TITLE
[Enhancement] SegmentedChipControl items as `label, value` pairs

### ISSUE THREAD

**Issue by SilverGull** [kirbydesign/designsystem#253]
**Is your enhancement request related to a problem? Please describe.**
The items is currently strings. This represents a problem when listening to `chipSelect` in a multi language application. It will emit a language dependent value if the items are language dependent.

**Describe the solution you'd like**
Items could be a `label, value` pair, `chipSelect` could emit an index value or `chipSelect` could emit an index value *and* the selected item as `label, value` pair. I would prefer having a value returned to avoid having to look it up in a collection based on an index.

**Describe alternatives you've considered**

**Additional context**

**Comment by jakobe** [comment]
Will be fixed by #344

**Comment by jakobe** [comment]
Will be fixed by #344
