### ISSUE TITLE
[BUG] Android - Hover-effect lingers after clicking on disabled calendar-items and segmented control items. 

### ISSUE THREAD

**Issue by mgy1192** [kirbydesign/designsystem#2531]
- [ ] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
Using Android, the Calendar and Segmented Control items will have the hover-effect lingering after the user has clicked on them. This persists until the user clicks outside the item with the lingering effect.

## Describe how to reproduce the bug
Click on segmented control item, or disabled date in calendar.
Observe how the item has a color matching the hover-effect color. 
Observe that the hover-effect clears when clicking outside. 

## Which Kirby version was used?
7.0.0

## What was the expected behavior?
No hover-effect when using android-app version. 

## Add any screenshots
![calendar_lingering_hover](https://user-images.githubusercontent.com/104763772/194307925-97df60ee-1ab2-4abc-a61f-e58e8fbbe3b2.jpeg)

## Please complete the following information:
- OS: Android 12

## Are there any additional context?
Discovered while testing Relationsbanken version 2022.10.292.19977

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/main/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by mgy1192** [comment]
Seems like this is also an issue with accordion items.

**Comment by mictro** [comment]
Not reproducable with kirby-8 on Android 12 - please upgrade the kirby version to 8.x.x

Closing issue.
