### ISSUE TITLE
[BUG] Kirby Segmented chips scrollbar is overlapping

### ISSUE THREAD

**Issue by azeemchauhan** [kirbydesign/designsystem#254]
**Describe the bug**
In Native(iOS/Android), Kirby segmented chip control component having overlapping issue with the scrollbar.
 
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Kirby Segment chip control'
2. Scroll right 

**Kirby version**
 - 0.0.134

**Expected behaviour**
There should be scrollbar but should not overlap with the chips

**Screenshots**
<img width="436" alt="Screenshot 2019-05-09 at 3 06 14 PM" src="https://user-images.githubusercontent.com/33758493/57444342-91862480-726d-11e9-874a-44950d691585.png">

**Native :**
 - Device: iPhone & Android

**Comment by jakobe** [comment]
Fixed by #282
