### ISSUE TITLE
[BUG] Kirby Segmented chip control distorted in mobile browser

### ISSUE THREAD

**Issue by azeemchauhan** [kirbydesign/designsystem#255]
**Describe the bug**
Kirby segmented chip control distorted in browser for small screen as well as bottom scrollbar is not align with the segmented chip control

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'segmented chip control section'
2. open on small screen
3. See error

**Kirby version**
 - 0.0.134

**Expected behaviour**
Kirby segmented chip control should not be overlap on each other and should have desired padding from bottom.

**Screenshots**
<img width="461" alt="Screenshot 2019-05-09 at 3 07 47 PM" src="https://user-images.githubusercontent.com/33758493/57445012-0f96fb00-726f-11e9-9ff5-d448911fd4ac.png">

**Mobile:**
 - Browser : chrome, safari, firefox

**Comment by jakobe** [comment]
We should replace the segmented chip control with segmented control + mode = default|chip and use the scrollable feature out of the box from Ionic:
https://ionicframework.com/docs/api/segment#properties
