### ISSUE TITLE
[Housekeeping] include-media dependency in core package

### ISSUE THREAD

**Issue by jkaltoft** [kirbydesign/designsystem#2571]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the housekeeping request

On September 19, 2022 Anders Hessellund Jensen noted in the `kirby-guild` Slack channel that the `core` package is missing a dependency on include-media (which is used by `core`):

> Hej Kirby.
I forbindelse med et eksperiment med at benytte pnpm pakke-manageren, så har jeg opdaget, at i bruger include-media pakken i jeres scss stylesheet i core pakken, men jeres core pakke har ikke nogen dependency på include-media.

We should investigate this and fix it if it needs fixing 🙂

## Have you considered any alternatives?

We could also consider to not use include-media. Instead we could use ordinary CSS media queries and Kirby's size design tokens – or a similar solution.

## Are there any additional context?

If you have access to the Slack channel here is the original message: https://bankdata.slack.com/archives/CGKJ1RBM4/p1663575516900039

**Comment by RasmusKjeldgaard** [comment]
This was "solved" in #2663, we are now adding the include-media scss file directly instead of as a package for unrelated reasons.
