### ISSUE TITLE
[BUG] kirby-segmented-control: Focus ring transition between buttons doesn't look smooth (Chrome 106)

### ISSUE THREAD

**Issue by mark-drastrup** [kirbydesign/designsystem#2592]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
When toggling between buttons in `kirby-segmented-control` the focus ring transition between the buttons is not smooth. And it will also change some corners to be square instead of rounded. 

## Describe how to reproduce the bug
https://user-images.githubusercontent.com/20282214/200556745-c06bae55-78f3-473a-8ebe-0caa4c8222dc.mov

## Which Kirby version was used?
7.0.0

## Please complete the following information:
- OS: MacOS
- Browser Chrome
- Browser version 106

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/main/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by RasmusKjeldgaard** [comment]
This has been investigated a bit further, and cannot be verified. 
It is a project-specific issue that relates to a version mismatch between Kirby v6 (dependency in a micro-frontend) and Kirby v7 (dependency in the host application).
