### ISSUE TITLE
[Housekeeping] Remove the deprecated registerPresentingElement method before next major release (Kirby v9)

### ISSUE THREAD

**Issue by mark-drastrup** [kirbydesign/designsystem#2596]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the housekeeping request
The `registerPresentingElement` method in `./libs/designsystem/src/lib/components/modal/services/modal.helper.ts` will be deprecated after #2528 is merged. We should completely remove the method before the next major release (Kirby v. 8). The method is still in the modal helper, but right now it doesn't do anything else besides console logging, that is has been deprecated.

**Comment by RasmusKjeldgaard** [comment]
Angular 15 has been merged, which means the next release is going to be a major. Since #2528 is not yet merged, this should probably be removed in v9 instead.
