### ISSUE TITLE
[Enhancement] Make att. level 3 button opacity-based

### ISSUE THREAD

**Issue by RasmusKjeldgaard** [kirbydesign/designsystem#2602]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the enhancement
The attention level 3 button should be changed from an outline to a see-through layer. 
![image](https://user-images.githubusercontent.com/42470636/201689081-681a8141-17eb-47e2-8e06-c2c4ea992fa4.png)

## Describe the solution you'd like
Attention level 3 of the button should be implemented with `themeColor` specific variants for light, white and dark backgrounds. This means they will automatically adapt when placed inside cards.   

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Refinement

- [ ] Request that the issue is [UX refined](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#ux-refinement); do not proceed until this is done.
- [ ] Request that the issue is [tech refined](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#tech-refinement); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Publish a WIP implementation to Github as a draft PR and ask for feedback. 
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Update the [cookbook](https://cookbook.kirby.design) with examples and showcases.

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request. If you created a draft PR during implementation you can just mark that as "ready for review".

**Comment by dennispedersen-bd** [comment]
Remember to adjust hover and pressed state acording to guidelines

**Comment by RasmusKjeldgaard** [comment]
New spec: 
![image](https://user-images.githubusercontent.com/42470636/203792583-c6180568-3236-4bd1-b17d-cc4676e48286.png)

**Comment by dennispedersen-bd** [comment]
Remember states.
