### ISSUE TITLE
[BUG] Page with fab-sheet is unable to scroll

### ISSUE THREAD

**Issue by mictro** [kirbydesign/designsystem#2609]
- [ ] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
On the fab-sheet page of the Kirby cookbook a 'backdrop-no-scroll' class is permanently applied to the body tag preventing scroll of the page.

## Describe how to reproduce the bug
1. Go to the kirby-cookbook
2. Click on fab-sheet
3. Scroll down on the page.
4. See that the page doesn't scroll

## Which Kirby version was used?
7.1.0

## What was the expected behavior?
The page should scroll downwards.

## Please complete the following information:
- OS: Windows, MacOS
- Browser Chrome
- Browser version <latest>

## Are there any additional context?
A missing opacity animation issue on the ion-backdrop of the fab-sheet was caused by swapping the ion-backdrop in-and-out the DOM.
The problem was fixed by replacing the swapping the element in-and-out with manipulating the the visibility of the element.
This in turn has the unfortunate side-effect of disallowing scroll on the page host.

<hr />
## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [x] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/main/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [x] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [x] Signal to others you are working on the issue by assigning yourself.
- [x] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [x] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [x] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [x] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [x] Create a pull-request.

**Comment by joachimboggild** [comment]
The page in the cookbook still does not scroll... 
I have updated package.json to reference Kirby ^7.3.0. , and I no longer see the problems on my own pages with fab-sheet.
