### ISSUE TITLE
[Enhancement] Modal: Add support for componentProps

### ISSUE THREAD

**Issue by jb-trm** [kirbydesign/designsystem#261]
**Describe the solution you'd like**
Currently the Kirby modal doesn't support data being passed to it when it is opened. It would be nice to be able to pass some context/componentProps.
The Ionic modal supports componentProps, and we are passing ModalWrapperConfig in that place - so maybe we could just expand the config interface:
https://ionicframework.com/docs/api/modal#passing-parameters

**Comment by hafstad** [comment]
I will take a look at this one
