### ISSUE TITLE
[Enhancement] Redo RxJS 7 upgrade

### ISSUE THREAD

**Issue by RasmusKjeldgaard** [kirbydesign/designsystem#2613]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the enhancement
In https://github.com/kirbydesign/designsystem/pull/2462 we upgraded to RxJS 7, but in https://github.com/kirbydesign/designsystem/pull/2510 we rolled back because it would be breaking.

## Describe the solution you'd like
We should apply the original changes again, and release them in the next major.

## Are there any additional context?

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Refinement

- [ ] Request that the issue is [UX refined](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#ux-refinement); do not proceed until this is done.
- [ ] Request that the issue is [tech refined](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#tech-refinement); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Publish a WIP implementation to Github as a draft PR and ask for feedback. 
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Update the [cookbook](https://cookbook.kirby.design) with examples and showcases.

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request. If you created a draft PR during implementation you can just mark that as "ready for review".

**Comment by mark-drastrup** [comment]
@kodeaben the RxJS upgrade was handled in the Angular 15 upgrade, right?

**Comment by RasmusKjeldgaard** [comment]
@mark-drastrup the wording I chose was a little confusing - when we rolled back we preserved RxJS 7, but removed the use of any new functions to preserve backwards compatibility. 

This issue is about using `firstValueFrom()` again, and we should also update the RxJS peer dependency for this problem to not happen again.

**Comment by mark-drastrup** [comment]
@RasmusKjeldgaard ahh I see! Sorry about the misunderstanding. I will take care of this issue :)
