### ISSUE TITLE
[Enhancement] Replace avatar shadow with stroke

### ISSUE THREAD

**Issue by jeppestromlundsgaard** [kirbydesign/designsystem#2622]
In the process of streamlining elevation, we will remove the shadow (z2 elevation) on the component "Avatar with Image".

We will **add** an inside stroke instead.

Stroke spec:
Inside stroke: #ebebeb — (Kirby / Style 01 / System / grey-02 (Semi-light))

![Avatar-with-image](https://user-images.githubusercontent.com/118980281/203780422-7536a1ce-30f4-40bb-91fd-9c2ea3827793.png)

**Comment by RasmusKjeldgaard** [comment]
**Tech refinement**
Currently the avatar has an input called `shadow` which should be replaced with e.g. `stroke` or `outline` input property. 
When used, the `shadow` input should log to the user that it is deprecated. 
In this case to ensure UI consistency and preserve compatability, I think we should set the `stroke/outline` input to true whenever users set the `shadow` input, and then at a later point remove the option for setting `shadow`.
