### ISSUE TITLE
[BUG] Kirby list pointer and hightlight sometimes works 

### ISSUE THREAD

**Issue by MartinCBBankdata** [kirbydesign/designsystem#2638]
Hi Kirby

The pointer and hightlight on hover on Kirby list sometimes works and sometimes It does not work. I can't fingure out what triggers the pointer and on hover hightligt however I my best guess is that the ```(itemSelect)="onItemSelect($event)"``` is the trigger. The code below is a anonymized version of my actual code. In the real code of my project the ```[disableSelectionHighlight]``` does not work and it seems like it triggers the pointer and on hover hightligt sometimes. It could however also just be a coincidence. Below are two pictures of the same code runned mutipletimes where it works and then it does not work. 

I would like it to always show the pointer and highlight on hover. 

HTML
```
<kirby-page>
  <kirby-page-content>
    <kirby-list [items]="testdata" [showDivider] = "true" (itemSelect)="onItemSelect($event)" *ngIf="HasLoaded$() | async; else spinner">
      <kirby-list-header *kirbyListHeader class="header-size"
      ><h3>
        Header
      </h3>
      </kirby-list-header>
      <kirby-item *kirbyListItemTemplate="let item">
        <p>{{item.label}}</p>
      </kirby-item>
    </kirby-list>
  </kirby-page-content>
  <ng-template #spinner>
    <kirby-spinner></kirby-spinner>
  </ng-template>
</kirby-page>
``` 

TS
```
export class TestComponent implements OnInit {
  testdata: any = [];
  constructor(
    public outstandingsService: OutstandingsService,
  ) {}

  ngOnInit(): void {
    this.Service.update();
    this.Service.getSubject().subscribe((data) => {
      this.testdata = [
        { label: "mock", status: "ok"},
        { label: "mock", status: "ok"},
        { label: "mock", status: "ok"},
        { label: "mock", status: "ok"}
      ];
    });
  }

  onItemSelect($event: any) {

  }

}
```

![image](https://user-images.githubusercontent.com/110449604/204545142-35c2a683-0a37-4b0a-8ca6-a624afe2a28e.png)
![image](https://user-images.githubusercontent.com/110449604/204545386-be353020-6061-47b5-9187-a5a692035ce6.png)

**Comment by mark-drastrup** [comment]
@MartinCBBankdata I have done some research on this issue and found out what's going on. You're right that it is `(itemSelect)="onItemSelect($event)"` that triggers the pointer and hover highlight. We have some internal logic in the component that loops through and marks the `kirby-item` components as selectable if `(itemSelect)="onItemSelect($event)"` is passed to the component. This logic breaks when a `*ngIf` is used with an `Observable` and a `async pipe`. The logic depends on this list:

```
@ContentChildren(ItemComponent)
kirbyItems: ItemComponent[];
```

When using the async pipe this list is empty, and as a result the item components are not marked as selectable. There is a very simple workaround for this. If you manually add `[selectable]="true"` to the `kirby-item` in your template, then you will still get the pointer and hover highlight. Does this workaround work for you? :)
