### ISSUE TITLE
[ENHANCEMENT] Button should be able to shrink to fit text on native

### ISSUE THREAD

**Issue by PetarRing** [kirbydesign/designsystem#265]
**Is your enhancement request related to a problem? Please describe.**
When using a kirby-button the button expands to fill the parrent layout on native.

**Describe the solution you'd like**
The kirby-button should shrink to fit the text provided on native, give or take the already provided margin. In generel the native usage of the kirby-button, should be the same on web and native.

**Describe alternatives you've considered**
If the button should default to 'block' size, the ability to make it shrink should be provided instead.

**Additional context**
![image](https://user-images.githubusercontent.com/8911645/57711112-6edd7c80-766e-11e9-9b4c-0c9d9a29b7cb.png)

**Comment by jakobe** [comment]
Will be fixed by #341
