### ISSUE TITLE
[Enhancement] Kirby-button should be able to have more background colors

### ISSUE THREAD

**Issue by PetarRing** [kirbydesign/designsystem#266]
**Is your enhancement request related to a problem? Please describe.**
When using a kirby-button its colors are only customizable to 'primary' and 'secondary' which is not enough if you want a grey button.

**Describe the solution you'd like**
When using kirby-button the [colorType] input should allow it to use: tertiary, warning, succes, danger, medium, light and dark 

**Describe alternatives you've considered**
If no support should be given, at least the ability to customize the background color of the button completely would be nice.

**Additional context**

**Comment by bommariusser** [comment]
@PetarRing i'm not sure but i think this is already doable in the css of the button (by changing the color), even though its not a property listed in the cookbook. It's probably more a hack and not sure if this is best practice. Maybe @jakobe can tell you this :D

**Comment by jakobe** [comment]
Will be fixed by #339

**Comment by jakobe** [comment]
You can only set background color of the button through `attentionLevel="1|2|3|4"`
