### ISSUE TITLE
[Enhancement] Kirby item message type disclosure exploration 

### ISSUE THREAD

**Issue by AgreSanGit** [kirbydesign/designsystem#2667]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the enhancement

On Kirby item message type explore how to work with disclosure. The disclosure on Kirby item message type is smaller than disclosure on Kirby item meaning the icon and spacing is different. Look at the picture below to see the difference. 

Kirby item message type:
![Screenshot 2022-12-12 at 13 45 39](https://user-images.githubusercontent.com/112690169/207048653-eb748c28-e140-4e0e-818a-a1c7d5a35dbb.png)

Kirby item no message type:
![Screenshot 2022-12-12 at 13 50 21](https://user-images.githubusercontent.com/112690169/207049503-cb0e1c65-c0eb-4329-b7d4-a2351b8e3745.png)

## Are there any additional context?

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Refinement

- [ ] Request that the issue is [UX refined](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#ux-refinement); do not proceed until this is done.
- [ ] Request that the issue is [tech refined](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#tech-refinement); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Publish a WIP implementation to Github as a draft PR and ask for feedback. 
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Update the [cookbook](https://cookbook.kirby.design) with examples and showcases.

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request. If you created a draft PR during implementation you can just mark that as "ready for review".

**Comment by dennispedersen-bd** [comment]
Vi har stadig brug for denne, for at kunne tilføje Disclosure til indbakken. Koordiner gerne med Emil omkring Jira task - RAOGF-5937

**Comment by dennispedersen-bd** [comment]
Vi har stadig brug for denne, for at kunne tilføje Disclosure til indbakken. Jira task - RAOGF-5937
