### ISSUE TITLE
[Housekeeping] Configure Prettier for HTML files

### ISSUE THREAD

**Issue by mark-drastrup** [kirbydesign/designsystem#2673]
- [ ] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

When Prettier formats HTML files on save it will sometimes append a semicolon at the end of the file. It seems like Prettier interprets the file as JSX instead of HTML.

![Uden navn](https://user-images.githubusercontent.com/20282214/207318343-1a30d04d-81f5-4f8a-bd6a-1a468a6b5b7d.png)
<img width="466" alt="Skærmbillede 2022-12-13 kl  13 16 02" src="https://user-images.githubusercontent.com/20282214/207318354-de26c147-7180-41fa-aad9-68792e771951.png">

We should configure prettier to format HTML files as HTML and not JSX. I'm not sure it it needs to be handled in `.prettierrc.json` or `.vscode/settings.json`

**Comment by thupi** [comment]
Hi @mark-drastrup, i couldn't reproduce this. Seem that all HTML rules are being overwritten in the .eslintrc.json :-)

Is there specific files where this happens and which extensions do you have installed :-) ?

**Comment by mark-drastrup** [comment]
Hey @thupi! I actually also have issues reproducing it now. It was @mictro who experienced the issue and I saw it happen on his machine 😅 @mictro can you help @thupi with some more information? 🙂

**Comment by thupi** [comment]
This doesn't seems to be an issue anymore as it seems to be more related to local configs more of VS code.
