### ISSUE TITLE
[BUG] Kirby page sticky content transparency

### ISSUE THREAD

**Issue by RasmusTraeholt** [kirbydesign/designsystem#2685]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
The `kirbyPageStickyContent` directive does not fill the entire device screen width on smaller devices (<752px). There is a 16px left and right gap, where normal page content that has box-shadow is visible behind the sticky page content when scrolling down.

## Describe how to reproduce the bug
On a kirby page use the `kirbyPageStickyContent` to insert any sticky content on the page. Insert any content in the standard kirby page content slot that has box-shadows. See that the box shadow is visible behind the sticky content when scrolling down

## Which Kirby version was used?
7.3.0

## What was the expected behavior?
No other page content is visible behind the sticky top content.

## Add any screenshots
![Screenshot 2022-12-14 at 11 15 38](https://user-images.githubusercontent.com/23026215/207844121-ee2b2aa5-f7c6-41f7-80fe-40d7e5d6bd1e.png)

## Please complete the following information:
- OS: [MacOS, iOS]
- Browser [Chrome, Safari, Firefox]

## Are there any additional context?

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [x] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/main/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by mictro** [comment]
Both reporter and investigator was unable to reproduce with kirby @8.x.x - closing.
