### ISSUE TITLE
[BUG] KirbyList - Noticeable flicker when toggling stand alone items  

### ISSUE THREAD

**Issue by mark-drastrup** [kirbydesign/designsystem#2692]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
When a stand alone item is updated, so it will no longer be stand alone, but part of the list, then there is a noticeable flicker, when the list updates.

Fx. when the button "Bekræft" is pressed, then the stand alone item should change to be part of a list.

<img width="759" alt="Skærmbillede 2022-12-20 kl  09 53 18" src="https://user-images.githubusercontent.com/20282214/208627362-3a008a6c-ee22-41d6-bd8e-1eff0c27e2be.png">

## Which Kirby version was used?
7.4.0

## What was the expected behavior?
The transition from stand alone to part of a list should be smoother without a noticeable flicker.

## Please complete the following information:
- OS: MacOS, iOS
- Browser: Chrome
- Browser version: 108

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/main/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by mictro** [comment]
Flicker when adding an item which will change a single-item category to a multi-item category is not reproducible in the flows app.

**Comment by mark-drastrup** [comment]
I'm closing this issue since we haven't been able to reproduce the bug.
