### ISSUE TITLE
[BUG] Rending issue when using stroke property on kirby-avatar

### ISSUE THREAD

**Issue by troelslenda** [kirbydesign/designsystem#2718]
- [ ] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug

When using the kirby-avatar with the stroke property the browser cuts off image top and bottom or sides.

## Describe how to reproduce the bug

1. Goto https://cookbook.kirby.design/#/home/showcase/avatar
2. Inspect and change the src property for the img tag in the kirby-avatar with stroke. (change it to https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Denmark_flag.GIF/320px-Denmark_flag.GIF for better visual representation of the bug described.)
3. Zoom the browser to 140 or 160%
4. See that the top and the bottom of the image is cutoff.
5. remove the border css property or change it to outline on the wrapping div element to see a perfect circle again.

## Which Kirby version was used?
The one deployed at https://cookbook.kirby.design
 

## What was the expected behavior?

A perfect circle

## Add any screenshots

![Screenshot 2023-01-04 at 12 54 24](https://user-images.githubusercontent.com/263060/210553425-270e89b3-5183-4bab-b37a-a346d2f066ac.png)
![Screenshot 2023-01-04 at 12 54 14](https://user-images.githubusercontent.com/263060/210553429-5df6d5a1-8c01-4284-a769-d6d11b1a1b29.png)
![image-2023-01-04-09-28-58-696](https://user-images.githubusercontent.com/263060/210802745-a11d2eb0-a24b-4bdc-9b6a-d8d266496a2d.png)

## Please complete the following information:
- OS: MacOS 13.0.1
- Browser: Vivaldi
- Browser version: 5.6.2867.50 (Stable channel) (arm64)
The above is used for reproduction. The bug was originally found using this device
![image](https://user-images.githubusercontent.com/263060/210553948-d6d83837-8092-4a80-96c0-19535aaef05c.png)

## Are there any additional context?

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/main/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by RasmusKjeldgaard** [comment]
I can't reproduce this in Chrome, Firefox or Safari on my Macbook. 
What browser is the device running is it Chrome web view inside the relationsbank app?

**Comment by troelslenda** [comment]
In chrome zoom to 90%, though not as obvious but the bug is present

**Comment by RasmusKjeldgaard** [comment]
For some reason I just cant reproduce it on my end, but saw it on @troelslendas screen yesterday.
@AgreSanGit could we do a quick fix and use outline instead of border?

**Comment by troelslenda** [comment]
What if you set the size/ class to md instead of lg? A little detail that I might have forgotten in reproduction steps.

**Comment by troelslenda** [comment]
With Vivaldi 6.1.3035.302 (Stable channel) (arm64) and newest of Kirby, reproduction is not possible anymore.
