### ISSUE TITLE
[COMPONENT] Multi select

### ISSUE THREAD

**Issue by bdyhsj** [kirbydesign/designsystem#2721]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the solution you'd like

For use in an ongoing Bankdata project, we need a searchable dropdown, that supports multiple selections.

## Have you considered any alternatives?

Since there will be upwards of 500 items in the dropdown for our use case, it is crucial that the dropdown is searchable.
Additionally, the requirement of selecting multiple values from the dropdown means that the current components are not sufficient.

## Are there any additional context?

Some information from UX is provided below.

### Mock-up
![mockup](https://user-images.githubusercontent.com/112956379/210793833-9540aa1a-2bc7-4b8e-8d0d-3a8815398f8c.png)

### Requirements

- [ ] When no items are selected, and the input is not focused, a placeholder text should be shown (Example 01)
- [ ] When the input is focused, the dropdown should start showing (Example 02).
  * This behaviour may have to change slightly in case of async search.
- [ ] The items shown in the dropdown should be filtered as the user types input. (Example 03)
  * Techincal note: A debounce should probably be forced here. UX previously suggested 500 ms, but this is subject to change.
- [ ] The input should show number of selected items when not focused. (Example 06)
- [ ] It should be possible to clear all selections when the input is not focused. (Example 06)
- [ ] When the dropdown is open, selected items should be placed first in the list. (Examples 05 and 07)
- [ ] There should be an option for displaying the total number of items matching a dropdown item. (Example B01)
  * I.e. an outer list with duplicates is filtered based on the selection in the multi select component.
    Each option in the dropdown shows the number of outer list elements with that value.
  * This would probably be achieved by allowing custom item label rendering.
- [ ] It should be possible to mark an item as disabled. (Example B01)
- [ ] It should be possible to mark the entire component as disabled.
- [ ] Provide an async search option, using `Observable` as suggested by @kodeaben [here](https://github.com/kirbydesign/designsystem/issues/2721#issuecomment-1372313120)

#### Single select mode

- [ ] The multi select functionality should be enabled if the `multiple` Input flag is set to true, otherwise the component should function as a searchable dropdown (Only one item can be selected)
- [ ] When in single select mode, the text / label of selected item should be shown instead of the number of selected items
- [ ] When in single select mode, the clear button should still appear when the input is not focused.

### Other

It is not yet clear if scroll virtualization is desirable.

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Refinement

- [x] Request that the issue is [UX refined](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#ux-refinement); do not proceed until this is done.
- [x] Request that the issue is [tech refined](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#tech-refinement); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [x] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [x] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Publish a WIP implementation to Github as a draft PR and ask for feedback. 
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Update the [cookbook](https://cookbook.kirby.design) with examples and showcases.

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request. If you created a draft PR during implementation you can just mark that as "ready for review".

**Comment by kodeaben** [comment]
Might I suggest you consider adding a requirement to make an async option for searches, using `Observables`? 
This way, if you actually need to search through 500+ items, the implementer can use a backend service to do so.

**Comment by kodeaben** [comment]
Should there ba a divider between selected and non selected items? example 5 doesn't have it, but 7 does
Clear button ? example 6
How many elements should be rendered?

B01: there is no description of disabled items if count is 0.
