### ISSUE TITLE
[BUG] FAB sheet backdrop does not show up correctly when used inside Tabs

### ISSUE THREAD

**Issue by RasmusKjeldgaard** [kirbydesign/designsystem#2765]
- [ ] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

![image](https://user-images.githubusercontent.com/42470636/212655527-5ba83e87-0425-4f04-b5d8-8d87734f40d3.png)

## Describe the bug
While the FAB sheet behaves as expected on its own cookbook page, it breaks when used on Tabs.
Alternatively, it is because of page - it is difficult to tell without further clarification.

## Describe how to reproduce the bug

1. Go to '[tabs showcase](https://cookbook.kirby.design/#/home/showcase/tabs)'
2. Click on the FAB inside the iPhone viewer

## Which Kirby version was used?
v7.4.1

## What was the expected behavior?
Backdrop should animate nicely and be full screen

## Please complete the following information:
- OS: MacOS
- Browser Chrome

**Comment by mictro** [comment]
This is also a problem on the advanced page in the cookbook. (see [page showcase](https://cookbook.kirby.design/#/home/showcase/page))

The problem has been present since the introduction of ionic 6 in v6.3.0.
