### ISSUE TITLE
[ENHANCEMENT] Item: Swipe actions for web (non-touch) 

### ISSUE THREAD

**Issue by NikolajSkousen** [kirbydesign/designsystem#2790]
- [ X] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the solution you'd like
Swipe actions for web (non-touch)
* On web swipe actions are displayed in an (additional?) item segment like an item with "07 Icon" in the end segment
* If only one action is available, the corresponding icon can be displayed in the segment (if the swipe action can be associated with an appropriate icon)
* If no icon is specified for a single swipe action a 01 Icons/general/more icon will be displayed. Pressing the icon will invoke an action list (dropdown) with the action name (appropriate action names must be specified for alle swipe actions). Pressing the action name will invoke the action.
* If more than one swipe action is available a 01 Icons/general/more icon will be displayed. Pressing the icon will invoke an action list (dropdown) with alle the action names (appropriate action names must be specified for alle swipe actions). Pressing an action name will invoke the corresponding action.

## Have you considered any alternatives?
Nope

## Are there any additional context?
<img width="2562" alt="image (8)" src="https://user-images.githubusercontent.com/85226992/213437699-3077af18-6f92-4c42-96fe-d1566d2607e1.png">

ZEPLIN: [https://zpl.io/7wnwwej](url)

Any questions please reach out to Lars Bruun: lab@bankdata.dk

(I am only a puppet creating this issue due to Lars being UX and thus not having a github account)

**Comment by henrikvoetmand** [comment]
**UX clarification:**
Disclosure icon and Swipe actions icon should **not** exist at the same time.
