### ISSUE TITLE
[Enhancement] Modal - placement of close button

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#280]
**Is your enhancement request related to a problem? Please describe.**
Modal should have the option to specify the placement of the close button. 

There are two cases, because the close button can either be inside the modal or outside the modal.

See also: https://zpl.io/VqvzKGl

**Comment by mmmtrifork** [comment]
<img width="932" alt="Screenshot 2019-05-20 at 11 14 25" src="https://user-images.githubusercontent.com/48326253/58010367-82feff00-7af0-11e9-85a5-4070a3eefb34.png">
These look exactly the same to me, but I do understand your point
