### ISSUE TITLE
[BUG] get-color does not work unless you write utils.get-color

### ISSUE THREAD

**Issue by joachimboggild** [kirbydesign/designsystem#2800]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
In scss: getting a colour with get-color results in an "invalid property value" in Chrome DevTools. For example: `background-color: get-color('warning');`.

A workaround exists, writing utils.get-color. However, this is not what the code in the cookbook does. In the color section (https://cookbook.kirby.design/#/home/showcase/colors), get-color is used without prefixing with utils. 

## Describe how to reproduce the bug
- Create an Angular component
- In the scss file, first line: `@use '@kirbydesign/designsystem/scss/utils';`
- Make a style with e.g. background-color: get-color('danger'); 
- Use this color on an element in the page.
- The element should have the warning colour (orange) as a background colour.

## Which Kirby version was used?
7.5.0-rc-1

## What was the expected behavior?
The expected behavior is that the colour specified should be rendered.

![image](https://user-images.githubusercontent.com/8225312/214052601-d7efc449-40c4-4c6e-84d9-ea8dbff3dc54.png)
![image](https://user-images.githubusercontent.com/8225312/214052710-d51ad645-2862-40de-b709-7dbf06caf858.png)

## Please complete the following information:
- OS: Windows
- Chrome
- 109.0.5414.75

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/main/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by RasmusKjeldgaard** [comment]
This is expected functionality with scss modules, https://sass-lang.com/documentation/at-rules/use#loading-members 
The solution to this issue is to update the documentation so it says utils.get-color()

**Comment by RasmusKjeldgaard** [comment]
I have created a PR ☝️, thanks so much for bringing this to our attention!
