### ISSUE TITLE
[Housekeeping] Align seperate modal version and combine into one (Modal v1 <- v2)

### ISSUE THREAD

**Issue by mark-drastrup** [kirbydesign/designsystem#2854]
- [X] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

⚠️ This issue is dependent on the [new alert](https://github.com/kirbydesign/designsystem/issues/2855) issue ⚠️

By cleaning up the old modal code we will delete the alert as well, since it is instantiated through the modal controller.

## Describe the housekeeping request
When the experimental modal becomes the new default modal, we should remember to clean up the following files and foldes:

**Folders**
- Delete the full modal folder at `libs/designsystem/modal/src`. The `experimental` folder should become the new `src`.
- Delete the full examples folder in the cookbook at `apps/cookbook/src/app/examples/modal-example`
- Delete the full showcase folder in the cookbook at `apps/cookbook/src/app/showcase/modal-showcase`

**Files**
- Remove global styles from `libs/core/src/scss/_global-styles.scss`
- Remove variables and maps from `libs/core/src/scss/base/_variables.scss`
- Remove all ModalController logic from `libs/designsystem/src/lib/kirby.module.ts`

After all the files have been removed, then all the `modal-experimental` names must be changed to `modal`. When the renaming is done the following files should be updated:

- Remove the path to the experimental modal from `libs/designsystem/tsconfig.json`
- Remove the path to the experimental modal from `libs/designsystem/tsconfig.spec.json`
- Remove the path to the experimental modal from `apps/flows/tsconfig.json`
- Remove the path to the experimental modal from `apps/cookbook/tsconfig.json`

**Comment by RasmusKjeldgaard** [comment]
We are introducing the declarative modal in modal v1 instead to avoid heavy refactoring in consumer projects. Modal v2 can be removed when the declarative modal is introduced to modal v1 as teams will have a vialbe migration path away from v2.
