### ISSUE TITLE
[BUG] Mock component for kirby-item is missing the disclosure input

### ISSUE THREAD

**Issue by mark-drastrup** [kirbydesign/designsystem#2869]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
The autogenerated mock file for kirby-item is missing the newly added `disclosure` input. That causes unit tests, that are utilizing the `KirbyTestingModule` to fail with the following error:

```
Error: NG0303: Can't bind to 'disclosure' since it isn't a known property of 'kirby-item' (used in the 'AppComponent' component template).
1. If 'kirby-item' is an Angular component and it has the 'disclosure' input, then verify that it is a part of an @NgModule where this component is declared.
2. If 'kirby-item' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.
```

It seems like the `generate-mocks` needs to be updated after secondary entries have been introduced. The path provided to the script is pointing to the old components folder, so it never looks into the new secondary entry folders.

## Describe how to reproduce the bug
1. Install Kirby v.8.0.0 in a new project
2. Use the kirby-item component in a component template
3. Add the testing module as described [here](https://github.com/kirbydesign/designsystem#testing)
4. Run the unit tests

## Which Kirby version was used?
8.0.0

## Please complete the following information:
- OS: [e.g. Windows, MacOS, iOS]
- Browser [e.g. Chrome, Safari]
- Browser version [e.g. 22]

## Are there any additional context?

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/main/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by RasmusKjeldgaard** [comment]
Fixed in #3000
