### ISSUE TITLE
[COMPONENT] Divider

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#287]
**Describe the solution you'd like**
We have different ways of seperating content dependant on the underlying content.

on canvas: https://zpl.io/blD3xq1
on white: https://zpl.io/a31EO51

See also: https://zpl.io/boDW5Wg

### Kick Off:
- [ ] Accept Feature incl. name of component (DSL)
- [ ] Update Kirby Component Status and publish to [Kirby Cookbook](https://cookbook.kirby.design)
### Code:
- [ ] Create Feature Branch
- [ ] Implement Skeleton Component:
    - [ ] Web implementation
    - [ ] {N} implementation
- [ ] [Implement Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Add link to showcase on Kirby Component Status (`component-status-items.ts => code.cookbookUrl`)
- [ ] Also remove `githubIssueNo` and set `status` to `ItemCodeStatus.ready`
- [ ] Push commits to GitHub
### Review:
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- Merge to master and delete branch

**Comment by jakobe** [comment]
Will be fixed by #338
