### ISSUE TITLE
[BUG] Form field - numeric input not working in Safari browser

### ISSUE THREAD

**Issue by henrikvoetmand** [kirbydesign/designsystem#2887]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
The form field with numeric input is not working in Safari web browser (on desktop)

## Describe how to reproduce the bug

1. Open Safari browser on desktop.
2. Go to "https://cookbook.kirby.design/#/home/showcase/form-field"
3. Find the form field with Numeric input
4. Try entering letters and special chars - other than numbers
5. Only numbers and "-"   "+"    "e"    "."    ","  should be allowed

## Which Kirby version was used?

8.0.0

## What was the expected behavior?

Only numbers and "-"   "+"    "e"    "."    ","  should be allowed

## Add any screenshots

https://user-images.githubusercontent.com/71710012/220574733-e938b84d-f8bf-4ef3-9e3e-820aac0f3f19.mov

## Please complete the following information:
- OS: [MacOS]
- Browser [Safari]
- Browser version [Version 15.6.1 (17613.3.9.1.16)]

## Are there any additional context?

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/main/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by mictro** [comment]
The kirby numeric input field implementation solely relies on setting the type="number" attribute on the standard html input element. This leaves it up to the browser to handle numeric input restrictions which differs greatly between Chrome and Safari/Firefox. The latter allows any character to be entered but will produce a validation error while chrome won't allow illegal characters to be entered.
If this behaviour difference is unacceptable (UX) either a general keyboard input and paste filter may carefully be added to the existing kirby numeric formfield. Another and perhaps better option option is to enhance the kirby-formfield with a general number-input-mask ala the existing decimal-input-mask.
