### ISSUE TITLE
[Enhancement] Animation on disclosure icon, on kirby item

### ISSUE THREAD

**Issue by hjorte-bd** [kirbydesign/designsystem#2901]
We are using the new disclosure icon on menu elements  to indicate state for a fold state. Previously we had an animation that is no longer possible if we use the disclosure option.

## Describe the enhancement
A way to animate discloure icons

## Describe the solution you'd like
A prebuilt rotate option or other way to pass an animation config to the disclosure icon.

## Have you considered any alternatives?
Not using disclure works today, but requires extra styling to match the items that can just disclosure, as is.

## Are there any additional context?
Previous solution
https://user-images.githubusercontent.com/110398431/221561601-235f678b-5b57-4ee5-bfff-05917d73bf6a.mov

Simply using disclosure
https://user-images.githubusercontent.com/110398431/221561614-d9cb1caf-7375-496f-af40-b9d487ff71b0.mov

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Refinement

- [x] Request that the issue is [UX refined](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#ux-refinement); do not proceed until this is done.
- [x] Request that the issue is [tech refined](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#tech-refinement); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [x] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [x] Signal to others you are working on the issue by assigning yourself.
- [x] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [x] Publish a WIP implementation to Github as a draft PR and ask for feedback. 
- [x] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Update the [cookbook](https://cookbook.kirby.design) with examples and showcases.

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request. If you created a draft PR during implementation you can just mark that as "ready for review".

**Comment by RasmusKjeldgaard** [comment]
@hjorte-bd this seems like a better usecase for an accordion with nested items. Accordion already has an animated disclosure icon. 

Have you tried that? Did you encounter any blocking issues with accordion?

**Comment by hjorte-bd** [comment]
@RasmusKjeldgaard Our UX designer didn't wanna use the accordion because the arrow has to point left, like "normal" menu points when closed. But if accordions can be used seamlessly in a kirby-list next to kirby-items, then maybe accordions could support alternative icons/rotations 🤔 What do you think about that approach instead?
