### ISSUE TITLE
[Inquiry] Should `Page` always depend on `RouterModule`?

### ISSUE THREAD

**Issue by kodeaben** [kirbydesign/designsystem#2903]
**Please complete the following information:**
The question is based on findings from another issue: #2902

## Subject area:
- [ ] Kirby UX
- [x] Kirby development
- [ ] Prioritysation status (Product owner)
- [ ] Other

The `<kirby-page>` component has a dependency on `ModalNavigationService`, which has a dependency on `ActivatedRoute` (See links below).
https://github.com/kirbydesign/designsystem/blob/c9cae3ae8383fe82f4438109e58f1168f4fcbe7b/libs/designsystem/page/src/page.component.ts#L276-L283

https://github.com/kirbydesign/designsystem/blob/c9cae3ae8383fe82f4438109e58f1168f4fcbe7b/libs/designsystem/modal/src/modal-navigation.service.ts#L9-L10

This means that in order to use a `kirby-page`, the implementer must import a `RouterModule`, even if they have no intention of using routes.
If they don't, the following error occurs: 
<img width="458" alt="Screenshot 2023-02-28 at 09 33 40" src="https://user-images.githubusercontent.com/114976818/221797716-29fb21bd-3166-4824-955f-8dfe21de3c9a.png">

My question is if there even is a usecase where the implementer will use a page without routing, and if yes, should we make an enhancement to separate Page and navigation?

**Comment by mark-drastrup** [comment]
Really nice finding @kodeaben! If we decide to keep the page implementation as is, then we should make sure to extract the ModalNavigationService out into its own secondary entry, when we deprecate the old modal. My initial thought was that we could completely deprecate all old modal functionality, when the experimental modal becomes the default. But that would break the page component, unless we extract the ModalNavigationService.
