### ISSUE TITLE
[BUG] Conditionally set disclosure on kirby-item

### ISSUE THREAD

**Issue by bdyhsj** [kirbydesign/designsystem#2905]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
 
It is not possible to conditionally set the disclosure of a `kirby-item` element, as the type of `disclosure` does not permit this.

## Describe how to reproduce the bug

Use either of the following patterns to conditionally define the disclosure:

```html
<kirby-item [disclosure]="someCondition ? 'arrow-more' : undefined">
  <h3>Item label 1</h3>
</kirby-item>
<kirby-item [disclosure]="someCondition ? 'arrow-more' : null">
    <h3>Item label 2</h3>
</kirby-item>
```

## Which Kirby version was used?
 
v8.0.1

## What was the expected behavior?

The program compiles without errors

## Add any screenshots

![image](https://user-images.githubusercontent.com/112956379/221858446-5aacd0e7-ccb3-408b-8b86-6f5b9fa089a6.png)

## Please complete the following information:
- OS: MacOS (BD dev machine).
- Browser: N/A
- Browser version: N/A

## Are there any additional context?

It may be as simple as extending the type of `disclosure` to include either `null`, `undefined`, or `'none'`.

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [x] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/main/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [x] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by kodeaben** [comment]
Looks good and it makes sense to allow conditional use. I would however suggest that we only allow `null` and not `undefined` as it is not a value made for assignment, but a value of a  property which has not yet been assigned.
