### ISSUE TITLE
[BUG] Modal vs. tab navigation iOS

### ISSUE THREAD

**Issue by unnamjolner** [kirbydesign/designsystem#291]
**Describe the bug**
After the tab navigation was introduced to the Relationsbank code base (Monday, May 20th), a Modal opened inside a feature area such as Konto, will not overlay the entire screen on iOS. The Tab bar is visible.

See attached screenshot (Android left, iOS right)

**To Reproduce**
1. Go to 'Konto'
2. Click on 'Overfør'
3. See modal placement

**Kirby version**
 - 0.0.142

**Expected behavior**
The modal should cover any bottom navigation (see attached screenshot)

**Screenshots**
Actual placement (iOS on the right)
<img width="811" alt="actual placement" src="https://user-images.githubusercontent.com/43847833/58076411-7343f100-7baa-11e9-9963-d073456bc02e.png">

Expected placement
![expected placement](https://user-images.githubusercontent.com/43847833/58076448-8ce53880-7baa-11e9-8088-f3e46cfbe22d.png)

**Native (please complete the following information):**
 - Device: iPhone6
 - OS: iOS 11.4

**Comment by unnamjolner** [comment]
As agreed with @mmmtrifork I will start out looking into if we can do something on the DRB side

**Comment by unnamjolner** [comment]
I have not found a solution, but 
If I open a modal from the HomeComponent (which is outside the tabview) it shows as expected on iOS. If I open from a component within a tabview, it shows wrong as on screenshot.

**Comment by labanos** [comment]
https://jira.bdpnet.dk/browse/RAOGF-851 shows a similar issue on android.

**Comment by bommariusser** [comment]
it's actually also an issue on the actionSheet @labanos @jakobe 

See screenshot below:

![Skærmbillede 2019-08-15 kl  09 12 14](https://user-images.githubusercontent.com/49033002/63078822-063bbf80-bf3d-11e9-92d7-7fef451a605f.png)

**Comment by mmmtrifork** [comment]
It would be useful to get the code for creating the tab navigation, so that we can try it in the kirby examples project, as we currently have no way of reproducing this in kirby

**Comment by unnamjolner** [comment]
Both navigation and modal will be different in native platforms soon. Closing the issue.
