### ISSUE TITLE
[BUG] Interaction with UI causes `Page` title to "flicker"

### ISSUE THREAD

**Issue by kodeaben** [kirbydesign/designsystem#2911]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
When interacting with the `Page` UI, the title "flickers" (see attatched)
## Describe how to reproduce the bug

1. Go to https://cookbook.kirby.design/#/home/showcase/page 
2. Scroll to the "Custom Title" example
3. In the mobile example viewer, scroll until the title is minimized in the toolbar
4. Keep an eye on the title and press the ellipsis button on the far right 

## Which Kirby version was used?
8.1.4

## What was the expected behavior?
The title not to flicker
## Add any screenshots

![title-flicker](https://user-images.githubusercontent.com/114976818/222417083-8fbcfb81-a65a-4566-a237-bd6555fb492e.gif)

## Are there any additional context?
It is worth to look into this PR: https://github.com/kirbydesign/designsystem/pull/2822
This is not the only place where this issue occurs.
<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [x] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/main/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [x] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by RasmusKjeldgaard** [comment]
Closed by reverting https://github.com/kirbydesign/designsystem/pull/2912
