### ISSUE TITLE
[Enhancement] Modal - margins and paddings

### ISSUE THREAD

**Issue by ckibsen** [kirbydesign/designsystem#292]
**Describe the solution you'd like**
.modal-wrapper has a padding-top og size('l').

On native devices the padding really should reflect the actual height of the status bar, eg. 20px on iPhone 6. 

However, a viable short term "quick enhancement" would be to use padding-top size('m') instead.

Moreover, the padding of .modal is currently specified as size('xs'). We need to be able to stretch our views all the way to the edge, so it really should be padding: 0;

**Describe alternatives you've considered**
n/a

**Additional context**

![Modal](https://user-images.githubusercontent.com/832287/58078945-30851780-7bb0-11e9-95b1-93b43a75cbb3.png)

### Kick Off:
- [ ] Accept Feature incl. name of component (DSL)
- [ ] Update Kirby Component Status and publish to [Kirby Cookbook](https://cookbook.kirby.design)
### Code:
- [ ] Create Feature Branch
- [ ] Implement Skeleton Component:
    - [ ] Web implementation
    - [ ] {N} implementation
- [ ] [Implement Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Add link to showcase on Kirby Component Status (`component-status-items.ts => code.cookbookUrl`)
- [ ] Also remove `githubIssueNo` and set `status` to `ItemCodeStatus.ready`
- [ ] Push commits to GitHub
### Review:
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- Merge to master and delete branch

**Comment by jakobe** [comment]
Top-margin: Won't fix.
Side-paddings: Fixed by #314
