### ISSUE TITLE
[BUG] page.component.ts triggers change detection excessively

### ISSUE THREAD

**Issue by NikolajSkousen** [kirbydesign/designsystem#2940]
When profiling an application using Kirby Design System using the page component results in an excessive amount of change detection cycles when scrolling the page. It seems to be the subscription on the ionScroll event that triggers it (see submitted video). 

https://user-images.githubusercontent.com/85226992/224697480-68b38490-a59c-4bf9-bbca-20ce98780a2d.mov

**Comment by mictro** [comment]
This bug report is duplicated in #2939
