### ISSUE TITLE
[BUG] When clicking on list item: No navigation to next page, browerser freezes

### ISSUE THREAD

**Issue by firdevs-yucelbas-jyskebank-dk** [kirbydesign/designsystem#2953]
- [ ] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
With kirby version 8.2 when navigating to "Forsikringer" from menu and clicking on Kirby list item the browser freezes and no navigation happens. No error messages are shown in the console. 

## Describe how to reproduce the bug

1. Go to 'Menu'
2. Click on 'Forsikringer'
3. Click on a list item
4. See error -->

## Which Kirby version was used?
8.2

## What was the expected behavior?
When clicking on the list item there should be navigated to a detailpage

## Please complete the following information:
- OS: Windows, MacOS
- Browser Chrome, Safari

## Are there any additional context?

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/main/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by alxzak** [comment]
N.S. mentions that it maybe have to do with the removal of the kirby-app and kirby-router-outlet, so that the CPU goes crazy and uses 120%. T.B. are looking into it.

**Comment by RasmusKjeldgaard** [comment]
Solved by @jakobe in https://github.com/kirbydesign/designsystem/pull/2931/commits/b48a3352f24482ddf08b47ff3915a8b124d30b86
