### ISSUE TITLE
Grid breakpoints should not take left-menu into account when calculate width-size [BUG]

### ISSUE THREAD

**Issue by Joeskov** [kirbydesign/designsystem#2982]
- [ ] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
Page Grid take left-side menu into account when calculate page px size.
When the menu is shown the grid size is 516px and not 768px.

## Which Kirby version was used?
Kirby 8.2

## Add any screenshots
![image (22)](https://user-images.githubusercontent.com/88030854/231179001-6b705ee6-eb4e-4e7a-9c62-bd90a0d0aa46.png)

## Please complete the following information:
- Browser with viewport 516px - 768px.

## Are there any additional context?

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing]

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/main/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by mark-drastrup** [comment]
I am closing this issue for now. According to the UX team it is correct that the grid adjusts itself based on the viewport, even if the left menu is present.
