### ISSUE TITLE
[BUG] Navigating with browser back/forward while modal is open will navigate openerpage

### ISSUE THREAD

**Issue by MonsterGameDev** [kirbydesign/designsystem#2986]
- [ x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
When opening a modal and using back/forward functionality on web will navigate the opener-window and keep the modal on top

## Describe how to reproduce the bug

1. Go to "Til dig"
2. Click on Betal og overfør
3. Click "Back" in browser
4. Opener (the page from where the modal was opened)  will navigate and leave the modal where it is. Now the modal is orphanned and has lost its logic connection to the opener.  fx. onClose functions will not work.

## Which Kirby version was used?
It has allways been like this

## What was the expected behavior?
Either the back button should not work at all - or it should reproduce the browsers former state - like closing the modal before navigating the opener

## Please complete the following information:
- All OS
- All Browsers
- Probably all versions after IE-2.0 :-)

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/main/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by RasmusKjeldgaard** [comment]
This is easily reproducible in our cookbook, https://cookbook.kirby.design/#/home/showcase/modal, by pressing 'Show Modal' and then navigating back with the browser back button.
