### ISSUE TITLE
Placeholder style til Kirby Item

### ISSUE THREAD

**Issue by Lars-UX** [kirbydesign/designsystem#2989]
## Describe the enhancement
Placeholder style til Kirby Item

## Describe the solution you'd like
Jeg vil gerne have mulighed for at kunne give title i item samme style som placeholder text i input, så det bliver tydeligt for brugeren at se, at brugeren mangler at foretage et valg.

<img width="375" alt="image" src="https://github.com/kirbydesign/designsystem/assets/123079811/22e916c6-ec9f-437c-bfe9-085d4b53a4c6">

## Have you considered any alternatives?
Hvis muligt, bør man selvfølgelig bruge en default-value. Men nogle gang er vi nødt til at bede brugeren om at foretage et valg.

## Are there any additional context?
Vi har behovet i forbindelse med at gøre **Overfør og betal** klar til web.

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Refinement

- [ ] Request that the issue is [UX refined](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#ux-refinement); do not proceed until this is done.
- [ ] Request that the issue is [tech refined](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#tech-refinement); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Publish a WIP implementation to Github as a draft PR and ask for feedback. 
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Update the [cookbook](https://cookbook.kirby.design) with examples and showcases.

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request. If you created a draft PR during implementation you can just mark that as "ready for review".

**Comment by alxzak** [comment]
@Lars-UX Could you provide a visual presentation of, what you would like?

**Comment by Lars-UX** [comment]
Har indsat skærmbillede @alxzak
