### ISSUE TITLE
[Enhancement] Avatar scaling not needed (right now)

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#299]
**Is your enhancement request related to a problem? Please describe.**
Our avatars scale (get bigger) on bigger screensizes. This is not actually a feature we need (right now) :) Our avatars stay the same on all screensizes.

Maybe this could be a property to turn on/off?

**Comment by jakobe** [comment]
We should remove the responsiveness (media queries) and only allow explicit sizes.
