### ISSUE TITLE
[Enhancement] Smaller Checkboxes

### ISSUE THREAD

**Issue by MartinCBBankdata** [kirbydesign/designsystem#2991]
## Describe the enhancement
Smaller Checkboxes that is 16x16 this might be a bug because the xs options gives a 24x24px so does sm and md. 

## Describe the solution you'd like
Checkboxes that are 16x16px
![image](https://user-images.githubusercontent.com/110449604/232040473-a376db12-3673-4d03-ba7e-c330db8f286e.png)

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Refinement

- [ ] Request that the issue is [UX refined](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#ux-refinement); do not proceed until this is done.
- [ ] Request that the issue is [tech refined](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#tech-refinement); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Publish a WIP implementation to Github as a draft PR and ask for feedback. 
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Update the [cookbook](https://cookbook.kirby.design) with examples and showcases.

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request. If you created a draft PR during implementation you can just mark that as "ready for review".

**Comment by henrikvoetmand** [comment]
It could be valid to have smaller checkboxes.
We need to design it.

**Comment by simonequach** [comment]
We **need** smaller checkboxes for web, especially for our Business sites, which are an Expert system, that requires more information on one page than private customers do. 

We have previously tried in MEP with 24*24px to the dismay of the users are they end up seeing less information and need to scroll more. They still to not like it after 2 years and are still requesting a more compressed view. In Online Business Banking we have lots of clients with 100+ accounts that we need to consider than so far the feedback from our tests is that the tables (with large checkboxes) take up way to much space.
