### ISSUE TITLE
[BUG] kirby-button in page footer is too wide

### ISSUE THREAD

**Issue by kodeaben** [kirbydesign/designsystem#2994]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
When placing a `kirby-button` in a `page-footer`, the button gets too wide and the second button isn't shown at all.

## Describe how to reproduce the bug
This [stackblitz](https://stackblitz.com/edit/angular-pifehw?file=src/kirby-demo/kirby-demo.component.html) link, demonstrates the issue. 

The code in question is the following snippet:
``` html
 <kirby-page-footer>
    <kirby-item>
      <button class="reject" kirby-button attentionLevel="3">
        <ng-container>Accepter valgte</ng-container>
      </button>
      <button class="accept-button" kirby-button>Accepter alle</button>
    </kirby-item>
  </kirby-page-footer>
```

If version 8.1.4 is installed in the stackblitz example, the buttons are shown as follows: 
![Screenshot 2023-04-17 at 13 38 42](https://user-images.githubusercontent.com/114976818/232473628-a2459ee4-535e-4a27-80d1-18af026f61c1.png)

In the current version (8.3.1) however, it looks like this: 
![Screenshot 2023-04-17 at 13 40 31](https://user-images.githubusercontent.com/114976818/232473978-c5405866-3101-4e5e-b533-7da7988ce6b1.png)

## Which Kirby version was used?
8.3.1
## Are there any additional context?
Adding `slot=start` and `slot=end´ seems to fix the width issue.
<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/main/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by jakobe** [comment]
Closing as the example code is wrapping the buttons in a `kirby-item` which is not intended use.
Looks fine, when not wrapped:
![image](https://github.com/kirbydesign/designsystem/assets/9556693/95c21335-6ffc-4822-b5e1-56e16c3156da)
