### ISSUE TITLE
[Enhancement] Expose functionality to hide/show kirby-header elements in page toolbar

### ISSUE THREAD

**Issue by RasmusKjeldgaard** [kirbydesign/designsystem#2997]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the enhancement
Currently Kirby Page handles the showing and hiding of toolbar elements (page title and down the line also header actions on canvas). This is done with by observing intersection ratios of the title/header action elements inside `kirby-page-content`.

In complex use cases consumers can benefit from being able to define when toolbar content should be shown/hidden instead of it happening automatically. An example of this is Virtual Scrolling where the entire kirby-header might be added and removed from the DOM based on scroll distance from the top. 

I have made a simple implementation of such a use-case [here](https://stackblitz.com/edit/angular-qvaa3h?file=src/home/kirby-page-header-demo/kirby-page-header-demo.component.html), and it illustrates two challenges that need to be handled with this feature: 
 - **title** - the title is correctly initialized and will show in the toolbaron the initial scroll of the page. Once you scroll back to the top of the page and the header becomes visible again, the title is not hidden in the toolbar. This is possibly because the original title element inside the header has been removed and is no longer observed.
    - This is likely solved by allowing consumers to define when to hide/show the toolbar elements. 
- **header actions** - once the header is scrolled far enough out of view to be removed from the DOM the toolbar actions will disappear too. This is likely because once the element is removed, our conditional content projection logic for duplicating the actions from the header area to the toolbar no longer has any template to project.   

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Refinement

- [ ] Request that the issue is [UX refined](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#ux-refinement); do not proceed until this is done.
- [ ] Request that the issue is [tech refined](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#tech-refinement); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Publish a WIP implementation to Github as a draft PR and ask for feedback. 
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Update the [cookbook](https://cookbook.kirby.design) with examples and showcases.

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request. If you created a draft PR during implementation you can just mark that as "ready for review".

**Comment by jakobe** [comment]
Fixed in ##2988
