### ISSUE TITLE
[Enhancement] Enforce emphasizeActions

### ISSUE THREAD

**Issue by jvh2** [kirbydesign/designsystem#3017]
- [ ] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the enhancement
Som jeg forstår det er team kirby snart på vej med en ændring til kirby header (emphasizeActions=true) sådan at man på device kan placere sine knapper/action group under selve header title, men på web bliver de højre centreret ud for title. Vi har dog brug for at de altid er placeret under kirby header title, sådan at vi kan vide hvor stor viewporten bliver til virtual scroll. Vi har derfor brug for at enforce emphasizeActions, sådan at knapper/action group altid er placeret under kirby header title/subtitle underordnet skærmens bredde.

## Describe the solution you'd like
En mulig for at enforce emphasizeActions

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Refinement

- [ ] Request that the issue is [UX refined](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#ux-refinement); do not proceed until this is done.
- [ ] Request that the issue is [tech refined](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#tech-refinement); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Publish a WIP implementation to Github as a draft PR and ask for feedback. 
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Update the [cookbook](https://cookbook.kirby.design) with examples and showcases.

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request. If you created a draft PR during implementation you can just mark that as "ready for review".

**Comment by jakobe** [comment]
@jvh2 Da dette er lidt en corner-case ift. resten af vores scenarier, så laver vi ikke en decideret property til det.

I stedet har vi tilføjet en "hidden feature", hvor jeres team kan sætte klassen `.single-column` på `kirby-header`, som så enforcer samme enkelt-kolonne layout på desktop som på mobil.
