### ISSUE TITLE
[Enhancement] Kirby icon : missing icons

### ISSUE THREAD

**Issue by Ranjot-Kaur** [kirbydesign/designsystem#303]
**Describe the solution you'd like**
Below icons are needed
Back arrow, cross icon and link icon illustrated in attached screenshot
![image](https://user-images.githubusercontent.com/35022750/58172859-5ea14f00-7cb7-11e9-9d1b-0da03266de8b.png)
![image](https://user-images.githubusercontent.com/35022750/58172900-72e54c00-7cb7-11e9-9a9c-2d55541114d2.png)
![image](https://user-images.githubusercontent.com/35022750/58172946-990aec00-7cb7-11e9-9d2b-767319056dd2.png)

**Comment by bommariusser** [comment]
@Ranjot-Kaur The back and close button might already be inside the system, i'll ask and get back to you on this. Also the link icon has just been updated and looks like this now :) But lets keep in touch throughout the day and find a solution. I already contacted some help :) https://zpl.io/V0LYzKK

**Comment by bommariusser** [comment]
@Ranjot-Kaur plan was to make this today but there is no time. We are looking at this the next week and i will make a feature request for this so we will fix this accordingly to the right process :) ok for you?

**Comment by hafstad** [comment]
Will be fixed by #315, closing this
