### ISSUE TITLE
[Housekeeping] Remove Kodeaben as member

### ISSUE THREAD

**Issue by kodeaben** [kirbydesign/designsystem#3039]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 
I know you miss me, but you must let me go. I belong to someone else now...

![logo#4](https://user-images.githubusercontent.com/114976818/236122974-1f753f87-6d2b-4ae0-a543-102f19c33334.png)

**Comment by RasmusKjeldgaard** [comment]
Thanks for reminding us, done!
