### ISSUE TITLE
[BUG] toggle should not emit change event when checked is programatically set

### ISSUE THREAD

**Issue by RasmusKjeldgaard** [kirbydesign/designsystem#3047]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
kirby-toggle emits checkedChange its `checkedChange` event whenever the checked-input. 
This is not the expected behavior, and can cause logic to run that should only be activated on user input.

In this example with the angular material toggle nothing is logged to console before you manually toggle it: https://stackblitz.com/edit/mqhnz6?file=src%2Fapp%2Fslide-toggle-overview-example.html 
 
## Describe how to reproduce the bug

1. Go to https://cookbook.kirby.design/#/home/showcase/toggle
2. Inspect the first toggle and highlight it in the Elements tab in the inspector tab
3. Go to the console tab and input `$0.checked = true`
4. See that the checkedChange event from the example is fired, which it should only do when pressed by a user

## Which Kirby version was used?
8.4.2

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/main/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by mark-drastrup** [comment]
@RasmusKjeldgaard according to [this comment](https://github.com/ionic-team/ionic-framework/issues/19651#issuecomment-1309333507) from one of the Ionic maintainer it seems like this issue will be automatically fixed, when we upgrade to Ionic v.7.
