### ISSUE TITLE
[BUG] Modal close/submit buttons are below native navigation (web mobile) 

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#307]
**Describe the bug**
When you open the Kirby modal, either in DRB or on the cookbook, the native navigation bar is lying over the close button, so you can actually not close the modal.

Little note: You can actually scroll on the layer under the modal. This makes the navigation disappear but i dont think its intended :D 

**To Reproduce**
1. Go to 'indbakke/konto'.
2. Click on 'skriv besked/overfør penge'.
4. See error.

**Expected behavior**
We want the close button/modal to float underneath the navigation control.

**Screenshots**
![IMG_453C86224CBF-1](https://user-images.githubusercontent.com/49033002/58243714-79c09d00-7d51-11e9-8c94-5e120170eea5.jpeg)

**Desktop (please complete the following information):**
 - OS: iPhoneX (Web mobile)

**Comment by mmmtrifork** [comment]
Is this still an issue ?

**Comment by jakobe** [comment]
Closed by #314
