### ISSUE TITLE
Layout shift Calendar when scrolling trough months

### ISSUE THREAD

**Issue by bhojland** [kirbydesign/designsystem#3105]
- [ ] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the enhancement
Navigation arrows for selecting a month in Calendar change position when scrolling through the months. This is because some have an extra row because there are more days to choose from.

## Describe the solution you'd like
The navigation arrows are in a fixed position to make scrolling easier

## Have you considered any alternatives?
On modal it is fixed, but the problem is still there in the mobile app, where it is displayed in a drawer.)

## Are there any additional context? 
![issue layout shift calendar@1x](https://github.com/kirbydesign/designsystem/assets/135959293/bb0f4dc6-5496-41b8-8e71-d6dc3876a7af)

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Refinement

- [x] Request that the issue is [UX refined](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#ux-refinement); do not proceed until this is done.
- [x] Request that the issue is [tech refined](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#tech-refinement); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Publish a WIP implementation to Github as a draft PR and ask for feedback. 
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Update the [cookbook](https://cookbook.kirby.design) with examples and showcases.

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request. If you created a draft PR during implementation you can just mark that as "ready for review".

**Comment by RasmusKjeldgaard** [comment]
I think issues like this would be solved by always reserving place for a sixth row of weekdays, similar to how it is done in [Carbon](https://carbondesignsystem.com/components/date-picker/usage/), [MUI](https://mui.com/x/react-date-pickers/date-calendar/) or the built in [date picker interface](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date) in browsers like Chrome and Safari.
