### ISSUE TITLE
[BUG] FAB fires more then once

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#313]
**Describe the bug**
When pressing the FAB more than once, very fast, it fires more than once.

**To Reproduce**
1. Go to 'indbakke'
2. Click on 'opret ny besked' twice very fast
3. See at least 2 modals on top of each other

**Expected behavior**
Disable button upon first press

**Comment by jakobe** [comment]
Will be fixed by a `disableWhenSelected` property on kirby button used by FAB sheet (#229)

**Comment by jakobe** [comment]
Cannot reproduce
