### ISSUE TITLE
[BUG] Interaction states are missing on Kirby Table

### ISSUE THREAD

**Issue by dennispedersen-bd** [kirbydesign/designsystem#3132]
- [ ] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
 

The Kirby Data Tables does not have correct interaction states for hover, focus and pressed. It needs to work with the same states as an item in a list has. Navigation via keyboard tab does not work either.

## Add any screenshots

https://github.com/kirbydesign/designsystem/assets/70525609/7af69e28-60c8-4558-b980-a291bcaa1c52

## Please complete the following information:
- OS: [e.g. Windows, MacOS, iOS]
- Browser [e.g. Chrome, Safari]
- Browser version [e.g. 22]

## Are there any additional context?

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/main/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by RasmusKjeldgaard** [comment]
@dennispedersen-bd thanks for the heads up! Seems like the team needs to add the proper class for this to work. 

With `kirby-selectable-row` the correct hover-state should show. And once https://github.com/kirbydesign/designsystem/pull/3154 is merged, active (pressed) state will show correctly too. 

As for the keyboard-tab part of your inquiry, the Kirby Data Table does not offer any solution for tabbing to each table row, as a data table meant for data display is not really geared towards navigating on a row-click like this.  The selectable row class mentioned before is added to support common use-cases for selecting displayed data with a checkbox, similar to how e.g. [Carbon](https://carbondesignsystem.com/components/data-table/usage/#live-demo) or [MUI](https://mui.com/material-ui/react-table/#sorting-amp-selecting) does it, but we should [add a checkbox to the docs](https://github.com/kirbydesign/designsystem/issues/3196) to make it more clear!

What you could do to add navigation support is to surround the relevant data within one of your data cells with an anchor tag (adding an anchor-tag around the whole row is _not_ valid HTML) that redirects the user to the sub-page. In your example I think it would make sense to add the anchor tag to each cell in the column of names. This way your table supports navigation in a screen-reader friendly way out of the box, and it is much more clear what the user can expect to happen when they click the link.

![image](https://github.com/kirbydesign/designsystem/assets/42470636/e24a54bc-868a-4164-b778-b8a697899a12)

If you want to make the whole row clickable, you could navigate programmatically too, when users click somewhere else than the link.
