### ISSUE TITLE
[Enhancement] No shadow on Slider cards

### ISSUE THREAD

**Issue by henrikvoetmand** [kirbydesign/designsystem#3135]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the enhancement
The default cards has a drop shadow. When cards are used in Slider component, the card shadow is hidden by the "swiper-container" (overflow = hidden). The result is that the cards does not look right.

We still need the "swiper-container" to hide the cards that are not in view.

## Describe the solution you'd like
Find a new way to hide cards not in view, but keep the card shadow visible.

## Have you considered any alternatives?
No

## Are there any additional context?
**Card shadow hidden:**
![Skærmbillede 2023-06-29 kl  10 35 19](https://github.com/kirbydesign/designsystem/assets/71710012/b16e1771-643b-4bc1-83b4-e6d572f5228f)

**Card shadow NOT hidden:**
<img width="1013" alt="Skærmbillede 2023-06-29 kl  10 43 08" src="https://github.com/kirbydesign/designsystem/assets/71710012/0eacdc7f-5379-4993-8868-76e50544be89">

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Refinement

- [ ] Request that the issue is [UX refined](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#ux-refinement); do not proceed until this is done.
- [ ] Request that the issue is [tech refined](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#tech-refinement); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Publish a WIP implementation to Github as a draft PR and ask for feedback. 
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Update the [cookbook](https://cookbook.kirby.design) with examples and showcases.

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request. If you created a draft PR during implementation you can just mark that as "ready for review".

**Comment by troelslenda** [comment]
I noticed the same. Here I changed kirby-card box-shadow to red to provide better visuals.
![image](https://github.com/kirbydesign/designsystem/assets/263060/dcb28690-3de5-4ef0-b829-a144c742ec27)

**Comment by troelslenda** [comment]
![image](https://github.com/kirbydesign/designsystem/assets/263060/574a6232-0f8a-4f1d-b691-61f39790909a)
