### ISSUE TITLE
Add all general icons 

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#315]
**Is your enhancement request related to a problem? Please describe.**
We would like to add all general icons, like navigation, link, settings etc. so that everyone can use them in their respective areas. So that we use the same icons cross platform.

See also: https://app.zeplin.io/project/5c99d69a79d02b35ea3b8f41/styleguide/components?cseid=5ca73870a994f9598bccef93

**Comment by hafstad** [comment]
should be fixed by #366
