### ISSUE TITLE
[BUG] Fix alert overlay issue in Firefox

### ISSUE THREAD

**Issue by mark-drastrup** [kirbydesign/designsystem#3179]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
When opening the alert in the cookbook in Firefox 

In Firefox the alert has some overlay / stacking issues. When the alert is opened the dialog will not show, and some elements in the cookbook, like the side-nav and code snippets, will lie on top of the backdrop (see screenshot). When the user interacts with the page again the alert will appear as expected. 

It should be verified if this bug only appears in the cookbook, or if it is a general issue in Kirby.

## Describe how to reproduce the bug
1. Go to https://cookbook.kirby.design/#/home/showcase/alert using Firefox
2. Click on 'Show alert'
3. Now the bug should appear
4. Interact with the page again
5. Now the alert should appear as expected

## Which Kirby version was used?
8.10.0 

## What was the expected behavior?
The alert will appear immediately like in Chrome and Safari.

## Add any screenshots
![Screenshot 2023-07-28 at 12 20 22](https://github.com/kirbydesign/designsystem/assets/20282214/2de3bfb6-0177-4d87-bc1b-b1cda6b19a93)

## Please complete the following information:
- OS: MacOS
- Browser: Firefox
- Browser version: 113.0.2

## Are there any additional context?
No

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/main/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by RasmusKjeldgaard** [comment]
No longer an issue, tested on Firefox 131.0.3
