### ISSUE TITLE
[BUG] Dropdown not updating with empty placeholder

### ISSUE THREAD

**Issue by JacobOJ** [kirbydesign/designsystem#3203]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
If a kirby-dropdown has no initial value and the placeholder is '' (empty string), then the dropdown will not update correctly when selecting a value.

The value is selected correctly in the underlying model and the change handler is fired, but the view does not update to show the selected value.

A workaround is to use the placeholder ' ' (one space).

## Describe how to reproduce the bug
Create a kirby-dropdown with placeholder = '' and no initial value.
Select a value.
Selected option is not shown.

## Which Kirby version was used?
8.8.0

## What was the expected behavior?
I expect the value to update in the view.

## Add any screenshots
https://github.com/kirbydesign/designsystem/assets/5394976/8e1356b4-b3d2-48ca-af05-2a629a64c1dd

## Please complete the following information:
- OS: MacOS
- Browser Firefox
- Browser version 116.0.3

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/main/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by AgreSanGit** [comment]
It's not something we consider fixing. We recommend not to have a placeholder with no value, since it's bad UX. The bug only occurs when you set placeholder to no value, which we don't think should be a case. Thank you for your issue and bringing awareness to the bug.
