### ISSUE TITLE
[Enhancement] allow kirby-button on <a>  to get an anchor styled as a button

### ISSUE THREAD

**Issue by rsreimer** [kirbydesign/designsystem#3210]
Allow adding kirby-button on anchor tags, to get a link styled as a button.

Currently the alternative is using a <button> and calling window.open in a click event handler, however that is not preferable: https://developer.mozilla.org/en-US/docs/Web/API/Window/open#avoid_resorting_to_window.open

```html
<a kirby-button href="https://some-site.com" target="_blank">text</a>
<a kirby-button routerLink="/some-page">text</a>
```

**Comment by jonas-jyskebank-dk** [comment]
Er der behov for et mere generelt kig på behovet ux mæssigt? 
Vi har fx click handle på kirby items i en kirby list, der bruger window.open (EXTERNAL_LINKS_API) til at åbne i nyt tab i browseren når man trykker på et item.
