### ISSUE TITLE
[BUG] Cannot build on a completely new blank project (Swiper dependency)

### ISSUE THREAD

**Issue by Hykalos** [kirbydesign/designsystem#3222]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
When starting from scratch, the project doesn't build because a type in Swiper can't be found (SwiperOptions)

## Describe how to reproduce the bug

1. Set up a new empty Angular project
2. Use the guide to include Kirby to your project
3. Try and run the project

## Which Kirby version was used?
8.11.1

## What was the expected behavior?
The project runs

## Add any screenshots
![d6bd388c-d08e-45d6-9e8c-fa4048aceb42](https://github.com/kirbydesign/designsystem/assets/10938841/bc1275cd-0c65-483f-a4c5-c50349203395)

## Please complete the following information:
- OS: Windows
- Browser: Edge
- Browser version: 116.0.1938.54

## Are there any additional context?

Forcing swiper to be version 9.X works. The missing type doesn't exist in version 10.X

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/main/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](../CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by RasmusKjeldgaard** [comment]
Hi @Hykalos, thanks for bringing this to our attention!
A workaround until we have a fix for this is to install Swiper 9 manually in your project.

**Comment by RasmusKjeldgaard** [comment]
Verified, and reproducible with the following steps:
1. Create a new angular project, e.g. `npx -p @angular/cli ng new angular-16`
2. `npm i @kirbydesign/designsystem`
3. import `KirbyModule` in app module
5. `npm start`
