### ISSUE TITLE
[BUG] console warning when importing KirbyTestingModule in a test 

### ISSUE THREAD

**Issue by cpoulsen** [kirbydesign/designsystem#3225]
## Describe the bug
When importing `KirbyTestingModule` in a jest test, console warnings are thrown with a "Component ID generation collision detected" with selector `kirby-page-title`
 

## Describe how to reproduce the bug
`imports: [KirbyTestingModule]` in a jest test when creating a component

## Which Kirby version was used?
8.11.1, but has been an issue for quite a few major releases

## What was the expected behavior?
To now throw a console warning. The massive output from the logs is slowing test execution

## Add any screenshots
![image](https://github.com/kirbydesign/designsystem/assets/26800068/c5bad3d3-7c16-4714-8bc5-f5956fdeb603)

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/main/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](../CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by RasmusKjeldgaard** [comment]
I tested this in a completely fresh project too, with no jest dependency, and get the same warning.

Steps to reproduce is:

1. Create a new angular project, e.g. `npx -p @angular/cli ng new angular-16`
2. `npm i @kirbydesign/designsystem`
3. (Install swiper v9.x.x to workaround [possible swiper error](https://github.com/kirbydesign/designsystem/issues/3222))
4. Import KirbyTestingBaseModule in the autogenerated test suite in `app.component.spec.ts` 

```
 import { TestBed } from '@angular/core/testing';
 import { AppComponent } from './app.component';
+import {KirbyTestingBaseModule } from '@kirbydesign/designsystem/testing-base'

 describe('AppComponent', () => {
   beforeEach(() => TestBed.configureTestingModule({
-    declarations: [AppComponent]
+    declarations: [AppComponent],
+    imports: [KirbyTestingBaseModule]
   }));
```
