### ISSUE TITLE
[ENHANCEMENT] Allow browser UI for picking date via date component

### ISSUE THREAD

**Issue by NillerW** [kirbydesign/designsystem#3235]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the enhancement

The Kirby input-field of type date should support selecting a date using the browsers native date picker. 

## Describe the solution you'd like

The Kirby input-field should be able to open a date picker for selecting a date.

- [ ] The date picker should use the browsers native implementation

## Have you considered any alternatives?

Later on a custom date picker (using Kirby `Calendar` component) can be created and replace the browsers default, but to have a MVP the date picker should simply be the browsers default.

## Are there any additional context?
In issue #3234 a calendar icon will be added. Clicking this icon should open the date picker.

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Refinement

- [x] Request that the issue is [UX refined](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#ux-refinement); do not proceed until this is done.
- [x] Request that the issue is [tech refined](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#tech-refinement); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](../CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Publish a WIP implementation to Github as a draft PR and ask for feedback. 
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Update the [cookbook](https://cookbook.kirby.design) with examples and showcases.

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request. If you created a draft PR during implementation you can just mark that as "ready for review".

**Comment by alxzak** [comment]
We recieved this bugdescription during af bughunt, please test if the new version supports this: He couldn't select October 2nd while the calendar was in September - had to press "month forward" to October before October 2nd could be selected, even though October 2nd was visible in the September selector (bug)

**Comment by jkaltoft** [comment]
**iPhone 15 Pro Simulator**

<table><tr>
<td><img src="https://github.com/kirbydesign/designsystem/assets/150451/ea9c262f-941b-40ca-b790-a25f575f7b9c"></td>
<td><img src="https://github.com/kirbydesign/designsystem/assets/150451/7700de83-289f-44dc-a46b-e81be811ca73"></td>
<td><img src="https://github.com/kirbydesign/designsystem/assets/150451/66b45005-d986-4116-93c3-40d75fa49e4d"></td>
</tr></table>

**Comment by jkaltoft** [comment]
**Safari**

![image](https://github.com/kirbydesign/designsystem/assets/150451/53835d0b-0b3c-45f2-8701-91bffdcb4a3a)


![Safari Screenshot 2023-11-13 at 15 49 31](https://github.com/kirbydesign/designsystem/assets/150451/2f7bab6b-c21d-4e04-82bb-a20e895f52ea)
![Safari Screenshot 2023-11-13 at 15 49 49](https://github.com/kirbydesign/designsystem/assets/150451/faa7786e-d2d8-43b3-8797-2b6d8d23289e)

![image](https://github.com/kirbydesign/designsystem/assets/150451/4c650b92-7148-4f03-8ce7-109af4c5812c)

**Comment by jkaltoft** [comment]
**Firefox**

![image](https://github.com/kirbydesign/designsystem/assets/150451/f1b6afe8-7d6a-40f7-9c82-2f1be1fd0c3b)

![Firefox Screenshot 2023-11-13 at 15 50 55](https://github.com/kirbydesign/designsystem/assets/150451/8818023c-8637-47a2-8181-dd1e3ddb4556)
![Firefox Screenshot 2023-11-13 at 15 51 01](https://github.com/kirbydesign/designsystem/assets/150451/4f4f7a8b-4798-4e08-96e7-7838121a7ffc)
![Firefox Screenshot 2023-11-13 at 15 51 15](https://github.com/kirbydesign/designsystem/assets/150451/8a521d28-5aeb-4c2a-859c-bcbda38f4ace)

**Comment by jkaltoft** [comment]
**Chrome**

![image](https://github.com/kirbydesign/designsystem/assets/150451/cd211fa5-aede-4e12-b5e1-e5b947ef8aeb)

![Chrome Screenshot 2023-11-13 at 15 51 46](https://github.com/kirbydesign/designsystem/assets/150451/dfd75387-9519-492f-83f0-442f579e993a)
![Chrome Screenshot 2023-11-13 at 15 53 41](https://github.com/kirbydesign/designsystem/assets/150451/d29c77c3-178f-4bab-85f5-90e21581e4ed)
![Chrome Screenshot 2023-11-13 at 15 51 55](https://github.com/kirbydesign/designsystem/assets/150451/1cf9f239-c2f1-4af7-880a-52bc80c5de96)

**Comment by jkaltoft** [comment]
**Edge**

Language set to Danish on OS level.

![image](https://github.com/kirbydesign/designsystem/assets/150451/22355d91-111e-4e53-9804-14f968a436d8)

![Edge Screenshot 2023-11-13 at 15 51 59](https://github.com/kirbydesign/designsystem/assets/150451/4b0200e9-09e8-4c68-bb45-46e758e46054)
![Edge Screenshot 2023-11-13 at 15 54 02](https://github.com/kirbydesign/designsystem/assets/150451/a2da1996-5358-4d1d-a8bb-324f12e05663)
![Edge Screenshot 2023-11-13 at 15 52 10](https://github.com/kirbydesign/designsystem/assets/150451/aed9d520-9f2a-4ba3-a217-f2cb5986100f)
