### ISSUE TITLE
[Enhancement] Segmented controls should be the same size

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#326]
**Describe the bug**
When looking at the segmented-control, the two buttons are not the same size, see also. 
![Production](https://user-images.githubusercontent.com/49033002/58459802-84ea4300-812c-11e9-8329-2d0b6fe460ff.png)

**To Reproduce**
1. Go to 'inbox'
2. See error

**Expected behavior**
The two buttons should be the same size. The control will still feel bigger because the selected button will be on top, but technically it's the same size. See also:

![Intended Design](https://user-images.githubusercontent.com/49033002/58459803-84ea4300-812c-11e9-828b-8722e5f2631e.png)

**Screenshots**
How should it work in inbox: 
https://zpl.io/29OYzvW

**Desktop (please complete the following information):**
All platforms 

**Native (please complete the following information):**
All platforms

**Comment by jakobe** [comment]
What to do if text is really long? What should be the min-width??
