### ISSUE TITLE
kirby-dropdown is cut off by kirby-card, and dropdown property usePopover is not documented.[BUG]

### ISSUE THREAD

**Issue by joachimboggild** [kirbydesign/designsystem#3265]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
If I try to use the <kirby-dropdown> component inside a <kirby-card>, the dropdown is cut off by the card. After searching for a while, I found out by accident that there is a property called UsePopover that can be used for this very purpose.

It seems strange that this behaviour is not enabled by default. Furthermore, the usePopover property is not listed in the available properties in the cookbook at https://cookbook.kirby.design/#/home/showcase/dropdown. This makes it hard to cope with the problem.

## Describe how to reproduce the bug
- Implement a<kirby-dropdown> component inside a <kirby-card>
- View the page
- Open the dropdown
- See that the dropdown is cut off by the card

## Which Kirby version was used?
8.11.2

## What was the expected behavior?
Top wish: That the dropdown floats above other parts of the page and is not cut off
Second priority: That the usePopover property is mentioned on the cookbook page

## Add any screenshots
![image](https://github.com/kirbydesign/designsystem/assets/8225312/fa1f0b05-1eb8-4162-81b1-5420398cd2a8)

## Please complete the following information:
- OS: Windows
- Chrome
- Browser version : 117.0.5938.132 

## Are there any additional context?

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/main/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](../CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by RasmusKjeldgaard** [comment]
Thanks for reporting! `usePopover` is not documented because it has been considered experimental, and we are looking at replacing it with a better default behavior that reuses our floating-ui util from `kirby-menu` to position itself. This task is on the backlog and we will look at it in one of the coming sprints! 🎉 

For this reason I will close this issue as a duplicate, see more on #2433 #3090 #2605
