### ISSUE TITLE
[Enhancement] Sticky button on top of keyboard on input (native)

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#328]
**Is your enhancement request related to a problem? Please describe.**
We would like a button behavior where it gets sticky when typing in a input field.

**Describe the solution you'd like**

Keyboard visible: https://zpl.io/2jQEkGx
Keyboard hidden: https://zpl.io/29OkB0B

**Comment by jakobe** [comment]
Could be related to the screen being opened in a modal (keyboard doesn't take height of window put slides on top of content instead...)

**Comment by labanos** [comment]
#653 could be solved in combination

**Comment by labanos** [comment]
cases are ok buttons when there is an input inside a modal... eg new message, transfer, buy paper..
