### ISSUE TITLE
[Enhancement] Decoration colors override for SPKS

### ISSUE THREAD

**Issue by henrikvoetmand** [kirbydesign/designsystem#3291]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the enhancement
Now that we have introduced new Decoration colors in Kirby, we need a way to override a range of colors en DRB for Sparekassen Sj-Fyn.

## Describe the solution you'd like
Override color variable values for Green and Yellow according to:
https://zpl.io/mDgKZ06

The variables in question to override are `$decoration-colors` and `$text-colors` and can be overridden using `map.set` or `map.merge`:

```scss
@use 'sass:map';

$decoration-colors: map.merge($decoration-colors, (
  "green": (
      10: #112233,
      20: #445566,
      30: #778899,
      ...,
    ),
    "yellow": (
      10: #112233,
      20: #445566,
      30: #778899,
      ...,
    )
  )
); 

$text-colors: map.merge($text-colors, (
    'positive': map.get($decoration-colors, 'green', 80),
    'negative': map.get($decoration-colors, 'red', 70),
  )
);
```

## Have you considered any alternatives?
No!

## Are there any additional context?
![Decoration colors - SPKS](https://github.com/kirbydesign/designsystem/assets/71710012/be75f6d2-3946-4a89-be59-e839248812d1)

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Refinement

- [ ] Request that the issue is [UX refined](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#ux-refinement); do not proceed until this is done.
- [ ] Request that the issue is [tech refined](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#tech-refinement); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](../CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Publish a WIP implementation to Github as a draft PR and ask for feedback. 
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Update the [cookbook](https://cookbook.kirby.design) with examples and showcases.

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request. If you created a draft PR during implementation you can just mark that as "ready for review".

**Comment by jakobe** [comment]
Done 👍
