### ISSUE TITLE
[Enhancement] Wrapper for FAB that doesn't block content

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#333]
**Is your enhancement request related to a problem? Please describe.**
The FAB doesn't have a container to place it the right place right now, and it actually blocks the content to the left of the fab. So we need a way to fix that 🗡 💃 See also attachment below

<img width="1482" alt="Skærmbillede 2019-06-04 kl  19 28 36" src="https://user-images.githubusercontent.com/49033002/58900283-2c541080-86ff-11e9-86e6-c89e7fb3a71f.png">

**Comment by hafstad** [comment]
This will be fixed by #345
