### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by saxjax** [kirbydesign/designsystem#3334]
- [ ] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
kirby9 can't be installed on Angular17 using `ng add `

## Describe how to reproduce the bug
1. create a new angular project
2. add kirby9 using : `ng add @kirbydesign/designsystem@9.0.0`

## Which Kirby version was used?
9.0.0

## What was the expected behavior?
Kirby9 should be installed, ready for use.

## Add any screenshots

<img width="1694" alt="image" src="https://github.com/kirbydesign/designsystem/assets/26431451/d6abef22-a287-4207-bfde-d9741768d233">

## Please complete the following information:
- OS:macOS 13.4
- VSC

**Comment by RasmusKjeldgaard** [comment]
This is working as intended, as Kirby has only been tested with Angular 16.
For clarity, I have created #3336.
