### ISSUE TITLE
[Enhancement] Baked-in dividers

### ISSUE THREAD

**Issue by jakobe** [kirbydesign/designsystem#338]
**Describe the solution you'd like**
We have different ways of seperating content dependant on the underlying content.

on canvas: https://zpl.io/blD3xq1
on white: https://zpl.io/a31EO51

See also: https://zpl.io/boDW5Wg

We should create dividers *within* the following components:
- [ ] Card
- [ ] List item (already there, but same color as the list item => fix)
- [ ] List/list items *within* action sheet
- [ ] Anything else...?

**Comment by MortenGregersen** [comment]
Maybe we should consider how the divider is shown on a card with shadow. In the screenshot mentioned, the divider has the same color as the background and the card has no shadow - it makes it look like the card is cut in half. This isn't possible when the card has a shadow.
