### ISSUE TITLE
[Enhancement] Button attention levels

### ISSUE THREAD

**Issue by mmmtrifork** [kirbydesign/designsystem#339]
Closes #266

https://zpl.io/VDKnZAl
Update button so that we: 
- [x] remove themeColor
- [x] isDestructive="true|false"
- [x] Add attentionLevel="1-4" (defaults to 1)
- [x] Map attentionLevel to colors:
- [x] 1 = primary fill/outline
- [x] 2 = white fill/outline
- [x] 3 = "medium" outline
- [x] 4 = no fill/outline
- [x] Add :host-context(.something greenish) and change color to match (e.g. white button on green card)
- [x] Check hover/press states for colors on Button

**Comment by jakobe** [comment]
Closed by #351
