### ISSUE TITLE
[Enhancement] Add min-width to chip in Segmented Control compact mode

### ISSUE THREAD

**Issue by dennispedersen-bd** [kirbydesign/designsystem#3416]
- [ ] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
 
The small chip is not circular. There is 1px difference in the ratio.

<img width="867" alt="Skærmbillede 2024-03-14 kl  15 41 06" src="https://github.com/kirbydesign/designsystem/assets/70525609/b2eb4271-6a12-4cb5-a2b4-06416c608028">

## Please complete the following information:
- OS: [e.g. Windows, MacOS, iOS]
- Browser [e.g. Chrome, Safari]
- Browser version [e.g. 22]

## Are there any additional context?

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/develop/.github/SUPPORT.md#team-kirby); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by RasmusKjeldgaard** [comment]
This is working as intended, as the chips width is dependent on its content. So for instance, with my selected text size in the browser this chip will be round: 
<img width="374" alt="image" src="https://github.com/kirbydesign/designsystem/assets/42470636/6b6f9a47-4cf5-43b9-a9e6-adb2cbcdc864">
While this will not: 
<img width="419" alt="image" src="https://github.com/kirbydesign/designsystem/assets/42470636/35972718-95ae-49d7-af51-ef6253830346">

If the segmented control should support circular chips, please consider submitting an enhancement.

**Comment by RasmusKjeldgaard** [comment]
Reopening as a request for added functionality to the chip, as this is not a bug.

**Comment by dennispedersen-bd** [comment]
![Artboard](https://github.com/kirbydesign/designsystem/assets/70525609/2d27f1f0-9d1e-43d9-842b-13c3679a817d)
Design spec on minimum width.
