### ISSUE TITLE
[Enhancement] Kirby Header: allow more horizontal space for page title and sub

### ISSUE THREAD

**Issue by simonequach** [kirbydesign/designsystem#3428]
## Describe the enhancement
A simple Kirby Header, which only consist of a Title and subtitles, currently cuts off customers or page name due to the fact that they are only allowed to fill half the slot of the component, as the rest is "saved" for potentiel action buttons, which are not present on all pages. 

This is a huge UI issue on Desktop, as we are seeing page titles and customer names either being cut off or broken down into several lines, pushing the content further down the page. Despite the fact that there are plenty of room on the righthand side of the page. Making it look unprofessional. 

## Describe the solution you'd like
If there are no actions or items in the later part of the component. It is expected that Title and subtitle are allowed to fill out the entire space of the component.

On desktop:
- Allow page title and sub to use all horizontal space, when there are no action buttons present in the header.
- Allow page title and sub to use all available horizontal space, when there are action buttons in the header.

## Have you considered any alternatives?
No.

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#the-process-of-contributing) correctly.

### Refinement

- [ ] Request that the issue is [UX refined](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#ux-refinement)
- [ ] Request that the issue is [tech refined](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#tech-refinement); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](../CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Publish a WIP implementation to Github as a draft PR and ask for feedback. 
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Update the [cookbook](https://cookbook.kirby.design) with examples and showcases.

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request. If you created a draft PR during implementation you can just mark that as "ready for review".

**Comment by henrikvoetmand** [comment]
![Image](https://github.com/kirbydesign/designsystem/assets/71710012/7115da8d-ccf2-4d55-bcc7-7e05baf663e1)
