### ISSUE TITLE
Page-template

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#345]
**Describe the solution you'd like**
Vi har en generel udfordring i programmet at UI elementer som er helt generelle, er forskelligt bygget op alt efter hvor vi kigger i hhv. team og/eller platform (native/web).

Se også https://developer.microsoft.com/en-us/azure-devops/components/page og https://developer.microsoft.com/en-us/azure-devops/components/header som inspiration

**Heri indgår:**

Page title
Tilbage knap (web)
Afstande til kant osv. #475 
Grid (1 vs. 2kolonner)
Sammenspil mellem de ovennævnte og Tab og Actionbar på hhv. native og web er heller ikke ensrettet.
Evt. også placering af komponenter som empty-state

 

Forneden findes der et screenshot hvordan det ser ud i produktion.

![Skærmbillede 2019-06-07 kl  13 38 13](https://user-images.githubusercontent.com/49033002/59101500-74ef1200-8929-11e9-8e1b-93a9d276fe5a.png)

Og hvordan det burde virke

![Skærmbillede 2019-06-07 kl  13 38 21](https://user-images.githubusercontent.com/49033002/59101523-86381e80-8929-11e9-9cf3-cd57582c8491.png)

 

--- 

 

Heri indgår også princippet om at scrolle ned og vise page-title i toppen (actionbar) på native. 

### Kick Off:
- [ ] Accept Feature incl. name of component (DSL)
- [ ] Update Kirby Component Status and publish to [Kirby Cookbook](https://cookbook.kirby.design)
### Code:
- [ ] Create Feature Branch
- [ ] Implement Skeleton Component:
    - [ ] Web implementation
    - [ ] {N} implementation
- [ ] [Implement Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Add link to showcase on Kirby Component Status (`component-status-items.ts => code.cookbookUrl`)
- [ ] Also remove `githubIssueNo` and set `status` to `ItemCodeStatus.ready`
- [ ] Push commits to GitHub
### Review:
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- Merge to master and delete branch

**Comment by hafstad** [comment]
**Whoever doing this please have ion-app and ion-content in mind for web**

**Comment by bommariusser** [comment]
Maybe the EmptyState placement on the site should be baked into this component. @hafstad and me talked about baking it in here instead.
