### ISSUE TITLE
[Enhancement] Show some part of segmented chip in the view port when there is more content towards right

### ISSUE THREAD

**Issue by Ranjot-Kaur** [kirbydesign/designsystem#346]
**Is your enhancement request related to a problem? Please describe.**
User is not able to understand that there are more chips on the right.

**Describe the solution you'd like**
When number of segmented chips are more and can not be accommodated in view port, then some part of last segmented chip in viewport should be visible so that user gets to know that the section is horizontally scrollable.

**Describe alternatives you've considered**
NA

**Additional context**
<img width="141" alt="Skærmbillede 2019-03-12 kl  14 30 27" src="https://user-images.githubusercontent.com/35022750/59185422-0ced3580-8b8e-11e9-8e1c-c6449d96f359.png">

**Comment by labanos** [comment]
Needs to be specified by UX - how should this look (also taking other background colors into account)

**Comment by bommariusser** [comment]
<img width="649" alt="Chip" src="https://user-images.githubusercontent.com/49033002/61814952-7cbb3500-ae49-11e9-8a0d-ef1d477c6d60.png">

**Comment by bommariusser** [comment]
<img width="941" alt="Skærmbillede 2019-07-24 kl  19 38 37" src="https://user-images.githubusercontent.com/49033002/61815505-ac1e7180-ae4a-11e9-8b49-4d0a889a1576.png">

**Comment by bommariusser** [comment]
@hafstad is this a valid solution? :D

**Comment by bommariusser** [comment]
See also https://sketch.cloud/s/7dl5Y/p/chip

**Comment by bommariusser** [comment]
We actually decided that chips are going to have some kind of fill on unselected, so that they are actually going to be more visible, when outside the view. We actually don't see this as an issue anymore. see also:

![Skærmbillede 2019-08-09 kl  12 55 30](https://user-images.githubusercontent.com/49033002/62774404-e885da80-baa4-11e9-9a64-96fde01c245b.png)
