### ISSUE TITLE
[Housekeeping] Remove deprecated use of `icon.customName` in cookbook

### ISSUE THREAD

**Issue by jakobe** [kirbydesign/designsystem#3480]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the housekeeping request

As `icon.customName` has been deprecated we shouldn't promote it's use in the cookbook.
Change to `icon.name` on the following pages:

- [x] Button
- [x] Empty State

## Have you considered any alternatives?

No.

## Are there any additional context?

No.

**Comment by jkaltoft** [comment]
@jakobe @RasmusKjeldgaard Should we remove `customName` from the properties table on https://cookbook.kirby.design/#/home/showcase/icon too?

![image](https://github.com/kirbydesign/designsystem/assets/150451/aa6ae06b-0462-4550-8737-08267faee801)

**Comment by RasmusKjeldgaard** [comment]
> @jakobe @RasmusKjeldgaard Should we remove `customName` from the properties table on https://cookbook.kirby.design/#/home/showcase/icon too?

We have a separate issue for that [here](https://github.com/kirbydesign/designsystem/issues/3472), so my suggestion is to bundle that with the other v10 changes.
