### ISSUE TITLE
[COMPONENT] Toggle

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#349]
**Describe the solution you'd like**
Toggles change the state of a single option. Toggles can be switched on or off by pressing or swiping them. They can also be checked programmatically by setting the checked property.

**Additional context**
https://ionicframework.com/docs/api/toggle
https://docs.nativescript.org/angular/ui/ng-ui-widgets/switch

ios and web looks like ios 
android looks like android

Colors are coming from kirby

Se også her for at se hvordan vi kommer til at bruge det:
https://zpl.io/beKAX3B

### Kick Off:
- [x] Accept Feature incl. name of component (DSL)
- [x] Update Kirby Component Status and publish to [Kirby Cookbook](https://cookbook.kirby.design)
### Code:
- [x] Create Feature Branch
- [x] Implement Skeleton Component:
    - [x] Web implementation
    - [x] {N} implementation
- [x] [Implement Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [x] Add link to showcase on Kirby Component Status (`component-status-items.ts => code.cookbookUrl`)
- [x] Also remove `githubIssueNo` and set `status` to `ItemCodeStatus.ready`
- [x] Push commits to GitHub
### Review:
- [x] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- Merge to master and delete branch

**Comment by jakobe** [comment]
Closed by #355
