### ISSUE TITLE
[Enhancement]Add Icons to Kirby

### ISSUE THREAD

**Issue by henrikvoetmand** [kirbydesign/designsystem#3491]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the enhancement
We need some icons in Kirby

## Describe the solution you'd like
Upload the attached icons to Kirby

## Have you considered any alternatives?
No!

## Are there any additional context?
**expand**
![expand](https://github.com/kirbydesign/designsystem/assets/71710012/a839f85c-fe35-460a-bd99-edb532c22255)
**contract**
![contract](https://github.com/kirbydesign/designsystem/assets/71710012/27f09f36-f475-4491-9ec6-d32cd8ccb08d)
**house**
![house](https://github.com/user-attachments/assets/760a9ba0-b16e-49a6-81c7-6d589b1188c6)
**tractor**
![tractor](https://github.com/user-attachments/assets/a71df74b-57d7-4931-b700-0fcf072afded)
**flower**
![flower](https://github.com/user-attachments/assets/bc2ab2e5-0dc2-46a4-aac6-2db752a752fb)
**basket**
![basket](https://github.com/user-attachments/assets/16680cbf-631c-4d0e-a82f-60c45dc12292)

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#the-process-of-contributing) correctly.

### Refinement

- [ ] Request that the issue is [UX refined](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#ux-refinement)
- [ ] Request that the issue is [tech refined](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#tech-refinement); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](../CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Publish a WIP implementation to Github as a draft PR and ask for feedback. 
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Update the [cookbook](https://cookbook.kirby.design) with examples and showcases.

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request. If you created a draft PR during implementation you can just mark that as "ready for review".

**Comment by jkaltoft** [comment]
I can't download the icons.

@henrikvoetmand can you add the icons again or send them to me?
