### ISSUE TITLE
[Enhancement] introduce hasPadding on accordion-items

### ISSUE THREAD

**Issue by sebastian639559** [kirbydesign/designsystem#3520]
## Describe the enhancement

I (Team-3. investment-in-drb) would like kirby-list to be able to have foldable-items. 

## Describe the solution you'd like

Nothing fancy. It should behave like this:

https://gyazo.com/e4bee180eca99c0ca6298b9ab484f95f

https://gyazo.com/391edfb2a21ce98b7067660924242097

## Have you considered any alternatives?

I considered using accordions, but inserting an accordion item into a kirby-list is not currently feasible. 

## Are there any additional context?

We have implemented foldable-items in kirby-list manually ourselves. Here is a link to the pr in case you might find it useful: [re3-mf-investment-core  -- pull-request 927](https://github.com/bd-b0100/re3-mf-investment-core/pull/927/files)

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#the-process-of-contributing) correctly.

### Refinement

- [ ] Request that the issue is [UX refined](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#ux-refinement)
- [ ] Request that the issue is [tech refined](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#tech-refinement); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](../CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Publish a WIP implementation to Github as a draft PR and ask for feedback. 
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Update the [cookbook](https://cookbook.kirby.design) with examples and showcases.

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request. If you created a draft PR during implementation you can just mark that as "ready for review".

**Comment by RasmusKjeldgaard** [comment]
After discussing with @sebastian639559 we agreed that the following use of existing kirby components satisfies the use-case: https://stackblitz.com/edit/stackblitz-starters-knin85?file=src%2Fmain.ts

**Comment by Fuzzy3** [comment]
After discussing with @RasmusKjeldgaard we decided to introduce "hasPadding" on kirby-accordion-item to give the option to remove the standard padding, which would cause in a "double-padding" when having "kirby-item"s within an accordion.
