### ISSUE TITLE
[TRACKING] Kirby Input features

### ISSUE THREAD

**Issue by dalsgaard** [kirbydesign/designsystem#360]
### Things we need in the Kirby Input control

1) Top label - a label in the top left corner (property).
1) Message - a message in the bottom left corner (property and for internal errors)
1) Error border - a red border on the input field when it goes into an error state.
1) Max length - there are three scenarios (properties): 
   - Too much text can be entered, but the component will go into an error state.
   - Too much text can not be entered.
   - Too much text can be entered and the component will go into error state (as in the first case), but there is also an absolute max on how much text there can be entered.
1) Character count - a counter in the bottom right corner - counting down from max length. If too much text is entered the counter will go into negative (property).
1) Legal characters - a regex that indicates legal characters (property). There are two scenarios (property):
   - The control will go into an error state if it does not conform.
   - The control will ignore illegal characters.
1) Focus events - the control should emit focus events.
1) Required - it should be possible to indicate that a value is required (property). If the control is required and empty it should go into an error state.
1) Toggling edit mode - it should be possible to toggle between edit and readonly mode (property). A pencil icon (to the right) should indicate the ability to go into edit mode.
1) Show attachments - show a list of attachments under the input field.
1) Numeric values only - only accept numeric values as input (property).
1) Changed events - the control should emit changed events.
1) Multi line - the control should support multi line editing (property).

**Comment by bdyken** [comment]
13. Multi line, init with 3 lines large input control and the input control expands when more more than 3 lines are added, so the user can see all the text

**Comment by bdyken** [comment]
14. be able to set the background and border to transparent

**Comment by bdyken** [comment]
6. character set, if illegal char is added by user the char is ignored.

**Comment by dalsgaard** [comment]
The text under point 6 has been altered to reflect the comment immediately above.

**Comment by dalsgaard** [comment]
Solved in DRb
