### ISSUE TITLE
[COMPONENT] Selectable button Group

### ISSUE THREAD

**Issue by azeemchauhan** [kirbydesign/designsystem#361]
**Describe the solution you'd like**
Its new component, functionality wise it should work as radio buttons and  let the user select only one of a limited number of choices

**Describe alternatives you've considered**
   N/A

**Additional context**
use case 1: 
![image](https://user-images.githubusercontent.com/33758493/60954017-e4d32c80-a31b-11e9-8ebf-b511641f5f62.png)
use case 2: 
![image](https://user-images.githubusercontent.com/33758493/60954732-21535800-a31d-11e9-8494-cdf79edff584.png)

https://app.zeplin.io/project/5c99d69a79d02b35ea3b8f41/screen/5cd32dcffb9c6f349ccbd389

### Kick Off:
- [ ] Accept Feature incl. name of component (DSL)
- [ ] Update Kirby Component Status and publish to [Kirby Cookbook](https://cookbook.kirby.design)
### Code:
- [ ] Create Feature Branch
- [ ] Implement Skeleton Component:
    - [ ] Web implementation
    - [ ] {N} implementation
- [ ] [Implement Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Add link to showcase on Kirby Component Status (`component-status-items.ts => code.cookbookUrl`)
- [ ] Also remove `githubIssueNo` and set `status` to `ItemCodeStatus.ready`
- [ ] Push commits to GitHub
### Review:
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- Merge to master and delete branch

**Comment by jb-trm** [comment]
@azeemchauhan I think that might have been a mistake from the UX'er that made that sketch example...can you ask him/her if its really a new component or if it was just supposed to be a segmented controller instead?

**Comment by azeemchauhan** [comment]
> @azeemchauhan I think that might have been a mistake from the UX'er that made that sketch example...can you ask him/her if its really a new component or if it was just supposed to be a segmented controller instead?

But it's functionality is quite different from exiting segmented controller, these selectable button control should behave like radio group selection, if its possible to achieve this behaviour and style through segmented controller then we can expect changes in segmented control component, 
I am again going to discuss with UX and update this issue accordingly.

**Comment by azeemchauhan** [comment]
@jakobe @hafstad  I have change update the requirement and also added the one more possible use case, so when we starting discussion on this.

**Comment by bommariusser** [comment]
This isnt relevant anymore
