### ISSUE TITLE
[BUG] Getting unnecessary right|left border in Kirby-List  

### ISSUE THREAD

**Issue by azeemchauhan** [kirbydesign/designsystem#363]
**Describe the bug**
  We are using the **kirby-list** and unfortunately we are getting extra right|left border on list 
  container(see screenshot)

**To Reproduce**
     please refer to below code snipped that we using
   
![image](https://user-images.githubusercontent.com/33758493/59847326-d2e71500-937f-11e9-8e7a-2c37bf3a6e01.png)

**Kirby version**
 -  0.0.179

**Expected behavior**
Left|Right border should't be there alone if we don't have top|bottom border.

**Screenshots**
![image](https://user-images.githubusercontent.com/33758493/59898950-8bf53000-9410-11e9-8483-5d0df10086d6.png)

**Native (please complete the following information):**
 -  iPhone6, Samsung
 - OS: iOS, Android

**Comment by hafstad** [comment]
This should have been fixed by #343, @azeemchauhan can you please try update Kirby to the latest version at your branch to see if it solves your issue?

**Comment by azeemchauhan** [comment]
This issue has been fix so I am closing this
