### ISSUE TITLE
[COMPONENT] Password

### ISSUE THREAD

**Issue by jakobe** [kirbydesign/designsystem#374]
We'll need a password component to enroll customers / re-login / sign.

See also: https://zpl.io/b6DGjZP

**Comment by bommariusser** [comment]
It's in DRB a shared component called "PincodeFieldComponent" let's figure out what to do with it. Is it a Kirby component or not?

**Comment by labanos** [comment]
DRB has this for now - must be reopened later if we have extra requirements outside DRB
