### ISSUE TITLE
[Enhancement] Add option to enable selected state on list items

### ISSUE THREAD

**Issue by jakobe** [kirbydesign/designsystem#375]
It should be possible to enable selected state on the Kirby list (e.g. a checkmark to the left of the list item).
The feature should be opt-in (default false).

https://app.zeplin.io/project/5c99d69a79d02b35ea3b8f41/screen/5d022940c297435df258d95c

**Comment by labanos** [comment]
how does this relate to account picker?

team 4 might have the same use case when changing a selection in the trade flow? eg account?

**Comment by labanos** [comment]
used on account picker case - where a list is shown in a modal (drawer)
