### ISSUE TITLE
[Enhancement] Segmented Composite Control (Items + Views)

### ISSUE THREAD

**Issue by jakobe** [kirbydesign/designsystem#378]
It should be possible to have a segmented composite control where you specify the items + the corresponding views (a la TabBar+TabViews).

The implementation could be something along the lines of:
```
<kirby-segmented-control>
    <kirby-segmented-control-view title="Messages">
       [custom content]
    </kirby-segmented-control-view>
    <kirby-segmented-control-view title="Documents">
       [custom content]
    </kirby-segmented-control-view>
     ...
</kirby-segmented-control>
```

**Comment by labanos** [comment]
Moving till "after 1st release" - but might make sense to do earlier if we have time for the effort.

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
