### ISSUE TITLE
[Enhancement] Separator

### ISSUE THREAD

**Issue by jakobe** [kirbydesign/designsystem#379]
It should be possible to separate groups of chips with a separator.

![image](https://user-images.githubusercontent.com/9556693/60186077-678fbe00-982b-11e9-8d71-cc6191c7964b.png)

**Comment by bommariusser** [comment]
They actually found another way of solving this "issue" but it involves another enhancement of the chip. I'll try to describe it here: It's  a way of grouping chips into one group to make it visually appear related to another. See also screenshot below.

It's team3 that need this as the only one right now. 

<img width="690" alt="groupedChip" src="https://user-images.githubusercontent.com/49033002/63040858-b1f5f880-bec6-11e9-8f47-d499c35c926d.png">

See also https://getbootstrap.com/docs/4.3/components/button-group/ for inspiration, although its a buttongroup ;) 

Not sure if this is another enhancement or if this is fine? @jakobe & @labanos - But it probably doesn't change the prioritization.

**Comment by labanos** [comment]
won't fix - solved as Marvin described
