### ISSUE TITLE
[Enhancement] Visual update (Actual round badges & better icon support)

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#389]
**Is your enhancement request related to a problem? Please describe.**
Our badge isn't really round right now, especially when we put an icon inside it. 

This is what we want :) : https://zpl.io/agkx7BO

**Comment by jonasjensen-brolstark** [comment]
@bommariusser  The example of the badge only have a single digit number in it. What will happen if it has more digits that can be contained inside the circle of the badge? Will it then grow as a circle or an ellipse?

**Comment by labanos** [comment]
Do we have examples in DRB, where icons are used inside badge?
Which platforms are "broken" web? ios? android?

PS putting in "after 1st release" for now - but will reprioritize when we have an overview of the "state" as is :)

**Comment by jonasjensen-brolstark** [comment]
> Do we have examples in DRB, where icons are used inside badge?
> Which platforms are "broken" web? ios? android?
> 
> PS putting in "after 1st release" for now - but will reprioritize when we have an overview of the "state" as is :)

On the transaction list in DRB a badge with icon is used.

Regarding the platform i will let @bommariusser answer.

**Comment by labanos** [comment]
@jonasjensen-brolstark got a customer+account with an example? =)

**Comment by bommariusser** [comment]
you can see the implementation right now here: https://cookbook.kirby.design/home/showcase/badge

@labanos 

and regarding the customer+account im not sure if its implemented right now @jonasjensen-brolstark . guess not :)? but its used to show an attachment, so also relevant for the inbox at some point. its the kirby way to show attachments.

But if its a badge with an icon or an avatar with an icon in extra-small. that you know better, technically.

I'm back on monday! :-*
