### ISSUE TITLE
[Enhancement] Modal (Drawer flavor)

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#391]
**Is your enhancement request related to a problem? Please describe.**
We want to have two different flavors of a modal:

- Drawer (Animate from the bottom) with minimize top left: https://zpl.io/Vqv4oAN
- Modal (Animate 'normally') with close button top right: https://zpl.io/VYp6BgE

Drawer opens 'normally' inside a modal thus is the minimize placed on the other side. 

A use case for the drawer is for example our account picker that you can open from everywhere

The enhancements include:
- [x] A new property - flavor : 'drawer' | 'modal' - added to the modal config (which can be extended with 'alert' to support #335)
- If flavor is 'drawer':
- [x] Animation: the modal always appears from the bottom of its opening context and slides up. 
- [x] Close button: the button is always placed on the left and has the arrow-down icon
- [x] Title: always centred
- [x] An additional (and optional) button can be added to the top right corner of the modal, which can do a custom action.
- If flavor is 'modal'
- [x] Animation: the modal always fades in (no animation for this PR)
- [x] Close button: the close button is always placed on the right and has the close icon
- [x] Title: always aligned left

**Comment by labanos** [comment]
@bommariusser lets briefly touch base on this - is possible to launch with just one flavor or modal - og is this essential for launch?

**Comment by bommariusser** [comment]
@labanos i'll get back to you, when i come back from vacation (monday) :)

**Comment by hafstad** [comment]
#335
