### ISSUE TITLE
[COMPONENT] QR Scanner

### ISSUE THREAD

**Issue by hafstad** [kirbydesign/designsystem#395]
**Describe the solution you'd like**
QR scanner with overlay with some text, cancel button and enable flashlight (native only).
Should be opened by clicking a button.

- [ ] Title at the top of the overlay
- [ ] Text at the top of the overlay
- [ ] Cancel button at the top of the overlay
- [ ] Border / area for QR code
- [ ] Button for enabling flashlight

**Additional context**
Need link from UX

### Kick Off:
- [ ] Accept Feature incl. name of component (DSL)
- [ ] Update Kirby Component Status and publish to [Kirby Cookbook](https://cookbook.kirby.design)
### Code:
- [ ] Create Feature Branch
- [ ] Implement Skeleton Component:
    - [ ] Web implementation
    - [ ] {N} implementation
- Ask UX for review:
    - Ensure implementation is correct on all 3 platforms:
      - [ ] Web
      - [ ] iOS
      - [ ] Android
    - [ ] Define the version of the implementation + steps needed to reach version 1.0 (create [enhancement requests](https://github.com/kirbydesign/designsystem/issues/new?assignees=&labels=enhancement&template=enhancement-request.md&title=%5BEnhancement%5D))
- [ ] [Implement Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Add link to showcase on Kirby Component Status (`component-status-items.ts => code.cookbookUrl`)
- [ ] Also remove `githubIssueNo` and set `status` to `ItemCodeStatus.ready`
- [ ] Push commits to GitHub
### Review:
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- Merge to master and delete branch

**Comment by labanos** [comment]
Not in scope of mvp/release 1 for now.

**Comment by labanos** [comment]
not likely to be a kirby thing for now..
