### ISSUE TITLE
[BUG] Web Calendar view is missing back/forward buttons

### ISSUE THREAD

**Issue by ckibsen** [kirbydesign/designsystem#400]
**Describe the bug**
Back and Forward buttons are not shown in calendar, when used from DRB

**To Reproduce**
Show Calendar from DRB

**Kirby version**
 - [0.0.200]

**Expected behavior**
Buttons are shown.

**Screenshots**
Attached

**Desktop (please complete the following information):**
 - Browser [chrome]
 - Version [75.0.3770.100]

**Additional context**
This seems to be referenced:

<ion-icon _ngcontent-sys-c2=“” ng-reflect-src=“assets/kirby/icons/svg/cog.svg” role=“img” class=“md hydrated”></ion-icon>

In DRB under node_modules there is a:

...../relationsbank/node_modules/@kirbydesign/designsystem/icons/svg/cog.svg

which is the "forward" icon. On the other hand, the “back icon” looks like :

<ion-icon _ngcontent-sys-c2=“” ng-reflect-src=“assets/kirby/icons/svg/arrow-b” role=“img” class=“md hydrated”></ion-icon>

There doesn't seem to be an arrow-b, but on the other hand an arrow-back.svg under ...../designsystem/icons/svg !!

**Comment by ckibsen** [comment]
<img width="671" alt="Screenshot 2019-07-02 at 14 15 50" src="https://user-images.githubusercontent.com/832287/60515346-b5993b80-9cdb-11e9-9f9b-6f975cc366f6.png">

**Comment by ckibsen** [comment]
Might be a caching issue, because after explicitly trying to load the missing icons (one by one) in the browser (localhost), they appear in the calendar. However, the log complains about a missing "arrow-forward", and Kirby seems to default to a "cog.svg" (!!!??).

![Screenshot 2019-07-03 at 09 59 27](https://user-images.githubusercontent.com/832287/60574176-630e5c80-9d79-11e9-8302-d359fcfef352.png)

**Comment by mmmtrifork** [comment]
You are looking for 'arrow-more'. 'arrow-forward' is not a kirby icon

**Comment by mmmtrifork** [comment]
I cannot reproduce this issue in the designsystem. Example from the cookbook:
<img width="351" alt="Screenshot 2019-08-02 at 11 48 36" src="https://user-images.githubusercontent.com/48326253/62361526-7f89ea00-b51b-11e9-92ae-69c8be2b368b.png">

**Comment by mmmtrifork** [comment]
Hi @ckibsen, is this issue still relevant?

**Comment by ckibsen** [comment]
@mmmtrifork it seems to be fixed on Web! However, the icons in the Calendar on iOS (while the correct symbols) are quite squeezed! Will create another issue on this.
