### ISSUE TITLE
[BUG] Date columns not aligned with weekday titles on large screens

### ISSUE THREAD

**Issue by ckibsen** [kirbydesign/designsystem#401]
**Describe the bug**
The Date columns seems to be a little off.

**To Reproduce**
See calendar in Web browser: https://cookbook.kirby.design/examples/calendar

**Kirby version**
 - [0.0.200]

**Expected behavior**
Date columns and weekday titles to be nicely aligned.

**Screenshots**

**Desktop (please complete the following information):**
 - Browser [chrome]
 - Version [75.0.3770.100]

**Additional context**
**AS-IS**
Desktop scrrenshot:
<img width="671" alt="Screenshot 2019-07-02 at 14 15 50" src="https://user-images.githubusercontent.com/832287/60515577-2c363900-9cdc-11e9-9834-a5e1814403a4.png">

iPad landscape screenshot:
![Tablet-AS-IS](https://user-images.githubusercontent.com/71710012/100065817-8afdd480-2e34-11eb-8ded-9e18ab238d6b.png)

**TO-BE**
![Tablet-TO-BE](https://user-images.githubusercontent.com/71710012/100070486-483efb00-2e3a-11eb-8e90-79a1f2008eaf.png)

**Comment by labanos** [comment]
@jakobe what is the workaround? (ps moving to "after 1st release" since it is "web" and "minor"

**Comment by MartinSkovsen** [comment]
Tech refinement: The text alignment of table cells should be center aligned like the table headers.
