### ISSUE TITLE
[BUG] white background color on kirby list header and no-more-items in web

### ISSUE THREAD

**Issue by bdyken** [kirbydesign/designsystem#403]
![image](https://user-images.githubusercontent.com/49056452/60568838-39036d00-9d6e-11e9-8906-209f7db95886.png)

The are set a background color on the .list-header class and it is needed to be transparent
![image](https://user-images.githubusercontent.com/49056452/60568969-77992780-9d6e-11e9-87a9-8e90af0d44cd.png)

The same with no-more-items
![image](https://user-images.githubusercontent.com/49056452/60575406-c5685c80-9d7b-11e9-8608-886d9e4e8dd9.png)

![image](https://user-images.githubusercontent.com/49056452/60575373-b2558c80-9d7b-11e9-9828-1f0d981e1a3b.png)

**Comment by jonasjensen-brolstark** [comment]
Fixed in version `0.7.12`.
