### ISSUE TITLE
[BUG] Icon not centered in outline on Android

### ISSUE THREAD

**Issue by MortenGregersen** [kirbydesign/designsystem#406]
**Describe the bug**
When outline is true on a Kirby Icon the icon isn't centered in the outline on Android. It works as it should on web and iOS.

When the icon is shown the following error is logged to the console (both for iOS and Android):
`JS: Error: Failed to apply property [padding] with value [var(--kirby-icon-padding)] to Label(53). Error: Invalid value: var(--kirby-icon-padding)`

**To Reproduce**
1. Open the cookbook on Android
2. Click on 'Icon'
3. Scroll to the bottom
4. See error on the outlined icon

**Kirby version**
 - 0.0.202

**Expected behavior**
The icon should be centered in the outline.

**Screenshots**
![Screenshot_1562157359](https://user-images.githubusercontent.com/759680/60591986-e6db3f80-9d9f-11e9-8009-926b36aafd84.png)

**Native:**
 - Device: Emulator
 - OS: Android 6

**Comment by jakobe** [comment]
I can confirm this

**Comment by jakobe** [comment]
The error regarding styling/css variables not being applied has been fixed here:
https://github.com/kirbydesign/designsystem/pull/409
