### ISSUE TITLE
Text on button in Action-sheet is not possible to change

### ISSUE THREAD

**Issue by laljyskebank** [kirbydesign/designsystem#412]
**Describe the bug**
On the Action-sheet the button text is not possible to change. It will always be "Cancel".

![image](https://user-images.githubusercontent.com/35138247/60663192-d1791a80-9e5e-11e9-96da-3088065acc49.png)

**To Reproduce**
1. Go to 'Faste betalinger'
2. Click on 'FAB'
3. Choose 'Opret betalingsservice aftale'
4. Click on 'Betales fra'
5. Choose 'Egen konto'
6. The text on the button is "Cancel"

**Kirby version**
 - [e.g. 0.0.200]

**Expected behavior**
The text on the button schould be able to change

**Screenshots**
![image](https://user-images.githubusercontent.com/35138247/60663192-d1791a80-9e5e-11e9-96da-3088065acc49.png)

**Desktop (please complete the following information):**
 - N/A

**Native (please complete the following information):**
 - N/A

**Additional context**

**Comment by bommariusser** [comment]
But the cancel button is always a "cancel" right? Maybe it's more an enhancement request towards language support, so it's called "luk"/"afbryd" on danish? :) @laljyskebank
