### ISSUE TITLE
[BUG] Button hover opacity

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#417]
**Describe the bug**
When you hover the a it's opacity is set to 0,80 see also 
<img width="615" alt="Skærmbillede 2019-07-08 kl  10 56 02" src="https://user-images.githubusercontent.com/49033002/60797127-004d0480-a16f-11e9-851d-a9d631112376.png">

**To Reproduce**
1. Go to 'konto'
2. Hover 'overfør penge'

**Kirby version**
 - [e.g. 0.0.55]

**Expected behavior**
We want the color to change not the opacity

**Desktop (please complete the following information):**
Web

**Additional context**

**Comment by jakobe** [comment]
Will be fixed by #549

**Comment by alxzak** [comment]
duplicate #549

This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
