### ISSUE TITLE
[Enhancement] Remove kirby card default margin in Native

### ISSUE THREAD

**Issue by azeemchauhan** [kirbydesign/designsystem#423]
**Is your enhancement request related to a problem? Please describe.**
In my case I want to use card in other container layout and I want that card should take all space inside the container layout but kirby card having default margin 
  `margin: size("xs");`

**Describe the solution you'd like**
Card should not have any margin on native like the web version

**Describe alternatives you've considered**
Give us a way to remove that default margin of kirby card

**Additional context**
We have two card A and B, see the green area which is the margin of kirby card with its container. so this green margin should't be here 
![image](https://user-images.githubusercontent.com/33758493/60885439-37a1db00-a26d-11e9-820d-5931b86bb95a.png)

**Comment by labanos** [comment]
Is there a running example of this? Eg a branch or something? Also moving this to "after 1st release" - based on nothing but gut-feeling (if this is a complete mess and ruins the user-experience we will ofc reconsider)

**Comment by mmmtrifork** [comment]
This is issue only on native
