### ISSUE TITLE
[BUG] setting themeColor on kirby-icon doesn't work for custom icon on web

### ISSUE THREAD

**Issue by SilverGull** [kirbydesign/designsystem#426]
**Describe the bug**
When setting a the `themeColor` property on a `kirby-icon` it doesn't affect the color of the icon if the icon is a custom icon. It does however affect the outline if that is shown. It is only a problem on web.

**To Reproduce**
You will need a custom icon.
The example below uses a custom icon and the color is black even though `themeColor` has been set to `medium`
`<kirby-icon customName="investment-graph" size="lg" themeColor="medium"></kirby-icon>`
If a standard icon is used the `themeColor` is set accordingly
`<kirby-icon name="cog" size="lg" themeColor="medium"></kirby-icon>` 

**Kirby version**
 - 0.0.209

**Expected behavior**
I expect the color of the custom icon to be the color defined as `themeColor`

**Screenshots**

**Desktop (please complete the following information):**
 - iOS
 - chrome
 - Version 75

**Native (please complete the following information):**

**Additional context**

**Comment by labanos** [comment]
Parking till after - because its a web only issue. Might be solved earlier with other icon related things - if it makes sense.

**Comment by hafstad** [comment]
@SilverGull Please check your svg for hardcoded fill, colors. If thats the case replace the color with "currentColor"

**Comment by SilverGull** [comment]
@hafstad the fill color is "none". Replacing it with "currentColor" doesn't seem to do the trick. Thank you for the input :-)

**Comment by MortenGregersen** [comment]
Had to make some changes to the SVG, to make it work.
