### ISSUE TITLE
[Houskeeping] Replace kirbyInfiniteScroll with ion-infinite-scroll on ion-list

### ISSUE THREAD

**Issue by szutrifork** [kirbydesign/designsystem#430]
**Describe the bug**
Currently we are using kirbyInfiniteScroll directive on ion-list. Use ionics own ion-infinite-scroll instead, once page-templates [issue #345](https://github.com/kirbydesign/designsystem/issues/345) is implemented.

**Kirby version**
0.0.218

**Expected behavior**
ion-infinite-scroll should completely replace kirbyInfiniteScroll 

**Screenshots**
See how to implement ion-infinite-scroll: https://ionicframework.com/docs/api/infinite-scroll

**Additional context**
ion-infinite-scroll is not working correctly in version 4.6.0. https://github.com/ionic-team/ionic/issues/18739
Kirby is running newest version of ionic 4.6.2 where the bug is fixed.

**Comment by labanos** [comment]
What bug are we trying to fix by this? Sounds more like a housekeeping thing - than a bugfix, unless a description of an actual "bug" is missing for the issue? @szutrifork could you elaborate?

**Comment by hafstad** [comment]
Dependent on #345

**Comment by alxzak** [comment]
@bommariusser Virtual scrolling fixes this.
