### ISSUE TITLE
[BUG] iOS: elevation directive

### ISSUE THREAD

**Issue by jonasjensen-brolstark** [kirbydesign/designsystem#433]
**Describe the bug**
When using the `KirbyElevation` directive it will throw an exception on iOS:

```bash
CONSOLE ERROR [native code]: ERROR TypeError: undefined is not an object (evaluating 'iosView.layer')
CONSOLE ERROR [native code]: ERROR CONTEXT {
"view": {
"def": {
"nodeFlags": 344073,
"rootNodeFlags": 1,
"nodeMatchedQueries": 0,
"flags": 0,
"nodes": [
{
"nodeIndex": 0,
"parent": null,
"renderParent": null,
"bindingIndex": 0,
"outputIndex": 0,
"checkIndex": 0,
"flags": 1,
"childFlags": 344073,
"directChildFlags": 344065,
"childMatchedQueries": 0,
"matchedQueries": {},
"matchedQueryIds": 0,
"references": {},
"ngContentIndex": null,
"childCount": 7,
"bindings": [],
"bindingFlags": 0,
"outputs": [
{
"type": 0,
"target": null,
"eventName": "loaded",
"propName": null
}
],
"element": {
"ns": "",
"name": "FlexboxLayout",
"attrs": [
[
<…>
```

It looks like it has the effect that if there are multiple elements with elevation on the page, one of them will not get an elevation.

**To Reproduce**
1. Run kirby cookbook on iOS with debugger attached
2. Go to 'card' example
3. See the exception in the console

**Kirby version**
 - 0.0.222

**Expected behavior**
I expected that it would not fail and all elements would get its elevation.

**Screenshots**

**Comment by jonasjensen-brolstark** [comment]
I think the issue is due to these lines of code in the `ngOnInit` function:

```typescript
    if (isAndroid) {
      this.elementRef.nativeElement.on('loaded', () => {
        this.applyElevation();
      });
    } else {
      this.applyElevation();
    }
```

If i change the code to:

```typescript
this.elementRef.nativeElement.on('loaded', () => {
  this.applyElevation();
});
```

It seams to work correctly. Maybe the one that wrote the code could confirm this @mmmtrifork ? Or maybe @hafstad ?

**Comment by hafstad** [comment]
@jonasjensen-brolstark I will look into it
