### ISSUE TITLE
[Enhancement] Ability to remove styling

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#456]
**Is your enhancement request related to a problem? Please describe.**
Should be possible to remove styling (background, border and elevation) so its possible to use in other contexts, like in the transfer money context where they don't use any background, elevation or border.

see also: https://zpl.io/amdWLxD

**Comment by jakobe** [comment]
@bommariusser Closing this, as it doesn't make sense to use a Kirby input if you want to remove all that it is :)
This can already be solved by using a plain html input and styling as needed.
