### ISSUE TITLE
[Enhancement] Ability to add prefix and suffix 

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#459]
## Describe the solution you'd like
It should be possible to add pre- and suffixes inside an input/form field to make it even more clear what the user is typing into that field. 

The solution should allow both icons and values, dependant on the usage-situation. The task should not be about making the icon also clickable. 

The design is either a black icon or a semi-dark text (see also screenshots)

## Are there any additional context?
We have considered the possibility that it should be possible to change the alignment of the text also, to make the suffix close to the the value you put inside it, but that might be too much configuration for the user using it...

See also: https://zpl.io/YYNKvmn

![Pre   Suffix](https://user-images.githubusercontent.com/49033002/173060070-d7e28f21-b61a-4e58-a7ae-d25250d2b008.png)

See also https://getbootstrap.com/docs/4.0/components/input-group/ for inspiration

and use case should be here:

**Comment by labanos** [comment]
sounds like at valid case - but zeplin link is broken...

**Comment by bommariusser** [comment]
hehe oh well the only thing we have right now is the transfer and the big KR i guess... :P

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
