### ISSUE TITLE
[Enhancement] Only keep 1 destructive button (Filled)

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#460]
**Is your enhancement request related to a problem? Please describe.**
In the use-cases we have right now we only have a filled destruction button (red background, black text)

We might also have an outline version that has a red outline with a black text, but thats it for now. The problem with a red text is that it is not accessible.

see also: https://zpl.io/VDKnZAl

**Comment by labanos** [comment]
cleanup task - for now - dont use the broken ones ;)

**Comment by jakobe** [comment]
**Tech refinement:** Override `attentionLevel` (set to 1) when `isDestructive=true`
