### ISSUE TITLE
[Enhancement] Remove "focus" on pressed 

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#462]
**Is your enhancement request related to a problem? Please describe.**
Right now the buttons have a blue outline when it's pressed, but it should only change color to its shade color. 

**NOTE: Outline should not be removed on :focus**

See also screenshot:
![Skærmbillede 2019-07-26 kl  09 54 27](https://user-images.githubusercontent.com/49033002/61935693-56051780-af8b-11e9-8966-0fc09977f152.png)

**Comment by hafstad** [comment]
@bommariusser this is default behaviour of the browser showing elements in focus. We can remove that, however you should be aware of that the outline are made for accesibility purposes

**Comment by bommariusser** [comment]
åh nej nu har jeg lukket den @hafstad :D kan man åbne igen?

**Comment by bommariusser** [comment]
on focus its fine, like tabbing to it. But it might be overkill to do it on pressed too? It already changes the color

**Comment by hafstad** [comment]
That makes sense
