### ISSUE TITLE
[Enhancement] Action Sheet Cancel button styling

### ISSUE THREAD

**Issue by mmmtrifork** [kirbydesign/designsystem#467]
In addition to #438 , according to the styleguide (https://zpl.io/2pMzkny) the button should be bolded. This currently relies on buttons being more style-flexible (e.g. would be great if we could first merge #461)

**Comment by bommariusser** [comment]
@mmmtrifork Also the button should be bigger when looking at our style :) The bold text is less important then the size of the button

Production:  
![Skærmbillede 2019-08-15 kl  08 27 32](https://user-images.githubusercontent.com/49033002/63076804-b22ddc80-bf36-11e9-9cdb-f61b62e87a7b.png)

Visuals: https://zpl.io/aRGdrNe

**Comment by bommariusser** [comment]
Fixed (Nativescript issue)
