### ISSUE TITLE
[Enhancement] Asynchronous modal configuration

### ISSUE THREAD

**Issue by askarby** [kirbydesign/designsystem#472]
Working with Kirby's modal configurations, there's an odd mismatch between its synchronous nature, and the applications (using Kirby) very asynchronous nature.

**Eg.** You want to display a modal, with data (or translated texts)... the data (or translated texts) is acquired asynchronously - hence you're forced into writing some RxJs boilerplate:

```typescript
showAlert() {
    const titleKey = 'title.key';
    const messageKey = 'message.key';
    const okKey = 'ok.key';
    this.translate
      .get([titleKey, messageKey, okKey])
      .pipe(first())
      .subscribe((translations) => {
        const config: AlertConfig = {
          title: translations[titleKey],
          message: translations[messageKey],
          okBtnText: translations[okKey],
        };
        this.modalController.showAlert(config);
      });
}
```
(the above example is related to "the Alert"-modal (and translations) - but could just as easily be concerned with "The modal" (and data from an HTTP endpoint)

**Describe the solution you'd like**
I'd much rather want to be able to pass an `Observable<AlertConfig>` (or `Observable<ModalConfig>`) in to the `modalController.showAlert` (or `modalController.showModal`).

Eg.:

```typescript
showAlert() {
    const titleKey = 'title.key';
    const messageKey = 'message.key';
    const okKey = 'ok.key';
    this.modalController.showAlert(
        this.translate
          .get([titleKey, messageKey, okKey])
          .pipe(map((translations) => {
            return {
              title: translations[titleKey],
              message: translations[messageKey],
              okBtnText: translations[okKey],
            };
          })
        )
    );
}
```

**Describe alternatives you've considered**
We're currently using the boilerplate approach... and can keep using that (but it's repetative code, and it's ugly, verbose, difficult to test and a potentially a point of failure.

**Additional context**
n/a

**Comment by labanos** [comment]
Putting this after 1st release - not becuase it's not a good idea to solve before.. but we are pressed for time. If we find the time - this would be very nice to solve - but requires effort in all to most teams current impl of the modal.

**Comment by jakobe** [comment]
@askarby We've later added support for Observables in input to the alert - could you verify whether this solves your problem? ☝🏻

**Comment by askarby** [comment]
Just close this issue, I've created a toolset of RxJs operators to interop with Kirby's Alerts, Modal (and Drawers), Toasts and ActionSheets (that's located in DRB instead).
