### ISSUE TITLE
[COMPONENT] App (NOT REFINED YET)

### ISSUE THREAD

**Issue by hafstad** [kirbydesign/designsystem#474]
**Describe the solution you'd like**
App is a container element for a Kirby application. There should only be one kirby-app element per project. An app can have many Kirby components including menus, headers, content, and footers. The overlay components get appended to the kirby-app when they are presented.
 
<ion-app> should be used for web implementation.
_See: https://ionicframework.com/docs/api/app_

### Kick Off:
- [ ] Accept Feature incl. name of component (DSL)
- [ ] Update Kirby Component Status and publish to [Kirby Cookbook](https://cookbook.kirby.design)
### Code:
- [ ] Create Feature Branch
- [ ] Implement Skeleton Component:
    - [ ] Web implementation
    - [ ] {N} implementation
- Ask UX for review:
    - Ensure implementation is correct on all 3 platforms:
      - [ ] Web
      - [ ] iOS
      - [ ] Android
    - [ ] Define the version of the implementation + steps needed to reach version 1.0 (create [enhancement requests](https://github.com/kirbydesign/designsystem/issues/new?assignees=&labels=enhancement&template=enhancement-request.md&title=%5BEnhancement%5D))
- [ ] [Implement Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Add link to showcase on Kirby Component Status (`component-status-items.ts => code.cookbookUrl`)
- [ ] Also remove `githubIssueNo` and set `status` to `ItemCodeStatus.ready`
- [ ] Push commits to GitHub
### Review:
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- Merge to master and delete branch

**Comment by bommariusser** [comment]
I'm not sure if this is a part of the task or a new task, but we need to support a safe area on devices with a nodge/faceid. 

See also: https://www.nativescript.org/blog/nativescript-5-ios-safe-area-support

**Comment by bommariusser** [comment]
See also https://sketch.cloud/s/b8Jm4/p/page-template-general-navigation-toolbar-tabbar for more information.

But in general we are now 1:1 crossplatform with different breakpoints:

<360dp
>= 360dp -> 768dp 
>768dp

**Part of the "App" is:**
- Toolbar **always** in top
- Tabbar:
      -  <768dp its placed in the bottom
      - >=768dp its placed in the top

**Part of the content is:**
- Page-title is always 8dp below the toolbar
- Page-title will scroll up in the toolbar when its not visible
- Page-title can de disabled if needed, but its enabled pr default (some sites have special layouts)
- (Optional) Buttons to the right of the page-title
     - Medium buttons (with icons or with text)
- (Optional) Buttons can also scroll up in the page-title

**See also**
<img width="591" alt="Skærmbillede 2019-09-05 kl  17 25 18" src="https://user-images.githubusercontent.com/49033002/64404462-514c7c80-d07c-11e9-8c52-c117f01d932a.png">

<img width="816" alt="Skærmbillede 2019-09-05 kl  21 43 59" src="https://user-images.githubusercontent.com/49033002/64404453-4b569b80-d07c-11e9-8fed-2c0a4d6858eb.png">
