### ISSUE TITLE
[Enhancement] Text size scaling dependent on amount of text

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#481]
**Is your enhancement request related to a problem? Please describe.**
We would like text scaling in size on our page-title dependent on amount of text on the page-title, from default H1 to minimum in size H3.

When we build a page we would like define what our max-height is in that page (eg. 2 lines). If the page-title on this page cant be shown in that "container", we would like to scale down, before we truncate. 

Eg. if the text doesn't fit, after the max height of the page-title has been reached, the text should scale down from the original H1 to minimum H3.

**See specific examples here from inbox**
Short text: https://zpl.io/2vPrN3J
Longer text: https://zpl.io/VDo7mll
Very long text: https://zpl.io/a7vlwWE

** See generic rule with 3 lines here**

<img width="898" alt="Skærmbillede 2019-10-15 kl  09 12 29" src="https://user-images.githubusercontent.com/49033002/66809003-bf624a00-ef2c-11e9-849c-103bc55b47a7.png">

**Comment by jakobe** [comment]
Maybe talk to @MortenGregersen as he's done something in this regard...
