### ISSUE TITLE
[BUG] Modal automatically focus TextField on physical Android devices

### ISSUE THREAD

**Issue by ckibsen** [kirbydesign/designsystem#484]
**Describe the bug**
When opening a Modal dialog containing a TextField, focus is automatically given to the TextField on PHYSICAL Android devices. This behaviour doesn't occur in the Android Emulator, and is not seen either in iOS Simulator og iOS physical devices.

**To Reproduce**
1. In the show case "Modal window", add a TextField and open the modal on a physical Android device.
2. See that the TextField is automatically focused.

**Kirby version**
 - [e.g. 0.0.242]

**Expected behavior**
TextField should not automatically be given focus by Kirby.

**Native (please complete the following information):**
 - Device: Android (physical devices)

**Comment by labanos** [comment]
@ckibsen is this a "showstopper" for going into production? (how "bad" are the sideeffects - eg. does it remove a placeholder text, that is important? does it do something wrong?)

Is there a possible workaround?

**Comment by labanos** [comment]
@ckibsen is this still an issue after NativeScript was removed?

**Comment by labanos** [comment]
closing - as far as i remember the issue it was "only" Android - so should be fixed. Reopen if the issue persists plz.
