### ISSUE TITLE
[Enhancement] Make current date in weekend selectable, when weekends are disabled

### ISSUE THREAD

**Issue by ckibsen** [kirbydesign/designsystem#490]
**Is your enhancement request related to a problem? Please describe.**
Eventhough weekend dates should generally not be selectable in our Transfer Flow, when transferring to an account where inter-bank clearing is not needed (eg. own accounts), it must always be possible to select current date as transfer date (even in weekends).

**Describe the solution you'd like**
An additional configuration property for the calendar component, eg. "alwaysEnableCurrentDate = true"

**Comment by labanos** [comment]
Remember to make the new property "optional" - and let Christian/Team2 know of the fix, when it is ready for DRB.

**Comment by mmmtrifork** [comment]
Hi @ckibsen, I believe you can build this functionality on your side by only using the  `disabledWeekends` input property of the calendar component. You can conditionally (e.g. If the user is transferring to an account where inter-bank clearing is not needed) set `disableWeekends=false` (or do not set it at all, as its default value is `false`). This should be equivalent to "alwaysEnableCurrentDate = true". 

It could be that I misunderstood your request. In that case, could you please clarify it better?

**Comment by ckibsen** [comment]
@mmmtrifork generally we want disabledWeekends=true, because you are not allowed to select a weekend day, EXCEPT if the user is in a "non inter-bank clearing flow", in which case the CURRENT day should be selectable! Therefore I think we need a combination of:

disableWeekends=true
alwaysEnableCurrentDate=true 

(so the latter property is actually 'allowSelectionOfCurrentDateDisregardingTheDisableWeekendsProperty' which is a little long, hence the 'alwaysEnableCurrentDate' suggestion - unless you can think of a better name!?).

Does that clarify your question?

**Comment by mmmtrifork** [comment]
ah! I see your point now. I think 'enableCurrentDate' should be fine for this purpose. Thanks for the clarifications ! :)
