### ISSUE TITLE
[BUG] Native badge placement

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#500]
**Describe the bug**
The badge is inside the segmentedControl and looks really weird :D

**To Reproduce**
1. Open a native platform with a segmentedControl and a badge

**Expected behavior**
The badge should be on top of the segmented control and not inside of it.
See also: https://zpl.io/29OYzvW

see also:

<img width="428" alt="Skærmbillede 2019-08-07 kl  21 34 14" src="https://user-images.githubusercontent.com/49033002/62652183-06472880-b95b-11e9-87bc-80bb1f086ce9.png">

**Desktop (please complete the following information):**
- Native

**Native (please complete the following information):**
- Tested on iPhone X

**Additional context**
See screenshot here: 

![IMG_922FED9A9CA4-1](https://user-images.githubusercontent.com/49033002/62651749-fed34f80-b959-11e9-81e9-668f4928d55b.jpeg)

**Comment by labanos** [comment]
No longer relevant - web seems better.
