### ISSUE TITLE
[Enhancement] Support for a black button 

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#501]
**Is your enhancement request related to a problem? Please describe.**
We need support for a **black button** (right now the need is only on white, since attention level 2 on white is a white button);

- **Solution**: Attention level 2 on white gets black 

See also: https://zpl.io/VYpZyvk

**Comment by lydemann** [comment]
@bommariusser 
What names should be used for setting the button to warning and success colors? Eg. currently danger color is set by setting destructive = true.

**Comment by jakobe** [comment]
> @bommariusser
> What names should be used for setting the button to warning and success colors? Eg. currently danger color is set by setting destructive = true.

God question, @lydemann . Let's talk with @bommariusser about this next time we meet (this monday)

**Comment by jakobe** [comment]
> > @bommariusser
> > What names should be used for setting the button to warning and success colors? Eg. currently danger color is set by setting destructive = true.
> 
> Good question, @lydemann . Let's talk with @bommariusser about this next time we meet (coming monday)

@lydemann For now this enhancement will only be related to the button getting black background color at attention level 2 on white
