### ISSUE TITLE
[ENHANCEMENT] No inherent padding on kirby-list-item

### ISSUE THREAD

**Issue by PetarRing** [kirbydesign/designsystem#504]
**Is your enhancement request related to a problem? Please describe.**
Since padding is inherently sat on kirby-list-item, it makes templates which would span the entire list width an impossibility.

**Describe the solution you'd like**
Removing the padding on kirby-list-item so the ability to create templates for the kirby-list-item which would span the entire width becomes available. The images below show, what is intended and what is reality.

**Describe alternatives you've considered**
The ability to disable padding on the list via input.

**Additional context**
![image](https://user-images.githubusercontent.com/8911645/62697884-0e937800-b9dc-11e9-9844-0e44654f6d66.png)
![image](https://user-images.githubusercontent.com/8911645/62697912-1ce19400-b9dc-11e9-8569-7b0df1fb6ac6.png)

**Comment by darpankumar** [comment]
I am also facing some issue with list padding attached the screen shot for the same.

**Comment by jb-roa** [comment]
Fixed by #612
