### ISSUE TITLE
[Enhancement] Remove margin outside the card

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#506]
**Is your enhancement request related to a problem? Please describe.**
Margin outside a component like a card makes it harder to actually use it and reuse it for other components. 

Use case: 
- We want to have 16dp "margin" between two cards vertically. To make this we have to know the margin-top and margin-bottom on the cards and calculate the rest so we get to 16dp.
- Also: If we make a page-template that has 16dp margin on left and right, and the card has a builtin margin to the right or left it gets quite hard to do that.

**Comment by hafstad** [comment]
Closing as this has already been fixed by #483
