### ISSUE TITLE
[BUG] Slide button doesn't work on web on mobile

### ISSUE THREAD

**Issue by unnamjolner** [kirbydesign/designsystem#514]
**Describe the bug**
The slide button works well on desktop web and on native apps. But when I slide the button in a browser on mobile device (a requirement for the transfer flow), nothing happens. The slideDone-event does not trigger.

**To Reproduce**
1. Go to Kirby Cookbook on a mobile device (or simulate through Chrome developer tools)
2. Slide the slide button to the right
3. Nothing happens

**Kirby version**
 - 0.0.242

**Expected behavior**
In the cookbook, the button should disappear and a alert be shown.

**Screenshots**
-

**Desktop (please complete the following information):**
-

**Native (please complete the following information):**
 - Device: iPhone6
 - OS: iOS
 - Browser Safari
 - Version 11.4

**Additional context**

**Comment by jakobe** [comment]
Closed by #533
