### ISSUE TITLE
[BUG] Selectable List Items (native)

### ISSUE THREAD

**Issue by mmmtrifork** [kirbydesign/designsystem#524]
I have observed the following on native:
- There is whitespace to the left of list items for both iOS and Android, which should not be there (see screenshot below):
<img width="365" alt="Screenshot 2019-08-15 at 12 48 36" src="https://user-images.githubusercontent.com/48326253/63090257-05b22180-bf5b-11e9-91b8-937b6c407759.png">
As shown in Zepplin, there should be no whitespace there: 
https://app.zeplin.io/project/5c99d69a79d02b35ea3b8f41/screen/5d022940c297435df258d95c

- There is a weird scrolling behaviour that appears on list item select (Android only). This is not expected to appear.
 
Could be related to #452 , #375

**Comment by labanos** [comment]
{N} rip
