### ISSUE TITLE
[Enhancement] Prettifying (Button size & margin between items on native)

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#526]
**Describe the bug**
1. (Native) The margin between the two components, title and subtitle, are off
2. The button is right now 40dp but should be 48dp. Also it should be possible to change the attention level of the button, so its not always supposed to be a primary button. 

**How it looks now on native in production:**
![Skærmbillede 2019-08-19 kl  08 56 42](https://user-images.githubusercontent.com/49033002/63245024-537ea080-c25f-11e9-8265-63c9364ac0d0.png)

**How it should look**
![Skærmbillede 2019-08-19 kl  08 56 52](https://user-images.githubusercontent.com/49033002/63245047-65604380-c25f-11e9-97cc-9275a2005213.png) 
![Skærmbillede 2019-08-19 kl  08 59 00](https://user-images.githubusercontent.com/49033002/63245135-9c365980-c25f-11e9-8b75-483296ff1b44.png)

**Comment by mmmtrifork** [comment]
button sizes handled in #341

**Comment by labanos** [comment]
seems ok in the cookbook web - so not sure this is a kirby issue
