### ISSUE TITLE
[BUG] Modal appears little high - gap between bottom bar and modal

### ISSUE THREAD

**Issue by Ranjot-Kaur** [kirbydesign/designsystem#548]
**Describe the bug**
There is a gap below modal, above the bar containing done.

**To Reproduce**
1. Go to my investment page
2. Click on 'Buy' button
3. Search Paper
4. Click on Paper
5. There is a gap between modal and bar containing done

**Kirby version**
 -  [0.0.262]

**Expected behavior**
There should not be gap below modal

**Screenshots**
![image](https://user-images.githubusercontent.com/35022750/63510155-8349d480-c4fb-11e9-8b94-903ce8d59647.png)

**Native (please complete the following information):**
 - Device: iPhone8, iPhoneSE

**Additional context**

**Comment by labanos** [comment]
@Ranjot-Kaur to avoid confusion - could you please fill in the kirby version?

Also - i assume this is native only? (since the screenshot is from the emulator?) So confirm on which device this has been tested and found failing?

**Comment by Ranjot-Kaur** [comment]
@labanos We have tested it on iPhone8 and iPhone SE. I have updated the kirby version and devices in the issue.

**Comment by labanos** [comment]
@Ranjot-Kaur ok thanks - i am still a bit confused about Browser [safari]? I looks like the native app - and not the website in a browser on a mobile. If no browser was involved - please delete that part =)

**Comment by Ranjot-Kaur** [comment]
@labanos My bad. Removed browser.

**Comment by labanos** [comment]
Duplicate of #291
