### ISSUE TITLE
[Enhancement] Pressed/Hover State (Buttons)

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#549]
**Is your enhancement request related to a problem? Please describe.**
We want some Pressed & Hover states (Hover is not high prioritized i guess) that use our color system like it should.

- Tint = Hover
- Shade = Pressed

Right now it is some weird behavior where the buttons turns blue because of the focus state, especially on or the button gets 80% opacity.

See also:

<img width="818" alt="Skærmbillede 2019-08-22 kl  14 46 10" src="https://user-images.githubusercontent.com/49033002/63515818-fa776c80-c4eb-11e9-9158-3a56f507b613.png">

**Comment by alxzak** [comment]
Pls consider to fix #417 & #460 during development of this issue.

**Comment by MadsBuchmann** [comment]
Is replaced by #1869
