### ISSUE TITLE
[BUG] Checkbox should constrain clickable area correctly 

### ISSUE THREAD

**Issue by ckibsen** [kirbydesign/designsystem#551]
**Describe the bug**
Depending on the context in which a Checkbox is shown, the clickable area can extend outside the borders of the Checkbox graphics (or in some circumstances be squeezed so that the clickable area is way smaller than the shown Checkbox graphics).

**To Reproduce**
Eg. Checkbox is placed inside a GridLayout which is stretched in the height (in this case because the text of the Label in col="1" wraps multiple lines): 

        <GridLayout columns="auto, *" rows="auto" class="express-transfer-wrapper">
          <kirby-checkbox
            [checked]="expressTransferSelected"
            (checkedChange)="expressTransferChange($event)"
            col="0"
            row="0"
          ></kirby-checkbox>
          <Label
            class="express-transfer-label"
            text="{{ expressTransferLabel }}"
            textWrap="true"
            col="1"
            row="0"
          ></Label>
        </GridLayout>

See attached screenshot, which show that the clickable (blue) area is way larger than the actual checkbox.

**Kirby version**
 - [e.g. 0.0.261]

**Expected behavior**
Clickable area should be constrained to always match the actual checkbox (maybe with an option to define a slightly larger clickable area), but it shouldn't extend way beyond the checkbox.

**Screenshots**
![KirbyCheckbox](https://user-images.githubusercontent.com/832287/63594800-b8b3f800-c5b7-11e9-9127-ba53006bf1ad.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: n/a
 - Version: n/a

**Native (please complete the following information):**
 - Device: iPhone SE
 - OS: 12.4
 - Browser: n/a
 - Version: n/a

**Comment by yucelbas** [comment]
Not relevant anymore.
