### ISSUE TITLE
[BUG] [NATIVE] [component:List] Click trigger on empty space 

### ISSUE THREAD

**Issue by darpankumar** [kirbydesign/designsystem#553]
**Describe the bug**
User is able to click on the padding which is white space and it trigger click event.
line-height property (applied threw kirby-class) causing issue, the 1st item in the list does not show properly this could be the issue with padding.

**To Reproduce**
1. Go to 'paper search page'
2. Enter search term.
3. A list will appear.
4. Try to click on the white space it trigger click event.
5. If you apply some styling (using kirby-class) the line height property causing issue in the 1st list item.

**Kirby version**
 - 0.0.262

**Expected behavior**
Click on the empty space should not trigger click event.
Even if some styling is applied the item in the list should appear properly

**Screenshots**
<img width="463" alt="Screenshot 2019-08-23 at 2 32 16 PM" src="https://user-images.githubusercontent.com/21257218/63674929-4cc6cf00-c805-11e9-8399-ac2df46ffd30.png">

**Native (please complete the following information):**
 - Device: [iPhone6]
 - Version 12.4

**Additional context**
This can be taken care along with
https://github.com/kirbydesign/designsystem/issues/524

**Comment by labanos** [comment]
cannot reproduce after {N} RIP
