### ISSUE TITLE
[BUG] Sort tekst på valgt segmentedControl 

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#555]
**Describe the bug**
On Android, the selected segmentedControl is shown with a black text inside the black control, thus the text is invisible.

**To Reproduce**
1. Find a Galaxy S8
2. Install master/592313ec45a83eaeb24ca90
3. Open inbox
4. See bug

**DRB version**
 - master/592313ec45a83eaeb24ca90

**Expected behavior**
The text should be white. 

**Screenshots**
![Skærmbillede 2019-08-26 kl  13 55 55](https://user-images.githubusercontent.com/49033002/63689267-cd87ca00-c809-11e9-88c6-1ee1e570afb7.png)

**Native (please complete the following information):**
 - Device: Galaxy S8
 - Version 7

**Comment by labanos** [comment]
cannot reproduce RIP {N}
