### ISSUE TITLE
[BUG] Deprecation Warning on Modals (Native)

### ISSUE THREAD

**Issue by mmmtrifork** [kirbydesign/designsystem#568]
We receive the deprecation warnings shown on the screenshot below:
<img width="847" alt="Screenshot 2019-08-29 at 12 48 43" src="https://user-images.githubusercontent.com/48326253/63934363-77aa6080-ca5b-11e9-881f-5594dcf44928.png">

This seems to be propagated by the https://www.npmjs.com/package/nativescript-windowed-modal plugin, hence updating the package might help resolve the problem. If that fails, we can potentially re-implement the plugin functionality on our end, which should also give us more control over the modals. 

To reproduce this behaviour:
1) Run kirby
2) Select 'Modal'
3) Select 'Show modal'
4) Check your terminal output

**Comment by labanos** [comment]
{N} RIP
