### ISSUE TITLE
[Enhancement] Segmented chip groups

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#572]
**Is your enhancement request related to a problem? Please describe.**
We want to be able to group chips into different segments, because even though some chips might be the same category, they can be separated into different groups. 

Like button groups, see also: https://getbootstrap.com/docs/4.3/components/button-group/

How we want to use them:
https://zpl.io/VQQAdgx and https://zpl.io/adNdYP7

** **

**Comment by labanos** [comment]
investment overview
