### ISSUE TITLE
[Enhancement] Ability to turn off default padding in modal

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#573]
**Is your enhancement request related to a problem? Please describe.**
Right now we visually cant make areas that go beyond the padding of the modal, like this: 
<img width="529" alt="Skærmbillede 2019-08-30 kl  08 03 38" src="https://user-images.githubusercontent.com/49033002/63997829-ea6d1780-caff-11e9-8d30-944a56753d9f.png">

it will always end up like this:
<img width="878" alt="Skærmbillede 2019-08-30 kl  07 47 37" src="https://user-images.githubusercontent.com/49033002/63997997-5e0f2480-cb00-11e9-8f96-e9fab584424a.png">

**Describe the solution you'd like**
Maybe we should be able to turn off the padding if we need to?

See also: https://zpl.io/aRXooxz

**Comment by bdyken** [comment]
An example for attachment pfd viewer where we would like to set left&right padding to 0
![image](https://user-images.githubusercontent.com/49056452/68113453-26ec3380-fef4-11e9-8328-81644b40dd2f.png)

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
