### ISSUE TITLE
[Enhancement] Click-event on the page-title

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#579]
**Is your enhancement request related to a problem? Please describe.**
We would like to be able to trigger the page-title in the toolbar and fire up other components, like a select/dropdown. 

This might also require that we need to be able to add an icon in the page-title to "communicate" that it's is clickable.

**Wireframes:** https://zpl.io/b61OPxK

<img width="451" alt="Skærmbillede 2019-09-02 kl  21 09 25" src="https://user-images.githubusercontent.com/49033002/64130979-fe499f80-cdc5-11e9-82af-c929dce656d1.png">

**Who needs this:** Team 5 is going to need this when page-title scroll up into the toolbar is going to be a thing.

![Skærmbillede 2019-09-05 kl  10 47 51](https://user-images.githubusercontent.com/49033002/64326640-a16b0680-cfca-11e9-81a0-b6348208b04d.png)

Inspiration was also found in eboks new app where you can do the same: 

<img width="745" alt="Skærmbillede 2019-09-02 kl  21 07 44" src="https://user-images.githubusercontent.com/49033002/64130940-bb87c780-cdc5-11e9-9386-e23968edb9b6.png">

**Comment by labanos** [comment]
Team 5 case: The pagetitle should allow interaction - to introduce a shorthand for changing balance viewed on a "totalkonto", which has more than one. This saves a trip back to the account list.

This issue describes how this should look, when the pagetitle is scrolled out of the view and into the toolbar...

**Comment by labanos** [comment]
might already be solved? works in the team 5 case? maybe just close?
