### ISSUE TITLE
[COMPONENT] Item

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#583]
**Describe the solution you'd like**
We thought of using items / content blocks / compositions, that can be used inside lists, cards and every other context where it could be relevant - Instead of everything being a list (the list that can solve everything ;) )

We have a lot of feature teams that are solving the same "things" without it being a Kirby item / content block (composition of atoms), which definitely could be optimized. 

**Implementation**
- An item should acts as a wrapper for text, icons, avatars, images, inputs, and any other native or custom element.
- The item handles the layout incl. margins and padding of the _elements_ within.
  - Elements within are layed out horizontally by default between named slots
  - Named slots on elements will place the element in that particular slot
- The wrapper for items (list, card, action sheet etc) handles the layout, size, dividers etc of the _items_ within.

***Code example;***
```
<kirby-item>
  <kirby-avatar> 
    <kirby-icon name="moneybag"></kirby-icon>
  </kirby-avatar>
  <h3>My label</h3>
  <h3 slot="end">kr. 1.234,-</h3>
</kirby-item>
```

**Describe alternatives you've considered**
See https://www.vic.gov.au/content-blocks-design-system or [ion-item](https://ionicframework.com/docs/api/item)

**Additional context**
In our sketch file, compositions of atoms are often items which are put into our views, so thats why we thought the same would maybe be nice in kirby to have.

![image](https://user-images.githubusercontent.com/9556693/64778206-e9a29f80-d55b-11e9-964d-cb403bef5a7e.png)

![List](https://user-images.githubusercontent.com/9556693/64778291-21a9e280-d55c-11e9-8286-52a652544db2.png "List")

![List](https://user-images.githubusercontent.com/9556693/64778738-b44a8180-d55c-11e9-9673-de15166a5d70.png "List")

![Action Sheet](https://user-images.githubusercontent.com/9556693/64780192-0640d680-d560-11e9-8fab-474dd43ed5e7.png "Action Sheet")

### Kick Off:
- [x] Accept Feature incl. name of component (DSL)
- [x] Update Kirby Component Status and publish to [Kirby Cookbook](https://cookbook.kirby.design)
### Code:
- [x] Create Feature Branch
- [x] Implement Skeleton Component
- Ask UX for review:
    - [ ] Ensure implementation is correct on in relation to UX design
    - [ ] Define the version of the implementation + steps needed to reach version 1.0 (create [enhancement requests](https://github.com/kirbydesign/designsystem/issues/new?assignees=&labels=enhancement&template=enhancement-request.md&title=%5BEnhancement%5D))
- [x] [Implement Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Add link to showcase on Kirby Component Status (`component-status-items.ts => code.cookbookUrl`)
- [ ] Also remove `githubIssueNo` and set `status` to `ItemCodeStatus.ready`
- [ ] Push commits to GitHub
### Review:
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- Merge to master and delete branch

**Comment by dalsgaard** [comment]
![400_Ændre-frakonto_betalregning](https://user-images.githubusercontent.com/679/64958571-c9dae680-d88f-11e9-91c7-0fc5d8bf7f96.png)
![701_Opsummering_m tekst](https://user-images.githubusercontent.com/679/64958623-e5de8800-d88f-11e9-92aa-b826ac9a128a.png)
![1001_Kvittering](https://user-images.githubusercontent.com/679/64958685-00b0fc80-d890-11e9-9431-c76dcd0b97c7.png)
![300_Regning_Opsummering_u beløb](https://user-images.githubusercontent.com/679/64958824-381fa900-d890-11e9-9d59-d9378fe68f7e.png)
![210_Vælg-modtager_egnekonti](https://user-images.githubusercontent.com/679/64958875-48378880-d890-11e9-987e-2ef48fa6d1e4.png)
