### ISSUE TITLE
[BUG] LG Button min width must be 220px

### ISSUE THREAD

**Issue by bdyken** [kirbydesign/designsystem#588]
**Describe the bug**
<button kirby-button size="lg"... must have a min-width of 220px, defined in the style guide. As it is now the button wrap around the text, with at short text, the button i smaller than 220px and we need to set the button to specific 220px in our styles guide

Expected:
![image](https://user-images.githubusercontent.com/49056452/64250973-b3d83800-cf17-11e9-9553-cc2fa8cbcbc1.png)
Actual:
![image](https://user-images.githubusercontent.com/49056452/64251557-20a00200-cf19-11e9-8d69-4a280fb1c804.png)

**Comment by bommariusser** [comment]
Totally agree @bdyken , thats how its defined in our UI styleguide ! But thats only on the LG button :) Maybe it should be default and not min? 

Remember to tag the component on the right :)

**Comment by bdyken** [comment]
I don't know if it's a good idea to the width default to 220px, if there are need for at lg button that are larger than 220px, so width-min: 220px is preferred

**Comment by bommariusser** [comment]
@bdyken its fixed right? I close the issue :)
