### ISSUE TITLE
[Enhancement] Enable LoadOnDemand after disabling

### ISSUE THREAD

**Issue by jonasjensen-brolstark** [kirbydesign/designsystem#590]
**Is your enhancement request related to a problem? Please describe.**
If i have a `kirby-list` with the `loadOnDemand` callback set, i can disable `loadOnDemand` by calling  `event.complete(true)` on the `LoadOnDemandEventData` event.

But i can not enable `LoadOnDemand` again.

**Describe the solution you'd like**
I would a simple way to enable the `loadOnDemand` events again.

Right now the `kirby-list` has a property called `isLoadOnDemandEnabled`.
If this was made an `@Input()` you would be able to set as a user of the `kirby-list` and that way enable `loadOnDemand` again.

**Describe alternatives you've considered**
The more pretty solution would be that the `kirby-list` would have a public method to enable/disable `loadOnDemand`.

**Comment by labanos** [comment]
team 5 might for now be the only ones with an issue here - parking till after 1st release - team 5 will solve it before if they think it is a big issue ;)
