### ISSUE TITLE
[Enhancement] Move inline buttons in toolbar (scroll down)

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#592]
**Is your enhancement request related to a problem? Please describe.**
We would love a possibility to move some inline actions in the toolbar on scrolldown. 

See also:

Primary action:
<img width="743" alt="Skærmbillede 2019-09-05 kl  18 53 18" src="https://user-images.githubusercontent.com/49033002/64363623-6a6c1380-d011-11e9-84d3-26c8693b6209.png">

Secondary action:
<img width="805" alt="Skærmbillede 2019-09-05 kl  18 53 22" src="https://user-images.githubusercontent.com/49033002/64363622-6a6c1380-d011-11e9-9cd0-f55c1f63f068.png">

**Comment by labanos** [comment]
@jakobe and @hafstad - Lets take this into consideration for the "page template" refinement. If it makes it too complicated you have the right to "postpone" till after 1st release ;)
