### ISSUE TITLE
[BUG] Modal exceeds fold on small screens

### ISSUE THREAD

**Issue by MonsterGameDev** [kirbydesign/designsystem#602]
**Describe the bug**
Web on Mobile
When modal content exceeds beyond the fold its not possible to scroll down to the bottom - losing the CTA or whatever you got hidden down there.
The Modal sadly exceeds beyond the fold

**To Reproduce**
1. Go to cookbook
2. pick the smallest possible mobile from chrome dev tools
3. fill in extra content (so you got more content than the modal can show
4. note that scrolling is not possible

**Kirby version**
 - 0.7.10

**Expected behavior**
You should see  whole modal on screen

**Screenshots**
![Screenshot 2019-09-13 at 10 54 40](https://user-images.githubusercontent.com/28903575/64850187-339b8c00-d615-11e9-810e-b9850e932774.png)

**Please complete the following information:**
 - OS: All
 - Browser Chrome
 - Version 76.0.3809.132 

**Additional context**
problem lies in styling - the top padding has been added by moving the modal with transformY.

**Comment by jb-trm** [comment]
Has been "fixed" in #605

However it also changes the design, the modal on mobile is supposed to be offset a little from the top, so the fix is temporary.
