### ISSUE TITLE
[BUG] Able to scroll in the list behind a modal view

### ISSUE THREAD

**Issue by MikaelKristoffersenBankdata** [kirbydesign/designsystem#603]
**Describe the bug**
When testing search function in account entries we were able to scroll in the content behind the modal.

**To Reproduce**

1.	Choose search modal in account entries (magnifying glass in rigt corner)
2.	Try to scroll in the modal
3.	You will see that the list behind the modal is moving

You will see the same problem in buy flow when you have to select number of stocks.

**Kirby version**
 - [0.7.8]

**Expected behavior**
You should be able to scroll in the modal without scrolling in the list in the background.

**Screenshots**

**Please complete the following information:**
 - OS: [iOS]

**Comment by jakobe** [comment]
@MikaelKristoffersenBankdata This seems to be fixed by the latest changes to the modal. Can you confirm?

**Comment by MikaelKristoffersenBankdata** [comment]
Just tested on Kirby 0.8.54 and it seems to be fixed.
