### ISSUE TITLE
[BUG] Font styling in Listheader on IOS

### ISSUE THREAD

**Issue by bdyken** [kirbydesign/designsystem#609]
The font in the list header er is overriden by ion-list-header to uppercase and different size, this is the present for normal test, H1 and H2.

1. Go to cookbook list: https://cookbook.kirby.design/home/showcase/list in chrome
2. Scroll down til "List with header and footer"
3. open developer tool, togle view to device iPhone X
4. reload page
5. The headers is uppercase ind header, not expected

![image](https://user-images.githubusercontent.com/49056452/64940965-ab5ff580-d865-11e9-8df3-d7cb2baee8c6.png)

The Expected
![image](https://user-images.githubusercontent.com/49056452/64941002-c3377980-d865-11e9-8045-f42047e956bf.png)

Experience on simulator and emulator locally
iPhone X
![image](https://user-images.githubusercontent.com/49056452/64941695-9e440600-d867-11e9-9719-785b218a2ab9.png)
Android
![image](https://user-images.githubusercontent.com/49056452/64941729-b1ef6c80-d867-11e9-9fac-a6ea87ecd78f.png)

**Comment by bommariusser** [comment]
Feels like this issue could be present in more then just this component. Is there any way we can research or test if our fonts work like they should, on all devices? :P @jb-trm ? :)
