### ISSUE TITLE
[Enhancement] Provide SCSS and Typescript responsive breakpoints

### ISSUE THREAD

**Issue by lydemann** [kirbydesign/designsystem#613]
**Is your enhancement request related to a problem? Please describe.**
We want to have the different responsive breakpoints so we have clearly defined the width for the different screen sizes: xs, sm, md, lg, xl

**Describe the solution you'd like**
We could just use the min-width breakpoints defined by Flexbox layout [here](https://github.com/angular/flex-layout/wiki/Responsive-API).
xs: 599px
sm: 600px-959px
md: 960px-1279px
lg: 1280px-1919px
xl: 1920px

Exposed as both a ResponsiveService and a responsive.scss file.

**Describe alternatives you've considered**
Maybe we want to use other breakpoints @bommariusser, ok with you?

**Additional context**
This should be exposed as both Typescript and SCSS variables as we need to use the breakpoints with both technologies.
Use cases for using these:
- Run logic only for specific screen sizes
- Styling eg. only for mobile

**Comment by jb-trm** [comment]
@lydemann We have some breakpoints here available in Scss here:
https://github.com/kirbydesign/designsystem/blob/0c71962d97e18077e3c0ab21fd059eabdd1e9880/src/kirby/scss/base/_variables.scss#L59

Though they were defined aprox. 3/4 year ago I believe. The xlarge and xxlarge need to be removed. 

For TS I believe there is a sass-helper file somewhere.

**Comment by lydemann** [comment]
@jb-trm ok. Would it make sense to also expose as a service that encapsulates the breakpoints? Instead of just using the sass-helper and DIY?

**Comment by labanos** [comment]
@lydemann sorry to be a bit "admin-mean" here - but i think this is a question/topic better discussed in the kirby slack channel? =) - closing the issue for now.
