### ISSUE TITLE
[BUG] Kirby drawer has uncentered header

### ISSUE THREAD

**Issue by SilverGull** [kirbydesign/designsystem#619]
**Describe the bug**
A drawer without an icon to the right in the header, will not be centered correctly - it is centered in the remaining space between the close arrow and the right side of the drawer.

**To Reproduce**
Make a drawer with a title and no right side icon in the header. Also See cookbook

**Kirby version**
 - 0.7.19

**Expected behavior**
In Zeplin the title is centered between the left and right side of the component, ignoring the icons.

**Screenshots**
![Screenshot 2019-09-23 at 12 30 14](https://user-images.githubusercontent.com/43959200/65419013-02ce0a80-ddfe-11e9-9709-662f87779626.png)

**Please complete the following information:**
 - Chrome

**Additional context**

**Comment by labanos** [comment]
seems to have been fixed already - cannot reproduce
