### ISSUE TITLE
[Bug] smooth scrolling does not work in modal.

### ISSUE THREAD

**Issue by Kristian2332** [kirbydesign/designsystem#622]
**When accessing a list in a modal and tries to scroll the list does not have smooth scrolling**

**The list should have smooth scrolling as is the case when scrolling in account list.**

**Go the the transfer flow and access account picker or go to investment buy/sell flow and access account picker**

**Comment by bommariusser** [comment]
@Kristian2332 changed it to bug, oki :) ?

**Comment by labanos** [comment]
really finding it har to reproduce this - does it require like 200+ accounts or something weird?

**Comment by jakobe** [comment]
Not verified
