### ISSUE TITLE
[BUG] Modal close button does not work on orphanned modal

### ISSUE THREAD

**Issue by MonsterGameDev** [kirbydesign/designsystem#623]
**Describe the bug**
If a view opens a modal and then gets closed, the modal is "orphaned" and cannot be closed by the close button/hideTopmost (though click on backdrop still works)

EDIT:
Problem appears also when trying to use modalController.hideTopmost / .hideAll  - which does not work either if modal is orphaned

**To Reproduce**
1. Create a modal
2.In its close-callback, open another dialog
3. close the "parent" modal
4. The close button on the  "orphaned" modal isn´t active
**Kirby version**
 - [0.7.14]

**Expected behavior**
If you can close the orphaned modal by clicking the backdrop - the close-button should work too

**Comment by labanos** [comment]
@MonsterGameDev is this a duplicate of https://github.com/kirbydesign/designsystem/issues/596? =)

**Comment by MonsterGameDev** [comment]
kind of correct - this is more precise so we are closing #596

**Comment by MonsterGameDev** [comment]
Fantastisk - problemet har løst sig selv - kan ikke genskabes.
