### ISSUE TITLE
[COMPONENT] Toggle-button

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#626]
**Describe the solution you'd like**
We would like a button that can change it's state (on/off) like a bridge between a toggle and a button.

To see a live example see google and its use of "follow" when youre searching for a stock:
https://www.google.com/search?safe=off&sxsrf=ACYBGNTawsT3H5WNLKyegrOu8Lj8711kSw%3A1569310829182&ei=bciJXcHhCq7IrgTLiKDQBA&q=apple+aktie&oq=apple+aktie&gs_l=psy-ab.3..0i131i70i250j0l6j0i203l3.1343.3965..4080...6.2..0.62.356.6......0....1..gws-wiz.......0i71j35i39j35i39i19j0i131i67j0i131j0i67j0i10.8QKBSCUWPx0&ved=0ahUKEwiBzI-0-ujkAhUupIsKHUsECEoQ4dUDCAs&uact=5

**Describe alternatives you've considered**
I've found this example that we might could use as a inspiration: https://material.angular.io/components/button-toggle/overview

**Additional context**
We are thinking about using a There might be some accessibility issues when we just use a button and exchange it with another button after we have pressed.

See also: https://www.accessibility-developer-guide.com/examples/sensible-aria-usage/pressed/ 

See also:
<img width="542" alt="Skærmbillede 2019-09-24 kl  09 44 42" src="https://user-images.githubusercontent.com/49033002/65491750-f4402b80-deaf-11e9-912e-6914aec8e248.png">

### Kick Off:
- [ ] Accept Feature incl. name of component (DSL)
- [ ] Update Kirby Component Status and publish to [Kirby Cookbook](https://cookbook.kirby.design)
### Code:
- [ ] Create Feature Branch
- [ ] Implement Skeleton Component
- [ ] Add any required mock and fakes to the `KirbyTestingModule`
- Ask UX for review:
    - [ ] Ensure implementation is correct in relation to UX design
    - [ ] Define the version of the implementation + steps needed to reach version 1.0 (create [enhancement requests](https://github.com/kirbydesign/designsystem/issues/new?assignees=&labels=enhancement&template=enhancement-request.md&title=%5BEnhancement%5D))
- [ ] [Implement Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Add link to showcase on Kirby Component Status (`component-status-items.ts => code.cookbookUrl`)
- [ ] Also remove `githubIssueNo` and set `status` to `ItemCodeStatus.ready`
- [ ] Push commits to GitHub
### Review:
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- Merge to master and delete branch

**Comment by jakobe** [comment]
`<kirby-toggle-button checked="true|false">
 <button kirby-button *showWhen="false" attentionLevel="3">
	<kirby-icon name="add" />
	Afstem
 </button>

 <button kirby-button *showWhen="true" color="success">
	Afstemt
	<kirby-icon name="checkbox" />
 </button>
</kirby-toggle-button>

------

KirbyToggleButtonColorDirective
selector: 'button[kirby-button showWhen color]'
@HostBinding('class')
@Input() color: 'success' | 'warning' | 'danger';

------

KirbyToggleButtonShowWhenDirective
selector: 'button[kirby-button showWhen]'
@input() showWhen: boolean


----

kirby-button => css => :host-context(kirby-toggle-button) { }`

**Comment by jakobe** [comment]
Closed by #1159
