### ISSUE TITLE
[BUG] Kirby button looks wrong

### ISSUE THREAD

**Issue by Kristian2332** [kirbydesign/designsystem#627]
![EC93AEE0-8E60-4441-B735-42BC9B228848](https://user-images.githubusercontent.com/49475219/65509347-8e18d000-ded2-11e9-96ea-82b3edcfd254.png)
![21777BBA-915E-4192-8C93-BCF73CBCDD34](https://user-images.githubusercontent.com/49475219/65509348-8e18d000-ded2-11e9-9d7c-61f9eb90bc05.png)
![2C09CB91-50B5-4B60-897F-872139B99197](https://user-images.githubusercontent.com/49475219/65509350-8e18d000-ded2-11e9-9d5f-a7aa3a272ebd.png)

**The Kirby button used to select language, unfold transactions and ‘aftem’ looks wrong after the last Kirby bump**

**To Reproduce**
1. Start the DRB Test build
2. See that the select language button looks funny.
3. Go to transaction 
4. Unfold upcoming transactions 
5. See that the unfold button looks funny

**Kirby version**
 - 0.7.18

**Expected behavior**

**Screenshots**

**Please complete the following information:**
 - OS: Android + iOS

**Additional context**

**Comment by bommariusser** [comment]
@Kristian2332 jeg har oprettet en issue #618 som burde fikse det issue, er det okay? :)
