### ISSUE TITLE
[Enhancement] Loading af pages/componenter

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#634]
**Is your enhancement request related to a problem? Please describe.**
Vi skal have en ensartet måde at loade sider og ting på:

- Page-title og andre komponenter der ikke er afhængig af en backend kald
- Der vises spinner i det content der er afhængig af backend

Fx. 
![Skærmbillede 2019-09-26 kl  10 27 31](https://user-images.githubusercontent.com/49033002/65671841-4a47d700-e048-11e9-8ff8-cf7a687190a7.png)

eller

![Skærmbillede 2019-09-26 kl  10 27 31](https://user-images.githubusercontent.com/49033002/65671972-8713ce00-e048-11e9-9a76-acbe2ad1b620.png)

Prøv også at se hvordan indbakken er blevet implementeret!

**Comment by labanos** [comment]
should be solved in DRB using overlay and spinner correctly and consistenly
