### ISSUE TITLE
[Enhancement] Grey color support

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#636]
**Is your enhancement request related to a problem? Please describe.**
We need to be able to have a grey version of the list background. We should find a semantic way of setting it but right now i have no idea of how to name those. 

Maybe attention level 1 = White 2 = grey :) 

See also: 
https://zpl.io/bljRlL1
![Skærmbillede 2019-09-26 kl  11 26 11](https://user-images.githubusercontent.com/49033002/65676620-84b57200-e050-11e9-8a68-1c198f473a7b.png)

**Comment by jonasjensen-brolstark** [comment]
Don't we already have support for this. See the `List with colored items:` section in the [cookbook](https://cookbook.kirby.design/home/showcase/list).

But yes it is right now we are doing it with a callback in code and not semantically.
