### ISSUE TITLE
[BUG] Modal resizes on keyboard activation

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#639]
**Describe the bug**
When you open a modal on native with an input inside itself, like "overfør og betal", the keyboard pushes the outer edges from the bottom up, instead the keyboard just being on top of the modal. 

This ends up with a modal that looks like it ends over the keyboard, until you close the keyboard.

**To Reproduce**
1. Go to "overfør og betal" (both web&native)
2. See the modal gets resized in the bottom.

**Expected behavior**
https://zpl.io/2E14Xjv

**Screenshots**

![IMG_4105](https://user-images.githubusercontent.com/49033002/65690039-79713f00-e06e-11e9-9866-004e21d80629.PNG)

![image](https://user-images.githubusercontent.com/49033002/65689775-023bab00-e06e-11e9-94cd-7cb99da129b1.png)

**Comment by TildeVingeHem** [comment]
In team 4 we have an issue with showing the input field in the center of the visible part of the modal once the keypad comes up. Could be great with a solution that makes sure that the activated input field is always placed in the middel of the visible part of the screen once the keypad / numpad comes up.
![image](https://user-images.githubusercontent.com/52239688/67756546-7c2ecd80-fa3a-11e9-943b-19c522c7fb7d.png)
![image](https://user-images.githubusercontent.com/52239688/67756587-8b158000-fa3a-11e9-86e8-fb131f9fb7e3.png)
Investering - handel med værdipapirer: Ved klik på "Kursværdi" eller "Antal" forsvinder inputfelterne under tastaturet.

**Comment by labanos** [comment]
Won't fix - avoid aligning content vertically, as stuff will "bounce" if you realign when the view is resized when the keyboard is shown. (see #801 for issue with focus on input fields and scrolling into view)
