### ISSUE TITLE
[Enhancement] List section header vertical alignment

### ISSUE THREAD

**Issue by jb-roa** [kirbydesign/designsystem#644]
**Is your enhancement request related to a problem? Please describe.**
The list section header is currently vertically centered between two sections. According to DRB UX'ers, the section header should be positioned at the top of the next item to indicate coherence. 

**Describe the solution you'd like**
Position the section header at the bottom of the dividing space like shown here: 
![JB0264_000005](https://user-images.githubusercontent.com/53940402/65861482-a2dee300-e36c-11e9-952a-d82c6ae23b50.png)

**Comment by labanos** [comment]
closed by #676
