### ISSUE TITLE
[Enhancement] Configurable margin on buttons

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#649]
**Describe the bug**
Buttons have today 4dp margin, but we should consider how we really want buttons to behave, since this margin makes it harder to place button in the view.

See: https://cookbook.kirby.design/home/showcase/button

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
