### ISSUE TITLE
[Enhancement] Delay spinner when when call to bff is fast (500ms'ish)

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#651]
**Is your enhancement request related to a problem? Please describe.**
We would like to put an automatic delay on the spinner, so it doesn't show when the respons from the backend / bff is fast.

If we don't do this we eventually will end up with a spinner that only blinks for a split-second.

**Comment by lydemann** [comment]
I don't think the spinner has anything to do with the BFF. Do we want to couple this logic into the spinner component or just implement this logic for the client app?

**Comment by bommariusser** [comment]
I was unsure where to put this so i just made an enhancement request. I do agree that it might be too much logic for a generic component.
