### ISSUE TITLE
[Enhancement] Make selectedItem in List an Input

### ISSUE THREAD

**Issue by lydemann** [kirbydesign/designsystem#652]
**Is your enhancement request related to a problem? Please describe.**
The enhancement is for enabling marking a row as selected without needing to click on it. I want to be able to set the selected item of the list without clicking, so it can make the row's text bold.

**Describe the solution you'd like**
I simply want selectedItem in ListComponent to be a component input.

**Describe alternatives you've considered**
I have considered manually triggering a click using code from the client app's code, but that is not very convenient.

**Additional context**
When rendering a list, I want it to be able to mark a row as selected initially (like this):
![image](https://user-images.githubusercontent.com/9210691/66043657-0cebb980-e520-11e9-939d-ef5bf98cac51.png)

**Comment by labanos** [comment]
@lydemann  is this still relevant? i can see you already solved it.. so not sure this issue still makes sense? plz close it if you feel it timed out =)

**Comment by lydemann** [comment]
@labanos I solved it by styling it manually outside of Kirby :)
I still think we should support setting a list row as initially selected through Kirby, so I don't need to do 50% in kirby and 50% in feature usage. :)

**Comment by jakobe** [comment]
@lydemann I think this should be solved by using plain Items in a Card instead like this example: https://cookbook.kirby.design/home/showcase/item
Agree?

**Comment by lydemann** [comment]
@jakobe I think this should be supported in lists as well.

**Comment by alxzak** [comment]
Agreed that this is already supported, then. :)
