### ISSUE TITLE
[Enhancement] Sticky Footer

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#653]
**Is your enhancement request related to a problem? Please describe.**
We would like to be able to animate set some content as sticky so that when the user scrolls by it it will appear in the footer of the page/modal.

**Comment by SilverGull** [comment]
This is also needed by team 3.
Example: https://zpl.io/VO1X71L

**Comment by bommariusser** [comment]
See also https://github.com/kirbydesign/designsystem/issues/918

**Comment by lydemann** [comment]
This is needed by team 5 as well:
https://zpl.io/b6XKDKN

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
