### ISSUE TITLE
[Enhancement] Truncate page-title if title is longer then your defined max-height of page-title

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#655]
**Is your enhancement request related to a problem? Please describe.**
We would like to truncate our page-title when we have longer titles that break our truncation rule (scale from h1 to h3). 

In the page-template we want to define what our max-height of our page-titles are, and we want to scale font down before we truncate.

The text-scaling task can be found here: https://github.com/kirbydesign/designsystem/issues/481

So the rule should be triggered when there is no more space in the title and the font-size has gone down to h3.

**See also**

Left to right: 
H1 - H2 - H3 & truncate
<img width="1195" alt="Skærmbillede 2019-10-07 kl  19 50 07" src="https://user-images.githubusercontent.com/49033002/66335664-c4773600-e93b-11e9-987f-50b3046889d5.png">

**Comment by jakobe** [comment]
Change from 🏷SKAL to 🏷BØR as #481 mitigates this issue
