### ISSUE TITLE
Kirby-list-header draws outside of Kirby card

### ISSUE THREAD

**Issue by Anders-Bloch** [kirbydesign/designsystem#66]
When you add the list header within a Kirby card, the header is drawn outside of the card (to the right). Removing width=100% css element fixes the problem.

**Comment by bdujrn** [comment]
Is this still an issue? Seems to work? 
![list_android](https://user-images.githubusercontent.com/41470068/51592727-a920e380-1ef0-11e9-930f-3f30bf7d25b2.png)
![list_ios](https://user-images.githubusercontent.com/41470068/51592729-a920e380-1ef0-11e9-8c88-e1a3d07ea45a.png)
![list_web](https://user-images.githubusercontent.com/41470068/51592730-a920e380-1ef0-11e9-8e14-b9a97d3e72bd.png)

**Comment by PetarRing** [comment]
@Anders-Bloch is this still an issue?
