### ISSUE TITLE
[BUG] Leftover from {N} in Cookbook?

### ISSUE THREAD

**Issue by ckibsen** [kirbydesign/designsystem#660]
**Describe the bug**
Modal showcase links to {N} Playground (and a close Github issue #385). Looks like a leftover from the {N} days, and 

**To Reproduce**
1. Go to https://cookbook.kirby.design/home/showcase/modal
2. Find 'Opening multiple modals from the same view'

**Kirby version**
 - [e.g. 0.0.55]

**Expected behavior**
No trace of {N} what so ever (gives me the creeps).

**Screenshots**

**Please complete the following information:**
- n/a

**Additional context**
<img width="1181" alt="Screenshot 2019-10-07 at 12 03 20" src="https://user-images.githubusercontent.com/832287/66303320-1350ab80-e8fb-11e9-890b-8edfc6c9af35.png">

**Comment by jakobe** [comment]
Fixed
