### ISSUE TITLE
[Enhancement] Insert DRB icons in Cookbook & Update icons in Kirby

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#668]
Emnet fortæller det hele. Vi skal indsætte & opdatere siden. Sådan at det er delt op i hhv. Kirby & Custom/DRB

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
