### ISSUE TITLE
[BUG] Text in Safari gets rendered different compared the Cookbook/Chrome etc. (The font is lighter)

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#670]
When we compare Safari and Cookbook there is a knowledgable difference in font rendering. This might be an ionic bug thing.

**See also:**
![Skærmbillede 2019-10-09 kl  16 06 27](https://user-images.githubusercontent.com/49033002/66488762-c57ca480-eaae-11e9-820a-8ed9be92f92d.png)

**Comment by jb-trm** [comment]
Ah, I found it. DRB isn't loading the Bold version of roboto. Will fix it in DRB and close this when its done.
