### ISSUE TITLE
[Enhancement] Update Grid to the rest of the "Sites" Layout/Width

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#671]
One of our rule has been at some point, that content cant go wider then 720dp. One of the areas that hasnt been updated towards that is the grid. The large card should never be wider then 720dp, but follow the rest of the sites grid. 

The grid has right now a max of 1280, so it looks off when you put something in the "til dig" site.

See also how here how it should behave:
https://zpl.io/2pvW0r8

**Comment by jakobe** [comment]
Max content width is enforced through kirby-page (which at the time of this issue was created wasn't wrapping the dashbaord / "Til dig")
