### ISSUE TITLE
[Enhancement] Toast - Press to dismiss/close

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#674]
We want toasts to be dismissable, when clicking on them, and if they can do that then they should also be get a close (X) indication on itself.

See also: https://zpl.io/2j635mp
![Skærmbillede 2020-08-18 kl  11 48 56](https://user-images.githubusercontent.com/49033002/90498708-edb24680-e148-11ea-8a19-06a5306ab914.png)

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
