### ISSUE TITLE
[Enhancement] Dynamic change of modal header/title

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#677]
**Is your enhancement request related to a problem? Please describe.**
We want the drawer to be able to change the header dynamically dependant on which action you want it to be. 

This could example be a new message where the modal starts to have "new message" in the title, and while the user changes the subject of the message the title of the modal changes together with that:

UI: https://zpl.io/V059ONm

See also:
<img width="687" alt="Skærmbillede 2019-10-12 kl  15 08 46" src="https://user-images.githubusercontent.com/49033002/66701957-77f87580-ed02-11e9-9170-1b4f74cc6b3f.png">

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
