### ISSUE TITLE
[Enhancement] Margin optimizing on small screens (<360dp)

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#678]
Right now we have 16dp margin into our content (left&right), like cards, text etc. In some places we even have more to break that (page title 32dp)

We want to minimize this when people using a smaller screen are using our service:

**<360dp: we go from: 
- 16->8 in content 
- 32->16 page-title.** 

See also:

<img width="975" alt="Skærmbillede 2019-10-13 kl  12 08 52" src="https://user-images.githubusercontent.com/49033002/66714161-99656a00-edb3-11e9-9e09-7e62cdbb51b9.png">

Eventually on bigger screens we probably do the same but in the other direction ;) (see also this for an example: https://github.com/kirbydesign/designsystem/issues/559) 

**Why?** 

Our guidelines say that we optimize in margin left&right dependent on which screen you are on (width of the device), and not margin top&bottom.

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
