### ISSUE TITLE
Component status - review/redesign/sunset

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#680]
**Describe the bug**
Our component status in the cookbook doesn't show all our enhancement that are still open. Especially the old ones are not shown.

**To Reproduce**
1. Go to Cookbook and compare with Enhancement in Github
4. See that the oldest enhancements are not shown in the cookbook

**Comment by labanos** [comment]
@bommariusser @jakobe @hafstad - lets talk about this! =)

**Comment by RasmusKjeldgaard** [comment]
Fixed by #1418
