### ISSUE TITLE
[Enhancement] Scroll up on pressing a selected tab

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#682]
**Is your enhancement request related to a problem? Please describe.**
We want a native behavior, that refreshes the site / scrolls up to the top / goes to the very first site of the menu-point, when the user taps an active menu.

Eg. when a user is in a posting-detail (4 level in accounts) and presses the account tab again, they get to the very first site of the account (account overview)

**Comment by jakobe** [comment]
@bommariusser is this a duplicate of #669 ?
