### ISSUE TITLE
[Enhancement] Cards should be able to take all the colors in our design system

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#684]
**Is your enhancement request related to a problem? Please describe.**
Right now cards can't be all colors and only theme colors, but we should be apply all colors in our design system, like semi-light and other which are not part of our "theme-colors".

See also:
https://zpl.io/2ZXq7X4

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
