### ISSUE TITLE
[BUG] Dokumentering af bugs / småforbedringer :)

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#693]
**Describe the bug**
See the attached screenshots below. They are mostly screenshot that are issues right now:

Mostly its about Toolbar + Tabbar (+safe area)

![Skærmbillede 2019-10-16 kl  12 56 47](https://user-images.githubusercontent.com/49033002/66914218-96b67f00-f016-11e9-8cea-952fc54118f2.png)

![Skærmbillede 2019-10-16 kl  12 57 01](https://user-images.githubusercontent.com/49033002/66914208-9322f800-f016-11e9-8f60-76ec471658ee.png)

<img width="510" alt="Skærmbillede 2019-10-16 kl  18 07 10" src="https://user-images.githubusercontent.com/49033002/66937540-ea898e00-f03f-11e9-829b-1c70ab8e96b8.png">

<img width="703" alt="Skærmbillede 2019-10-16 kl  18 06 19" src="https://user-images.githubusercontent.com/49033002/66937541-ea898e00-f03f-11e9-8d7b-cc42c8de0389.png">

<img width="823" alt="Skærmbillede 2019-10-16 kl  18 06 15" src="https://user-images.githubusercontent.com/49033002/66937542-ea898e00-f03f-11e9-9ce4-bd168711c9a5.png">

<img width="899" alt="Skærmbillede 2019-10-16 kl  21 35 08" src="https://user-images.githubusercontent.com/49033002/66952436-eb7ce880-f05c-11e9-8e76-a3ade60561f6.png">

<img width="809" alt="Skærmbillede 2019-10-19 kl  08 48 32" src="https://user-images.githubusercontent.com/49033002/67139184-7fada200-f24d-11e9-9d9d-3cb4d26444da.png">

**Please complete the following information:**
- OS: iOS (På en X'er) & Web Chrome

**Comment by labanos** [comment]
duplicated
