### ISSUE TITLE
[Enhancement] Elevation, opacity & blur on tabbar

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#694]
It's hard to differentiate the difference between canvas, the toolbar and the tabbar. see also this screenshot
![Skærmbillede 2020-07-09 kl  13 18 50](https://user-images.githubusercontent.com/49033002/87033604-cc277c00-c1e6-11ea-9006-fed29b3becab.png)

Thats why we are going to make some changes to make the difference more visible, see also
![Skærmbillede 2020-07-09 kl  13 18 54](https://user-images.githubusercontent.com/49033002/87033737-13157180-c1e7-11ea-9e5d-f05bed0f5320.png)

Specs:
2. Tabbar white + 1px light border top (Hvidt vidt hvidt!)
3. Tabbar 4 px background Blur & 94% Opacity

**Comment by jakobe** [comment]
@bommariusser Think this needs refinement / example / screenshot
