### ISSUE TITLE
[Enhancement] Spinner with text

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#696]
**Is your enhancement request related to a problem? Please describe.**
We would like to be able to add some text under the Spinner, especially for use-cases where it takes around 20-30seconds or more to load something.

See also:
https://zpl.io/25A74PQ

**Comment by labanos** [comment]
@bommariusser not sure the link is correct? At least there is no spinner on that page?

**Comment by bommariusser** [comment]
@labanos sådan :D heller ik så nemt hvis skærme ændrer sig til noget helt andet :)

**Comment by jakobe** [comment]
@bommariusser Is this still relevant? Also please update the dead Zeplin link and/or include a screenshot in this issue 🙏🏻

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
