### ISSUE TITLE
[Enhancement] Keyboard toolbar actions (Only enable close keyboard "Luk")

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#698]
We would like to lock the amount of choices you have when you choose the Toolbar above the Keyboard.

The only thing we want to have on the right side of the toolbar is to close the keyboard without confirming anything.

![Skærmbillede 2019-10-21 kl  15 01 47](https://user-images.githubusercontent.com/49033002/67207508-07dda400-f414-11e9-9ada-55d3e7190d80.png)

**Comment by labanos** [comment]
Is a DRB thing - this is a reminder..

**Comment by jakobe** [comment]
This is not a Kirby (or Ionic)n feature, but Capacitor in the target project.
