### ISSUE TITLE
[Enhancement] Sticky page title on custom sites.

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#707]
**Is your enhancement request related to a problem? Please describe.**
We want to be able to define a  "STICKY PAGE TITLE" , especially on custom sites, that scrolls into the toolbar as soon as the text is hidden.

See also: 
![Skærmbillede 2019-10-23 kl  10 45 00](https://user-images.githubusercontent.com/49033002/67375192-8d7f6200-f582-11e9-82e6-df23e8deb6c6.png)

**Comment by bommariusser** [comment]
@jonasjensen-brolstark see here. :)

**Comment by flemcito** [comment]
Closing, at it is addressed by #1155 (more specifically #1483 )
