### ISSUE TITLE
[Enhancement] Rename Empty State to Messaging States

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#711]
**Is your enhancement request related to a problem? Please describe.**
We decided that Empty State wasn't a good name for the actual funcitonality of it, since it had different flavors, like

1. Empty
2. Error
3. Success
4. Danger

Empty State is going to be **Messaging States** 

our inspiration comes from https://www.lightningdesignsystem.com/guidelines/messaging/states/

and we have already renamed it in our design files: https://zpl.io/2j7MXe6

**Comment by jakobe** [comment]
**Tech refinement:** To avoid introducing a breaking change, the current `<kirby-empty-state>` component should be enhanced with an additional selector `<kirby-messaging-state>`or alternatively wrap a new `<kirby-messaging-state>` component inside the legacy `<kirby-empty-state>` component.
