### ISSUE TITLE
Account name (sticky) still visible after returning from Postings [BUG]

### ISSUE THREAD

**Issue by SteffenElberg** [kirbydesign/designsystem#718]
**Describe the bug**
Sticky account name in page template still visible after navigating back from Postings 

**To Reproduce**

1. Scroll down on Account list - until 'Konto' sticker in top is visible
2. Choose a sub account
3. Click on Account
4. Scroll to top of page: BUG = sticky 'Konto' + 'Konto + Overfør og betal' is shown

**Kirby version**

- 0.8.12

**Screenshots**
Not able to take screenshot from App

**Please complete the following information:**

- OS: Android 10, Pixel 3

**Comment by bommariusser** [comment]
@SteffenElberg godt spottet :) sku selv oprette denne.
