### ISSUE TITLE
[BUG] Kirby-fab-sheet throws "ion-backdrop is not a known element"

### ISSUE THREAD

**Issue by laljyskebank** [kirbydesign/designsystem#719]
**Describe the bug**
When testing on a component where kirby-fab-sheet is used, we get an error with "ion-backdrop is not a known element"

**To Reproduce**

1. kirby-fab-sheet is used on micro -> recurring-payments -> containers -> overview
2. when unit testing the component we get an error with "ion-backdrop is not a known element"

**Kirby version**

- 0.8.12

**Screenshots**

![Screen Shot 2019-10-25 at 08 41 40](https://user-images.githubusercontent.com/35138247/67550067-ea575580-f705-11e9-804f-81586b52bfc9.png)

**Comment by labanos** [comment]
@laljyskebank does this "break" UX or flow? or is it "just" a bug to fix when we have time?

**Comment by laljyskebank** [comment]
We can't write unit where FAB sheet is involved. It doesn't break UX or flow,, only regarding unit test.

**Comment by labanos** [comment]
Ok - unless there are two mondays in the next couple of weeks... im putting it till after release.. not because i want to.. but because i doubt we will get around to it before.. sorry (feel free to fix it yourselves ofc ;)

**Comment by laljyskebank** [comment]
I agree :-)

**Comment by jakobe** [comment]
Fixed
