### ISSUE TITLE
[Enhancement] FABSheet should be refactored to use items instead of actionsheet items

### ISSUE THREAD

**Issue by FinnCarlsen** [kirbydesign/designsystem#724]
**Is your enhancement request related to a problem? Please describe.**
I'm always frustrated when ......

**Describe the solution you'd like**
The ability to add an avatar in each action sheet item that symbolises the actual item. 

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or enhancement you've considered.

**Additional context**
Screenshot from Zeplin, recurring payments, team 6
https://app.zeplin.io/project/5c99d69a79d02b35ea3b8f41/screen/5d7f2d4b667d6618337d5ecf

**Comment by labanos** [comment]
@FinnCarlsen a link to a zeplin example, and maybe some info on when this is needed would be nice? =) (also doesnt hurt to add relevant labels eg ActionSheet and T6

**Comment by labanos** [comment]
@hafstad wouldn't it make more sense if this was solve with being able to put "items" in the action sheet? or is that weird?

**Comment by labanos** [comment]
unless you do it yourselves - its after first release ;)

**Comment by bommariusser** [comment]
@FinnCarlsen can you change the title to "FABSheet should be refactored to use items instead of actionsheet items"

**Comment by bommariusser** [comment]
@FinnCarlsen tak :D

**Comment by jakobe** [comment]
@FinnCarlsen Is this issue stil relevant? 🤔

**Comment by alxzak** [comment]
@bommariusser is this stil relevant?

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
