### ISSUE TITLE
[BUG] List with divider has no divider on small screens

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#729]
**Describe the bug**
A list with dividers has no dividers on small screens, but it should always have a divider.

![Skærmbillede 2019-10-28 kl  13 32 53](https://user-images.githubusercontent.com/49033002/67678801-cc008c80-f987-11e9-996e-2e18930218c7.png)

**To Reproduce**

1. Go to  cookbook

**Comment by jonasjensen-brolstark** [comment]
Closed by #737
