### ISSUE TITLE
[BUG] Kirby-overlay-spinner - importIssue, layoutHeightIssue

### ISSUE THREAD

**Issue by yucelbas** [kirbydesign/designsystem#731]
**Describe the bug**
1) When imported it causes a linting error.
2) It has a "content-wrapper" which does not allow for a page height of 100%.

**To Reproduce**

1. Go to 'transfer'
2. Input amount 
3. choose destination account from the list
4. See error - page does not look according to design. 

**Expected behavior**
I expect the card on the page to be at the bottom and more space between input-amount field and the card.

**Screenshots**
<img width="865" alt="spinner with overlay issue" src="https://user-images.githubusercontent.com/43955031/67752914-2820ea80-fa34-11e9-8cb9-b33cfeb46a60.png">

**Please complete the following information:**
both mobile and web

**Comment by labanos** [comment]
@lydemann could you maybe please take a look at this with team 2 to investigate a bit? =)

**Comment by lydemann** [comment]
@yucelbas  Can you reach out to me about this? What lint error are you getting?

**Comment by yucelbas** [comment]
I have texted you via Slack.

**Comment by lydemann** [comment]
I looked into this.

1): Just to be clear on the naming the component is called kirby-loading-overlay.
2) I tried to wrap "transfer-component" in the spinner and that didn't affect the look.
![image](https://user-images.githubusercontent.com/9210691/68990667-16be4780-0856-11ea-886f-00fff62e08fb.png)

Am I doing something wrong to reproduce the issue? @yucelbas Maybe you can send me a branch with the issue being present?

**Comment by yucelbas** [comment]
It is not transfer-component in which we need the loading-overlay but in transfer-and-pay-bill component. 
I have placed the loading-spinner in the code, where we want it to be - but it is outcommented. If you make a search on loading-overlay in the code you will land on the file.

**Comment by lydemann** [comment]
I will look more into this later. I can see it is not prioritized for 1st release.

**Comment by jakobe** [comment]
Fixed by modal refactoring
