### ISSUE TITLE
[Enhancement] Disable scrollview on page-template

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#738]
**Is your enhancement request related to a problem? Please describe.**
On some sites (vælg adgangskode etc.) we have not a lot of content , so we don't want the site to scroll. 

https://zpl.io/VKjXWP7

**Describe the solution you'd like**
Comment from @hafstad 

"Det er ikke noget den kan nu, men det vil være nemt at fixe :)
Du kan se her, hvad man kan ændre på ionic komponenten vi bruger. Hvis det står der er det noget vi får ud af boksen som bare skal udstilles via kirby  

https://ionicframework.com/docs/api/content

->under properties"

**Comment by jakobe** [comment]
Not sure about this one, it actually might be by design (the "bounce" signals to the user, you can't scroll) 🤔

**Comment by bommariusser** [comment]
closed and mentioned by jakobs issue
