### ISSUE TITLE
[BUG] Disable swipe back on root sites

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#742]
**Describe the bug**
When we are on our root sites like, "For You", "Accounts" & "Inbox" etc. we can actually swipe to the right to "logout"

**To Reproduce**

1. Swipe back on a root page like for you, accounts or inbox
2. See error

**Expected behavior**
We only want to be able to swipe back and navigate by it, when we also have a back button in our toolbar (Not in our root)

See also: https://github.com/ionic-team/ionic/issues/17600

**Comment by hafstad** [comment]
will be fixed by https://github.com/Bankdata/relationsbank/pull/1603
