### ISSUE TITLE
[COMPONENT] Flag

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#749]
**Describe the solution you'd like**

Flags highlight the status of an item or other component, e.g. status of an order or account. 

Compared to badges, flags are not used on top of other components but only near or inside other compenents. 

**Types**

XS & SM: Used inside of Items to indicate a specific status of the item - eg. if a the value of a posting or investment in a overview. Only used with values.

MD: Used near the page-title or inside a card to indicate a status of either a collection of items or a single item. Can work together with a badge in different ways in different levels (see also concept) Only used with text.

**AttentionLVL & color/notification variations**

Same as buttons, the flags have rules of attention and color. The less important the flag is the lower the number from 1-3. 

**Spec**
- Naming of the flag sizes are 1:1 taken from or font sizes, eg. XS Flag has a XS fontsize

- 2dp padding on top/bottom and 4dp left/right

- Flags have no elevation since they only indicate a status

- Compared to badges, flags are not decorative and thus they need to be accessible in all their variations. They inform a user of something important!

- Flags are often used in a combination, from high-level to detail.
	- Eg. from “Something is going on” -> “What is going on”

**Describe alternatives you've considered**
Inspiration is totally from: https://design-system.futurelearn.com/atoms/flag

**Additional context**
Types: https://zpl.io/amAm4L6 

There are 5 types (colors). Notification and attention lvl 1 & 2 see also 
![Skærmbillede 2020-06-03 kl  14 40 44](https://user-images.githubusercontent.com/49033002/83637708-51948c80-a5a8-11ea-9703-97c81c7103eb.png)

Concept: https://zpl.io/V49LPkz

### Kick Off:

- [x] Accept Feature incl. name of component (DSL)
- [ ] Update Kirby Component Status and publish to [Kirby Cookbook](https://cookbook.kirby.design)

### Code:

- [x] Create Feature Branch
- [x] Implement Skeleton Component
- [ ] Add any required mock and fakes to the `KirbyTestingModule`
- Ask UX for review:
  - [ ] Ensure implementation is correct in relation to UX design
  - [ ] Define the version of the implementation + steps needed to reach version 1.0 (create [enhancement requests](https://github.com/kirbydesign/designsystem/issues/new?assignees=&labels=enhancement&template=enhancement-request.md&title=%5BEnhancement%5D))
- [x] [Implement Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Add link to showcase on Kirby Component Status (`component-status-items.ts => code.cookbookUrl`)
- [ ] Also remove `githubIssueNo` and set `status` to `ItemCodeStatus.ready`
- [ ] Push commits to GitHub

### Review:

- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- Merge to master and delete branch

**Comment by labanos** [comment]
Already used in items - but should be its own.

**Comment by bommariusser** [comment]
be aware this might also require some refactoring in both kirby and drb. See also https://cookbook.kirby.design/home/showcase/item under "flagged" and in DRB under postings and investments - There is actually quite much use of the component without being the right one :/ @ckibsen

**Comment by ckibsen** [comment]
Right @bommariusser! I'll change /showcase/item to use kirby-flag, and notify team 3/5 when they can start using the new component.

I had a kickoff chat with @jakobe and according to him, the topmost sample in flag koncept -> Overview (where "Insert message" appears as a header in a card), should not be addressed initially, as he thinks that kirby-flag is not necessarily the right solution for this case!

**Comment by bommariusser** [comment]
fedt @ckibsen :) har lagt den header flag opgave her https://github.com/kirbydesign/designsystem/issues/1063

**Comment by ckibsen** [comment]
Tech refined: Flag Component API: 

ThemeColor: ['success', 'danger', 'warning', 'semi-light', 'transparent' (default)]
themeColor translates to CSS-classes - transparent gets a medium-color border.
transparent flags gets white-contrast color for it's text-color!
