### ISSUE TITLE
[BUG]Empty-State title font-weight should be bold

### ISSUE THREAD

**Issue by laljyskebank** [kirbydesign/designsystem#752]
**Describe the bug**
The Empty-State title font-weight should be bold instead of normal.

**To Reproduce**

1. Go to 'https://cookbook.kirby.design/home/showcase/empty-state'
2. See the title font-weight is normal.

**Kirby version**
- 0.8.27

**Expected behavior**
Title font-weight should be bold.

**Comment by labanos** [comment]
@laljyskebank har du spurt Tom/Marvin? den er 700 - dvs ikke normal.. så er det ikke "rigtigt" alligevel?

**Comment by laljyskebank** [comment]
Jeg tog et skærmbillede af Kirby lokalt hvor den var 0.8.27. Her er title ikke bold. Så opdaterede jeg til version 0.8.32. Så var den bold. Det må være blevet opdateret for nylig. Jeg lukker denne bug

Kirby 0.8.27
![Screen Shot 2019-11-05 at 13 52 09](https://user-images.githubusercontent.com/35138247/68209646-1e6b2a00-ffd4-11e9-89e7-0b0024093554.png)


Kirby 0.8.32
![Screen Shot 2019-11-05 at 13 58 49](https://user-images.githubusercontent.com/35138247/68209769-6ab66a00-ffd4-11e9-945e-537face60081.png)
