### ISSUE TITLE
[Enhancement] Numeric input has spin buttons

### ISSUE THREAD

**Issue by shojb** [kirbydesign/designsystem#758]
Version: 0.8.33
Platform: Web.

After consulting with the UX (Tom) in team 6, who states that the spin buttons should not be shown on numeric fields, they should be removed.
![Screenshot 2019-11-07 at 11 48 18](https://user-images.githubusercontent.com/48122929/68382713-919baa00-0154-11ea-8b6a-dff9a9536032.png)

the up/down arrows..

As of this moment it is on branch feature/rb100create.. go to faste betalinger click the fab menu and choose tilmeld betalingservice.

**Comment by bommariusser** [comment]
@shojb what is a spin button? Please take your time making your bugs, it's quite hard to fix something which is just "this doesnt work the way i want it to work" ;) 

Also there is no UX team in team 6? Be specifik. It will help everyone.

**Comment by labanos** [comment]
@shojb i must admit i am confused.. you created an Enhancement request? to remove stuff that is not supposed to be there?

Sounds more like a bug - which has a different template... asking sensible questions like: on which platforms it happens?

The above description is really hard for the "poor" developer that reads it to work with.. image you should solve it? ;)

I for one cannot reproduce this on iOS - so is it a browser only thing?

**Comment by shojb** [comment]
> Sounds more like a bug - which has a different template... asking sensible questions like: on which platforms it happens?

I created it as an Enhancement on request from Alex, I have talked to him again, and he still sees it as an enhancement.. 

I have added platform and kirby version.
