### ISSUE TITLE
[Enhancement] Text should not be visible when the round "drag button" hits the text

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#759]
**Is your enhancement request related to a problem? Please describe.**
Right now the text is visible throughout the whole swipe, which ends up like this:

![Skærmbillede 2019-11-07 kl  10 37 57](https://user-images.githubusercontent.com/49033002/68377587-f225e980-014a-11ea-958d-f1161de497b1.png)

**Describe the solution you'd like**
We would like a solution where the text is faded out as soon as the "drag button" hits the text. 

![Skærmbillede 2019-11-07 kl  10 35 20](https://user-images.githubusercontent.com/49033002/68377985-a32c8400-014b-11ea-917c-1107e27d36d7.png)

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
