### ISSUE TITLE
[Enhancement] input fields in modal etc.. should be able to autofocus

### ISSUE THREAD

**Issue by shojb** [kirbydesign/designsystem#761]
**Is your enhancement request related to a problem? Please describe.**

Today when you open a form in a modal and so on, the first input field is not in focus even though you have added autofocus=true as a inputfield attribute.

**Describe the solution you'd like**
I would like that the field I have added autofocus on is in focus when the modal and etc. is shown....

**Describe alternatives you've considered**
if this is not added in to kirby everyone with a form in a modal and etc.. should add javascript to do so.
**Additional context**

![Screenshot 2019-11-07 at 11 48 18](https://user-images.githubusercontent.com/48122929/68384656-5d29ed00-0158-11ea-9826-5a3efd34735b.png)
not in focus, fieldcursor not blinking..

**Comment by labanos** [comment]
This issue has already been discussed in tech coordination, and in other places. It is not a modal issue, nor is it a kirby issue. It is a general iOS decision - that is they do not want you to set focus, before the uses interacts - and hence showing the keyboard. It does work on all other platforms.

Yes teams are looking into fixing this.. but it is not "really" a kirby issue :/
