### ISSUE TITLE
[COMPONENT]  form select, radio, checkbox, etc.?

### ISSUE THREAD

**Issue by jamalsoueidan** [kirbydesign/designsystem#762]
We are developing kirby-schema-form and we need all the form elements, such as select, radio and checkbox so we can auto generate forms from schema json.

When can we except those to be developed?

Thank you,

**Comment by labanos** [comment]
@jamalsoueidan sorry but with our launch coming up in january - all focus is on fixing bugs, and enhancing the current set of components. So giving any time-frame wouldn't be serious. Best guess atm. would be sometime during Q1.

PS im closing this - as we would like to use github for specific issues - questions like these are perhaps better answered via mail request. Feel free to reach out to be at peter.bugge@jyskebank.dk if you have further questions =)
