### ISSUE TITLE
[Enhancement] Support linebreak in text 

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#765]
**Is your enhancement request related to a problem? Please describe.**
In some usecases we have more then one text that we want to put into our alerts. Fx 2 texts coming from different backends. Here we want to be able to line break / seperate those text, because they are supposed to be seperated from each other. 

Like this: https://zpl.io/bl6pyB0 or https://zpl.io/bP18ExA or https://zpl.io/29zNJWA

**Describe the solution you'd like**
Maybe the alert can translate a /n to a linebreak so that we are able to do something like that?

**Comment by labanos** [comment]
consider a new general atom for outputting test, so we can solve it in all cases - modals, alerts etc etc. So we can handle all cases where test is coming from a backend or from input by the user,

**Comment by labanos** [comment]
white-space: pre-wrap;
