### ISSUE TITLE
[Enhancement] property to allocate space for label and error-message

### ISSUE THREAD

**Issue by MonsterGameDev** [kirbydesign/designsystem#766]
**Is your enhancement request related to a problem? Please describe.**
In the PayBill feature i need a form with the 3 fields for giro-payment card.
![image](https://user-images.githubusercontent.com/28903575/68749479-994cca00-05fe-11ea-8de1-93df81fad8a7.png)

but if i dont enter a label value - given I align-items with flex-start, the result will be:
![image](https://user-images.githubusercontent.com/28903575/68749842-327be080-05ff-11ea-9d08-f51d49b65290.png)

same issue with the error message - given i align-items with flex-end

Due to viewencapsulation i cannot style my way out of it if :ng-deep is no-go

**Describe the solution you'd like**
I think the right solution would be to add two properties to the kirby-form-field to state that i need the space, even if nothing goes there. like:
<kirby-form-field allocateLabelSpace=true allocateErrMsgSpace=true... (or what ever would be descriptive names.

**Comment by labanos** [comment]
@MonsterGameDev is it possible for now to add a label with " "? Just wondering if there is a workaround - so we can fix this after launch.

**Comment by jakobe** [comment]
@MonsterGameDev Is this still relevant?

**Comment by MonsterGameDev** [comment]
No sorry - should have cleaned this up a long time ago...
