### ISSUE TITLE
[BUG] input counter wraps into two lines if form-field is small 

### ISSUE THREAD

**Issue by MonsterGameDev** [kirbydesign/designsystem#767]
**Describe the bug**
I suppose this is not as it is supposed to be

![image](https://user-images.githubusercontent.com/28903575/68750408-1af12780-0600-11ea-97b7-b600feae069a.png)

**To Reproduce**
1. Create a -kirby-form-field and incclude kirby-input-counter
2. style the kirby-form-field width
3. if small enough see the error (as seen in the img above

**Kirby version**
 "@kirbydesign/designsystem": "0.8.33",

**Expected behavior**
It should look like this without me having to style my way out of trouble...
![image](https://user-images.githubusercontent.com/28903575/68750746-ac609980-0600-11ea-8186-d189e6dbf4cd.png)

**Screenshots**

**Please complete the following information:**

- OS: MacOS
- Browser Chrome
Version 78.0.3904.87 (Official Build) (64-bit)

**Comment by labanos** [comment]
@MonsterGameDev only on web? not an issue on native? (and sounds like you have a workaround?)

**Comment by jakobe** [comment]
Fixed
