### ISSUE TITLE
[Enhancement] Support icons on buttons in Alerts

### ISSUE THREAD

**Issue by mvindahl** [kirbydesign/designsystem#768]
**Is your enhancement request related to a problem? Please describe.**
Our UI mockup in some cases requires a link button with an icon to make it possible to identify it as a link. (Zeplin#904)
![image](https://user-images.githubusercontent.com/5991804/68852996-4a279780-06d9-11ea-867e-32ea4a1473d0.png)

The API for the alert allows us to specify texts for the ok button and for the optional cancel button but it does not allow us to specify any additional decorations.

**Describe the solution you'd like**
Assuming that we stick to the concept of an "ok" and a "cancel" button, and to make the solution consistent across the buttons, I suggest two new optional properties ´okBtnIconName´ and ´cancelBtnIconName´. This can be used to name which kirby icon should render within the button, if any.

Alternative suggestion: extend syntax for okBtn and cancelBtn to allow something along the lines of { okBtn: { text: 'Yup', iconName: 'football' }, .. }

**Describe alternatives you've considered**
We use a kirby alert, configuring the cancel button to render with a "read more" label, but without any icon.

**Additional context**

**Comment by mvindahl** [comment]
Also, in order to "abuse" the cancel button for our specific purpose, we'd like to have a way to handle events from it without it the dialog being closed. I'm not 100% sure how this works but it may mean that we'd need a way to pass a "isDestructive=false" property to it.

**Comment by bommariusser** [comment]
@mvindahl have u considered putting the link in the text above? As you say it yourself this is kind of an hack :D to overwrite the cancel with another action. maybe you can link to the zeplin issue?

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
