### ISSUE TITLE
[Enhancement] (Text)Links

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#770]
**Describe the solution you'd like**
We would like to have (Text)links that are not styled as buttons but styled more as a textstyle.

These are mostly combined with some other text that describe the user what this is all about before changing the context, that either link inside the application (underline) or outside the application (underline + link icon)

These follow the same sizes as our text sizes. 
- Text size: xs & Icon Size sm
- Text size: sm & Icon Size: sm
- Text size: p & Icon Size md

<img width="294" alt="Skærmbillede 2021-03-29 kl  14 03 07" src="https://user-images.githubusercontent.com/49033002/112833771-7b6af280-9097-11eb-92d7-d6dbc0eff169.png">

See in zeplin here: https://app.zeplin.io/project/5e1f27f01ffb15bd95efc426/styleguide/components?cseid=5e46809806041da857a4bf49

<img width="362" alt="Skærmbillede 2019-11-14 kl  14 44 23" src="https://user-images.githubusercontent.com/49033002/68862191-456cde80-06ed-11ea-820c-728b17cfdf4b.png">

**Additional context**
See also this for some other inspiration:

https://www.carbondesignsystem.com/components/link/code/

### Kick Off:

- [x] Accept Feature incl. name of component (DSL)
- [x] Update Kirby Component Status and publish to [Kirby Cookbook](https://cookbook.kirby.design)

### Code:

- [x] Create Feature Branch from [master branch](https://github.com/kirbydesign/designsystem/tree/master)
- [x] Implement Skeleton Component and push to Github
- [x] Ask a member of @kirbydesign/kirby-guild for a WIP review by creating a draft Pull Request
- [x] Implement unit tests
- [x] Implement Cookbook Examples and Showcase, i.e. see [Radio](https://cookbook.kirby.design/home/showcase/radio)  
_Also remember to add any relevant API documentation_

### Review:

- UX review:
  - [ ] Ensure implementation is correct in relation to the UX design and the [Kirby Styleguide on Zeplin](https://zpl.io/258pXGj)
  - [ ] With UX agree on the version of the implementation + any additional steps needed to reach version 1.0 (create [enhancement requests](https://github.com/kirbydesign/designsystem/issues/new/choose))
- Code review:
  - [ ] Open a pull request (or mark the existing draft PR as `Ready for review`) and ask @kirbydesign/kirby-guild for a review  
_Remember to add `closes #issueno` to the description of the PR._
  - [ ] Once approved, merge feature branch/PR to master
- [ ] Ask a member of @kirbydesign/kirby-guild to add a link to component showcase from Kirby Component Status

:tada: Celebrate

**Comment by RasmusKjeldgaard** [comment]
@bommariusser the issue says 'These are mostly combined with some other text that describe the user what this is all about before changing the context'

Would you say that we also want the links to be inline with other text on either side of the link, or should the text link component only support a 'standalone' link like the screenshot?

**Comment by bommariusser** [comment]
it's also related in context with some other texts @RasmusKjeldgaard 
![Skærmbillede 2021-04-14 kl  07 32 01](https://user-images.githubusercontent.com/49033002/114659214-780c7380-9cf3-11eb-9f16-dfda67d7b2b3.png)

**Comment by bommariusser** [comment]
![Skærmbillede 2021-04-28 kl  11 30 08](https://user-images.githubusercontent.com/49033002/116382117-dff3ab80-a815-11eb-9a75-c06596232f59.png)

Can we have a talk about inline vs. standalone links @RasmusKjeldgaard?

**Comment by RasmusKjeldgaard** [comment]
After additional tech refinement of this issue, based on new requirements from @kofoeddk and @MortenGregersen, we decided on NOT creating a separate component for this, but rather use the builtin <a> html tag. We see links as part of the content, not as a separate component as such. This is the same way we use headings (<h1-6>) and paragraphs (<p>) which are also built into HTML itself.

We will style <a> by default in libs/designsystem/src/lib/scss/base/_typography.scss the same way we style headings (<h1-6>) and paragraphs (<p>).
This means any project using Kirby by default will get styled links out-of-the-box

We should also create a showcase on how to use links with guidelines from UX (even though we don't have a separate component for them).

**Comment by RasmusKjeldgaard** [comment]
FYI the new requirements are
1. Styling of links that come from backend, CMS etc., where you do not have control over the content.
2. A new project with no existing global styles, using Kirby, will have default (blue/purple) link styling. It should be deliberately styled to match kirby.

**Comment by RasmusKjeldgaard** [comment]
**Round 2:** 
We have decided that the 'Open' icon should be added only when the `target` attribute is set to `_blank`, as opposed to adding it when the links is an absolute link (http:// or similar). The link is meant to indicate that a new tab is opened, not that the link/resource is outside the app/current domain. 

We will write in the guidelines that links within text should generally not have an icon, and thus should not open in a new tab. It should rather have be very descriptive about where the user is sent: 'Click here to

**Comment by RasmusKjeldgaard** [comment]
Using `target="_blank"` for adding the icon was not acceptable in DRB, as inline links should still be able to open in a new tab, without having the icon added. Instead, developers will have to add a class to the anchor tag, whenever they want the icon to be shown. 

This will not add the icon to existing links in the code base, but this is acceptable as custom solutions has been implemented where necessary, that would be broken by automatically adding the icon. 
Instead, these can now be refactored to use the css-class if necessary.
