### ISSUE TITLE
[QUESTION] checkbox checked attribute

### ISSUE THREAD

**Issue by jamalsoueidan** [kirbydesign/designsystem#773]
Why do we change the input checked on click?

https://github.com/kirbydesign/designsystem/blob/master/src/kirby/components/checkbox/checkbox.component.ts#L35

Is this not supposed to be controlled by the developer?

**Comment by labanos** [comment]
hmm really sorry - but im not sure i can spot a valid reason for it not being like this?

could you maybe explain why this is a problem for you?

**Comment by labanos** [comment]
@jamalsoueidan have you joined our internal slack channel #kirby-guild - maybe it would be better to ask question there? 

Github is really for solving issues - we don't have ulimited resources to support kirby via this channel - so maybe asking on slack would be better for everyone.. =)
