### ISSUE TITLE
[BUG] input counter is zero when field holds an initial value

### ISSUE THREAD

**Issue by FinnCarlsen** [kirbydesign/designsystem#774]
**Describe the bug**
![image](https://user-images.githubusercontent.com/53520395/68944494-3a2db780-07ae-11ea-8337-30485e654e84.png)
The first part of the counter doesn't reflect the length of the initial value.

**To Reproduce**
Is at the moment in branch 'feature/rb-100-edit-description' and can be accessed through the artifacts-manager.

1. Go to 'Faste betalinger'
2. Click on a payment agreement (BS) which has a description, and details will open.
3. See error

ad. 2) If the payments has no descriptions click anyway and type in your own description and close the page, then click the agreement and see the error.

**Kirby version**
"@kirbydesign/designsystem": "0.8.33",

**Expected behavior**
![image](https://user-images.githubusercontent.com/53520395/68944595-782adb80-07ae-11ea-8f7a-955112378f67.png)
The first part of the counter reflects the length of the input's initial value

**Please complete the following information:**

- OS: [MacOS]
- Browser [Chrome]
- Version [78.0.3904.87]

**Comment by labanos** [comment]
@FinnCarlsen is there no workaround possible? like forcing an update of the counter or something?

**Comment by labanos** [comment]
![Skærmbillede 2019-11-19 kl  12 10 37](https://user-images.githubusercontent.com/5631507/69141895-f399cf00-0ac5-11ea-92e0-0f72d47862ad.png)

**Comment by labanos** [comment]
@FinnCarlsen kan du/i prøve at tjekke ud, hvordan det er løst i overfør - her ser det ud til at counteren fint er "initialiseret" til det rigtige med "forudfyldte" værdier? (måske er det ikke Kirby-formfield?)

**Comment by FinnCarlsen** [comment]
@labanos Du har ret. Det ikke et kirby men et drb-input-field som har et characterCount parameter.
Jeg har ikke fundet en workaround vedr. kirby-input-counter og kirby-form-field.

**Comment by jakobe** [comment]
Done
