### ISSUE TITLE
[Enhancement] Add Font-Colors (White, Black, Semi-Dark to start with)

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#776]
**Is your enhancement request related to a problem? Please describe.**
We had some a11y findings which involved our semi-dark color, which was used in "unselected" states on both text and components. 

The findings are based upon that (interactive)components inactive states should also have 3:1 contrast to be AA. 

https://zpl.io/2jQB6XQ

<img width="682" alt="Skærmbillede 2020-01-28 kl  11 36 52" src="https://user-images.githubusercontent.com/49033002/73260879-31ecf200-41cb-11ea-9cdd-cac2e5f8513e.png">

**Describe the solution you'd like**
1. Rename semi-dark to semi-dark-text and change its color to #707070
2. Add semi-dark-graphic with a color #8e8e8e
3. Change component "unselected" states (eg. radio/toggle/checkmark) to semi-dark-graphic

Toggle: https://zpl.io/VKQ3JPW
Checkmark: https://zpl.io/2GRqAZm

**Comment by MortenGregersen** [comment]
Should this be a breaking change, or should we keep the `semi-dark` and make it an alias for `semi-dark-text`?

**Comment by bommariusser** [comment]
@MortenGregersen Var det denne opgave jeg skulle sætte lidt mere kød på? Kan ikke huske opgaver fra det møde vi havde

**Comment by bommariusser** [comment]
We want a "semi-dark" color which is only used for text (new color #707070) and keep the semi-dark color for our graphic components. 

<img width="793" alt="Skærmbillede 2020-02-21 kl  16 26 48" src="https://user-images.githubusercontent.com/49033002/75035188-600eda80-54c8-11ea-9873-f47c57a5c4c2.png">

@MortenGregersen anything else? :>
