### ISSUE TITLE
[BUG] rendering is delayed when closing modal with long kirby list

### ISSUE THREAD

**Issue by mvindahl** [kirbydesign/designsystem#779]
**Describe the bug**
When closing a modal containing a kirby list with a large number of items, there is a noticeable delay in updating the UI. The length of this delay depends upon hardware, of course, but on a Macbook Pro we have observed ~200 msecs delay for a list of ~70 items for our account picker. During this period, the angular framework appears to spin frantically, creating and garbage collecting objects en masse. I have no clue as to why it does this.

**To Reproduce**

I've reproduced it in a "vanilla" setting by:
1. Checking out the kirby repository
2. Changing first-embedded-modal-example.component.html to render a kirby list and nothing else:
```html
<div>
  <kirby-list [items]="items">
    <kirby-list-item *kirbyListItem="let item" [title]="item.title" [amount]="item.amount">
    </kirby-list-item>
  </kirby-list>
</div>
```
3. Adding a field to first-embedded-modal-example.component.ts with some mock data:
```typescript
  public items: any[] = [...Array(400).keys()].map((idx) => ({
    id: idx,
    title: 'Vestas Wind Systems has a very long name ' + idx,
    subTitle: '2000 pcs',
    amount: '5.587.218.309 DKK',
    detail: 225,
    color: 'default',
  }));
```
4. Also, to better visualize the rendering delay I added a counter field to modal-example.component.ts:
```typescript
modalsClosedCount = 0;
```
.. modified the onModalClose method to bump the count (using lambda for binding to work):
```typescript
onModalClose = (data: any) => {
  console.log('Callback from Embedded Modal:');
  console.log(`Data received: ${JSON.stringify(data)}`);
  this.modalsClosedCount++;
};
```
.. and rendered the value in the bottom of modal-example.component.html:
```html
Modals closed: {{ modalsClosedCount }}
```
I then spun the kirby project up with `npm start`and connected Chrome to http://localhost:4200/examples/modal.

EXHIBIT A: Open the modal, open the console in Chrome devtools, and dismiss the dialog.
![image](https://user-images.githubusercontent.com/5991804/69143871-4ecdc080-0aca-11ea-8c93-5cdb55a606f6.png)
Note that there is a very visible delay between "Callback from embedded modal" printing to the console and the "Modals closed" counter updating in the UI.

EXHIBIT B: Do the same thing, but this time use the devtools "performance" tab to record what happens while the dialog is closing.
![image](https://user-images.githubusercontent.com/5991804/69144141-ed5a2180-0aca-11ea-857a-cc8307f45c5b.png)
Note the heavy activity for (in this example) ~5 seconds.

Zoomed in view:
![image](https://user-images.githubusercontent.com/5991804/69144272-35794400-0acb-11ea-9182-750764d939eb.png)

I've tested with various list sizes and not sure how it scales exactly but at a quick glance it scales worse than O(n):
![image](https://user-images.githubusercontent.com/5991804/69144436-999c0800-0acb-11ea-9c3d-abeaab4514e1.png)

**Kirby version**

Most recent master at the time of writing

**Expected behavior**
I'd expect dismissal of the modal to be a great deal faster, especially since I'm running on a fairly new MBP. I've used a list of 400 items for illustration but even a list of 50 items causes a ~200 msecs delay when being dismissed on my MBP; longer on real-life devices.

**Screenshots**
I've inlined the screenshots.

**Please complete the following information:**

- OS: MacOS
- Browser: Chrome
- Version: recent

**Additional context**
The problem affects our ability to render spinners etc., especially on slower devices. We've put the problem aside as it affects our account picker, and since we plan to switch to a common account picker as implemented by team 6. We hope that will magically fix it. But since it seems to be reproducible in plain kirby we figured that we'd direct your attention to it.

**Comment by labanos** [comment]
@mvindahl remember Kirby is "our" ;) But thanks for the heads up!

**Comment by mvindahl** [comment]
Heh, yeah, true dat. Anyway, I'm hoping that someone with deeper insight can figure out what's going in as it's a riddle to me :)

**Comment by labanos** [comment]
@jakobe would this be "solved" when/if we change the underlaying list implementation? (maybe it has already happend?)

**Comment by alxzak** [comment]
@mvindahl This will be fixed by:
https://github.com/kirbydesign/designsystem/issues/853

In case of performance issues, please use lists in virtual scrolling field.
