### ISSUE TITLE
[COMPONENT] Overlay

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#790]
**Describe the solution you'd like**
Overlays are full screen components that overlay other components. They are useful behind components that transition in on top of other content and can be used to dismiss that component.

Overlays come in two different versions: Dark and Light

Dark: https://zpl.io/b6Djlky
Light: https://zpl.io/VOdKBzr

**Describe alternatives you've considered**
Naming: Backdrop...

https://ionicframework.com/docs/api/backdrop
http://designsystem.morningstar.com/visual-language/layering.html

### Kick Off:

- [ ] Accept Feature incl. name of component (DSL)
- [ ] Update Kirby Component Status and publish to [Kirby Cookbook](https://cookbook.kirby.design)

### Code:

- [ ] Create Feature Branch
- [ ] Implement Skeleton Component
- [ ] Add any required mock and fakes to the `KirbyTestingModule`
- Ask UX for review:
  - [ ] Ensure implementation is correct in relation to UX design
  - [ ] Define the version of the implementation + steps needed to reach version 1.0 (create [enhancement requests](https://github.com/kirbydesign/designsystem/issues/new?assignees=&labels=enhancement&template=enhancement-request.md&title=%5BEnhancement%5D))
- [ ] [Implement Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Add link to showcase on Kirby Component Status (`component-status-items.ts => code.cookbookUrl`)
- [ ] Also remove `githubIssueNo` and set `status` to `ItemCodeStatus.ready`
- [ ] Push commits to GitHub

### Review:

- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- Merge to master and delete branch

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
