### ISSUE TITLE
[BLOCKED][Enhancement] hover on chip same as buttons

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#795]
**Is your enhancement request related to a problem? Please describe.**
Right now our chips have a separate hover-effect compared to our buttons (dark on chips and tint on buttons). We want those to be aligned so they are the same.

**Comment by jakobe** [comment]
BLOCKED: UX are refining hover states in general (including buttons), which needs to be done first.

**Comment by alxzak** [comment]
Hey @bommariusser 
I think we need a screenshot, i dont se how the chip can be the same tint at button, as the chip haven't a background color?
