### ISSUE TITLE
[Enhancement] Revisit breakpoints & paddings

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#799]
**Is your enhancement request related to a problem? Please describe.**
Last time we changed the modals we had some things we didn't change to get things done faster:

- Modals should be 768px but we didn't change it because the Large breakpoint right now is 720px, and we couldn't figure out what to do: If we should add another breakpoint or just change the breakpoint to 768px 

- Margin bottom: We ended up not putting any margin bottom, but we should at least have 24 in bottom: https://zpl.io/VxQD00m

- Overlay: We should use Kirby-overlays, and maybe also use a blurred version on the modal: https://zpl.io/adYLzpK

- Margin small screens: Should probably be 8px on the sides instead of 16

**Describe alternatives you've considered**
Here is some inspiration of how to think about Breakpoints:
- https://backpack.github.io/components/breakpoint?platform=web

**Additional context**

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
