### ISSUE TITLE
[Enhancement] Input field should scroll into view when focus

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#801]
**Is your enhancement request related to a problem? Please describe.**
In team 4 we have had an issue with showing the input field in the center of the visible part of the modal once the keypad comes up. Could be great with a solution that always makes sure that the activated input field is placed in the middel of the visible part of the screen once the keypad / numpad comes up.

<img width="288" alt="Skærmbillede 2019-12-02 kl  14 34 40" src="https://user-images.githubusercontent.com/49033002/69963701-14741280-1511-11ea-9068-b244abdc60c7.png">

**Describe the solution you'd like**
It should scroll and show the input field

**Comment by labanos** [comment]
Waiting for ionic fix - for now a workaround has been made in DRB for the above situation.
