### ISSUE TITLE
[Enhancement] 2 lines truncate on detail

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#802]
**Is your enhancement request related to a problem? Please describe.**
We would like to show a 2 lines teaser tekst in our items, that also truncate with a "..." on long messages. 

See also: https://zpl.io/29OYzvW

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
