### ISSUE TITLE
[Enhancement] Configurable margin on kirby-divider

### ISSUE THREAD

**Issue by askarby** [kirbydesign/designsystem#805]
**Is your enhancement request related to a problem? Please describe.**
Separating two (or more) `kirby-item`s using a `kirby-divider` adds excessive margin to the bottom of the `kirby-item` before it, and excessive margin to the top of the `kirby-item` after it.

**Describe the solution you'd like**
Either completely remove `margin-top` and `margin-bottom` from `kirby-divider` or create a option that can disable the margin.

**Describe alternatives you've considered**
Using `::ng-deep` but then I felt guilty and decided to file an enhancement request instead.

**Additional context**
It looks like the browser's default styling or `hr`-elements is "bleeding through.

Example from DRB-app:
![image](https://user-images.githubusercontent.com/44014/70058519-59ff1100-15df-11ea-882d-91320a1a3476.png)

Dev-tools, indicating user agent stylesheet "bleeding through":
![image](https://user-images.githubusercontent.com/44014/70058399-1f957400-15df-11ea-824a-0801191de5f9.png)

**Comment by bommariusser** [comment]
@peterlindholm har vi ikke samme udfordring?

**Comment by peterlindholm** [comment]
> @peterlindholm har vi ikke samme udfordring?

Jo, det ses bare ikke så tydeligt der hvor vi bruger den.

**Comment by MortenGregersen** [comment]
I vote for adding an option to disable the margin 🗳

**Comment by bommariusser** [comment]
hvornår bruger vi det med margin? :) @MortenGregersen

**Comment by MortenGregersen** [comment]
@bommariusser Bl.a. på Puljedetaljer og Papirdetaljer 
![Screenshot 2019-12-04 at 13 17 30](https://user-images.githubusercontent.com/759680/70141981-7f9c2100-1698-11ea-8db6-d388b189b8df.png)
![Screenshot 2019-12-04 at 13 18 34](https://user-images.githubusercontent.com/759680/70142004-93478780-1698-11ea-9d4c-68e1b48796ff.png)

**Comment by bommariusser** [comment]
i see that @MortenGregersen not sure if that space should come from the divider? :) 

@jakobe @askarby @hafstad  not sure which way we should go with this one? Either make it possible to remove the margin or we shouldn't have a margin on this component :)

**Comment by bommariusser** [comment]
best practice is not to have margin on components that are this small (atoms), because they are used in other places where they are combined with other components (molecules etc.)
