### ISSUE TITLE
[BUG] Texts gets bold when clicking on kirby-item in kirby-list

### ISSUE THREAD

**Issue by SilverGull** [kirbydesign/designsystem#809]
**Describe the bug**
Upon clicking on a kirby-item in a list with an itemSelect listener, the kirby-item will get a .selected class that makes the text bold. This creates an undesired user experience when navigating when clicking. You will see a short glimpse of the text getting bold and when navigating back to the page the text will still be bold.

**To Reproduce**

1. Go to 'Investment'
2. Click on a paper in the list to go to paper details
3. Navigate back
4. The text in the return component is now bold

**Kirby version**

- [0.8.47]

**Expected behavior**
I don't expect the font to change when navigating

**Screenshots**
![Screenshot 2019-12-05 at 12 25 25](https://user-images.githubusercontent.com/43959200/70231805-5a241b80-175b-11ea-94f6-6ba5bfae793a.png)

**Please complete the following information:**

- OS: [MacOS]
- Browser [Chrome]
- Version [77]

**Additional context**

**Comment by labanos** [comment]
Looks like a "browser" only issue - maybe some "visited" style "out of the box" (ionic or angular..)

**Comment by alxzak** [comment]
Duplicate to #1473 and will be fixed by that. :)
