### ISSUE TITLE
[BUG] Max-width should be 359dp + Margin changes

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#810]
**Describe the bug**

Max-width of an alert is 330dp right now but it should be a tad wider. It also has 16dp margin which takes some space :) 

**To Reproduce**

1. Go to https://cookbook.kirby.design/home/showcase/alert
2. Click on "Show alert" 

**Kirby version**

- v0.8.49

**Expected behavior**
It should be 359dp in max-width and have 8dp margin instead of 16dp margin (left/right)

**Comment by jakobe** [comment]
Fixed
