### ISSUE TITLE
[Enhancement] Subtitle on page-title

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#811]
**Is your enhancement request related to a problem? Please describe.**
We would like to add the possibility to add a subtitle on our page-template that places itself below the Title.

See also: 

- https://zpl.io/VKjXWP7
- https://zpl.io/2pMwndN

How is the bug looking:

![IMG_5390 2](https://user-images.githubusercontent.com/49033002/75548073-a1edd280-5a2c-11ea-80c7-dc843f9de0b5.PNG)

**Comment by labanos** [comment]
The challenge is the "margin" between the actual title and the "subtitle" - right now it is 40px - but should be alot closer.
When using the current title - and putting the subtitle with the main title.. it introduces a scrolling issue - where both title and subtitle needs to be scroll out of view, before moving the title to the toolbar.

**Comment by MadsBuchmann** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-Workspace-612de54795710600195b61fa/issues/kirbydesign/designsystem/811?planning-poker) with ZenHub @RasmusKjeldgaard @jkaltoft @mictro

**Comment by MadsBuchmann** [comment]
# Tech Refinement
The new ‘subtitle’ functionality of the page is in many ways parallel to the ‘title’.

## API:
- It should be possible to set a simple subtitle with default styling by providing a string to a new `subtitle` input property.
    - This is similar to the `title` input property that is used for setting a simple title.
    - The markup should be structured such that the subtitle element is not contained in the title element, in order to be able to solve: #1981 
- It should be possible to create custom subtitles by applying a `KirbyPageSubtitle` directive to the element that should be used as the subtitle of the page
   - This is similar to the `KirbyPageTitle` directive used for creating custom titles

## Other requirements:
- The new subtitle should respect the `titleAlignment` input property. For example if `titleAlignment=‘center’` the subtitle should be centered along with the title

## Unknowns:
- The default styling for the simple subtitle provided via the `subtitle` input property needs more UX refinement. But work can start regardless.
