### ISSUE TITLE
[BUG] It is possible to mark 2 chips on Segmented Chip control

### ISSUE THREAD

**Issue by LVinther** [kirbydesign/designsystem#814]
**Describe the bug**
It is possible to "visually" mark 2 chips - content only shows content for 1 chip. 

**To Reproduce**

1. Go to 'Investeringer'
2. Click on 'Search icon'
3. Type 'Ve' in input field
4. Do horisontal scroll on chips by moving finger to the left
5. Do horisontal scroll on chips by moving finger to the right
6. The scroll to the right sometimes marks a chip (hover state) and the marking doesn't disappear when user removes finger.

**Kirby version**
0.8.50

**Expected behavior**
The horisontal scroll should not leave chips black 

**Screenshots**

![IMG_3D3BACA31982-1](https://user-images.githubusercontent.com/53176253/70418407-9610f680-1a63-11ea-820d-120c078cae59.jpeg)
![File](https://user-images.githubusercontent.com/53176253/70418408-9610f680-1a63-11ea-94de-fbc4782f845f.jpg)

**Please complete the following information:**

- iOS, version 13.2.3

**Additional context**

**Comment by jakobe** [comment]
This is an iOS bug: iOS applies the hover style when selecting/tapping/sliding the chips.
Fix: Only apply :hover styles for desktop.
