### ISSUE TITLE
[Enhancement] First-&Last-Item padding without styling

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#817]
**Is your enhancement request related to a problem? Please describe.**
Right now all list's with items get padding on the first item and the last item, and thats okay if there is a styling on the list (white background). 

The problem is when we want to do something that breaks the "traditional" way of making a list with sections. 

![Skærmbillede 2019-12-09 kl  10 37 07](https://user-images.githubusercontent.com/49033002/70432518-bf3f8000-1a7f-11ea-9ed5-fe4d46509ba0.png)

**Describe the solution you'd like**
We would like to be able to use a list with items, without styling, that doesn't inherit first & last padding, so that we can build something that doesn't look like a traditional list.

For example:
https://zpl.io/VOpW4YP

**Alternatives**

Maybe Load On Demand should be seperated to be used on other stuff so we are not reliable to use a list every time we want to be able to load on demand..

**Comment by MadsBuchmann** [comment]
Closing issue after conversation with author as this is no longer a problem 😄
