### ISSUE TITLE
[BUG] - Search & falafelmenu cannot be in the tab-bar at the same time.  

### ISSUE THREAD

**Issue by Kristian2332** [kirbydesign/designsystem#834]
**Describe the bug**
When scrolling down on the transaction list the search icon will move up into the tab-bar, however when you do it on an iPhone SE with a small screen both icons cannot be there - they will overlap (Se picture). 

**You need to be on a Total account to reproduce** 

**Kirby version**

- [0.8.59]
![IMG_0163](https://user-images.githubusercontent.com/49475219/70935384-57b99f80-2040-11ea-90a2-277db389be88.PNG)

**Please complete the following information:**

- OS: [iOS 13 - iPhone SE]

**Comment by bommariusser** [comment]
@Kristian2332 er det ik fixed nu hvor farven ik er hvid længere?

**Comment by jakobe** [comment]
Has been fixed
