### ISSUE TITLE
[BUG] View scrolls behind an alert (iOS 12)

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#841]
**Describe the bug**
When you scroll/swipe inside the window of the alert, the view behind scrolls with it.

**To Reproduce**

1. Go to https://cookbook.kirby.design/home/showcase/alert
2. Scroll up/down inside the alert 

**Kirby version**
v0.8.69

**Expected behavior**
It shouldnt scroll behind.

Here is some documentation:

1. https://ionicframework.com/docs/demos/api/alert/index.html
2. https://stackoverflow.com/questions/28790889/css-how-to-prevent-scrolling-on-ios-safari

**Please complete the following information:**

- iOS 12

**Comment by jakobe** [comment]
Cannot be verified
