### ISSUE TITLE
[BUG] Selected state is active when used for navigation

### ISSUE THREAD

**Issue by LVinther** [kirbydesign/designsystem#842]
**Describe the bug**
When navigating back from a list item, the item you are navigating back to is in bold (selected).

**To Reproduce**

1. Go to 'Investering'
2. Click on 'A paper in the paper list'
3. Click on the 'back arrow'
4. See 'the return is in bold'

**Kirby version**

- [e.g. 0.8.69]

**Expected behavior**
When navigating back the list item should not be bold.

**Screenshots**

![IMG_6929](https://user-images.githubusercontent.com/53176253/71156899-3e337600-2241-11ea-8c5a-a005235d1c5d.PNG)
![IMG_6928](https://user-images.githubusercontent.com/53176253/71156904-3f64a300-2241-11ea-85b7-1514a9ca8e1d.PNG)

**Please complete the following information:**

- OS: [iOS]
- Version [13]

**Additional context**
This also happens in Search (in Investeringer)

**Comment by bommariusser** [comment]
@hafstad er det noget med at man skal sige til item at det ikke er selected state når man putter det ind?

Det kunne være vi sku lave det omvendt fordi det er vel "selected" pr default et item? eller misforstår jeg :)

**Comment by lydemann** [comment]
Vi har det samme problem for feed. Mit foreslag, er at vi laver et flag til, hvorvidt at en liste skal være bold ved select.

Et workaround dog er at undgå at bruge **itemSelect** output og bare bruge click på list item.
