### ISSUE TITLE
Add the color Semi-Light as a variable to color palette 

### ISSUE THREAD

**Issue by LVinther** [kirbydesign/designsystem#846]
**Is your enhancement request related to a problem? Please describe.**
Add the color Semi-Light as a variable to color palette. We need this color in Investering and Posteringer

![Posteringer - Kommende](https://user-images.githubusercontent.com/53176253/71256525-4a96fc00-2331-11ea-9150-67cf4eb22966.png)
![Posteringer](https://user-images.githubusercontent.com/53176253/71256526-4a96fc00-2331-11ea-9271-8afa137ab95d.png)
![Buy, Pre-trade page](https://user-images.githubusercontent.com/53176253/71256527-4b2f9280-2331-11ea-84ba-057612cd9d5d.png)
![Buy, Pre-trade page, Trade type drawer](https://user-images.githubusercontent.com/53176253/71256528-4b2f9280-2331-11ea-98d6-c34ba058f4ea.png)

**Additional context**
The color is already shown in our cookbook but is not available to developers 

![Skærmbillede 2019-12-20 kl  07 43 51](https://user-images.githubusercontent.com/53176253/71256539-52ef3700-2331-11ea-9388-f23520ecb61e.png)

**Comment by bommariusser** [comment]
@LVinther ok jeg fjerner den? https://github.com/kirbydesign/designsystem/issues/684 fikser issuet :)
