### ISSUE TITLE
[BUG] List/Card header should be List/Card flag

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#848]
**Describe the bug**
Right now we have a List/Card header which is not the "original" way we have thought a card-header to be. But this should be a flag inside the card, which is placed in the very top of the card.

This size of the flag is also a bit off and maybe we should talk about refactoring header and flag on Card/List

![Skærmbillede 2020-01-08 kl  13 27 04](https://user-images.githubusercontent.com/49033002/71978009-96dfa880-321a-11ea-9789-37b1cd738f6b.png)

Card-flag: https://zpl.io/bLGKyMQ
Card-header: https://zpl.io/adYrW3E

**To Reproduce**

1. Go to https://cookbook.kirby.design/home/showcase/list-no-shape
2. See error

**Kirby version**

- v0.8.71

**Please complete the following information:**

- OS: [e.g. Windows, MacOS, iOS]
- Browser [e.g. Chrome, Safari]

**Additional context**

**Comment by jakobe** [comment]
@bommariusser Card now has support for `flagged` state (https://cookbook.kirby.design/home/showcase/card)
This should be refactored in the target project (DRB)
