### ISSUE TITLE
[BUG]-LoadingOverlayService: error: portal already attached

### ISSUE THREAD

**Issue by MonsterGameDev** [kirbydesign/designsystem#849]
Service: LoadingOverlayService has a method : showLoadingOverlay() which attaches spinnerOverlayPortal. This attach will fail with "portal already attached" if called after the outlet has been filled with whatever component. 

**To Reproduce**

1. setUp a loading$ observable
2. subscribe to loading$ and run
3. loadingOverlayService.showLoadingOverlay(bool) within the subscribe
4. fails with: "portal already attached"

**Kirby version**
0.8.71

**Expected behavior**
I expect no error to occur

- OS: MacOS
- Browser Chrome
- Version  79.0.3945.88

**Additional context**
Solution must be to change:
-------------------------------------------------------------------------
  showLoadingOverlay(showBackdrop: boolean = true): void {
    if (!this.overlayRef) {
      this.overlayRef = this.overlay.create();
    }

    const spinnerOverlayPortal = new ComponentPortal(FullscreenLoadingOverlayComponent);
    const component = this.overlayRef.attach(spinnerOverlayPortal);
    component.instance.showBackdrop = showBackdrop;
  }
-------------------------------------------------------------------------

TO:
-------------------------------------------------------------------------
showLoadingOverlay(showBackdrop: boolean = true): void {
    if (!this.overlayRef) {
      this.overlayRef = this.overlay.create();
    }

    const spinnerOverlayPortal = new ComponentPortal(FullscreenLoadingOverlayComponent);
    if (!this.overlayRef.hasAttached()) {
      const component = this.overlayRef.attach(spinnerOverlayPortal);
      component.instance.showBackdrop = showBackdrop;
    }
  }
-------------------------------------------------------------------------

Solution described in CDK github: 
https://github.com/GetTerminus/terminus-ui/pull/1463/files

**Comment by jonasjensen-brolstark** [comment]
@MonsterGameDev is this fixed with PR #854 ?

**Comment by MonsterGameDev** [comment]
Yeps, just forgot to close the issue
