### ISSUE TITLE
[BUG] Alert can't be closed if presented async from a modal which is closed before alert is presented

### ISSUE THREAD

**Issue by MortenGregersen** [kirbydesign/designsystem#851]
**Describe the bug**
When an alert is presented asynchronously (eg. from an ngrx effect) and the async task is started from a modal which is closed before the alert is presented, the alert is presented on the previous page and can't be closed.

**To Reproduce**
1. Go to security details
2. Click on 'Buy'
3. Enter amount and click 'Continue'
4. Click 'OK' and before the HTTP request is done, close the modal
5. The alert is presented on the security details
6. The alert now can't be closed

**Kirby version**
0.8.71

**Expected behavior**
The alert should be closable.

**System**
- OS: iOS and Mac
- Browser Capacitor, Chrome, Safari

**Additional context**
In the research to try to fix it, we concluded that this maybe unfixable in Kirby, and be an Ionic issue, as the close event for the alert comes from Ionic. We post the issue here, as we may be wrong.

**Comment by jakobe** [comment]
Fixed by #993
