### ISSUE TITLE
[Enhancement] Ensure icons don't have a hardcoded fill

### ISSUE THREAD

**Issue by hafstad** [kirbydesign/designsystem#857]
**Is your enhancement request related to a problem? Please describe.**
Icons / SVG's exported from sketch has a hardcoded fill color, which disables the possibility to change the color.  

**Describe the solution you'd like**
Create a custom linting rule, or some automation which ensures hardcoded fill colors won't be published or have an auto svg clean-up in our pipe-line

**Describe alternatives you've considered**
Look into changing the way we change color of the icons so we make sure overwriting the hardcoded fill color

**Comment by alxzak** [comment]
@henrikvoetmand is this still relevant?

**Comment by henrikvoetmand** [comment]
Could be relevant but i guess it is a nice to have feature. When we export new svg files to be used as default Kirby svg's we allways ensure no hardcoded fill. But it would be nice with a code check for this.

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
