### ISSUE TITLE
[Enhancement] Transparent background and contextual padding on items

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#858]
**Is your enhancement request related to a problem? Please describe.**
Right now our items come with a white color as default, which makes it hard to put them on anything else then a card as a background, like on canvas. 

The same goes for the padding/margin which is redundant when its placed on places like the canvas because the canvas is responsible for the padding.

Fx. https://zpl.io/aBd13Aq where it comes with a double padding to the left because it has both a padding in the modal and in the item.

**Describe the solution you'd like**
We would either:

Color
1. Items should be transparent so the component underneath is responsible for the color (eg a card for a list or something)
2. Possiblity to change the color in some kind of way (Or like a flavor or something)

Padding
1. If you dont have like a display and don't need so why not just be able to disable it? That is the left side of the avatar, the place available there :)

**Comment by lydemann** [comment]
We also have use cases for supporting semi-light items: https://zpl.io/Vkg1X1K

**Comment by jakobe** [comment]
**Possible breaking change** This needs careful refinement as to not introduce a breaking change ❗
