### ISSUE TITLE
[Enhancement] 44dp touch area

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#866]
**Is your enhancement request related to a problem? Please describe.**
We would like to have a touch area around some of our smaller components, so that's easier to hit them with the finger :) For that a 44x44px area would be optimal!

![Skærmbillede 2020-01-14 kl  08 22 02](https://user-images.githubusercontent.com/49033002/72322582-fc161c80-36a6-11ea-9edf-2b1490882053.png)

Components that needs to be looked on are:
- Buttons
- Checkmarks
- Radio (not ready yet)
- Item (Small should be 44 not 40)
- Others?

**Comment by EdwinSilvaDK** [comment]
Item [Small] already has the size of 44px

**Comment by RasmusKjeldgaard** [comment]
Just checked up on the state of this issue:
- Small size of `Button`, `Chip` in `Segmented Control`, `Dropdown` and `Toggle` all have a touch area that matches their size, which is `32 px`. 
- `Checkbox` and `Radio` has an extra small size, that explicitly limits the height of the touch area to `32px`. 
- `Item` with size small is `44px` and it is explicitly mentioned that extra small size is not supposed to be used for touch. 

So what do you think @bommariusser, do you agree that the focus should be on making the touch area of all the 44px for all the interactive elements that have a 32px size (`Button`, `Chip` in `Segmented Control`, `Dropdown` and `Toggle`)?

**Comment by bommariusser** [comment]
yes @RasmusKjeldgaard i agree :)

**Comment by RasmusKjeldgaard** [comment]
When adding the 44px touch area around a small button (height of 32px), it extends above and below the button and its 4px margin.

This means that the touch areas overlap if you place multiple buttons vertically without any additional spacing, like our attention level showcase in the cookbook:
https://user-images.githubusercontent.com/42470636/115253449-ac859280-a12c-11eb-9579-a97eb76b9e00.mov

This could also happen for other elements, like toggle and chip. 

So I think we should discuss if and how we want to solve this, here are some thoughts on what we could do: 
- Introduce spacing in components where two or more elements could potentially be placed horizontally 
- Accept the functionality as is, as placing elements like this is probably a rare use case anyways
- Remove the touch area functionality again, if it causes too many problems to have the touch area extend over the visual part of the element.
