### ISSUE TITLE
[Enhancement] add the possibility to use icons in controls

### ISSUE THREAD

**Issue by LVinther** [kirbydesign/designsystem#868]
We need to be able to add icons in the controls.

![Papirdetaljeside, Data](https://user-images.githubusercontent.com/53176253/72557110-5cbc7980-38a0-11ea-999f-6712a557b554.png)

Context: https://zpl.io/agp9PMZ

**Comment by bommariusser** [comment]
Vi tilføjer den igen når vi reelt får et behov
