### ISSUE TITLE
[Enhancement] Add possibility to use ionic reorder

### ISSUE THREAD

**Issue by sorenfruergaard** [kirbydesign/designsystem#874]
**Is your enhancement request related to a problem? Please describe.**
Users must be able to sort lists by using "drag and drop"

**Describe the solution you'd like**
A Kirby wrapper for ionic-reorder, so it is possible so sort list items by the user. It should be possible to supply a function which is called upon reorder completion.

**Describe alternatives you've considered**
None

**Additional context**
https://ionicframework.com/docs/api/reorder

**Comment by ThomasSkovbakke** [comment]
**A little context:**
Users should be able to sort their list of accounts and shawdow accounts by choice. When clicking the sort-icon on the toolbar in the account list, a modal pops up with a reproduction of all the accounts on the account list, but without shadows. From here the user can drag and drop their accounts and shadow accounts at will. The drag and drop styling is a bit different from Ionics. 

**Specs**
- The dragged item should scale 105% and not have opacity. It should also get a shadow z8 when pressed and dragged.
- When released it goes back to normal. 
- When pressing a shadow account, a light overlay focuses on the "totalkonto" and helps the user to understand the sorting-restrictions from this type of account.

**Zeplin links:**
Sorting (modal): https://zpl.io/agpYp79
Sort account: https://zpl.io/adGeGnp
Sort shadow account: https://zpl.io/boNqNlv
