### ISSUE TITLE
Sticky page title should use text baseline as vanishing point

### ISSUE THREAD

**Issue by tja1607** [kirbydesign/designsystem#875]
Transformation / animation of fixed text i header should occur when scrolling to the baseline of text element and not when element ends. Look at IOS behavior.

## Baseline
![IMG_1697](https://user-images.githubusercontent.com/3206272/72734783-c8e9f680-3b9a-11ea-96d9-0917e25fb687.PNG)

## After baseline
![IMG_1696](https://user-images.githubusercontent.com/3206272/72734798-d43d2200-3b9a-11ea-9408-7464037a2c8e.PNG)

## Fixed header text
![IMG_1698](https://user-images.githubusercontent.com/3206272/72734809-d99a6c80-3b9a-11ea-8415-d032fd0a090f.PNG)

**Comment by bommariusser** [comment]
@tja1607 men ios gør det da ikke dynamisk imens man scroller den op? Den venter da indtil det er helt færdigt - Eller mener du selve animationen hvor den flyver op? :D

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
