### ISSUE TITLE
[Enhancement] Resize text-field dynamically 

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#878]
**Is your enhancement request related to a problem? Please describe.**
We would like a property that enables the text-field to get bigger instead of inserting af scroll bar to the right of the field.

<img width="647" alt="Skærmbillede 2020-01-22 kl  09 44 06" src="https://user-images.githubusercontent.com/49033002/72878709-c18e2e80-3cfb-11ea-9852-495c9ac71da0.png">

**Comment by jonasjensen-brolstark** [comment]
We have in DRB used the npm package [ngx-autosize](https://www.npmjs.com/package/ngx-autosize) with success.

**Comment by labanos** [comment]
Closing for now - as this will most likely not be prioritized right now, maybe some day ;)
