### ISSUE TITLE
[Enhancement] Util for font scaling (Eg Display 1->3)

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#881]
**Is your enhancement request related to a problem? Please describe.**
Right now we have 3 different Display sizes (1-3) even though the font itself should be scaleable from     
 1 ->3 . That means if u use a Display1 right now it doesn't behave in a good way.

We need an easy way to do such a behavior and/or the Display font should to that font scaling by default.

![Skærmbillede 2020-01-23 kl  09 51 37](https://user-images.githubusercontent.com/49033002/72969596-17c7a400-3dc6-11ea-9f25-f9513b907d4a.png)

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
