### ISSUE TITLE
[BUG]Maxlength is not working on android

### ISSUE THREAD

**Issue by laljyskebank** [kirbydesign/designsystem#882]
**Describe the bug**
On android devices, maxlength on input field is not working. It is possible to write more characters than specified.

**To Reproduce**

1. Go to 'Faste betalinger'
2. Click on 'FAB'
3. Click on 'Tilmeld Betalingsservice'
4. Click on 'Beskrivelse'
5. Enter more than 32 characters

![Screen Shot 2020-01-23 at 11 52 42](https://user-images.githubusercontent.com/35138247/72978532-eb685380-3dd6-11ea-9c8e-90f20ed361ce.png)

**Kirby version**
- v0.0.83

**Expected behavior**
Restrict characters to maxlength

**Comment by jonasjensen-brolstark** [comment]
I can reproduce this error also in the cookbook, if i move the marker into the middle of the text and start writing.

But i can also reproduce it in a vanilla HTML input element [here](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_input_maxlength). So i think i may be an android/chrome issue.

**Comment by laljyskebank** [comment]
Closed and moved to #883
