### ISSUE TITLE
[Enhancement] Add character counter to textarea

### ISSUE THREAD

**Issue by szutrifork** [kirbydesign/designsystem#889]
**Is your enhancement request related to a problem? Please describe.**
In current project 'Kunderum' we need to have a character counter on textarea.

**Describe the solution you'd like**
Same logic and functionality that is already implemented on 'kirby-input'

![Screenshot 2020-01-27 at 12 35 00](https://user-images.githubusercontent.com/13220212/73171640-81ff8200-4101-11ea-80cf-83c961f7ff14.png)

**Comment by jonasjensen-brolstark** [comment]
Hi @szutrifork ,

i have made a draft (#891) for the changes you are looking for. You can test and see if that is enough to cover your needs for a counter.
