### ISSUE TITLE
Add Highchart.timeseries to the existing Kirby chart options [Enhancement]

### ISSUE THREAD

**Issue by hawkish** [kirbydesign/designsystem#890]
**Is your enhancement request related to a problem? Please describe.**
We need another Highchart option for investment - since none of the existing options are able to solve the underlying UX issue.

**Describe the solution you'd like**
I'm going to add the Highchart timeseries as an option - similar to the areaspline option.

**Describe alternatives you've considered**
No alternatives considered.

**Additional context**
https://zpl.io/b6o84rK

**Comment by hafstad** [comment]
closed by #897
