### ISSUE TITLE
[BUG] ModalController in confused state after closing one modal, then quickly opening another

### ISSUE THREAD

**Issue by mvindahl** [kirbydesign/designsystem#895]
**Describe the bug**
To be clear, we have only seen this when automating the UI with test frameworks (Cypress). It's probably impossible to manually reproduce so I was a bit in doubt as to whether I should file as a bug or as an enhancement request. 

**To Reproduce**
Using Cypress, close a modal, then immediately open another modal. The UI will now be in a state where dismissing the second modal does not work.

**Kirby version**

- [e.g. 0.8.83]

**Expected behavior**
It should be possible to close the second modal.

**Please complete the following information:**

- OS: [MacOS]
- Browser [Chrome (automated)]
- Version [most recent]

**Additional context**
I debugged the Kirby ModalController and the problem seems to arise when the first modal is dismissed using the hideTopMost() method and the second modal is opened before the modalCloseEvent is received. When the event handler subsequently calls forgetTopmost(), it forgets the second modal, not the first one.

One solution might be to make explicit note of which modal was opened and to specifically close that one:
```
  public showModal(config: ModalConfig, onCloseModal?: (data?: any) => void): void {
    let myModal;
    const modalCloseEvent: Promise<any> = this.modalHelper.showModalWindow(
      config,
      (modal) => {
        this.register(modal);
        myModal = modal;
      }
    );
    modalCloseEvent.then((data) => {
      this.modals = this.modals.filter(modal => modal != myModal);
      if (onCloseModal) {
        // Since Ionic wraps the return value in an object, which contains data as a property, we need to return data.data
        // We don't expect this on native, hence we return just data
        onCloseModal(typeof data === 'object' && 'data' in data ? data.data : data);
      }
    });
  }
```
The above implementation seemed to fix the issue but I've only loosely tested it. Also, there may be more elegant solutions.

For now, our workaround is to make Cypress wait until the first dialog has fully animated away and is no longer visible. This probably wastes time, though.

**Comment by jakobe** [comment]
Fixed by #993
@mvindahl Instead of using `ModalController. hideTopMost()` you should hide the current modal from within the embedded component, by injectin the `Modal` interface and call `modal.close()`
