### ISSUE TITLE
[Enhancement] Property for wrapping "Label" in Item

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#904]
**Is your enhancement request related to a problem? Please describe.**
Right now all labels/defaults in our items are getting truncated, but we would like a property where you can wrap some text "

See also this:

![Skærmbillede 2020-01-31 kl  14 06 28](https://user-images.githubusercontent.com/49033002/73541503-eb99cc00-4432-11ea-81f2-007089695290.png)

This is how we like it to behave if we have it wrapping

![Skærmbillede 2020-01-31 kl  14 07 37](https://user-images.githubusercontent.com/49033002/73541594-269bff80-4433-11ea-88a9-03e397f77932.png)

**Additional context**

**Comment by jakobe** [comment]
@bommariusser This can already be achieved for a plain list of radios using `kirby-radio-group` (see: [Radio - Multiline Label](https://cookbook.kirby.design/home/showcase/radio).
Do we need this anywhere else? 🤔

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993

**Comment by bommariusser** [comment]
Yes we also need this in other contexts where we dont use radio :) like this: 
![Skærmbillede 2022-01-13 kl  09 57 22](https://user-images.githubusercontent.com/49033002/149298008-d3c3100f-46f9-483e-ba85-73866adb9c71.png)




Also we would like the linebreaks to be dynamically dependent on screensize, not manually.
