### ISSUE TITLE
[Enhancement] Cleanup design and definition

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#914]
**Note:** Updated design: https://zpl.io/awEL1vM

**Is your enhancement request related to a problem? Please describe.**
Right now our checkmark is still in a "walking skeleton" state and there is a lot of unneeded stuff, like the amount of colors or the shapes, because we only have a boxed version and not a round version

Maybe we could even make a property on the checkbox which says if its single select or multiselect, but that might also be another issue. 

**Describe the solution you'd like**
We would like the checkbox to only have three "flavors" in regards to color and background

<img width="1156" alt="Skærmbillede 2020-02-07 kl  07 48 08" src="https://user-images.githubusercontent.com/49033002/74007314-58a2e980-497e-11ea-9a97-3bb050063665.png">

**Single:** Uses the sucess color and is used in places where you only turn on/off a single selection

**Multi** Uses the "secondary"/black color and is used in places where you have more selections or more checkboxes underneath each other

**Radio** Uses no "fill" color and is only used in context where you can select in a "radio" way.

**Other things to consider**

There is also an issue regarding the hit area which should be fixed at the same time.

**Comment by HStokbro** [comment]
Hey @bommariusser

I would like to have the radio look taken out of the checkbox and moved to the radiobutton.
We will get a kirby radiobutton soon:
https://github.com/kirbydesign/designsystem/issues/865

The radiobutton should then have it's normal radio-circle look and the radio-checkmark look as a secondary flavor.

The reason: 
The radiobutton comes with the actual radio functionality you want together with this look. 
(Only allowing one to be selected)

Do you agree?

**Comment by bommariusser** [comment]
We agree @HStokbro and good that you mention it! 

We have defined our guidelines for radio like this but this task is not updated to that yet. And naming of the both levels is just a draft and up to discussion.

![Guidelines](https://user-images.githubusercontent.com/49033002/101189909-f5461e80-3657-11eb-81f3-c584fa9657b6.png)

**Comment by HStokbro** [comment]
Updated design: https://zpl.io/awEL1vM
