### ISSUE TITLE
[Enhancement] Make it possible to render calendar uniformly across timezones 

### ISSUE THREAD

**Issue by mvindahl** [kirbydesign/designsystem#916]
**Is your enhancement request related to a problem? Please describe.**
The calendar alway obtains today's date from the local timezone. Thus, it may mark one date as the current one if accessed from, say, New Zealand and simultaneously mark another date as the current one if accessed from Hawaii. (This can be emulated by changing the system timezone).

This conflicts with the desired behaviour of our application as we want to present all users with the same view as if they were located in Denmark.

**Describe the solution you'd like**
Where as the behaviour may be fine in some applications, it is not the desired behaviour in our application. We desire a way to override it.

~~I think my preferred solution would be to introduce an optional property to fix the calendar rendering to a specific timezone, using any timezone string accepted by moment-timezone. In our case we would specify it as `[renderingTimezone]="Europe/Copenhagen"`. The calendar would then behave as if the browser were in Copenhagen, marking the current date as whichever date is the current one in .dk.~~
EDIT: On closer consideration, I think this would have been overengineering.

**Describe alternatives you've considered**
Introducing an optional property `todayDate` to explicitly tell the calendar which date it should consider to be today.

**Additional context**
There is another feature request relating to the Calendar and timezones: https://github.com/kirbydesign/designsystem/issues/826.

These two feature requests are orthogonal in the sense that this feature request deals with the internal workings of the calendar where as #826 deals with the date format used by its interface.

**Comment by mvindahl** [comment]
On closer consideration I would vote for the simple `todayDate` property. This would also make it possible to control calendar state when running cypress tests. (I tried cy.clock() but I couldn't make it work).

**Comment by mvindahl** [comment]
I have experimented with introducing `todayDate` as an optional property. It would solve all of our current issues.

I've implemented the change on a fork of the project: https://github.com/mvindahl/designsystem/tree/calendar-add-todaydate-parameter

If the suggestion is approved a pull request would be just a few clicks away.

**Comment by mvindahl** [comment]
The following design has been agreed upon:

- introduce new optional input property `todayDate` to be able to tell the calender which calender date is the current one
- legal values is a Date following the same conventions as properties 'minDate', 'maxDate', etc. That is, it should point to midnight (see also #826).
- when omitted, defaults to constructing a calendar date based upon browser time, for backwards compatibility

@jakobe @Anders-Bloch please voice your objection if this is incorrect

**Comment by jakobe** [comment]
Closed by #994
