### ISSUE TITLE
Enhancement: Split cookbook and kirby source into two projects.

### ISSUE THREAD

**Issue by jonasjensen-brolstark** [kirbydesign/designsystem#92]
As it is build right now, we will never discover stuff like issues like there was with the polyfills import.

So would it not be better to split the cookbook and kirby source in two projects (but keep the source together). Just so we do real [dog feeding](https://en.wikipedia.org/wiki/Eating_your_own_dog_food)?

Any thoughts @jakobe and are there any infrastructure issues with this @langecode ?

**Comment by langecode** [comment]
As long as the source code is in same repository I see no problem in re-organizing. Then the cookbook and the library will still have the same lifecycle. And infrastructural-wise we can just change the build of Docker container to fetch the files from elsewhere and adjust the commands Travis run according to the code organization.

So from here it sounds like a good idea.

**Comment by labanos** [comment]
How important is this enhancement? and how much effort is needed? Eg can it wait? should it wait? etc?

**Comment by jakobe** [comment]
Solved (a long time ago...)
