### ISSUE TITLE
[Enhancement] Have graphics and charts go to the edge of the screen when inside a Kirby-page

### ISSUE THREAD

**Issue by SilverGull** [kirbydesign/designsystem#927]
*NOT Prioritized*
- Needed for May 2020 release

*NOT Tech Refined*
- In progress

**Is your enhancement request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Charts and/or graphics should go to the edge of the screen on mobile in portrait mode. Landscape and web has not been UX'ed  

**Describe alternatives you've considered**
None

**Additional context**
Example of chart that goes to the edges of the screen. @LVinther tells me that based on current feedback from DesignIt we may see this functionality for other graphical elements as well.

![Screenshot 2020-02-18 at 09 34 07](https://user-images.githubusercontent.com/43959200/74718102-dba32a00-5231-11ea-895c-fdec28fb9d27.png)

**Comment by SilverGull** [comment]
Please set this on hold. The graph has developed quite a bitt the last couple of weeks and I am unsure whether we need this feature still.

**Comment by jakobe** [comment]
**Tech refinement**: Could be solved by adding an opt-out option regarding padding on Page container and then wrapping everything that still needs spacing in a new layout component (i.e. `kirby-section`or similar).

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
