### ISSUE TITLE
[BUG] Button with text and icon is recognized as icon only

### ISSUE THREAD

**Issue by Lenny04** [kirbydesign/designsystem#928]
**Describe the bug**
When creating a kirby button with text first and a kirby icon second and then adds a ngIf statement to the icon, so it only should show when a condition is met, the button is recognized as an icon only button. 

**To Reproduce**

1. Create a kirby button
2. Add button text inside
3. Add a kirby icon inside
4. Apply a ngIf statement with a condition
5. See how the kirby button is rendered in a wrong way, the frame is too small as it is meant  for a button with only an icon and the button text is not fully visible.

**Kirby version**

0.8.101

**Expected behavior**
A kirby button with text to the left and a kirby icon to the right, which is only shown if the specific condition is met.

**Screenshots**
![Skærmbillede 2020-02-24 kl  10 52 09](https://user-images.githubusercontent.com/23257928/75142953-700b0200-56f4-11ea-90c7-3e37c98f78c0.png)

**Please complete the following information:**

- OS: MacOS
- Browser: Chrome
- Version 80.0.3987.116 

**Additional context**

*Solve*
- [ ] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [ ] Create Fix Branch
- [ ] Create test reproducing the error
- [ ] Add any required mock and fakes to the `KirbyTestingModule`
- [ ] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- Merge to master and delete branch

**Comment by jakobe** [comment]
Note: It's possible to work around this issue by creating 2 buttons (1 WITH icon, 1 WITHOUT) and applying the `*ngIf` condition to those 2 buttons.

**Comment by MadsBuchmann** [comment]
I am not able to recreate this bug when inserting text first and a kirby-icon second. If i do it in the opposite order (see code below) i can however trigger the bug. 

Is it a mistake in the bug description or could the steps to reproduce the bug have been changed, since it was originally posted? 😄
 
![Screenshot 2021-02-09 at 11 31 08](https://user-images.githubusercontent.com/17269698/107350925-506a1680-6aca-11eb-86dc-a28e713e3567.png)
<img width="138" alt="Screenshot 2021-02-09 at 11 35 28" src="https://user-images.githubusercontent.com/17269698/107351540-06356500-6acb-11eb-92a6-6c5d60c75da2.png">

**Comment by Lenny04** [comment]
> I am not able to recreate this bug when inserting text first and a kirby-icon second. If i do it in the opposite order (see code below) i can however trigger the bug.
> 
> Is it a mistake in the bug description or could the steps to reproduce the bug have been changed, since it was originally posted? 😄
> 
> ![Screenshot 2021-02-09 at 11 31 08](https://user-images.githubusercontent.com/17269698/107350925-506a1680-6aca-11eb-86dc-a28e713e3567.png)
> <img alt="Screenshot 2021-02-09 at 11 35 28" width="138" src="https://user-images.githubusercontent.com/17269698/107351540-06356500-6acb-11eb-92a6-6c5d60c75da2.png">

@MadsBuchmann When I created this issue, I was able to create this bug by inserting text first and a kirby-icon second as written in the description. I'm not sure if any changes has been made since that has been affected this behaviour :)
