### ISSUE TITLE
[Enhancement] Items inside Input

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#929]
**Is your enhancement request related to a problem? Please describe.**
Right now we can't add items inside or on top of a textfield - which we would like to do in some usecases, like adding attachments to a message. 

Which means we need to separate the attachments and the message even though its part of each other:

<img width="446" alt="Skærmbillede 2020-02-26 kl  08 23 28" src="https://user-images.githubusercontent.com/49033002/75323094-77591980-5874-11ea-9c5c-db0a14b0f80e.png">

**Describe the solution you'd like**
We would like to be able to put items on top or in the bottom of a text field.

<img width="478" alt="Skærmbillede 2020-02-26 kl  08 24 53" src="https://user-images.githubusercontent.com/49033002/75323122-863fcc00-5874-11ea-938e-06ab5f85fbcd.png">

**Comment by jakobe** [comment]
**Tech refinement**: This probably should NOT be part of the textarea, but could be solved by wrapping a textarea + an item within a card, and the wrapping the whole thing in a form field. Needs triage...
