### ISSUE TITLE
kirby-checkbox not working with reactive forms

### ISSUE THREAD

**Issue by yassertal** [kirbydesign/designsystem#935]
**Describe the bug**

Cannot use kirby-checkbox with Angular reactive forms.
"formControlName" is not a known attribute on "kirby-checkbox".

**To Reproduce**

<kirby-checkbox  checked="true"  formControlName="myCheckboxFormControl"></kirby-checkbox>

**Kirby version**
"@kirbydesign/designsystem": "^0.8.104",

**Please complete the following information:**
- OS:  Windows
- Browser Chrome
- Version 80.0.3987.122 (Officiel version) (64-bit)

**Comment by labanos** [comment]
@yassertal any input on when you need this? (or have you found a workaround for now? ;)

**Comment by yassertal** [comment]
Hi @labanos 
It is needed in my project asap. :-)
I have a workaround by using a dropdown in stead of checkbox.

**Comment by labanos** [comment]
@yassertal ok we will see what we can do - however we do have other issues and new components needed by teams on DRB before Easter. So i cannot give you any firm deadline. Another option is that you look into fixing it in Kirby yourself - with guidance from @jakobe or @hafstad. That is take a short kickoff meeting virtually with either - to get a direction on the solution.

**Comment by jakobe** [comment]
**Tech refinement:** Implement ControlValueAccessorInterface on kirby-checkbox

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
