### ISSUE TITLE
[BUG] Empty State padding 

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#936]
**Describe the bug**
The padding from text to button is right now 8px but should be 24px.

Right now
<img width="663" alt="Skærmbillede 2020-03-01 kl  13 55 41" src="https://user-images.githubusercontent.com/49033002/75626149-3854fc00-5bc5-11ea-8b8e-95eab2f1b0bd.png">

How it should be:

<img width="360" alt="Skærmbillede 2020-03-01 kl  14 02 09" src="https://user-images.githubusercontent.com/49033002/75626162-515dad00-5bc5-11ea-8419-a4c10f8d65fc.png">

https://zpl.io/2j7MXe6

**To Reproduce**

1. Go to https://cookbook.kirby.design/home/showcase/empty-state 
2. See error

**Kirby version**

- v0.8.109

**Additional context**

**Process around fixing and prioritization**
In order to fix bugs in a timely fashion please follow these few steps when relevant

*NOT Prioritized*
- [ ] Consider urgency of the Bug and be specific if it is blocking for your project. Describe any deadlines for the issue - eg. X needs this done by Y date, to be used in Z sprint. Suggest a milestone for the issue. The Not Prioritized will be removed by the Kirby team. If the bug has "low" priority it will be solved eventually - typically when working with the effected component in a different context.

*NOT Tech Refined*
- [ ] Sketch a solution in technical terms, that is how will the bug will be fixed. Call for a brief meeting or spend enough time with someone from @kirbydesign/kirby-guild to get a "go ahead". Remove NOT Tech Refined label. (Move issue from "Backlog" -> "Ready to do" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)

*Solve*
- [ ] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [ ] Create Fix Branch
- [ ] Create test reproducing the error
- [ ] Add any required mock and fakes to the `KirbyTestingModule`
- [ ] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- Merge to master and delete branch

**Comment by jakobe** [comment]
Fixed
