### ISSUE TITLE
[Enhancement] Swipe to change segment

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#941]
**Mandatory steps to ensure alignment between stakeholders and the progression of Kirby**
In order to ensure steady progress and quality of Kirby, please follow our outlined process. By default three labels are added to new component issues and enhancements. To help Kirby please follow these steps, and remove the labels from the issue when done.

*NOT Prioritized*
- [ ] Describe any deadlines for the issue - eg. X needs this done by Y date, to be used in Z sprint. Suggest a milestone for the issue. The `Not Prioritized` label will be removed by the Kirby team. 

*NOT UX Refined*
- [ ] Make sure the new Component, has a name, can be found in Zeplin, and is used in minimum one reviewed screen. Remove the `NOT UX Refined` label and add links to Zeplin.

*NOT Tech Refined*
- [ ] Sketch a solution in technical terms, that is how will the component be enhanced - eg. build it from scratch or build using X Ionic component. Call for a brief meeting or spend enough time with someone from @kirbydesign/kirby-guild to get a "go ahead". Remove the `NOT Tech Refined` label.

**Is your enhancement request related to a problem? Please describe.**
Right now we can only change the state of a SegmentedControl by pressing on the control that is not selected.

**Describe the solution you'd like**
We would like to be able to switch a segment by dragging it with either mouse or touch. You can test it here https://ionicframework.com/docs/api/segment

**Comment by jakobe** [comment]
This has been fixed - but see #987
