### ISSUE TITLE
[Enhancement] Improve showcase (Form in a item)

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#946]
**Mandatory steps to ensure alignment between stakeholders and the progression of Kirby**
In order to ensure steady progress and quality of Kirby, please follow our outlined process. By default three labels are added to new component issues and enhancements. To help Kirby please follow these steps, and remove the labels from the issue when done.

*NOT Prioritized*
- [ ] Describe any deadlines for the issue - eg. X needs this done by Y date, to be used in Z sprint. Suggest a milestone for the issue. The `Not Prioritized` label will be removed by the Kirby team. 

*NOT UX Refined*
- [x] Make sure the new Component, has a name, can be found in Zeplin, and is used in minimum one reviewed screen. Remove the `NOT UX Refined` label and add links to Zeplin.

*NOT Tech Refined*
- [ ] Sketch a solution in technical terms, that is how will the component be enhanced - eg. build it from scratch or build using X Ionic component. Call for a brief meeting or spend enough time with someone from @kirbydesign/kirby-guild to get a "go ahead". Remove the `NOT Tech Refined` label.

**Is your enhancement request related to a problem? Please describe.**
Our showcase that shows a form-control in an item only activates the form-control when pressing it (like the checkbox). Right now it even shows that the item is clickable, but it doesnt change the form control. 

**Describe the solution you'd like**
A item with a checkbox (or another form control) should be activated/deactivated by pressing the whole item.

**Comment by RasmusKjeldgaard** [comment]
Seems reality has caught up with this one. The solution is already implemented, see [Item > with checkbox](https://cookbook.kirby.design/home/showcase/item)
