### ISSUE TITLE
[Enhancement] Ability to align Spinner and Empty State Consistent on Page

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#951]
**Is your enhancement request related to a problem? Please describe.**
Right now all our teams are trying to place the spinner and the respective empty and error states in the middle of their content, without it being an easy task.

And we actually end up with different solutions for each of our respective areas.

**Describe the solution you'd like**
We would like a solution where the page has some variables that make this task easier so this can be achieved:

![Skærmbillede 2020-03-13 kl  14 34 55](https://user-images.githubusercontent.com/49033002/76625998-9fb16b00-6538-11ea-820b-83ad3e381aaa.png)

**Comment by yucelbas** [comment]
An additional comment: 
Empty state / error-state does not center when used combined with Kirby-page /kirby-page-content.

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
