### ISSUE TITLE
Bug: HMR is not working in cookbook app

### ISSUE THREAD

**Issue by jonasjensen-brolstark** [kirbydesign/designsystem#96]
HMR is not working in the mobile version of the cookbook app.

**Comment by jakobe** [comment]
@jonasjensen-brolstark Is this still an issue after the upgrade to {N} 5.2?

**Comment by jonasjensen-brolstark** [comment]
> @jonasjensen-brolstark Is this still an issue after the upgrade to {N} 5.2?

Nope looks fixed for me. So is fine by me if we close this issue.

**Comment by jonasjensen-brolstark** [comment]
HMR is working but you can see an error like `FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory` or `FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`

This can be fixed by following the step described [here](https://docs.nativescript.org/angular/performance-optimizations/bundling-with-webpack#javascript-heap-out-of-memory)
