### ISSUE TITLE
[Enhancement] - Dropdown width and placement

### ISSUE THREAD

**Issue by SilverGull** [kirbydesign/designsystem#964]
*Prioritized*
- We would like this enhancement to have high priority as we need it for a feature that we hoped to release in this sprint and enhance upon in the next sprint

*UX Refined*
- https://zpl.io/aB8ddDK

*Tech Refined*
- We'll do a quick bugfix for the placement issue: When the dropdown is aligned to the right side of the screen and the left offset+the width of the dropdown options is wider than the width of the screen, the dropdown options should be right aligned.
- The min-width will be explored in different enhancement issue: #940

**Is your enhancement request related to a problem? Please describe.**

1. The dropdown i as default placed so that the left side aligns with the left side of the button. This makes the dropdown go off the right of the screen when the dropdown is placed at the right side of the screen.
2. The min width of the dropdown is quite wide leaving a lot of empty space in some of our dropdowns. 

**Describe the solution you'd like**
1. The possibility to set right or left alignment. Default left (as is) and right should make the right side of the dropdown align with the right side of the button.
2. A smaller min width or width adjusted to content. Not as important as number 1.

**Describe alternatives you've considered**

**Additional context**
What we would like
![Screenshot 2020-03-23 at 13 40 31](https://user-images.githubusercontent.com/43959200/77317731-063e4200-6d0c-11ea-940f-3459e16d2400.png)

Current behaviour
![Screenshot 2020-03-23 at 13 42 16](https://user-images.githubusercontent.com/43959200/77317787-240ba700-6d0c-11ea-96e8-3555461bf4be.png)

**Comment by bommariusser** [comment]
@SilverGull super fint :) Det er vel én af de her opgaver som står her: https://github.com/kirbydesign/designsystem/issues/940

Jeg synes umiddelbart at dropdownen skal selv kunne håndtere hvordan den åbner udefra der hvor den står venstre/højre, sådan at man ik selv skal bestemme det, men blot skal ligge den det rigtige sted i ui'et.

Og som du også siger, bredden at popoveren er nødvendigvis ik så vigtigt til at starte med, hvis det overhovedet er vigtigt.

**Comment by SilverGull** [comment]
@bommariusser You are absolutely right. Didn't see that one. Should this one be deleted?

Your suggestion about placement would make it nicer to use for developers but properly more costly to implement - but excellent suggestion!
