### ISSUE TITLE
[BUG] Modal scroll on tablet with keyboard

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#966]
**Describe the bug**
When you open a modal on a tablet and the keyboard comes in from the bottom, the modal "scrolls up".
![Skærmbillede 2020-03-23 kl  12 48 11](https://user-images.githubusercontent.com/49033002/77397002-16eec680-6da5-11ea-8406-54d40a477d6c.png)

This has only been tested on iOS but i guess its a crossplatform thing. 

**To Reproduce**

1. Go to indbakke (on a tablet, in landscape)
2. Click on write new message
3. See error

**Kirby version**

v1.0.11

**Expected behavior**
I expected the modal to keep its position and the top-bar be fixed so the content scrolls underneath. 

![Skærmbillede 2020-03-24 kl  07 44 22](https://user-images.githubusercontent.com/49033002/77396750-9760f780-6da4-11ea-89a2-fd2878856b17.png)

**Please complete the following information:**

only tested on iOS tablet

**Process around fixing and prioritization**
In order to fix bugs in a timely fashion please follow these few steps when relevant

*NOT Prioritized*
- [ ] Consider urgency of the Bug and be specific if it is blocking for your project. Describe any deadlines for the issue - eg. X needs this done by Y date, to be used in Z sprint. Suggest a milestone for the issue. The Not Prioritized will be removed by the Kirby team. If the bug has "low" priority it will be solved eventually - typically when working with the effected component in a different context.

*NOT Tech Refined*
- [ ] Sketch a solution in technical terms, that is how will the bug will be fixed. Call for a brief meeting or spend enough time with someone from @kirbydesign/kirby-guild to get a "go ahead". Remove NOT Tech Refined label. (Move issue from "Backlog" -> "Ready to do" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)

*Solve*
- [ ] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [ ] Create Fix Branch
- [ ] Create test reproducing the error
- [ ] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- Merge to master and delete branch

**Comment by jakobe** [comment]
Issue closed as the bug can no longer be recreated (probably due to several refactorings of Modal since the issue was opened)
