### ISSUE TITLE
[BUG] Page-title doesn't support longer words

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#967]
**Describe the bug**
When u put a longer word into the page-title it goes out of the view. 
![Skærmbillede 2020-03-24 kl  09 06 58](https://user-images.githubusercontent.com/49033002/77402504-0cd1c580-6daf-11ea-8078-ba47bdf1afee.png)
<img width="1230" alt="Skærmbillede 2020-03-24 kl  09 03 18" src="https://user-images.githubusercontent.com/49033002/77402509-0e02f280-6daf-11ea-9e8e-3233270d86da.png">

**To Reproduce**

1. Go to indbakke
2. Write a message with a long emne
3. See error

**Kirby version**

- v1.0.11

**Expected behavior**
Dependant on what the page is setup to be (1 line max or 2 etc.) it either goes into more lines with a "-" at the end of the line or scales the font to fit.

**Screenshots**
![Skærmbillede 2020-03-24 kl  09 11 39](https://user-images.githubusercontent.com/49033002/77402895-a6997280-6daf-11ea-9e9e-59ed58e8e269.png)

**Process around fixing and prioritization**
In order to fix bugs in a timely fashion please follow these few steps when relevant

*NOT Prioritized*
- [ ] Consider urgency of the Bug and be specific if it is blocking for your project. Describe any deadlines for the issue - eg. X needs this done by Y date, to be used in Z sprint. Suggest a milestone for the issue. The Not Prioritized will be removed by the Kirby team. If the bug has "low" priority it will be solved eventually - typically when working with the effected component in a different context.

*NOT Tech Refined*
- [ ] Sketch a solution in technical terms, that is how will the bug will be fixed. Call for a brief meeting or spend enough time with someone from @kirbydesign/kirby-guild to get a "go ahead". Remove NOT Tech Refined label. (Move issue from "Backlog" -> "Ready to do" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)

*Solve*
- [ ] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [ ] Create Fix Branch
- [ ] Create test reproducing the error
- [ ] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- Merge to master and delete branch

**Comment by flemcito** [comment]
Kinda the same bug #1095

**Comment by jkaltoft** [comment]
# Suggestion for solving this and #1095 

To manage text overflow: Wrap overflowing text and use hyphens.

📚 [Wrapping and breaking text](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Text/Wrapping_Text)

🍿 [How do you wrap long words in CSS?](https://youtu.be/UOKQ6gw21NA)

**Comment by alxzak** [comment]
closed together with this issue https://github.com/kirbydesign/designsystem/issues/1095
