### ISSUE TITLE
[Enhancement] Close by drag in content

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#973]
**Is your enhancement request related to a problem? Please describe.**
Now where we have the possibility to close the drawer and the modal by dragging, it would be nice in some cases to be able to close the modal/drawer by dragging it in the content and not just in the header.

This is only relevant when the user is in the very top of the modal/drawer and should not be activated while swiping up. 

This should not be the default behavior and should not be used for longer flows.

This is especially expected for some of our users in the modal when it's more context based without any flow, eg. image modals - But tbh also in pickers like "accountpicker" eg.

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
