### ISSUE TITLE
[Enhancement] Reorder all items in a sections with more than 1 item

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#974]
**Is your enhancement request related to a problem? Please describe.**

**Describe the solution you'd like**
It's not possible to change order of a section with all the items inside it, because the sub-items are always defined to be "child-element", and only those can be sorted. 

Look also here:
<img width="239" alt="Skærmbillede 2020-03-30 kl  11 56 25" src="https://user-images.githubusercontent.com/49033002/77899915-8c630700-727d-11ea-86fa-679e3af009f3.png">

**Describe alternatives you've considered**
We would like to be able to change subitems in a section so they're not all build up on the "totalkonti" & "delkonti" logic

![Skærmbillede 2020-03-30 kl  11 56 42](https://user-images.githubusercontent.com/49033002/77900080-cc29ee80-727d-11ea-9445-dc5852ba54b1.png)

**Additional context**
In Team1 we have a workaround for now, but as soon as we get "subitems" we'll have to look into this :)

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
