### ISSUE TITLE
Bug: kirby button does not take dynamic colorType

### ISSUE THREAD

**Issue by cckring-work** [kirbydesign/designsystem#98]
@jakobe 

I am trying to set colortype from at boolean value, but it has no effect.

`<!--<button kirby-button class="balance-button" colortype="{{ !isBalanced ? 'secondary' : 'primary' }}"  expand="full" shape="round" (click)="onBalanceTapped()">{{buttonText(isBalanced)}}</button>-->`

I have had @jonasjensen-brolstark help me and he is as much in wonder why mode as me, and mentions that he would probably make it more robust by adding classes instede of strings for colorType.

We have also tried the example below fetching colorType from at priperty in the ts file:
`  <button kirby-button class="balance-button" [colortype]="buttonType"  expand="full" shape="round" (click)="onBalanceTapped()">{{buttonText(isBalanced)}}</button>`

Can you help?

**Comment by cckring-work** [comment]
@ckibsen FYI

**Comment by jakobe** [comment]
Fixed by #300
