### ISSUE TITLE
[COMPONENT] Sizing as "Design tokens"

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#983]
**Describe the solution you'd like**
When designing UI we use spacing variables in sketch ranging from 2->40 - This has also been implemented in Zeplin.

![Skærmbillede 2020-04-02 kl  13 11 04](https://user-images.githubusercontent.com/49033002/78245089-1b268c80-74e7-11ea-948a-5772a51b7bf3.png)

Thus we should find a way to implement and align so these values are 1:1 between UI and DEV.

**Describe alternatives you've considered**
One way to do it is tshirt sizes xxs -> xxl , but this gets fast awkward in naming when it gets below xxs etc. and its pretty hard to figure out what xxs means.

Another way is to use some way of system where you can translate the name to the actual value. Eg.

0,5 = 4px
1 = 8px
2 = 16px
etc.

**Examples**
***Base unit `2px`***
- `xxxxs => x1 = 2px`
- `xxxs => x2 = 4px`
- `xxs => x4 = 8px`
- `xs => x6 = 12px`
- `s => x8 = 16px`
- `...`
- `xxxl => x28 = 56px`

***Base unit `4px`***
- `xxxxs => x0.5 = 2px`
- `xxxs => x1 = 4px`
- `xxs => x2 = 8px`
- `xs => x3 = 12px`
- `s => x4 = 16px`
- `...`
- `xxxl => x14 = 56px`

***Base unit `8px`***
- `xxxxs => x0.25 = 2px`
- `xxxs => x0.5 = 4px`
- `xxs => x1 = 8px`
- `xs => x1.5 = 12px`
- `s => x2 = 16px`
- `...`
- `xxxl => x7 = 56px`

**Additional context**
So what do others do?

Carbon use REM as reference = https://www.carbondesignsystem.com/guidelines/spacing/
and so on.

### Kick Off:

- [ ] Accept Feature incl. name of component (DSL)
- [ ] Update Kirby Component Status and publish to [Kirby Cookbook](https://cookbook.kirby.design)

### Code:

- [ ] Create Feature Branch
- [ ] Implement Skeleton Component
- Ask UX for review:
  - [ ] Ensure implementation is correct in relation to UX design
  - [ ] Define the version of the implementation + steps needed to reach version 1.0 (create [enhancement requests](https://github.com/kirbydesign/designsystem/issues/new?assignees=&labels=enhancement&template=enhancement-request.md&title=%5BEnhancement%5D))
- [ ] [Implement Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Add link to showcase on Kirby Component Status (`component-status-items.ts => code.cookbookUrl`)
- [ ] Also remove `githubIssueNo` and set `status` to `ItemCodeStatus.ready`
- [ ] Push commits to GitHub

### Review:

- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- Merge to master and delete branch

**Comment by jakobe** [comment]
@bommariusser Just added some example regarding new taxonomy ☝️ 
Should we bring this up again on the next Kirby refinement? 🤔

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
