### ISSUE TITLE
[Enhancement] 24px spacing between cards/content on "Til dig"

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#984]
**Is your enhancement request related to a problem? Please describe.**
We would like to give our "frontpage" some more breathing in between our content which means it goes from 16 -> 24, only between content and **not** margin to the side. 

This is how its going to look:
https://zpl.io/2y95kPJ

<img width="400" alt="Skærmbillede 2020-04-02 kl  13 56 25" src="https://user-images.githubusercontent.com/49033002/78246642-c2a4be80-74e9-11ea-9e99-1c973a6413a2.png">

* A) The default grid should **not** be changed to 'm' - This is only related to the frontpage
* B) Should the grid be configurable? **Svar:** (Maybe? Right now the frontpage is the only place where we want this kind of feature so it might be overkill)
* C) The column and row gap is always the same between content/cards - Maybe we should differentiate between content and margin so not everything on the site gets 24px (The content should still follow the same "content grid" - left/right)
* D) How should this look on smaller screens? **Svar:** We'll look into this, because right now it's 8px all the way around on smaller screens, which also should be changed, but i don't have the right answer for that right now.

**Comment by jakobe** [comment]
@bommariusser The grid has a default column and row gap of `16px` and `8px`on small screens (width <= 320px).
* A) Should the default be changed to `24px` ('m')
* B) Should the grid be configurable
* C) Is the column and row gap always the same?

**Comment by bommariusser** [comment]
A) the default between all cards should be 24px between (top & bottom) and (left & right)
B) right now this is not needed
C) yes in the grid
