### ISSUE TITLE
[Enhancement] Visual indication of "sliding"

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#987]
**Is your enhancement request related to a problem? Please describe.**

Right now it's possible to "slide" our segmented control to another segment, but it's just not shown visible that the user is sliding, until the sliding is finished and the user removes the finger after the sliding.

**Describe the solution you'd like**

In Ionic it's possible to "slide" the control and https://ionicframework.com/docs/api/segment but because we've changed some visuals of ionics segment.

**Comment by alxzak** [comment]
This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
