### ISSUE TITLE
[BUG] - Dropdown dropping to the wrong side on Android

### ISSUE THREAD

**Issue by SilverGull** [kirbydesign/designsystem#991]
**Describe the bug**
When having a dropdown at the right side of the screen it will some times drop right instead of left. It only seems to happen on Android (native app) and when the drop down drops to the left it won't go back to dropping right.

**To Reproduce**

I have not found a sure way to reproduce it every time yet.
- Open the DRB app (mock or staging) on an Android device - could be using Browser stack
- Go to the Investment feature
- Click the dropdowns at the right side (to toggle between return modes)

**Kirby version**
- 1.1.6 

**Expected behavior**
It should always drop left when the dropdown is placed to the right side of the screen

**Screenshots**
First click
<img width="330" alt="Screenshot 2020-04-20 at 14 51 03" src="https://user-images.githubusercontent.com/43959200/79753664-93c67f00-8316-11ea-9297-893e1cb0e29c.png">

Second click
<img width="321" alt="Screenshot 2020-04-20 at 14 51 28" src="https://user-images.githubusercontent.com/43959200/79753674-97f29c80-8316-11ea-8ce8-b58df3340abf.png">

**Please complete the following information:**
- OS: Android
- Native app
- Multiple Android versions

**Additional context**

The bug is quite urgent as we have an important feature that we cannot release do to the Android user experience.

## Tasks:
- [ ] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [ ] Create Fix Branch
- [ ] Create test reproducing the error
- [ ] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch

**Comment by bommariusser** [comment]
@SilverGull any chance you can add a screenshot? :)

**Comment by SilverGull** [comment]
@bommariusser here you are, a couple of nice pics :-)

**Comment by SilverGull** [comment]
I have tried using the dev tool on browserstack to gain some insight as to what is happening but it didn't give me anything. Any ideas as to how to pursue this problem?
