### ISSUE TITLE
[Enhancement] Animate footer in/up

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#996]
**Is your enhancement request related to a problem? Please describe.**
Right now the footer is always in the view from the beginning, when opening a modal, which also is fine for "simple footers" only with buttons.

**Describe the solution you'd like**
We would like to be able to animate the footer up - This is especially wanted in flows where the user has to go through different steps before the footer "shows up"

Technically it should work like this:
1. The footer should first animate in when the modal-animation is done
2. See below how the animation should be

<img width="772" alt="Skærmbillede 2020-04-22 kl  11 31 06" src="https://user-images.githubusercontent.com/49033002/79966031-20934900-848d-11ea-8490-186f6c1243cc.png">

**Additional information*
1. This could also be conditionally triggered in a view, where the user has to do something before the footer shows up.

2. This is also a preparing task for making a "sticky footer", where buttons in the view are going to be sticky in the bottom when you scroll past them - Scrolling past the buttons will trigger the sticky footer with the same animation. See also task https://github.com/kirbydesign/designsystem/issues/653

**Comment by alxzak** [comment]
https://app.zenhub.com/workspaces/zenhub-602b70d809e4aa00141a1a93/board?labels=priority%202&repos=147814567
